#! /bin/bash 
function topic_combinations { 
echo Human-north_sami.conllu Human-irish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-north_sami.conllu data/Human/Human-irish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-north_sami.conllu Human-scottish_gaelic.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-north_sami.conllu data/Human/Human-scottish_gaelic.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-north_sami.conllu Human-hindi.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-north_sami.conllu data/Human/Human-hindi.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-north_sami.conllu Human-maltese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-north_sami.conllu data/Human/Human-maltese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-north_sami.conllu Human-marathi.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-north_sami.conllu data/Human/Human-marathi.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-north_sami.conllu Human-urdu.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-north_sami.conllu data/Human/Human-urdu.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-north_sami.conllu Human-uyghur.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-north_sami.conllu data/Human/Human-uyghur.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-irish.conllu Human-scottish_gaelic.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-irish.conllu data/Human/Human-scottish_gaelic.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-irish.conllu Human-hindi.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-irish.conllu data/Human/Human-hindi.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-irish.conllu Human-maltese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-irish.conllu data/Human/Human-maltese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-irish.conllu Human-marathi.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-irish.conllu data/Human/Human-marathi.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-irish.conllu Human-urdu.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-irish.conllu data/Human/Human-urdu.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-irish.conllu Human-uyghur.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-irish.conllu data/Human/Human-uyghur.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-scottish_gaelic.conllu Human-hindi.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-scottish_gaelic.conllu data/Human/Human-hindi.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-scottish_gaelic.conllu Human-maltese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-scottish_gaelic.conllu data/Human/Human-maltese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-scottish_gaelic.conllu Human-marathi.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-scottish_gaelic.conllu data/Human/Human-marathi.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-scottish_gaelic.conllu Human-urdu.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-scottish_gaelic.conllu data/Human/Human-urdu.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-scottish_gaelic.conllu Human-uyghur.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-scottish_gaelic.conllu data/Human/Human-uyghur.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-hindi.conllu Human-maltese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-hindi.conllu data/Human/Human-maltese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-hindi.conllu Human-marathi.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-hindi.conllu data/Human/Human-marathi.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-hindi.conllu Human-urdu.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-hindi.conllu data/Human/Human-urdu.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-hindi.conllu Human-uyghur.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-hindi.conllu data/Human/Human-uyghur.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-maltese.conllu Human-marathi.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-maltese.conllu data/Human/Human-marathi.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-maltese.conllu Human-urdu.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-maltese.conllu data/Human/Human-urdu.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-maltese.conllu Human-uyghur.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-maltese.conllu data/Human/Human-uyghur.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-marathi.conllu Human-urdu.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-marathi.conllu data/Human/Human-urdu.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-marathi.conllu Human-uyghur.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-marathi.conllu data/Human/Human-uyghur.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-urdu.conllu Human-uyghur.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-urdu.conllu data/Human/Human-uyghur.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-belarusian.conllu Human-danish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-belarusian.conllu data/Human/Human-danish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-belarusian.conllu Human-estonian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-belarusian.conllu data/Human/Human-estonian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-belarusian.conllu Human-korean.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-belarusian.conllu data/Human/Human-korean.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-belarusian.conllu Human-croatian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-belarusian.conllu data/Human/Human-croatian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-belarusian.conllu Human-latin.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-belarusian.conllu data/Human/Human-latin.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-belarusian.conllu Human-latvian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-belarusian.conllu data/Human/Human-latvian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-belarusian.conllu Human-lithuanian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-belarusian.conllu data/Human/Human-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-belarusian.conllu Human-polish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-belarusian.conllu data/Human/Human-polish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-belarusian.conllu Human-sanskrit.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-belarusian.conllu data/Human/Human-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-belarusian.conllu Human-swedish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-belarusian.conllu data/Human/Human-swedish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-belarusian.conllu Human-tamil.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-belarusian.conllu data/Human/Human-tamil.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-belarusian.conllu Human-telugu.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-belarusian.conllu data/Human/Human-telugu.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-belarusian.conllu Human-classical_chinese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-belarusian.conllu data/Human/Human-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-danish.conllu Human-estonian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-danish.conllu data/Human/Human-estonian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-danish.conllu Human-korean.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-danish.conllu data/Human/Human-korean.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-danish.conllu Human-croatian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-danish.conllu data/Human/Human-croatian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-danish.conllu Human-latin.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-danish.conllu data/Human/Human-latin.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-danish.conllu Human-latvian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-danish.conllu data/Human/Human-latvian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-danish.conllu Human-lithuanian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-danish.conllu data/Human/Human-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-danish.conllu Human-polish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-danish.conllu data/Human/Human-polish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-danish.conllu Human-sanskrit.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-danish.conllu data/Human/Human-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-danish.conllu Human-swedish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-danish.conllu data/Human/Human-swedish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-danish.conllu Human-tamil.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-danish.conllu data/Human/Human-tamil.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-danish.conllu Human-telugu.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-danish.conllu data/Human/Human-telugu.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-danish.conllu Human-classical_chinese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-danish.conllu data/Human/Human-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-estonian.conllu Human-korean.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-estonian.conllu data/Human/Human-korean.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-estonian.conllu Human-croatian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-estonian.conllu data/Human/Human-croatian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-estonian.conllu Human-latin.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-estonian.conllu data/Human/Human-latin.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-estonian.conllu Human-latvian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-estonian.conllu data/Human/Human-latvian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-estonian.conllu Human-lithuanian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-estonian.conllu data/Human/Human-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-estonian.conllu Human-polish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-estonian.conllu data/Human/Human-polish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-estonian.conllu Human-sanskrit.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-estonian.conllu data/Human/Human-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-estonian.conllu Human-swedish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-estonian.conllu data/Human/Human-swedish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-estonian.conllu Human-tamil.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-estonian.conllu data/Human/Human-tamil.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-estonian.conllu Human-telugu.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-estonian.conllu data/Human/Human-telugu.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-estonian.conllu Human-classical_chinese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-estonian.conllu data/Human/Human-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-korean.conllu Human-croatian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-korean.conllu data/Human/Human-croatian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-korean.conllu Human-latin.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-korean.conllu data/Human/Human-latin.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-korean.conllu Human-latvian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-korean.conllu data/Human/Human-latvian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-korean.conllu Human-lithuanian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-korean.conllu data/Human/Human-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-korean.conllu Human-polish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-korean.conllu data/Human/Human-polish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-korean.conllu Human-sanskrit.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-korean.conllu data/Human/Human-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-korean.conllu Human-swedish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-korean.conllu data/Human/Human-swedish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-korean.conllu Human-tamil.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-korean.conllu data/Human/Human-tamil.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-korean.conllu Human-telugu.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-korean.conllu data/Human/Human-telugu.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-korean.conllu Human-classical_chinese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-korean.conllu data/Human/Human-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-croatian.conllu Human-latin.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-croatian.conllu data/Human/Human-latin.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-croatian.conllu Human-latvian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-croatian.conllu data/Human/Human-latvian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-croatian.conllu Human-lithuanian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-croatian.conllu data/Human/Human-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-croatian.conllu Human-polish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-croatian.conllu data/Human/Human-polish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-croatian.conllu Human-sanskrit.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-croatian.conllu data/Human/Human-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-croatian.conllu Human-swedish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-croatian.conllu data/Human/Human-swedish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-croatian.conllu Human-tamil.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-croatian.conllu data/Human/Human-tamil.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-croatian.conllu Human-telugu.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-croatian.conllu data/Human/Human-telugu.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-croatian.conllu Human-classical_chinese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-croatian.conllu data/Human/Human-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-latin.conllu Human-latvian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-latin.conllu data/Human/Human-latvian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-latin.conllu Human-lithuanian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-latin.conllu data/Human/Human-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-latin.conllu Human-polish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-latin.conllu data/Human/Human-polish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-latin.conllu Human-sanskrit.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-latin.conllu data/Human/Human-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-latin.conllu Human-swedish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-latin.conllu data/Human/Human-swedish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-latin.conllu Human-tamil.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-latin.conllu data/Human/Human-tamil.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-latin.conllu Human-telugu.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-latin.conllu data/Human/Human-telugu.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-latin.conllu Human-classical_chinese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-latin.conllu data/Human/Human-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-latvian.conllu Human-lithuanian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-latvian.conllu data/Human/Human-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-latvian.conllu Human-polish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-latvian.conllu data/Human/Human-polish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-latvian.conllu Human-sanskrit.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-latvian.conllu data/Human/Human-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-latvian.conllu Human-swedish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-latvian.conllu data/Human/Human-swedish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-latvian.conllu Human-tamil.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-latvian.conllu data/Human/Human-tamil.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-latvian.conllu Human-telugu.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-latvian.conllu data/Human/Human-telugu.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-latvian.conllu Human-classical_chinese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-latvian.conllu data/Human/Human-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-lithuanian.conllu Human-polish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-lithuanian.conllu data/Human/Human-polish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-lithuanian.conllu Human-sanskrit.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-lithuanian.conllu data/Human/Human-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-lithuanian.conllu Human-swedish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-lithuanian.conllu data/Human/Human-swedish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-lithuanian.conllu Human-tamil.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-lithuanian.conllu data/Human/Human-tamil.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-lithuanian.conllu Human-telugu.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-lithuanian.conllu data/Human/Human-telugu.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-lithuanian.conllu Human-classical_chinese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-lithuanian.conllu data/Human/Human-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-polish.conllu Human-sanskrit.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-polish.conllu data/Human/Human-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-polish.conllu Human-swedish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-polish.conllu data/Human/Human-swedish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-polish.conllu Human-tamil.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-polish.conllu data/Human/Human-tamil.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-polish.conllu Human-telugu.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-polish.conllu data/Human/Human-telugu.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-polish.conllu Human-classical_chinese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-polish.conllu data/Human/Human-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-sanskrit.conllu Human-swedish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-sanskrit.conllu data/Human/Human-swedish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-sanskrit.conllu Human-tamil.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-sanskrit.conllu data/Human/Human-tamil.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-sanskrit.conllu Human-telugu.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-sanskrit.conllu data/Human/Human-telugu.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-sanskrit.conllu Human-classical_chinese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-sanskrit.conllu data/Human/Human-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-swedish.conllu Human-tamil.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-swedish.conllu data/Human/Human-tamil.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-swedish.conllu Human-telugu.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-swedish.conllu data/Human/Human-telugu.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-swedish.conllu Human-classical_chinese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-swedish.conllu data/Human/Human-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-tamil.conllu Human-telugu.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-tamil.conllu data/Human/Human-telugu.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-tamil.conllu Human-classical_chinese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-tamil.conllu data/Human/Human-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-telugu.conllu Human-classical_chinese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-telugu.conllu data/Human/Human-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-bulgarian.conllu Human-czech.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-bulgarian.conllu data/Human/Human-czech.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-bulgarian.conllu Human-welsh.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-bulgarian.conllu data/Human/Human-welsh.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-bulgarian.conllu Human-greek.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-bulgarian.conllu data/Human/Human-greek.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-bulgarian.conllu Human-spanish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-bulgarian.conllu data/Human/Human-spanish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-bulgarian.conllu Human-basque.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-bulgarian.conllu data/Human/Human-basque.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-bulgarian.conllu Human-persian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-bulgarian.conllu data/Human/Human-persian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-bulgarian.conllu Human-armenian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-bulgarian.conllu data/Human/Human-armenian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-bulgarian.conllu Human-indonesian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-bulgarian.conllu data/Human/Human-indonesian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-bulgarian.conllu Human-kazakh.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-bulgarian.conllu data/Human/Human-kazakh.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-bulgarian.conllu Human-dutch.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-bulgarian.conllu data/Human/Human-dutch.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-bulgarian.conllu Human-russian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-bulgarian.conllu data/Human/Human-russian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-bulgarian.conllu Human-slovenian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-bulgarian.conllu data/Human/Human-slovenian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-bulgarian.conllu Human-serbian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-bulgarian.conllu data/Human/Human-serbian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-bulgarian.conllu Human-ukrainian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-bulgarian.conllu data/Human/Human-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-bulgarian.conllu Human-vietnamese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-bulgarian.conllu data/Human/Human-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-bulgarian.conllu Human-chinese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-bulgarian.conllu data/Human/Human-chinese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-czech.conllu Human-welsh.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-czech.conllu data/Human/Human-welsh.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-czech.conllu Human-greek.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-czech.conllu data/Human/Human-greek.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-czech.conllu Human-spanish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-czech.conllu data/Human/Human-spanish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-czech.conllu Human-basque.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-czech.conllu data/Human/Human-basque.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-czech.conllu Human-persian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-czech.conllu data/Human/Human-persian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-czech.conllu Human-armenian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-czech.conllu data/Human/Human-armenian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-czech.conllu Human-indonesian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-czech.conllu data/Human/Human-indonesian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-czech.conllu Human-kazakh.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-czech.conllu data/Human/Human-kazakh.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-czech.conllu Human-dutch.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-czech.conllu data/Human/Human-dutch.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-czech.conllu Human-russian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-czech.conllu data/Human/Human-russian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-czech.conllu Human-slovenian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-czech.conllu data/Human/Human-slovenian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-czech.conllu Human-serbian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-czech.conllu data/Human/Human-serbian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-czech.conllu Human-ukrainian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-czech.conllu data/Human/Human-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-czech.conllu Human-vietnamese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-czech.conllu data/Human/Human-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-czech.conllu Human-chinese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-czech.conllu data/Human/Human-chinese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-welsh.conllu Human-greek.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-welsh.conllu data/Human/Human-greek.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-welsh.conllu Human-spanish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-welsh.conllu data/Human/Human-spanish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-welsh.conllu Human-basque.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-welsh.conllu data/Human/Human-basque.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-welsh.conllu Human-persian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-welsh.conllu data/Human/Human-persian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-welsh.conllu Human-armenian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-welsh.conllu data/Human/Human-armenian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-welsh.conllu Human-indonesian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-welsh.conllu data/Human/Human-indonesian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-welsh.conllu Human-kazakh.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-welsh.conllu data/Human/Human-kazakh.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-welsh.conllu Human-dutch.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-welsh.conllu data/Human/Human-dutch.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-welsh.conllu Human-russian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-welsh.conllu data/Human/Human-russian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-welsh.conllu Human-slovenian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-welsh.conllu data/Human/Human-slovenian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-welsh.conllu Human-serbian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-welsh.conllu data/Human/Human-serbian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-welsh.conllu Human-ukrainian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-welsh.conllu data/Human/Human-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-welsh.conllu Human-vietnamese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-welsh.conllu data/Human/Human-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-welsh.conllu Human-chinese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-welsh.conllu data/Human/Human-chinese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-greek.conllu Human-spanish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-greek.conllu data/Human/Human-spanish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-greek.conllu Human-basque.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-greek.conllu data/Human/Human-basque.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-greek.conllu Human-persian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-greek.conllu data/Human/Human-persian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-greek.conllu Human-armenian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-greek.conllu data/Human/Human-armenian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-greek.conllu Human-indonesian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-greek.conllu data/Human/Human-indonesian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-greek.conllu Human-kazakh.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-greek.conllu data/Human/Human-kazakh.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-greek.conllu Human-dutch.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-greek.conllu data/Human/Human-dutch.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-greek.conllu Human-russian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-greek.conllu data/Human/Human-russian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-greek.conllu Human-slovenian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-greek.conllu data/Human/Human-slovenian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-greek.conllu Human-serbian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-greek.conllu data/Human/Human-serbian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-greek.conllu Human-ukrainian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-greek.conllu data/Human/Human-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-greek.conllu Human-vietnamese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-greek.conllu data/Human/Human-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-greek.conllu Human-chinese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-greek.conllu data/Human/Human-chinese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-spanish.conllu Human-basque.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-spanish.conllu data/Human/Human-basque.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-spanish.conllu Human-persian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-spanish.conllu data/Human/Human-persian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-spanish.conllu Human-armenian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-spanish.conllu data/Human/Human-armenian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-spanish.conllu Human-indonesian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-spanish.conllu data/Human/Human-indonesian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-spanish.conllu Human-kazakh.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-spanish.conllu data/Human/Human-kazakh.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-spanish.conllu Human-dutch.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-spanish.conllu data/Human/Human-dutch.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-spanish.conllu Human-russian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-spanish.conllu data/Human/Human-russian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-spanish.conllu Human-slovenian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-spanish.conllu data/Human/Human-slovenian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-spanish.conllu Human-serbian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-spanish.conllu data/Human/Human-serbian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-spanish.conllu Human-ukrainian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-spanish.conllu data/Human/Human-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-spanish.conllu Human-vietnamese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-spanish.conllu data/Human/Human-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-spanish.conllu Human-chinese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-spanish.conllu data/Human/Human-chinese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-basque.conllu Human-persian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-basque.conllu data/Human/Human-persian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-basque.conllu Human-armenian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-basque.conllu data/Human/Human-armenian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-basque.conllu Human-indonesian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-basque.conllu data/Human/Human-indonesian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-basque.conllu Human-kazakh.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-basque.conllu data/Human/Human-kazakh.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-basque.conllu Human-dutch.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-basque.conllu data/Human/Human-dutch.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-basque.conllu Human-russian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-basque.conllu data/Human/Human-russian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-basque.conllu Human-slovenian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-basque.conllu data/Human/Human-slovenian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-basque.conllu Human-serbian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-basque.conllu data/Human/Human-serbian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-basque.conllu Human-ukrainian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-basque.conllu data/Human/Human-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-basque.conllu Human-vietnamese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-basque.conllu data/Human/Human-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-basque.conllu Human-chinese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-basque.conllu data/Human/Human-chinese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-persian.conllu Human-armenian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-persian.conllu data/Human/Human-armenian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-persian.conllu Human-indonesian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-persian.conllu data/Human/Human-indonesian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-persian.conllu Human-kazakh.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-persian.conllu data/Human/Human-kazakh.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-persian.conllu Human-dutch.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-persian.conllu data/Human/Human-dutch.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-persian.conllu Human-russian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-persian.conllu data/Human/Human-russian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-persian.conllu Human-slovenian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-persian.conllu data/Human/Human-slovenian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-persian.conllu Human-serbian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-persian.conllu data/Human/Human-serbian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-persian.conllu Human-ukrainian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-persian.conllu data/Human/Human-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-persian.conllu Human-vietnamese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-persian.conllu data/Human/Human-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-persian.conllu Human-chinese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-persian.conllu data/Human/Human-chinese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-armenian.conllu Human-indonesian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-armenian.conllu data/Human/Human-indonesian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-armenian.conllu Human-kazakh.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-armenian.conllu data/Human/Human-kazakh.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-armenian.conllu Human-dutch.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-armenian.conllu data/Human/Human-dutch.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-armenian.conllu Human-russian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-armenian.conllu data/Human/Human-russian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-armenian.conllu Human-slovenian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-armenian.conllu data/Human/Human-slovenian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-armenian.conllu Human-serbian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-armenian.conllu data/Human/Human-serbian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-armenian.conllu Human-ukrainian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-armenian.conllu data/Human/Human-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-armenian.conllu Human-vietnamese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-armenian.conllu data/Human/Human-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-armenian.conllu Human-chinese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-armenian.conllu data/Human/Human-chinese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-indonesian.conllu Human-kazakh.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-indonesian.conllu data/Human/Human-kazakh.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-indonesian.conllu Human-dutch.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-indonesian.conllu data/Human/Human-dutch.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-indonesian.conllu Human-russian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-indonesian.conllu data/Human/Human-russian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-indonesian.conllu Human-slovenian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-indonesian.conllu data/Human/Human-slovenian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-indonesian.conllu Human-serbian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-indonesian.conllu data/Human/Human-serbian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-indonesian.conllu Human-ukrainian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-indonesian.conllu data/Human/Human-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-indonesian.conllu Human-vietnamese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-indonesian.conllu data/Human/Human-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-indonesian.conllu Human-chinese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-indonesian.conllu data/Human/Human-chinese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-kazakh.conllu Human-dutch.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-kazakh.conllu data/Human/Human-dutch.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-kazakh.conllu Human-russian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-kazakh.conllu data/Human/Human-russian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-kazakh.conllu Human-slovenian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-kazakh.conllu data/Human/Human-slovenian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-kazakh.conllu Human-serbian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-kazakh.conllu data/Human/Human-serbian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-kazakh.conllu Human-ukrainian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-kazakh.conllu data/Human/Human-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-kazakh.conllu Human-vietnamese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-kazakh.conllu data/Human/Human-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-kazakh.conllu Human-chinese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-kazakh.conllu data/Human/Human-chinese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-dutch.conllu Human-russian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-dutch.conllu data/Human/Human-russian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-dutch.conllu Human-slovenian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-dutch.conllu data/Human/Human-slovenian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-dutch.conllu Human-serbian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-dutch.conllu data/Human/Human-serbian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-dutch.conllu Human-ukrainian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-dutch.conllu data/Human/Human-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-dutch.conllu Human-vietnamese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-dutch.conllu data/Human/Human-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-dutch.conllu Human-chinese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-dutch.conllu data/Human/Human-chinese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-russian.conllu Human-slovenian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-russian.conllu data/Human/Human-slovenian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-russian.conllu Human-serbian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-russian.conllu data/Human/Human-serbian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-russian.conllu Human-ukrainian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-russian.conllu data/Human/Human-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-russian.conllu Human-vietnamese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-russian.conllu data/Human/Human-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-russian.conllu Human-chinese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-russian.conllu data/Human/Human-chinese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-slovenian.conllu Human-serbian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-slovenian.conllu data/Human/Human-serbian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-slovenian.conllu Human-ukrainian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-slovenian.conllu data/Human/Human-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-slovenian.conllu Human-vietnamese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-slovenian.conllu data/Human/Human-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-slovenian.conllu Human-chinese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-slovenian.conllu data/Human/Human-chinese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-serbian.conllu Human-ukrainian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-serbian.conllu data/Human/Human-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-serbian.conllu Human-vietnamese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-serbian.conllu data/Human/Human-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-serbian.conllu Human-chinese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-serbian.conllu data/Human/Human-chinese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-ukrainian.conllu Human-vietnamese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-ukrainian.conllu data/Human/Human-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-ukrainian.conllu Human-chinese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-ukrainian.conllu data/Human/Human-chinese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-vietnamese.conllu Human-chinese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-vietnamese.conllu data/Human/Human-chinese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-english.conllu Human-afrikaans.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-english.conllu data/Human/Human-afrikaans.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-english.conllu Human-arabic.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-english.conllu data/Human/Human-arabic.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-english.conllu Human-catalan.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-english.conllu data/Human/Human-catalan.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-english.conllu Human-german.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-english.conllu data/Human/Human-german.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-english.conllu Human-french.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-english.conllu data/Human/Human-french.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-english.conllu Human-galician.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-english.conllu data/Human/Human-galician.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-english.conllu Human-japanese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-english.conllu data/Human/Human-japanese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-english.conllu Human-portuguese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-english.conllu data/Human/Human-portuguese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-english.conllu Human-romanian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-english.conllu data/Human/Human-romanian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-english.conllu Human-slovak.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-english.conllu data/Human/Human-slovak.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-english.conllu Human-finnish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-english.conllu data/Human/Human-finnish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-english.conllu Human-turkish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-english.conllu data/Human/Human-turkish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-afrikaans.conllu Human-arabic.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-afrikaans.conllu data/Human/Human-arabic.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-afrikaans.conllu Human-catalan.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-afrikaans.conllu data/Human/Human-catalan.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-afrikaans.conllu Human-german.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-afrikaans.conllu data/Human/Human-german.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-afrikaans.conllu Human-french.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-afrikaans.conllu data/Human/Human-french.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-afrikaans.conllu Human-galician.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-afrikaans.conllu data/Human/Human-galician.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-afrikaans.conllu Human-japanese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-afrikaans.conllu data/Human/Human-japanese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-afrikaans.conllu Human-portuguese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-afrikaans.conllu data/Human/Human-portuguese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-afrikaans.conllu Human-romanian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-afrikaans.conllu data/Human/Human-romanian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-afrikaans.conllu Human-slovak.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-afrikaans.conllu data/Human/Human-slovak.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-afrikaans.conllu Human-finnish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-afrikaans.conllu data/Human/Human-finnish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-afrikaans.conllu Human-turkish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-afrikaans.conllu data/Human/Human-turkish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-arabic.conllu Human-catalan.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-arabic.conllu data/Human/Human-catalan.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-arabic.conllu Human-german.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-arabic.conllu data/Human/Human-german.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-arabic.conllu Human-french.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-arabic.conllu data/Human/Human-french.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-arabic.conllu Human-galician.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-arabic.conllu data/Human/Human-galician.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-arabic.conllu Human-japanese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-arabic.conllu data/Human/Human-japanese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-arabic.conllu Human-portuguese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-arabic.conllu data/Human/Human-portuguese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-arabic.conllu Human-romanian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-arabic.conllu data/Human/Human-romanian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-arabic.conllu Human-slovak.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-arabic.conllu data/Human/Human-slovak.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-arabic.conllu Human-finnish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-arabic.conllu data/Human/Human-finnish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-arabic.conllu Human-turkish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-arabic.conllu data/Human/Human-turkish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-catalan.conllu Human-german.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-catalan.conllu data/Human/Human-german.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-catalan.conllu Human-french.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-catalan.conllu data/Human/Human-french.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-catalan.conllu Human-galician.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-catalan.conllu data/Human/Human-galician.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-catalan.conllu Human-japanese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-catalan.conllu data/Human/Human-japanese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-catalan.conllu Human-portuguese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-catalan.conllu data/Human/Human-portuguese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-catalan.conllu Human-romanian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-catalan.conllu data/Human/Human-romanian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-catalan.conllu Human-slovak.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-catalan.conllu data/Human/Human-slovak.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-catalan.conllu Human-finnish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-catalan.conllu data/Human/Human-finnish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-catalan.conllu Human-turkish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-catalan.conllu data/Human/Human-turkish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-german.conllu Human-french.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-german.conllu data/Human/Human-french.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-german.conllu Human-galician.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-german.conllu data/Human/Human-galician.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-german.conllu Human-japanese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-german.conllu data/Human/Human-japanese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-german.conllu Human-portuguese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-german.conllu data/Human/Human-portuguese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-german.conllu Human-romanian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-german.conllu data/Human/Human-romanian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-german.conllu Human-slovak.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-german.conllu data/Human/Human-slovak.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-german.conllu Human-finnish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-german.conllu data/Human/Human-finnish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-german.conllu Human-turkish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-german.conllu data/Human/Human-turkish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-french.conllu Human-galician.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-french.conllu data/Human/Human-galician.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-french.conllu Human-japanese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-french.conllu data/Human/Human-japanese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-french.conllu Human-portuguese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-french.conllu data/Human/Human-portuguese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-french.conllu Human-romanian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-french.conllu data/Human/Human-romanian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-french.conllu Human-slovak.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-french.conllu data/Human/Human-slovak.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-french.conllu Human-finnish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-french.conllu data/Human/Human-finnish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-french.conllu Human-turkish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-french.conllu data/Human/Human-turkish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-galician.conllu Human-japanese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-galician.conllu data/Human/Human-japanese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-galician.conllu Human-portuguese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-galician.conllu data/Human/Human-portuguese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-galician.conllu Human-romanian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-galician.conllu data/Human/Human-romanian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-galician.conllu Human-slovak.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-galician.conllu data/Human/Human-slovak.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-galician.conllu Human-finnish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-galician.conllu data/Human/Human-finnish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-galician.conllu Human-turkish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-galician.conllu data/Human/Human-turkish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-japanese.conllu Human-portuguese.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-japanese.conllu data/Human/Human-portuguese.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-japanese.conllu Human-romanian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-japanese.conllu data/Human/Human-romanian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-japanese.conllu Human-slovak.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-japanese.conllu data/Human/Human-slovak.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-japanese.conllu Human-finnish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-japanese.conllu data/Human/Human-finnish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-japanese.conllu Human-turkish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-japanese.conllu data/Human/Human-turkish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-portuguese.conllu Human-romanian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-portuguese.conllu data/Human/Human-romanian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-portuguese.conllu Human-slovak.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-portuguese.conllu data/Human/Human-slovak.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-portuguese.conllu Human-finnish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-portuguese.conllu data/Human/Human-finnish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-portuguese.conllu Human-turkish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-portuguese.conllu data/Human/Human-turkish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-romanian.conllu Human-slovak.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-romanian.conllu data/Human/Human-slovak.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-romanian.conllu Human-finnish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-romanian.conllu data/Human/Human-finnish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-romanian.conllu Human-turkish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-romanian.conllu data/Human/Human-turkish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-slovak.conllu Human-finnish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-slovak.conllu data/Human/Human-finnish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-slovak.conllu Human-turkish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-slovak.conllu data/Human/Human-turkish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-finnish.conllu Human-turkish.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-finnish.conllu data/Human/Human-turkish.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
echo Human-hebrew.conllu Human-hungarian.conllu >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
gfud cosine-similarity data/Human/Human-hebrew.conllu data/Human/Human-hungarian.conllu DEPREL >> cosine-sim-per-topic/Human-cosine-sim.txt ; 
} 
topic_combinations