#! /bin/bash 
function topic_combinations { 
echo Iraq-north_sami.conllu Iraq-scottish_gaelic.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-north_sami.conllu data/Iraq/Iraq-scottish_gaelic.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-north_sami.conllu Iraq-gothic.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-north_sami.conllu data/Iraq/Iraq-gothic.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-north_sami.conllu Iraq-maltese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-north_sami.conllu data/Iraq/Iraq-maltese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-north_sami.conllu Iraq-sanskrit.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-north_sami.conllu data/Iraq/Iraq-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-north_sami.conllu Iraq-classical_chinese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-north_sami.conllu data/Iraq/Iraq-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-north_sami.conllu Iraq-wolof.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-north_sami.conllu data/Iraq/Iraq-wolof.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-scottish_gaelic.conllu Iraq-gothic.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-scottish_gaelic.conllu data/Iraq/Iraq-gothic.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-scottish_gaelic.conllu Iraq-maltese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-scottish_gaelic.conllu data/Iraq/Iraq-maltese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-scottish_gaelic.conllu Iraq-sanskrit.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-scottish_gaelic.conllu data/Iraq/Iraq-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-scottish_gaelic.conllu Iraq-classical_chinese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-scottish_gaelic.conllu data/Iraq/Iraq-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-scottish_gaelic.conllu Iraq-wolof.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-scottish_gaelic.conllu data/Iraq/Iraq-wolof.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-gothic.conllu Iraq-maltese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-gothic.conllu data/Iraq/Iraq-maltese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-gothic.conllu Iraq-sanskrit.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-gothic.conllu data/Iraq/Iraq-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-gothic.conllu Iraq-classical_chinese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-gothic.conllu data/Iraq/Iraq-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-gothic.conllu Iraq-wolof.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-gothic.conllu data/Iraq/Iraq-wolof.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-maltese.conllu Iraq-sanskrit.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-maltese.conllu data/Iraq/Iraq-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-maltese.conllu Iraq-classical_chinese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-maltese.conllu data/Iraq/Iraq-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-maltese.conllu Iraq-wolof.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-maltese.conllu data/Iraq/Iraq-wolof.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-sanskrit.conllu Iraq-classical_chinese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-sanskrit.conllu data/Iraq/Iraq-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-sanskrit.conllu Iraq-wolof.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-sanskrit.conllu data/Iraq/Iraq-wolof.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-classical_chinese.conllu Iraq-wolof.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-classical_chinese.conllu data/Iraq/Iraq-wolof.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-afrikaans.conllu Iraq-welsh.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-afrikaans.conllu data/Iraq/Iraq-welsh.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-afrikaans.conllu Iraq-irish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-afrikaans.conllu data/Iraq/Iraq-irish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-afrikaans.conllu Iraq-hindi.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-afrikaans.conllu data/Iraq/Iraq-hindi.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-afrikaans.conllu Iraq-croatian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-afrikaans.conllu data/Iraq/Iraq-croatian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-afrikaans.conllu Iraq-indonesian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-afrikaans.conllu data/Iraq/Iraq-indonesian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-afrikaans.conllu Iraq-latin.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-afrikaans.conllu data/Iraq/Iraq-latin.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-afrikaans.conllu Iraq-lithuanian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-afrikaans.conllu data/Iraq/Iraq-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-afrikaans.conllu Iraq-marathi.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-afrikaans.conllu data/Iraq/Iraq-marathi.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-afrikaans.conllu Iraq-romanian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-afrikaans.conllu data/Iraq/Iraq-romanian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-afrikaans.conllu Iraq-slovak.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-afrikaans.conllu data/Iraq/Iraq-slovak.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-afrikaans.conllu Iraq-slovenian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-afrikaans.conllu data/Iraq/Iraq-slovenian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-afrikaans.conllu Iraq-tamil.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-afrikaans.conllu data/Iraq/Iraq-tamil.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-afrikaans.conllu Iraq-uyghur.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-afrikaans.conllu data/Iraq/Iraq-uyghur.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-welsh.conllu Iraq-irish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-welsh.conllu data/Iraq/Iraq-irish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-welsh.conllu Iraq-hindi.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-welsh.conllu data/Iraq/Iraq-hindi.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-welsh.conllu Iraq-croatian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-welsh.conllu data/Iraq/Iraq-croatian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-welsh.conllu Iraq-indonesian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-welsh.conllu data/Iraq/Iraq-indonesian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-welsh.conllu Iraq-latin.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-welsh.conllu data/Iraq/Iraq-latin.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-welsh.conllu Iraq-lithuanian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-welsh.conllu data/Iraq/Iraq-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-welsh.conllu Iraq-marathi.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-welsh.conllu data/Iraq/Iraq-marathi.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-welsh.conllu Iraq-romanian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-welsh.conllu data/Iraq/Iraq-romanian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-welsh.conllu Iraq-slovak.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-welsh.conllu data/Iraq/Iraq-slovak.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-welsh.conllu Iraq-slovenian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-welsh.conllu data/Iraq/Iraq-slovenian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-welsh.conllu Iraq-tamil.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-welsh.conllu data/Iraq/Iraq-tamil.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-welsh.conllu Iraq-uyghur.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-welsh.conllu data/Iraq/Iraq-uyghur.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-irish.conllu Iraq-hindi.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-irish.conllu data/Iraq/Iraq-hindi.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-irish.conllu Iraq-croatian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-irish.conllu data/Iraq/Iraq-croatian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-irish.conllu Iraq-indonesian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-irish.conllu data/Iraq/Iraq-indonesian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-irish.conllu Iraq-latin.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-irish.conllu data/Iraq/Iraq-latin.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-irish.conllu Iraq-lithuanian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-irish.conllu data/Iraq/Iraq-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-irish.conllu Iraq-marathi.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-irish.conllu data/Iraq/Iraq-marathi.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-irish.conllu Iraq-romanian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-irish.conllu data/Iraq/Iraq-romanian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-irish.conllu Iraq-slovak.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-irish.conllu data/Iraq/Iraq-slovak.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-irish.conllu Iraq-slovenian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-irish.conllu data/Iraq/Iraq-slovenian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-irish.conllu Iraq-tamil.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-irish.conllu data/Iraq/Iraq-tamil.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-irish.conllu Iraq-uyghur.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-irish.conllu data/Iraq/Iraq-uyghur.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-hindi.conllu Iraq-croatian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-hindi.conllu data/Iraq/Iraq-croatian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-hindi.conllu Iraq-indonesian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-hindi.conllu data/Iraq/Iraq-indonesian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-hindi.conllu Iraq-latin.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-hindi.conllu data/Iraq/Iraq-latin.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-hindi.conllu Iraq-lithuanian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-hindi.conllu data/Iraq/Iraq-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-hindi.conllu Iraq-marathi.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-hindi.conllu data/Iraq/Iraq-marathi.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-hindi.conllu Iraq-romanian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-hindi.conllu data/Iraq/Iraq-romanian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-hindi.conllu Iraq-slovak.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-hindi.conllu data/Iraq/Iraq-slovak.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-hindi.conllu Iraq-slovenian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-hindi.conllu data/Iraq/Iraq-slovenian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-hindi.conllu Iraq-tamil.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-hindi.conllu data/Iraq/Iraq-tamil.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-hindi.conllu Iraq-uyghur.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-hindi.conllu data/Iraq/Iraq-uyghur.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-croatian.conllu Iraq-indonesian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-croatian.conllu data/Iraq/Iraq-indonesian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-croatian.conllu Iraq-latin.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-croatian.conllu data/Iraq/Iraq-latin.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-croatian.conllu Iraq-lithuanian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-croatian.conllu data/Iraq/Iraq-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-croatian.conllu Iraq-marathi.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-croatian.conllu data/Iraq/Iraq-marathi.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-croatian.conllu Iraq-romanian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-croatian.conllu data/Iraq/Iraq-romanian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-croatian.conllu Iraq-slovak.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-croatian.conllu data/Iraq/Iraq-slovak.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-croatian.conllu Iraq-slovenian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-croatian.conllu data/Iraq/Iraq-slovenian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-croatian.conllu Iraq-tamil.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-croatian.conllu data/Iraq/Iraq-tamil.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-croatian.conllu Iraq-uyghur.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-croatian.conllu data/Iraq/Iraq-uyghur.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-indonesian.conllu Iraq-latin.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-indonesian.conllu data/Iraq/Iraq-latin.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-indonesian.conllu Iraq-lithuanian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-indonesian.conllu data/Iraq/Iraq-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-indonesian.conllu Iraq-marathi.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-indonesian.conllu data/Iraq/Iraq-marathi.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-indonesian.conllu Iraq-romanian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-indonesian.conllu data/Iraq/Iraq-romanian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-indonesian.conllu Iraq-slovak.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-indonesian.conllu data/Iraq/Iraq-slovak.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-indonesian.conllu Iraq-slovenian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-indonesian.conllu data/Iraq/Iraq-slovenian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-indonesian.conllu Iraq-tamil.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-indonesian.conllu data/Iraq/Iraq-tamil.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-indonesian.conllu Iraq-uyghur.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-indonesian.conllu data/Iraq/Iraq-uyghur.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-latin.conllu Iraq-lithuanian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-latin.conllu data/Iraq/Iraq-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-latin.conllu Iraq-marathi.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-latin.conllu data/Iraq/Iraq-marathi.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-latin.conllu Iraq-romanian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-latin.conllu data/Iraq/Iraq-romanian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-latin.conllu Iraq-slovak.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-latin.conllu data/Iraq/Iraq-slovak.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-latin.conllu Iraq-slovenian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-latin.conllu data/Iraq/Iraq-slovenian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-latin.conllu Iraq-tamil.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-latin.conllu data/Iraq/Iraq-tamil.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-latin.conllu Iraq-uyghur.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-latin.conllu data/Iraq/Iraq-uyghur.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-lithuanian.conllu Iraq-marathi.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-lithuanian.conllu data/Iraq/Iraq-marathi.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-lithuanian.conllu Iraq-romanian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-lithuanian.conllu data/Iraq/Iraq-romanian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-lithuanian.conllu Iraq-slovak.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-lithuanian.conllu data/Iraq/Iraq-slovak.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-lithuanian.conllu Iraq-slovenian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-lithuanian.conllu data/Iraq/Iraq-slovenian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-lithuanian.conllu Iraq-tamil.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-lithuanian.conllu data/Iraq/Iraq-tamil.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-lithuanian.conllu Iraq-uyghur.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-lithuanian.conllu data/Iraq/Iraq-uyghur.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-marathi.conllu Iraq-romanian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-marathi.conllu data/Iraq/Iraq-romanian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-marathi.conllu Iraq-slovak.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-marathi.conllu data/Iraq/Iraq-slovak.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-marathi.conllu Iraq-slovenian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-marathi.conllu data/Iraq/Iraq-slovenian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-marathi.conllu Iraq-tamil.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-marathi.conllu data/Iraq/Iraq-tamil.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-marathi.conllu Iraq-uyghur.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-marathi.conllu data/Iraq/Iraq-uyghur.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-romanian.conllu Iraq-slovak.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-romanian.conllu data/Iraq/Iraq-slovak.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-romanian.conllu Iraq-slovenian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-romanian.conllu data/Iraq/Iraq-slovenian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-romanian.conllu Iraq-tamil.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-romanian.conllu data/Iraq/Iraq-tamil.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-romanian.conllu Iraq-uyghur.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-romanian.conllu data/Iraq/Iraq-uyghur.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-slovak.conllu Iraq-slovenian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-slovak.conllu data/Iraq/Iraq-slovenian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-slovak.conllu Iraq-tamil.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-slovak.conllu data/Iraq/Iraq-tamil.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-slovak.conllu Iraq-uyghur.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-slovak.conllu data/Iraq/Iraq-uyghur.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-slovenian.conllu Iraq-tamil.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-slovenian.conllu data/Iraq/Iraq-tamil.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-slovenian.conllu Iraq-uyghur.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-slovenian.conllu data/Iraq/Iraq-uyghur.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-tamil.conllu Iraq-uyghur.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-tamil.conllu data/Iraq/Iraq-uyghur.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-belarusian.conllu Iraq-bulgarian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-belarusian.conllu data/Iraq/Iraq-bulgarian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-belarusian.conllu Iraq-catalan.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-belarusian.conllu data/Iraq/Iraq-catalan.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-belarusian.conllu Iraq-danish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-belarusian.conllu data/Iraq/Iraq-danish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-belarusian.conllu Iraq-estonian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-belarusian.conllu data/Iraq/Iraq-estonian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-belarusian.conllu Iraq-greek.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-belarusian.conllu data/Iraq/Iraq-greek.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-belarusian.conllu Iraq-spanish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-belarusian.conllu data/Iraq/Iraq-spanish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-belarusian.conllu Iraq-basque.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-belarusian.conllu data/Iraq/Iraq-basque.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-belarusian.conllu Iraq-galician.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-belarusian.conllu data/Iraq/Iraq-galician.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-belarusian.conllu Iraq-korean.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-belarusian.conllu data/Iraq/Iraq-korean.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-belarusian.conllu Iraq-italian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-belarusian.conllu data/Iraq/Iraq-italian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-belarusian.conllu Iraq-hebrew.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-belarusian.conllu data/Iraq/Iraq-hebrew.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-belarusian.conllu Iraq-kazakh.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-belarusian.conllu data/Iraq/Iraq-kazakh.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-belarusian.conllu Iraq-latvian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-belarusian.conllu data/Iraq/Iraq-latvian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-belarusian.conllu Iraq-polish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-belarusian.conllu data/Iraq/Iraq-polish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-belarusian.conllu Iraq-portuguese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-belarusian.conllu data/Iraq/Iraq-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-belarusian.conllu Iraq-serbian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-belarusian.conllu data/Iraq/Iraq-serbian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-belarusian.conllu Iraq-finnish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-belarusian.conllu data/Iraq/Iraq-finnish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-belarusian.conllu Iraq-swedish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-belarusian.conllu data/Iraq/Iraq-swedish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-belarusian.conllu Iraq-turkish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-belarusian.conllu data/Iraq/Iraq-turkish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-belarusian.conllu Iraq-ukrainian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-belarusian.conllu data/Iraq/Iraq-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-belarusian.conllu Iraq-urdu.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-belarusian.conllu data/Iraq/Iraq-urdu.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-belarusian.conllu Iraq-vietnamese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-belarusian.conllu data/Iraq/Iraq-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-belarusian.conllu Iraq-chinese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-belarusian.conllu data/Iraq/Iraq-chinese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-bulgarian.conllu Iraq-catalan.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-bulgarian.conllu data/Iraq/Iraq-catalan.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-bulgarian.conllu Iraq-danish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-bulgarian.conllu data/Iraq/Iraq-danish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-bulgarian.conllu Iraq-estonian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-bulgarian.conllu data/Iraq/Iraq-estonian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-bulgarian.conllu Iraq-greek.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-bulgarian.conllu data/Iraq/Iraq-greek.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-bulgarian.conllu Iraq-spanish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-bulgarian.conllu data/Iraq/Iraq-spanish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-bulgarian.conllu Iraq-basque.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-bulgarian.conllu data/Iraq/Iraq-basque.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-bulgarian.conllu Iraq-galician.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-bulgarian.conllu data/Iraq/Iraq-galician.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-bulgarian.conllu Iraq-korean.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-bulgarian.conllu data/Iraq/Iraq-korean.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-bulgarian.conllu Iraq-italian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-bulgarian.conllu data/Iraq/Iraq-italian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-bulgarian.conllu Iraq-hebrew.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-bulgarian.conllu data/Iraq/Iraq-hebrew.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-bulgarian.conllu Iraq-kazakh.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-bulgarian.conllu data/Iraq/Iraq-kazakh.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-bulgarian.conllu Iraq-latvian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-bulgarian.conllu data/Iraq/Iraq-latvian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-bulgarian.conllu Iraq-polish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-bulgarian.conllu data/Iraq/Iraq-polish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-bulgarian.conllu Iraq-portuguese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-bulgarian.conllu data/Iraq/Iraq-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-bulgarian.conllu Iraq-serbian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-bulgarian.conllu data/Iraq/Iraq-serbian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-bulgarian.conllu Iraq-finnish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-bulgarian.conllu data/Iraq/Iraq-finnish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-bulgarian.conllu Iraq-swedish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-bulgarian.conllu data/Iraq/Iraq-swedish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-bulgarian.conllu Iraq-turkish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-bulgarian.conllu data/Iraq/Iraq-turkish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-bulgarian.conllu Iraq-ukrainian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-bulgarian.conllu data/Iraq/Iraq-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-bulgarian.conllu Iraq-urdu.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-bulgarian.conllu data/Iraq/Iraq-urdu.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-bulgarian.conllu Iraq-vietnamese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-bulgarian.conllu data/Iraq/Iraq-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-bulgarian.conllu Iraq-chinese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-bulgarian.conllu data/Iraq/Iraq-chinese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-catalan.conllu Iraq-danish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-catalan.conllu data/Iraq/Iraq-danish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-catalan.conllu Iraq-estonian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-catalan.conllu data/Iraq/Iraq-estonian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-catalan.conllu Iraq-greek.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-catalan.conllu data/Iraq/Iraq-greek.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-catalan.conllu Iraq-spanish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-catalan.conllu data/Iraq/Iraq-spanish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-catalan.conllu Iraq-basque.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-catalan.conllu data/Iraq/Iraq-basque.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-catalan.conllu Iraq-galician.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-catalan.conllu data/Iraq/Iraq-galician.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-catalan.conllu Iraq-korean.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-catalan.conllu data/Iraq/Iraq-korean.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-catalan.conllu Iraq-italian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-catalan.conllu data/Iraq/Iraq-italian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-catalan.conllu Iraq-hebrew.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-catalan.conllu data/Iraq/Iraq-hebrew.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-catalan.conllu Iraq-kazakh.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-catalan.conllu data/Iraq/Iraq-kazakh.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-catalan.conllu Iraq-latvian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-catalan.conllu data/Iraq/Iraq-latvian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-catalan.conllu Iraq-polish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-catalan.conllu data/Iraq/Iraq-polish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-catalan.conllu Iraq-portuguese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-catalan.conllu data/Iraq/Iraq-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-catalan.conllu Iraq-serbian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-catalan.conllu data/Iraq/Iraq-serbian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-catalan.conllu Iraq-finnish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-catalan.conllu data/Iraq/Iraq-finnish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-catalan.conllu Iraq-swedish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-catalan.conllu data/Iraq/Iraq-swedish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-catalan.conllu Iraq-turkish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-catalan.conllu data/Iraq/Iraq-turkish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-catalan.conllu Iraq-ukrainian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-catalan.conllu data/Iraq/Iraq-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-catalan.conllu Iraq-urdu.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-catalan.conllu data/Iraq/Iraq-urdu.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-catalan.conllu Iraq-vietnamese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-catalan.conllu data/Iraq/Iraq-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-catalan.conllu Iraq-chinese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-catalan.conllu data/Iraq/Iraq-chinese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-danish.conllu Iraq-estonian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-danish.conllu data/Iraq/Iraq-estonian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-danish.conllu Iraq-greek.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-danish.conllu data/Iraq/Iraq-greek.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-danish.conllu Iraq-spanish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-danish.conllu data/Iraq/Iraq-spanish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-danish.conllu Iraq-basque.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-danish.conllu data/Iraq/Iraq-basque.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-danish.conllu Iraq-galician.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-danish.conllu data/Iraq/Iraq-galician.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-danish.conllu Iraq-korean.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-danish.conllu data/Iraq/Iraq-korean.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-danish.conllu Iraq-italian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-danish.conllu data/Iraq/Iraq-italian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-danish.conllu Iraq-hebrew.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-danish.conllu data/Iraq/Iraq-hebrew.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-danish.conllu Iraq-kazakh.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-danish.conllu data/Iraq/Iraq-kazakh.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-danish.conllu Iraq-latvian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-danish.conllu data/Iraq/Iraq-latvian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-danish.conllu Iraq-polish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-danish.conllu data/Iraq/Iraq-polish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-danish.conllu Iraq-portuguese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-danish.conllu data/Iraq/Iraq-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-danish.conllu Iraq-serbian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-danish.conllu data/Iraq/Iraq-serbian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-danish.conllu Iraq-finnish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-danish.conllu data/Iraq/Iraq-finnish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-danish.conllu Iraq-swedish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-danish.conllu data/Iraq/Iraq-swedish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-danish.conllu Iraq-turkish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-danish.conllu data/Iraq/Iraq-turkish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-danish.conllu Iraq-ukrainian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-danish.conllu data/Iraq/Iraq-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-danish.conllu Iraq-urdu.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-danish.conllu data/Iraq/Iraq-urdu.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-danish.conllu Iraq-vietnamese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-danish.conllu data/Iraq/Iraq-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-danish.conllu Iraq-chinese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-danish.conllu data/Iraq/Iraq-chinese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-estonian.conllu Iraq-greek.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-estonian.conllu data/Iraq/Iraq-greek.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-estonian.conllu Iraq-spanish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-estonian.conllu data/Iraq/Iraq-spanish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-estonian.conllu Iraq-basque.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-estonian.conllu data/Iraq/Iraq-basque.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-estonian.conllu Iraq-galician.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-estonian.conllu data/Iraq/Iraq-galician.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-estonian.conllu Iraq-korean.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-estonian.conllu data/Iraq/Iraq-korean.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-estonian.conllu Iraq-italian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-estonian.conllu data/Iraq/Iraq-italian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-estonian.conllu Iraq-hebrew.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-estonian.conllu data/Iraq/Iraq-hebrew.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-estonian.conllu Iraq-kazakh.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-estonian.conllu data/Iraq/Iraq-kazakh.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-estonian.conllu Iraq-latvian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-estonian.conllu data/Iraq/Iraq-latvian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-estonian.conllu Iraq-polish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-estonian.conllu data/Iraq/Iraq-polish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-estonian.conllu Iraq-portuguese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-estonian.conllu data/Iraq/Iraq-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-estonian.conllu Iraq-serbian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-estonian.conllu data/Iraq/Iraq-serbian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-estonian.conllu Iraq-finnish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-estonian.conllu data/Iraq/Iraq-finnish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-estonian.conllu Iraq-swedish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-estonian.conllu data/Iraq/Iraq-swedish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-estonian.conllu Iraq-turkish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-estonian.conllu data/Iraq/Iraq-turkish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-estonian.conllu Iraq-ukrainian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-estonian.conllu data/Iraq/Iraq-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-estonian.conllu Iraq-urdu.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-estonian.conllu data/Iraq/Iraq-urdu.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-estonian.conllu Iraq-vietnamese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-estonian.conllu data/Iraq/Iraq-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-estonian.conllu Iraq-chinese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-estonian.conllu data/Iraq/Iraq-chinese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-greek.conllu Iraq-spanish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-greek.conllu data/Iraq/Iraq-spanish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-greek.conllu Iraq-basque.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-greek.conllu data/Iraq/Iraq-basque.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-greek.conllu Iraq-galician.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-greek.conllu data/Iraq/Iraq-galician.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-greek.conllu Iraq-korean.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-greek.conllu data/Iraq/Iraq-korean.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-greek.conllu Iraq-italian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-greek.conllu data/Iraq/Iraq-italian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-greek.conllu Iraq-hebrew.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-greek.conllu data/Iraq/Iraq-hebrew.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-greek.conllu Iraq-kazakh.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-greek.conllu data/Iraq/Iraq-kazakh.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-greek.conllu Iraq-latvian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-greek.conllu data/Iraq/Iraq-latvian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-greek.conllu Iraq-polish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-greek.conllu data/Iraq/Iraq-polish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-greek.conllu Iraq-portuguese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-greek.conllu data/Iraq/Iraq-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-greek.conllu Iraq-serbian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-greek.conllu data/Iraq/Iraq-serbian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-greek.conllu Iraq-finnish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-greek.conllu data/Iraq/Iraq-finnish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-greek.conllu Iraq-swedish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-greek.conllu data/Iraq/Iraq-swedish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-greek.conllu Iraq-turkish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-greek.conllu data/Iraq/Iraq-turkish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-greek.conllu Iraq-ukrainian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-greek.conllu data/Iraq/Iraq-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-greek.conllu Iraq-urdu.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-greek.conllu data/Iraq/Iraq-urdu.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-greek.conllu Iraq-vietnamese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-greek.conllu data/Iraq/Iraq-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-greek.conllu Iraq-chinese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-greek.conllu data/Iraq/Iraq-chinese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-spanish.conllu Iraq-basque.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-spanish.conllu data/Iraq/Iraq-basque.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-spanish.conllu Iraq-galician.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-spanish.conllu data/Iraq/Iraq-galician.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-spanish.conllu Iraq-korean.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-spanish.conllu data/Iraq/Iraq-korean.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-spanish.conllu Iraq-italian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-spanish.conllu data/Iraq/Iraq-italian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-spanish.conllu Iraq-hebrew.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-spanish.conllu data/Iraq/Iraq-hebrew.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-spanish.conllu Iraq-kazakh.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-spanish.conllu data/Iraq/Iraq-kazakh.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-spanish.conllu Iraq-latvian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-spanish.conllu data/Iraq/Iraq-latvian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-spanish.conllu Iraq-polish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-spanish.conllu data/Iraq/Iraq-polish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-spanish.conllu Iraq-portuguese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-spanish.conllu data/Iraq/Iraq-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-spanish.conllu Iraq-serbian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-spanish.conllu data/Iraq/Iraq-serbian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-spanish.conllu Iraq-finnish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-spanish.conllu data/Iraq/Iraq-finnish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-spanish.conllu Iraq-swedish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-spanish.conllu data/Iraq/Iraq-swedish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-spanish.conllu Iraq-turkish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-spanish.conllu data/Iraq/Iraq-turkish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-spanish.conllu Iraq-ukrainian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-spanish.conllu data/Iraq/Iraq-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-spanish.conllu Iraq-urdu.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-spanish.conllu data/Iraq/Iraq-urdu.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-spanish.conllu Iraq-vietnamese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-spanish.conllu data/Iraq/Iraq-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-spanish.conllu Iraq-chinese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-spanish.conllu data/Iraq/Iraq-chinese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-basque.conllu Iraq-galician.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-basque.conllu data/Iraq/Iraq-galician.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-basque.conllu Iraq-korean.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-basque.conllu data/Iraq/Iraq-korean.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-basque.conllu Iraq-italian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-basque.conllu data/Iraq/Iraq-italian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-basque.conllu Iraq-hebrew.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-basque.conllu data/Iraq/Iraq-hebrew.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-basque.conllu Iraq-kazakh.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-basque.conllu data/Iraq/Iraq-kazakh.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-basque.conllu Iraq-latvian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-basque.conllu data/Iraq/Iraq-latvian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-basque.conllu Iraq-polish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-basque.conllu data/Iraq/Iraq-polish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-basque.conllu Iraq-portuguese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-basque.conllu data/Iraq/Iraq-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-basque.conllu Iraq-serbian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-basque.conllu data/Iraq/Iraq-serbian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-basque.conllu Iraq-finnish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-basque.conllu data/Iraq/Iraq-finnish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-basque.conllu Iraq-swedish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-basque.conllu data/Iraq/Iraq-swedish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-basque.conllu Iraq-turkish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-basque.conllu data/Iraq/Iraq-turkish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-basque.conllu Iraq-ukrainian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-basque.conllu data/Iraq/Iraq-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-basque.conllu Iraq-urdu.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-basque.conllu data/Iraq/Iraq-urdu.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-basque.conllu Iraq-vietnamese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-basque.conllu data/Iraq/Iraq-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-basque.conllu Iraq-chinese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-basque.conllu data/Iraq/Iraq-chinese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-galician.conllu Iraq-korean.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-galician.conllu data/Iraq/Iraq-korean.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-galician.conllu Iraq-italian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-galician.conllu data/Iraq/Iraq-italian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-galician.conllu Iraq-hebrew.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-galician.conllu data/Iraq/Iraq-hebrew.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-galician.conllu Iraq-kazakh.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-galician.conllu data/Iraq/Iraq-kazakh.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-galician.conllu Iraq-latvian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-galician.conllu data/Iraq/Iraq-latvian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-galician.conllu Iraq-polish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-galician.conllu data/Iraq/Iraq-polish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-galician.conllu Iraq-portuguese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-galician.conllu data/Iraq/Iraq-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-galician.conllu Iraq-serbian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-galician.conllu data/Iraq/Iraq-serbian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-galician.conllu Iraq-finnish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-galician.conllu data/Iraq/Iraq-finnish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-galician.conllu Iraq-swedish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-galician.conllu data/Iraq/Iraq-swedish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-galician.conllu Iraq-turkish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-galician.conllu data/Iraq/Iraq-turkish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-galician.conllu Iraq-ukrainian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-galician.conllu data/Iraq/Iraq-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-galician.conllu Iraq-urdu.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-galician.conllu data/Iraq/Iraq-urdu.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-galician.conllu Iraq-vietnamese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-galician.conllu data/Iraq/Iraq-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-galician.conllu Iraq-chinese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-galician.conllu data/Iraq/Iraq-chinese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-korean.conllu Iraq-italian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-korean.conllu data/Iraq/Iraq-italian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-korean.conllu Iraq-hebrew.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-korean.conllu data/Iraq/Iraq-hebrew.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-korean.conllu Iraq-kazakh.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-korean.conllu data/Iraq/Iraq-kazakh.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-korean.conllu Iraq-latvian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-korean.conllu data/Iraq/Iraq-latvian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-korean.conllu Iraq-polish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-korean.conllu data/Iraq/Iraq-polish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-korean.conllu Iraq-portuguese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-korean.conllu data/Iraq/Iraq-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-korean.conllu Iraq-serbian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-korean.conllu data/Iraq/Iraq-serbian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-korean.conllu Iraq-finnish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-korean.conllu data/Iraq/Iraq-finnish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-korean.conllu Iraq-swedish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-korean.conllu data/Iraq/Iraq-swedish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-korean.conllu Iraq-turkish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-korean.conllu data/Iraq/Iraq-turkish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-korean.conllu Iraq-ukrainian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-korean.conllu data/Iraq/Iraq-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-korean.conllu Iraq-urdu.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-korean.conllu data/Iraq/Iraq-urdu.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-korean.conllu Iraq-vietnamese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-korean.conllu data/Iraq/Iraq-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-korean.conllu Iraq-chinese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-korean.conllu data/Iraq/Iraq-chinese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-italian.conllu Iraq-hebrew.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-italian.conllu data/Iraq/Iraq-hebrew.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-italian.conllu Iraq-kazakh.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-italian.conllu data/Iraq/Iraq-kazakh.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-italian.conllu Iraq-latvian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-italian.conllu data/Iraq/Iraq-latvian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-italian.conllu Iraq-polish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-italian.conllu data/Iraq/Iraq-polish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-italian.conllu Iraq-portuguese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-italian.conllu data/Iraq/Iraq-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-italian.conllu Iraq-serbian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-italian.conllu data/Iraq/Iraq-serbian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-italian.conllu Iraq-finnish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-italian.conllu data/Iraq/Iraq-finnish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-italian.conllu Iraq-swedish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-italian.conllu data/Iraq/Iraq-swedish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-italian.conllu Iraq-turkish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-italian.conllu data/Iraq/Iraq-turkish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-italian.conllu Iraq-ukrainian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-italian.conllu data/Iraq/Iraq-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-italian.conllu Iraq-urdu.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-italian.conllu data/Iraq/Iraq-urdu.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-italian.conllu Iraq-vietnamese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-italian.conllu data/Iraq/Iraq-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-italian.conllu Iraq-chinese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-italian.conllu data/Iraq/Iraq-chinese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-hebrew.conllu Iraq-kazakh.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-hebrew.conllu data/Iraq/Iraq-kazakh.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-hebrew.conllu Iraq-latvian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-hebrew.conllu data/Iraq/Iraq-latvian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-hebrew.conllu Iraq-polish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-hebrew.conllu data/Iraq/Iraq-polish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-hebrew.conllu Iraq-portuguese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-hebrew.conllu data/Iraq/Iraq-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-hebrew.conllu Iraq-serbian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-hebrew.conllu data/Iraq/Iraq-serbian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-hebrew.conllu Iraq-finnish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-hebrew.conllu data/Iraq/Iraq-finnish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-hebrew.conllu Iraq-swedish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-hebrew.conllu data/Iraq/Iraq-swedish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-hebrew.conllu Iraq-turkish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-hebrew.conllu data/Iraq/Iraq-turkish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-hebrew.conllu Iraq-ukrainian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-hebrew.conllu data/Iraq/Iraq-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-hebrew.conllu Iraq-urdu.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-hebrew.conllu data/Iraq/Iraq-urdu.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-hebrew.conllu Iraq-vietnamese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-hebrew.conllu data/Iraq/Iraq-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-hebrew.conllu Iraq-chinese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-hebrew.conllu data/Iraq/Iraq-chinese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-kazakh.conllu Iraq-latvian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-kazakh.conllu data/Iraq/Iraq-latvian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-kazakh.conllu Iraq-polish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-kazakh.conllu data/Iraq/Iraq-polish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-kazakh.conllu Iraq-portuguese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-kazakh.conllu data/Iraq/Iraq-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-kazakh.conllu Iraq-serbian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-kazakh.conllu data/Iraq/Iraq-serbian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-kazakh.conllu Iraq-finnish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-kazakh.conllu data/Iraq/Iraq-finnish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-kazakh.conllu Iraq-swedish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-kazakh.conllu data/Iraq/Iraq-swedish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-kazakh.conllu Iraq-turkish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-kazakh.conllu data/Iraq/Iraq-turkish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-kazakh.conllu Iraq-ukrainian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-kazakh.conllu data/Iraq/Iraq-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-kazakh.conllu Iraq-urdu.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-kazakh.conllu data/Iraq/Iraq-urdu.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-kazakh.conllu Iraq-vietnamese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-kazakh.conllu data/Iraq/Iraq-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-kazakh.conllu Iraq-chinese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-kazakh.conllu data/Iraq/Iraq-chinese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-latvian.conllu Iraq-polish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-latvian.conllu data/Iraq/Iraq-polish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-latvian.conllu Iraq-portuguese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-latvian.conllu data/Iraq/Iraq-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-latvian.conllu Iraq-serbian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-latvian.conllu data/Iraq/Iraq-serbian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-latvian.conllu Iraq-finnish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-latvian.conllu data/Iraq/Iraq-finnish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-latvian.conllu Iraq-swedish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-latvian.conllu data/Iraq/Iraq-swedish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-latvian.conllu Iraq-turkish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-latvian.conllu data/Iraq/Iraq-turkish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-latvian.conllu Iraq-ukrainian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-latvian.conllu data/Iraq/Iraq-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-latvian.conllu Iraq-urdu.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-latvian.conllu data/Iraq/Iraq-urdu.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-latvian.conllu Iraq-vietnamese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-latvian.conllu data/Iraq/Iraq-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-latvian.conllu Iraq-chinese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-latvian.conllu data/Iraq/Iraq-chinese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-polish.conllu Iraq-portuguese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-polish.conllu data/Iraq/Iraq-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-polish.conllu Iraq-serbian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-polish.conllu data/Iraq/Iraq-serbian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-polish.conllu Iraq-finnish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-polish.conllu data/Iraq/Iraq-finnish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-polish.conllu Iraq-swedish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-polish.conllu data/Iraq/Iraq-swedish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-polish.conllu Iraq-turkish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-polish.conllu data/Iraq/Iraq-turkish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-polish.conllu Iraq-ukrainian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-polish.conllu data/Iraq/Iraq-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-polish.conllu Iraq-urdu.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-polish.conllu data/Iraq/Iraq-urdu.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-polish.conllu Iraq-vietnamese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-polish.conllu data/Iraq/Iraq-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-polish.conllu Iraq-chinese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-polish.conllu data/Iraq/Iraq-chinese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-portuguese.conllu Iraq-serbian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-portuguese.conllu data/Iraq/Iraq-serbian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-portuguese.conllu Iraq-finnish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-portuguese.conllu data/Iraq/Iraq-finnish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-portuguese.conllu Iraq-swedish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-portuguese.conllu data/Iraq/Iraq-swedish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-portuguese.conllu Iraq-turkish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-portuguese.conllu data/Iraq/Iraq-turkish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-portuguese.conllu Iraq-ukrainian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-portuguese.conllu data/Iraq/Iraq-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-portuguese.conllu Iraq-urdu.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-portuguese.conllu data/Iraq/Iraq-urdu.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-portuguese.conllu Iraq-vietnamese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-portuguese.conllu data/Iraq/Iraq-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-portuguese.conllu Iraq-chinese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-portuguese.conllu data/Iraq/Iraq-chinese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-serbian.conllu Iraq-finnish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-serbian.conllu data/Iraq/Iraq-finnish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-serbian.conllu Iraq-swedish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-serbian.conllu data/Iraq/Iraq-swedish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-serbian.conllu Iraq-turkish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-serbian.conllu data/Iraq/Iraq-turkish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-serbian.conllu Iraq-ukrainian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-serbian.conllu data/Iraq/Iraq-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-serbian.conllu Iraq-urdu.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-serbian.conllu data/Iraq/Iraq-urdu.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-serbian.conllu Iraq-vietnamese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-serbian.conllu data/Iraq/Iraq-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-serbian.conllu Iraq-chinese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-serbian.conllu data/Iraq/Iraq-chinese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-finnish.conllu Iraq-swedish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-finnish.conllu data/Iraq/Iraq-swedish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-finnish.conllu Iraq-turkish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-finnish.conllu data/Iraq/Iraq-turkish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-finnish.conllu Iraq-ukrainian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-finnish.conllu data/Iraq/Iraq-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-finnish.conllu Iraq-urdu.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-finnish.conllu data/Iraq/Iraq-urdu.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-finnish.conllu Iraq-vietnamese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-finnish.conllu data/Iraq/Iraq-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-finnish.conllu Iraq-chinese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-finnish.conllu data/Iraq/Iraq-chinese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-swedish.conllu Iraq-turkish.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-swedish.conllu data/Iraq/Iraq-turkish.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-swedish.conllu Iraq-ukrainian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-swedish.conllu data/Iraq/Iraq-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-swedish.conllu Iraq-urdu.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-swedish.conllu data/Iraq/Iraq-urdu.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-swedish.conllu Iraq-vietnamese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-swedish.conllu data/Iraq/Iraq-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-swedish.conllu Iraq-chinese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-swedish.conllu data/Iraq/Iraq-chinese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-turkish.conllu Iraq-ukrainian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-turkish.conllu data/Iraq/Iraq-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-turkish.conllu Iraq-urdu.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-turkish.conllu data/Iraq/Iraq-urdu.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-turkish.conllu Iraq-vietnamese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-turkish.conllu data/Iraq/Iraq-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-turkish.conllu Iraq-chinese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-turkish.conllu data/Iraq/Iraq-chinese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-ukrainian.conllu Iraq-urdu.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-ukrainian.conllu data/Iraq/Iraq-urdu.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-ukrainian.conllu Iraq-vietnamese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-ukrainian.conllu data/Iraq/Iraq-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-ukrainian.conllu Iraq-chinese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-ukrainian.conllu data/Iraq/Iraq-chinese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-urdu.conllu Iraq-vietnamese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-urdu.conllu data/Iraq/Iraq-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-urdu.conllu Iraq-chinese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-urdu.conllu data/Iraq/Iraq-chinese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-vietnamese.conllu Iraq-chinese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-vietnamese.conllu data/Iraq/Iraq-chinese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-czech.conllu Iraq-french.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-czech.conllu data/Iraq/Iraq-french.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-czech.conllu Iraq-hungarian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-czech.conllu data/Iraq/Iraq-hungarian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-czech.conllu Iraq-dutch.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-czech.conllu data/Iraq/Iraq-dutch.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-czech.conllu Iraq-russian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-czech.conllu data/Iraq/Iraq-russian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-french.conllu Iraq-hungarian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-french.conllu data/Iraq/Iraq-hungarian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-french.conllu Iraq-dutch.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-french.conllu data/Iraq/Iraq-dutch.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-french.conllu Iraq-russian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-french.conllu data/Iraq/Iraq-russian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-hungarian.conllu Iraq-dutch.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-hungarian.conllu data/Iraq/Iraq-dutch.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-hungarian.conllu Iraq-russian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-hungarian.conllu data/Iraq/Iraq-russian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-dutch.conllu Iraq-russian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-dutch.conllu data/Iraq/Iraq-russian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-english.conllu Iraq-arabic.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-english.conllu data/Iraq/Iraq-arabic.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-english.conllu Iraq-german.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-english.conllu data/Iraq/Iraq-german.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-english.conllu Iraq-persian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-english.conllu data/Iraq/Iraq-persian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-english.conllu Iraq-armenian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-english.conllu data/Iraq/Iraq-armenian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-english.conllu Iraq-japanese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-english.conllu data/Iraq/Iraq-japanese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-english.conllu Iraq-telugu.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-english.conllu data/Iraq/Iraq-telugu.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-arabic.conllu Iraq-german.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-arabic.conllu data/Iraq/Iraq-german.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-arabic.conllu Iraq-persian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-arabic.conllu data/Iraq/Iraq-persian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-arabic.conllu Iraq-armenian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-arabic.conllu data/Iraq/Iraq-armenian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-arabic.conllu Iraq-japanese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-arabic.conllu data/Iraq/Iraq-japanese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-arabic.conllu Iraq-telugu.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-arabic.conllu data/Iraq/Iraq-telugu.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-german.conllu Iraq-persian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-german.conllu data/Iraq/Iraq-persian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-german.conllu Iraq-armenian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-german.conllu data/Iraq/Iraq-armenian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-german.conllu Iraq-japanese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-german.conllu data/Iraq/Iraq-japanese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-german.conllu Iraq-telugu.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-german.conllu data/Iraq/Iraq-telugu.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-persian.conllu Iraq-armenian.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-persian.conllu data/Iraq/Iraq-armenian.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-persian.conllu Iraq-japanese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-persian.conllu data/Iraq/Iraq-japanese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-persian.conllu Iraq-telugu.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-persian.conllu data/Iraq/Iraq-telugu.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-armenian.conllu Iraq-japanese.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-armenian.conllu data/Iraq/Iraq-japanese.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-armenian.conllu Iraq-telugu.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-armenian.conllu data/Iraq/Iraq-telugu.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
echo Iraq-japanese.conllu Iraq-telugu.conllu >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
gfud cosine-similarity data/Iraq/Iraq-japanese.conllu data/Iraq/Iraq-telugu.conllu DEPREL >> cosine-sim-per-topic/Iraq-cosine-sim.txt ; 
} 
topic_combinations