#! /bin/bash 
function topic_combinations { 
echo Iron-belarusian.conllu Iron-welsh.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-belarusian.conllu data/Iron/Iron-welsh.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-belarusian.conllu Iron-maltese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-belarusian.conllu data/Iron/Iron-maltese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-belarusian.conllu Iron-urdu.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-belarusian.conllu data/Iron/Iron-urdu.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-belarusian.conllu Iron-uyghur.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-belarusian.conllu data/Iron/Iron-uyghur.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-welsh.conllu Iron-maltese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-welsh.conllu data/Iron/Iron-maltese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-welsh.conllu Iron-urdu.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-welsh.conllu data/Iron/Iron-urdu.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-welsh.conllu Iron-uyghur.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-welsh.conllu data/Iron/Iron-uyghur.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-maltese.conllu Iron-urdu.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-maltese.conllu data/Iron/Iron-urdu.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-maltese.conllu Iron-uyghur.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-maltese.conllu data/Iron/Iron-uyghur.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-urdu.conllu Iron-uyghur.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-urdu.conllu data/Iron/Iron-uyghur.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-estonian.conllu Iron-irish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-estonian.conllu data/Iron/Iron-irish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-estonian.conllu Iron-scottish_gaelic.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-estonian.conllu data/Iron/Iron-scottish_gaelic.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-estonian.conllu Iron-korean.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-estonian.conllu data/Iron/Iron-korean.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-estonian.conllu Iron-armenian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-estonian.conllu data/Iron/Iron-armenian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-estonian.conllu Iron-latin.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-estonian.conllu data/Iron/Iron-latin.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-estonian.conllu Iron-latvian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-estonian.conllu data/Iron/Iron-latvian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-estonian.conllu Iron-lithuanian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-estonian.conllu data/Iron/Iron-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-estonian.conllu Iron-marathi.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-estonian.conllu data/Iron/Iron-marathi.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-estonian.conllu Iron-dutch.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-estonian.conllu data/Iron/Iron-dutch.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-estonian.conllu Iron-polish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-estonian.conllu data/Iron/Iron-polish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-estonian.conllu Iron-sanskrit.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-estonian.conllu data/Iron/Iron-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-estonian.conllu Iron-slovak.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-estonian.conllu data/Iron/Iron-slovak.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-estonian.conllu Iron-swedish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-estonian.conllu data/Iron/Iron-swedish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-estonian.conllu Iron-tamil.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-estonian.conllu data/Iron/Iron-tamil.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-estonian.conllu Iron-telugu.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-estonian.conllu data/Iron/Iron-telugu.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-estonian.conllu Iron-turkish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-estonian.conllu data/Iron/Iron-turkish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-estonian.conllu Iron-classical_chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-estonian.conllu data/Iron/Iron-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-irish.conllu Iron-scottish_gaelic.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-irish.conllu data/Iron/Iron-scottish_gaelic.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-irish.conllu Iron-korean.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-irish.conllu data/Iron/Iron-korean.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-irish.conllu Iron-armenian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-irish.conllu data/Iron/Iron-armenian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-irish.conllu Iron-latin.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-irish.conllu data/Iron/Iron-latin.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-irish.conllu Iron-latvian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-irish.conllu data/Iron/Iron-latvian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-irish.conllu Iron-lithuanian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-irish.conllu data/Iron/Iron-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-irish.conllu Iron-marathi.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-irish.conllu data/Iron/Iron-marathi.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-irish.conllu Iron-dutch.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-irish.conllu data/Iron/Iron-dutch.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-irish.conllu Iron-polish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-irish.conllu data/Iron/Iron-polish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-irish.conllu Iron-sanskrit.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-irish.conllu data/Iron/Iron-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-irish.conllu Iron-slovak.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-irish.conllu data/Iron/Iron-slovak.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-irish.conllu Iron-swedish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-irish.conllu data/Iron/Iron-swedish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-irish.conllu Iron-tamil.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-irish.conllu data/Iron/Iron-tamil.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-irish.conllu Iron-telugu.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-irish.conllu data/Iron/Iron-telugu.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-irish.conllu Iron-turkish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-irish.conllu data/Iron/Iron-turkish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-irish.conllu Iron-classical_chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-irish.conllu data/Iron/Iron-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-scottish_gaelic.conllu Iron-korean.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-scottish_gaelic.conllu data/Iron/Iron-korean.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-scottish_gaelic.conllu Iron-armenian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-scottish_gaelic.conllu data/Iron/Iron-armenian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-scottish_gaelic.conllu Iron-latin.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-scottish_gaelic.conllu data/Iron/Iron-latin.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-scottish_gaelic.conllu Iron-latvian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-scottish_gaelic.conllu data/Iron/Iron-latvian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-scottish_gaelic.conllu Iron-lithuanian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-scottish_gaelic.conllu data/Iron/Iron-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-scottish_gaelic.conllu Iron-marathi.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-scottish_gaelic.conllu data/Iron/Iron-marathi.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-scottish_gaelic.conllu Iron-dutch.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-scottish_gaelic.conllu data/Iron/Iron-dutch.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-scottish_gaelic.conllu Iron-polish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-scottish_gaelic.conllu data/Iron/Iron-polish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-scottish_gaelic.conllu Iron-sanskrit.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-scottish_gaelic.conllu data/Iron/Iron-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-scottish_gaelic.conllu Iron-slovak.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-scottish_gaelic.conllu data/Iron/Iron-slovak.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-scottish_gaelic.conllu Iron-swedish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-scottish_gaelic.conllu data/Iron/Iron-swedish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-scottish_gaelic.conllu Iron-tamil.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-scottish_gaelic.conllu data/Iron/Iron-tamil.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-scottish_gaelic.conllu Iron-telugu.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-scottish_gaelic.conllu data/Iron/Iron-telugu.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-scottish_gaelic.conllu Iron-turkish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-scottish_gaelic.conllu data/Iron/Iron-turkish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-scottish_gaelic.conllu Iron-classical_chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-scottish_gaelic.conllu data/Iron/Iron-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-korean.conllu Iron-armenian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-korean.conllu data/Iron/Iron-armenian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-korean.conllu Iron-latin.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-korean.conllu data/Iron/Iron-latin.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-korean.conllu Iron-latvian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-korean.conllu data/Iron/Iron-latvian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-korean.conllu Iron-lithuanian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-korean.conllu data/Iron/Iron-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-korean.conllu Iron-marathi.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-korean.conllu data/Iron/Iron-marathi.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-korean.conllu Iron-dutch.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-korean.conllu data/Iron/Iron-dutch.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-korean.conllu Iron-polish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-korean.conllu data/Iron/Iron-polish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-korean.conllu Iron-sanskrit.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-korean.conllu data/Iron/Iron-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-korean.conllu Iron-slovak.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-korean.conllu data/Iron/Iron-slovak.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-korean.conllu Iron-swedish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-korean.conllu data/Iron/Iron-swedish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-korean.conllu Iron-tamil.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-korean.conllu data/Iron/Iron-tamil.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-korean.conllu Iron-telugu.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-korean.conllu data/Iron/Iron-telugu.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-korean.conllu Iron-turkish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-korean.conllu data/Iron/Iron-turkish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-korean.conllu Iron-classical_chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-korean.conllu data/Iron/Iron-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-armenian.conllu Iron-latin.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-armenian.conllu data/Iron/Iron-latin.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-armenian.conllu Iron-latvian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-armenian.conllu data/Iron/Iron-latvian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-armenian.conllu Iron-lithuanian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-armenian.conllu data/Iron/Iron-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-armenian.conllu Iron-marathi.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-armenian.conllu data/Iron/Iron-marathi.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-armenian.conllu Iron-dutch.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-armenian.conllu data/Iron/Iron-dutch.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-armenian.conllu Iron-polish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-armenian.conllu data/Iron/Iron-polish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-armenian.conllu Iron-sanskrit.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-armenian.conllu data/Iron/Iron-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-armenian.conllu Iron-slovak.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-armenian.conllu data/Iron/Iron-slovak.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-armenian.conllu Iron-swedish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-armenian.conllu data/Iron/Iron-swedish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-armenian.conllu Iron-tamil.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-armenian.conllu data/Iron/Iron-tamil.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-armenian.conllu Iron-telugu.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-armenian.conllu data/Iron/Iron-telugu.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-armenian.conllu Iron-turkish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-armenian.conllu data/Iron/Iron-turkish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-armenian.conllu Iron-classical_chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-armenian.conllu data/Iron/Iron-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-latin.conllu Iron-latvian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-latin.conllu data/Iron/Iron-latvian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-latin.conllu Iron-lithuanian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-latin.conllu data/Iron/Iron-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-latin.conllu Iron-marathi.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-latin.conllu data/Iron/Iron-marathi.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-latin.conllu Iron-dutch.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-latin.conllu data/Iron/Iron-dutch.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-latin.conllu Iron-polish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-latin.conllu data/Iron/Iron-polish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-latin.conllu Iron-sanskrit.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-latin.conllu data/Iron/Iron-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-latin.conllu Iron-slovak.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-latin.conllu data/Iron/Iron-slovak.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-latin.conllu Iron-swedish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-latin.conllu data/Iron/Iron-swedish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-latin.conllu Iron-tamil.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-latin.conllu data/Iron/Iron-tamil.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-latin.conllu Iron-telugu.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-latin.conllu data/Iron/Iron-telugu.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-latin.conllu Iron-turkish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-latin.conllu data/Iron/Iron-turkish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-latin.conllu Iron-classical_chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-latin.conllu data/Iron/Iron-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-latvian.conllu Iron-lithuanian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-latvian.conllu data/Iron/Iron-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-latvian.conllu Iron-marathi.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-latvian.conllu data/Iron/Iron-marathi.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-latvian.conllu Iron-dutch.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-latvian.conllu data/Iron/Iron-dutch.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-latvian.conllu Iron-polish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-latvian.conllu data/Iron/Iron-polish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-latvian.conllu Iron-sanskrit.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-latvian.conllu data/Iron/Iron-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-latvian.conllu Iron-slovak.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-latvian.conllu data/Iron/Iron-slovak.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-latvian.conllu Iron-swedish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-latvian.conllu data/Iron/Iron-swedish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-latvian.conllu Iron-tamil.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-latvian.conllu data/Iron/Iron-tamil.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-latvian.conllu Iron-telugu.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-latvian.conllu data/Iron/Iron-telugu.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-latvian.conllu Iron-turkish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-latvian.conllu data/Iron/Iron-turkish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-latvian.conllu Iron-classical_chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-latvian.conllu data/Iron/Iron-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-lithuanian.conllu Iron-marathi.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-lithuanian.conllu data/Iron/Iron-marathi.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-lithuanian.conllu Iron-dutch.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-lithuanian.conllu data/Iron/Iron-dutch.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-lithuanian.conllu Iron-polish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-lithuanian.conllu data/Iron/Iron-polish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-lithuanian.conllu Iron-sanskrit.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-lithuanian.conllu data/Iron/Iron-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-lithuanian.conllu Iron-slovak.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-lithuanian.conllu data/Iron/Iron-slovak.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-lithuanian.conllu Iron-swedish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-lithuanian.conllu data/Iron/Iron-swedish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-lithuanian.conllu Iron-tamil.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-lithuanian.conllu data/Iron/Iron-tamil.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-lithuanian.conllu Iron-telugu.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-lithuanian.conllu data/Iron/Iron-telugu.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-lithuanian.conllu Iron-turkish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-lithuanian.conllu data/Iron/Iron-turkish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-lithuanian.conllu Iron-classical_chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-lithuanian.conllu data/Iron/Iron-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-marathi.conllu Iron-dutch.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-marathi.conllu data/Iron/Iron-dutch.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-marathi.conllu Iron-polish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-marathi.conllu data/Iron/Iron-polish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-marathi.conllu Iron-sanskrit.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-marathi.conllu data/Iron/Iron-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-marathi.conllu Iron-slovak.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-marathi.conllu data/Iron/Iron-slovak.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-marathi.conllu Iron-swedish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-marathi.conllu data/Iron/Iron-swedish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-marathi.conllu Iron-tamil.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-marathi.conllu data/Iron/Iron-tamil.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-marathi.conllu Iron-telugu.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-marathi.conllu data/Iron/Iron-telugu.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-marathi.conllu Iron-turkish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-marathi.conllu data/Iron/Iron-turkish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-marathi.conllu Iron-classical_chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-marathi.conllu data/Iron/Iron-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-dutch.conllu Iron-polish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-dutch.conllu data/Iron/Iron-polish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-dutch.conllu Iron-sanskrit.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-dutch.conllu data/Iron/Iron-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-dutch.conllu Iron-slovak.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-dutch.conllu data/Iron/Iron-slovak.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-dutch.conllu Iron-swedish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-dutch.conllu data/Iron/Iron-swedish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-dutch.conllu Iron-tamil.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-dutch.conllu data/Iron/Iron-tamil.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-dutch.conllu Iron-telugu.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-dutch.conllu data/Iron/Iron-telugu.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-dutch.conllu Iron-turkish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-dutch.conllu data/Iron/Iron-turkish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-dutch.conllu Iron-classical_chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-dutch.conllu data/Iron/Iron-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-polish.conllu Iron-sanskrit.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-polish.conllu data/Iron/Iron-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-polish.conllu Iron-slovak.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-polish.conllu data/Iron/Iron-slovak.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-polish.conllu Iron-swedish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-polish.conllu data/Iron/Iron-swedish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-polish.conllu Iron-tamil.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-polish.conllu data/Iron/Iron-tamil.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-polish.conllu Iron-telugu.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-polish.conllu data/Iron/Iron-telugu.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-polish.conllu Iron-turkish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-polish.conllu data/Iron/Iron-turkish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-polish.conllu Iron-classical_chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-polish.conllu data/Iron/Iron-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-sanskrit.conllu Iron-slovak.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-sanskrit.conllu data/Iron/Iron-slovak.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-sanskrit.conllu Iron-swedish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-sanskrit.conllu data/Iron/Iron-swedish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-sanskrit.conllu Iron-tamil.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-sanskrit.conllu data/Iron/Iron-tamil.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-sanskrit.conllu Iron-telugu.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-sanskrit.conllu data/Iron/Iron-telugu.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-sanskrit.conllu Iron-turkish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-sanskrit.conllu data/Iron/Iron-turkish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-sanskrit.conllu Iron-classical_chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-sanskrit.conllu data/Iron/Iron-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-slovak.conllu Iron-swedish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-slovak.conllu data/Iron/Iron-swedish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-slovak.conllu Iron-tamil.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-slovak.conllu data/Iron/Iron-tamil.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-slovak.conllu Iron-telugu.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-slovak.conllu data/Iron/Iron-telugu.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-slovak.conllu Iron-turkish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-slovak.conllu data/Iron/Iron-turkish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-slovak.conllu Iron-classical_chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-slovak.conllu data/Iron/Iron-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-swedish.conllu Iron-tamil.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-swedish.conllu data/Iron/Iron-tamil.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-swedish.conllu Iron-telugu.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-swedish.conllu data/Iron/Iron-telugu.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-swedish.conllu Iron-turkish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-swedish.conllu data/Iron/Iron-turkish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-swedish.conllu Iron-classical_chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-swedish.conllu data/Iron/Iron-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-tamil.conllu Iron-telugu.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-tamil.conllu data/Iron/Iron-telugu.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-tamil.conllu Iron-turkish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-tamil.conllu data/Iron/Iron-turkish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-tamil.conllu Iron-classical_chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-tamil.conllu data/Iron/Iron-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-telugu.conllu Iron-turkish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-telugu.conllu data/Iron/Iron-turkish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-telugu.conllu Iron-classical_chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-telugu.conllu data/Iron/Iron-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-turkish.conllu Iron-classical_chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-turkish.conllu data/Iron/Iron-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-afrikaans.conllu Iron-catalan.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-afrikaans.conllu data/Iron/Iron-catalan.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-afrikaans.conllu Iron-danish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-afrikaans.conllu data/Iron/Iron-danish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-afrikaans.conllu Iron-greek.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-afrikaans.conllu data/Iron/Iron-greek.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-afrikaans.conllu Iron-spanish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-afrikaans.conllu data/Iron/Iron-spanish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-afrikaans.conllu Iron-persian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-afrikaans.conllu data/Iron/Iron-persian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-afrikaans.conllu Iron-french.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-afrikaans.conllu data/Iron/Iron-french.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-afrikaans.conllu Iron-galician.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-afrikaans.conllu data/Iron/Iron-galician.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-afrikaans.conllu Iron-hindi.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-afrikaans.conllu data/Iron/Iron-hindi.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-afrikaans.conllu Iron-croatian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-afrikaans.conllu data/Iron/Iron-croatian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-afrikaans.conllu Iron-italian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-afrikaans.conllu data/Iron/Iron-italian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-afrikaans.conllu Iron-hebrew.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-afrikaans.conllu data/Iron/Iron-hebrew.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-afrikaans.conllu Iron-kazakh.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-afrikaans.conllu data/Iron/Iron-kazakh.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-afrikaans.conllu Iron-hungarian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-afrikaans.conllu data/Iron/Iron-hungarian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-afrikaans.conllu Iron-japanese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-afrikaans.conllu data/Iron/Iron-japanese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-afrikaans.conllu Iron-portuguese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-afrikaans.conllu data/Iron/Iron-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-afrikaans.conllu Iron-romanian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-afrikaans.conllu data/Iron/Iron-romanian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-afrikaans.conllu Iron-russian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-afrikaans.conllu data/Iron/Iron-russian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-afrikaans.conllu Iron-serbian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-afrikaans.conllu data/Iron/Iron-serbian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-afrikaans.conllu Iron-finnish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-afrikaans.conllu data/Iron/Iron-finnish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-afrikaans.conllu Iron-ukrainian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-afrikaans.conllu data/Iron/Iron-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-afrikaans.conllu Iron-vietnamese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-afrikaans.conllu data/Iron/Iron-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-afrikaans.conllu Iron-chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-afrikaans.conllu data/Iron/Iron-chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-catalan.conllu Iron-danish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-catalan.conllu data/Iron/Iron-danish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-catalan.conllu Iron-greek.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-catalan.conllu data/Iron/Iron-greek.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-catalan.conllu Iron-spanish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-catalan.conllu data/Iron/Iron-spanish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-catalan.conllu Iron-persian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-catalan.conllu data/Iron/Iron-persian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-catalan.conllu Iron-french.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-catalan.conllu data/Iron/Iron-french.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-catalan.conllu Iron-galician.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-catalan.conllu data/Iron/Iron-galician.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-catalan.conllu Iron-hindi.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-catalan.conllu data/Iron/Iron-hindi.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-catalan.conllu Iron-croatian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-catalan.conllu data/Iron/Iron-croatian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-catalan.conllu Iron-italian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-catalan.conllu data/Iron/Iron-italian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-catalan.conllu Iron-hebrew.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-catalan.conllu data/Iron/Iron-hebrew.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-catalan.conllu Iron-kazakh.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-catalan.conllu data/Iron/Iron-kazakh.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-catalan.conllu Iron-hungarian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-catalan.conllu data/Iron/Iron-hungarian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-catalan.conllu Iron-japanese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-catalan.conllu data/Iron/Iron-japanese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-catalan.conllu Iron-portuguese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-catalan.conllu data/Iron/Iron-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-catalan.conllu Iron-romanian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-catalan.conllu data/Iron/Iron-romanian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-catalan.conllu Iron-russian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-catalan.conllu data/Iron/Iron-russian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-catalan.conllu Iron-serbian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-catalan.conllu data/Iron/Iron-serbian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-catalan.conllu Iron-finnish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-catalan.conllu data/Iron/Iron-finnish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-catalan.conllu Iron-ukrainian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-catalan.conllu data/Iron/Iron-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-catalan.conllu Iron-vietnamese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-catalan.conllu data/Iron/Iron-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-catalan.conllu Iron-chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-catalan.conllu data/Iron/Iron-chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-danish.conllu Iron-greek.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-danish.conllu data/Iron/Iron-greek.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-danish.conllu Iron-spanish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-danish.conllu data/Iron/Iron-spanish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-danish.conllu Iron-persian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-danish.conllu data/Iron/Iron-persian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-danish.conllu Iron-french.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-danish.conllu data/Iron/Iron-french.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-danish.conllu Iron-galician.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-danish.conllu data/Iron/Iron-galician.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-danish.conllu Iron-hindi.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-danish.conllu data/Iron/Iron-hindi.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-danish.conllu Iron-croatian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-danish.conllu data/Iron/Iron-croatian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-danish.conllu Iron-italian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-danish.conllu data/Iron/Iron-italian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-danish.conllu Iron-hebrew.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-danish.conllu data/Iron/Iron-hebrew.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-danish.conllu Iron-kazakh.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-danish.conllu data/Iron/Iron-kazakh.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-danish.conllu Iron-hungarian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-danish.conllu data/Iron/Iron-hungarian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-danish.conllu Iron-japanese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-danish.conllu data/Iron/Iron-japanese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-danish.conllu Iron-portuguese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-danish.conllu data/Iron/Iron-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-danish.conllu Iron-romanian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-danish.conllu data/Iron/Iron-romanian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-danish.conllu Iron-russian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-danish.conllu data/Iron/Iron-russian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-danish.conllu Iron-serbian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-danish.conllu data/Iron/Iron-serbian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-danish.conllu Iron-finnish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-danish.conllu data/Iron/Iron-finnish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-danish.conllu Iron-ukrainian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-danish.conllu data/Iron/Iron-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-danish.conllu Iron-vietnamese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-danish.conllu data/Iron/Iron-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-danish.conllu Iron-chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-danish.conllu data/Iron/Iron-chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-greek.conllu Iron-spanish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-greek.conllu data/Iron/Iron-spanish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-greek.conllu Iron-persian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-greek.conllu data/Iron/Iron-persian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-greek.conllu Iron-french.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-greek.conllu data/Iron/Iron-french.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-greek.conllu Iron-galician.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-greek.conllu data/Iron/Iron-galician.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-greek.conllu Iron-hindi.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-greek.conllu data/Iron/Iron-hindi.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-greek.conllu Iron-croatian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-greek.conllu data/Iron/Iron-croatian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-greek.conllu Iron-italian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-greek.conllu data/Iron/Iron-italian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-greek.conllu Iron-hebrew.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-greek.conllu data/Iron/Iron-hebrew.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-greek.conllu Iron-kazakh.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-greek.conllu data/Iron/Iron-kazakh.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-greek.conllu Iron-hungarian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-greek.conllu data/Iron/Iron-hungarian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-greek.conllu Iron-japanese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-greek.conllu data/Iron/Iron-japanese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-greek.conllu Iron-portuguese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-greek.conllu data/Iron/Iron-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-greek.conllu Iron-romanian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-greek.conllu data/Iron/Iron-romanian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-greek.conllu Iron-russian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-greek.conllu data/Iron/Iron-russian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-greek.conllu Iron-serbian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-greek.conllu data/Iron/Iron-serbian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-greek.conllu Iron-finnish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-greek.conllu data/Iron/Iron-finnish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-greek.conllu Iron-ukrainian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-greek.conllu data/Iron/Iron-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-greek.conllu Iron-vietnamese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-greek.conllu data/Iron/Iron-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-greek.conllu Iron-chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-greek.conllu data/Iron/Iron-chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-spanish.conllu Iron-persian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-spanish.conllu data/Iron/Iron-persian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-spanish.conllu Iron-french.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-spanish.conllu data/Iron/Iron-french.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-spanish.conllu Iron-galician.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-spanish.conllu data/Iron/Iron-galician.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-spanish.conllu Iron-hindi.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-spanish.conllu data/Iron/Iron-hindi.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-spanish.conllu Iron-croatian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-spanish.conllu data/Iron/Iron-croatian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-spanish.conllu Iron-italian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-spanish.conllu data/Iron/Iron-italian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-spanish.conllu Iron-hebrew.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-spanish.conllu data/Iron/Iron-hebrew.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-spanish.conllu Iron-kazakh.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-spanish.conllu data/Iron/Iron-kazakh.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-spanish.conllu Iron-hungarian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-spanish.conllu data/Iron/Iron-hungarian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-spanish.conllu Iron-japanese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-spanish.conllu data/Iron/Iron-japanese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-spanish.conllu Iron-portuguese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-spanish.conllu data/Iron/Iron-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-spanish.conllu Iron-romanian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-spanish.conllu data/Iron/Iron-romanian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-spanish.conllu Iron-russian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-spanish.conllu data/Iron/Iron-russian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-spanish.conllu Iron-serbian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-spanish.conllu data/Iron/Iron-serbian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-spanish.conllu Iron-finnish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-spanish.conllu data/Iron/Iron-finnish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-spanish.conllu Iron-ukrainian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-spanish.conllu data/Iron/Iron-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-spanish.conllu Iron-vietnamese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-spanish.conllu data/Iron/Iron-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-spanish.conllu Iron-chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-spanish.conllu data/Iron/Iron-chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-persian.conllu Iron-french.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-persian.conllu data/Iron/Iron-french.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-persian.conllu Iron-galician.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-persian.conllu data/Iron/Iron-galician.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-persian.conllu Iron-hindi.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-persian.conllu data/Iron/Iron-hindi.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-persian.conllu Iron-croatian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-persian.conllu data/Iron/Iron-croatian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-persian.conllu Iron-italian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-persian.conllu data/Iron/Iron-italian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-persian.conllu Iron-hebrew.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-persian.conllu data/Iron/Iron-hebrew.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-persian.conllu Iron-kazakh.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-persian.conllu data/Iron/Iron-kazakh.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-persian.conllu Iron-hungarian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-persian.conllu data/Iron/Iron-hungarian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-persian.conllu Iron-japanese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-persian.conllu data/Iron/Iron-japanese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-persian.conllu Iron-portuguese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-persian.conllu data/Iron/Iron-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-persian.conllu Iron-romanian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-persian.conllu data/Iron/Iron-romanian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-persian.conllu Iron-russian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-persian.conllu data/Iron/Iron-russian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-persian.conllu Iron-serbian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-persian.conllu data/Iron/Iron-serbian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-persian.conllu Iron-finnish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-persian.conllu data/Iron/Iron-finnish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-persian.conllu Iron-ukrainian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-persian.conllu data/Iron/Iron-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-persian.conllu Iron-vietnamese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-persian.conllu data/Iron/Iron-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-persian.conllu Iron-chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-persian.conllu data/Iron/Iron-chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-french.conllu Iron-galician.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-french.conllu data/Iron/Iron-galician.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-french.conllu Iron-hindi.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-french.conllu data/Iron/Iron-hindi.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-french.conllu Iron-croatian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-french.conllu data/Iron/Iron-croatian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-french.conllu Iron-italian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-french.conllu data/Iron/Iron-italian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-french.conllu Iron-hebrew.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-french.conllu data/Iron/Iron-hebrew.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-french.conllu Iron-kazakh.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-french.conllu data/Iron/Iron-kazakh.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-french.conllu Iron-hungarian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-french.conllu data/Iron/Iron-hungarian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-french.conllu Iron-japanese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-french.conllu data/Iron/Iron-japanese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-french.conllu Iron-portuguese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-french.conllu data/Iron/Iron-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-french.conllu Iron-romanian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-french.conllu data/Iron/Iron-romanian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-french.conllu Iron-russian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-french.conllu data/Iron/Iron-russian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-french.conllu Iron-serbian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-french.conllu data/Iron/Iron-serbian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-french.conllu Iron-finnish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-french.conllu data/Iron/Iron-finnish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-french.conllu Iron-ukrainian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-french.conllu data/Iron/Iron-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-french.conllu Iron-vietnamese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-french.conllu data/Iron/Iron-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-french.conllu Iron-chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-french.conllu data/Iron/Iron-chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-galician.conllu Iron-hindi.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-galician.conllu data/Iron/Iron-hindi.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-galician.conllu Iron-croatian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-galician.conllu data/Iron/Iron-croatian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-galician.conllu Iron-italian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-galician.conllu data/Iron/Iron-italian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-galician.conllu Iron-hebrew.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-galician.conllu data/Iron/Iron-hebrew.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-galician.conllu Iron-kazakh.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-galician.conllu data/Iron/Iron-kazakh.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-galician.conllu Iron-hungarian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-galician.conllu data/Iron/Iron-hungarian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-galician.conllu Iron-japanese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-galician.conllu data/Iron/Iron-japanese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-galician.conllu Iron-portuguese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-galician.conllu data/Iron/Iron-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-galician.conllu Iron-romanian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-galician.conllu data/Iron/Iron-romanian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-galician.conllu Iron-russian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-galician.conllu data/Iron/Iron-russian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-galician.conllu Iron-serbian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-galician.conllu data/Iron/Iron-serbian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-galician.conllu Iron-finnish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-galician.conllu data/Iron/Iron-finnish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-galician.conllu Iron-ukrainian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-galician.conllu data/Iron/Iron-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-galician.conllu Iron-vietnamese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-galician.conllu data/Iron/Iron-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-galician.conllu Iron-chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-galician.conllu data/Iron/Iron-chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-hindi.conllu Iron-croatian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-hindi.conllu data/Iron/Iron-croatian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-hindi.conllu Iron-italian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-hindi.conllu data/Iron/Iron-italian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-hindi.conllu Iron-hebrew.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-hindi.conllu data/Iron/Iron-hebrew.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-hindi.conllu Iron-kazakh.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-hindi.conllu data/Iron/Iron-kazakh.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-hindi.conllu Iron-hungarian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-hindi.conllu data/Iron/Iron-hungarian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-hindi.conllu Iron-japanese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-hindi.conllu data/Iron/Iron-japanese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-hindi.conllu Iron-portuguese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-hindi.conllu data/Iron/Iron-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-hindi.conllu Iron-romanian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-hindi.conllu data/Iron/Iron-romanian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-hindi.conllu Iron-russian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-hindi.conllu data/Iron/Iron-russian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-hindi.conllu Iron-serbian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-hindi.conllu data/Iron/Iron-serbian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-hindi.conllu Iron-finnish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-hindi.conllu data/Iron/Iron-finnish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-hindi.conllu Iron-ukrainian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-hindi.conllu data/Iron/Iron-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-hindi.conllu Iron-vietnamese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-hindi.conllu data/Iron/Iron-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-hindi.conllu Iron-chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-hindi.conllu data/Iron/Iron-chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-croatian.conllu Iron-italian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-croatian.conllu data/Iron/Iron-italian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-croatian.conllu Iron-hebrew.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-croatian.conllu data/Iron/Iron-hebrew.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-croatian.conllu Iron-kazakh.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-croatian.conllu data/Iron/Iron-kazakh.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-croatian.conllu Iron-hungarian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-croatian.conllu data/Iron/Iron-hungarian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-croatian.conllu Iron-japanese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-croatian.conllu data/Iron/Iron-japanese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-croatian.conllu Iron-portuguese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-croatian.conllu data/Iron/Iron-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-croatian.conllu Iron-romanian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-croatian.conllu data/Iron/Iron-romanian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-croatian.conllu Iron-russian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-croatian.conllu data/Iron/Iron-russian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-croatian.conllu Iron-serbian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-croatian.conllu data/Iron/Iron-serbian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-croatian.conllu Iron-finnish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-croatian.conllu data/Iron/Iron-finnish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-croatian.conllu Iron-ukrainian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-croatian.conllu data/Iron/Iron-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-croatian.conllu Iron-vietnamese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-croatian.conllu data/Iron/Iron-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-croatian.conllu Iron-chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-croatian.conllu data/Iron/Iron-chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-italian.conllu Iron-hebrew.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-italian.conllu data/Iron/Iron-hebrew.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-italian.conllu Iron-kazakh.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-italian.conllu data/Iron/Iron-kazakh.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-italian.conllu Iron-hungarian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-italian.conllu data/Iron/Iron-hungarian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-italian.conllu Iron-japanese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-italian.conllu data/Iron/Iron-japanese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-italian.conllu Iron-portuguese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-italian.conllu data/Iron/Iron-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-italian.conllu Iron-romanian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-italian.conllu data/Iron/Iron-romanian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-italian.conllu Iron-russian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-italian.conllu data/Iron/Iron-russian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-italian.conllu Iron-serbian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-italian.conllu data/Iron/Iron-serbian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-italian.conllu Iron-finnish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-italian.conllu data/Iron/Iron-finnish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-italian.conllu Iron-ukrainian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-italian.conllu data/Iron/Iron-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-italian.conllu Iron-vietnamese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-italian.conllu data/Iron/Iron-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-italian.conllu Iron-chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-italian.conllu data/Iron/Iron-chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-hebrew.conllu Iron-kazakh.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-hebrew.conllu data/Iron/Iron-kazakh.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-hebrew.conllu Iron-hungarian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-hebrew.conllu data/Iron/Iron-hungarian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-hebrew.conllu Iron-japanese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-hebrew.conllu data/Iron/Iron-japanese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-hebrew.conllu Iron-portuguese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-hebrew.conllu data/Iron/Iron-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-hebrew.conllu Iron-romanian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-hebrew.conllu data/Iron/Iron-romanian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-hebrew.conllu Iron-russian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-hebrew.conllu data/Iron/Iron-russian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-hebrew.conllu Iron-serbian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-hebrew.conllu data/Iron/Iron-serbian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-hebrew.conllu Iron-finnish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-hebrew.conllu data/Iron/Iron-finnish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-hebrew.conllu Iron-ukrainian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-hebrew.conllu data/Iron/Iron-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-hebrew.conllu Iron-vietnamese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-hebrew.conllu data/Iron/Iron-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-hebrew.conllu Iron-chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-hebrew.conllu data/Iron/Iron-chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-kazakh.conllu Iron-hungarian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-kazakh.conllu data/Iron/Iron-hungarian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-kazakh.conllu Iron-japanese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-kazakh.conllu data/Iron/Iron-japanese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-kazakh.conllu Iron-portuguese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-kazakh.conllu data/Iron/Iron-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-kazakh.conllu Iron-romanian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-kazakh.conllu data/Iron/Iron-romanian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-kazakh.conllu Iron-russian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-kazakh.conllu data/Iron/Iron-russian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-kazakh.conllu Iron-serbian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-kazakh.conllu data/Iron/Iron-serbian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-kazakh.conllu Iron-finnish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-kazakh.conllu data/Iron/Iron-finnish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-kazakh.conllu Iron-ukrainian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-kazakh.conllu data/Iron/Iron-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-kazakh.conllu Iron-vietnamese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-kazakh.conllu data/Iron/Iron-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-kazakh.conllu Iron-chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-kazakh.conllu data/Iron/Iron-chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-hungarian.conllu Iron-japanese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-hungarian.conllu data/Iron/Iron-japanese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-hungarian.conllu Iron-portuguese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-hungarian.conllu data/Iron/Iron-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-hungarian.conllu Iron-romanian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-hungarian.conllu data/Iron/Iron-romanian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-hungarian.conllu Iron-russian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-hungarian.conllu data/Iron/Iron-russian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-hungarian.conllu Iron-serbian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-hungarian.conllu data/Iron/Iron-serbian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-hungarian.conllu Iron-finnish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-hungarian.conllu data/Iron/Iron-finnish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-hungarian.conllu Iron-ukrainian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-hungarian.conllu data/Iron/Iron-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-hungarian.conllu Iron-vietnamese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-hungarian.conllu data/Iron/Iron-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-hungarian.conllu Iron-chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-hungarian.conllu data/Iron/Iron-chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-japanese.conllu Iron-portuguese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-japanese.conllu data/Iron/Iron-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-japanese.conllu Iron-romanian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-japanese.conllu data/Iron/Iron-romanian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-japanese.conllu Iron-russian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-japanese.conllu data/Iron/Iron-russian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-japanese.conllu Iron-serbian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-japanese.conllu data/Iron/Iron-serbian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-japanese.conllu Iron-finnish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-japanese.conllu data/Iron/Iron-finnish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-japanese.conllu Iron-ukrainian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-japanese.conllu data/Iron/Iron-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-japanese.conllu Iron-vietnamese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-japanese.conllu data/Iron/Iron-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-japanese.conllu Iron-chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-japanese.conllu data/Iron/Iron-chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-portuguese.conllu Iron-romanian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-portuguese.conllu data/Iron/Iron-romanian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-portuguese.conllu Iron-russian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-portuguese.conllu data/Iron/Iron-russian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-portuguese.conllu Iron-serbian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-portuguese.conllu data/Iron/Iron-serbian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-portuguese.conllu Iron-finnish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-portuguese.conllu data/Iron/Iron-finnish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-portuguese.conllu Iron-ukrainian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-portuguese.conllu data/Iron/Iron-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-portuguese.conllu Iron-vietnamese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-portuguese.conllu data/Iron/Iron-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-portuguese.conllu Iron-chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-portuguese.conllu data/Iron/Iron-chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-romanian.conllu Iron-russian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-romanian.conllu data/Iron/Iron-russian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-romanian.conllu Iron-serbian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-romanian.conllu data/Iron/Iron-serbian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-romanian.conllu Iron-finnish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-romanian.conllu data/Iron/Iron-finnish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-romanian.conllu Iron-ukrainian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-romanian.conllu data/Iron/Iron-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-romanian.conllu Iron-vietnamese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-romanian.conllu data/Iron/Iron-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-romanian.conllu Iron-chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-romanian.conllu data/Iron/Iron-chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-russian.conllu Iron-serbian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-russian.conllu data/Iron/Iron-serbian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-russian.conllu Iron-finnish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-russian.conllu data/Iron/Iron-finnish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-russian.conllu Iron-ukrainian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-russian.conllu data/Iron/Iron-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-russian.conllu Iron-vietnamese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-russian.conllu data/Iron/Iron-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-russian.conllu Iron-chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-russian.conllu data/Iron/Iron-chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-serbian.conllu Iron-finnish.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-serbian.conllu data/Iron/Iron-finnish.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-serbian.conllu Iron-ukrainian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-serbian.conllu data/Iron/Iron-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-serbian.conllu Iron-vietnamese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-serbian.conllu data/Iron/Iron-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-serbian.conllu Iron-chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-serbian.conllu data/Iron/Iron-chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-finnish.conllu Iron-ukrainian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-finnish.conllu data/Iron/Iron-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-finnish.conllu Iron-vietnamese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-finnish.conllu data/Iron/Iron-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-finnish.conllu Iron-chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-finnish.conllu data/Iron/Iron-chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-ukrainian.conllu Iron-vietnamese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-ukrainian.conllu data/Iron/Iron-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-ukrainian.conllu Iron-chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-ukrainian.conllu data/Iron/Iron-chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-vietnamese.conllu Iron-chinese.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-vietnamese.conllu data/Iron/Iron-chinese.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-czech.conllu Iron-basque.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-czech.conllu data/Iron/Iron-basque.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-czech.conllu Iron-indonesian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-czech.conllu data/Iron/Iron-indonesian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-czech.conllu Iron-slovenian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-czech.conllu data/Iron/Iron-slovenian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-basque.conllu Iron-indonesian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-basque.conllu data/Iron/Iron-indonesian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-basque.conllu Iron-slovenian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-basque.conllu data/Iron/Iron-slovenian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-indonesian.conllu Iron-slovenian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-indonesian.conllu data/Iron/Iron-slovenian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-english.conllu Iron-arabic.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-english.conllu data/Iron/Iron-arabic.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-english.conllu Iron-bulgarian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-english.conllu data/Iron/Iron-bulgarian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-english.conllu Iron-german.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-english.conllu data/Iron/Iron-german.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-arabic.conllu Iron-bulgarian.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-arabic.conllu data/Iron/Iron-bulgarian.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-arabic.conllu Iron-german.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-arabic.conllu data/Iron/Iron-german.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
echo Iron-bulgarian.conllu Iron-german.conllu >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
gfud cosine-similarity data/Iron/Iron-bulgarian.conllu data/Iron/Iron-german.conllu DEPREL >> cosine-sim-per-topic/Iron-cosine-sim.txt ; 
} 
topic_combinations