#! /bin/bash 
function topic_combinations { 
echo Islam-scottish_gaelic.conllu Islam-gothic.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-scottish_gaelic.conllu data/Islam/Islam-gothic.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-scottish_gaelic.conllu Islam-maltese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-scottish_gaelic.conllu data/Islam/Islam-maltese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-gothic.conllu Islam-maltese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-gothic.conllu data/Islam/Islam-maltese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-afrikaans.conllu Islam-north_sami.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-afrikaans.conllu data/Islam/Islam-north_sami.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-afrikaans.conllu Islam-basque.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-afrikaans.conllu data/Islam/Islam-basque.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-afrikaans.conllu Islam-irish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-afrikaans.conllu data/Islam/Islam-irish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-afrikaans.conllu Islam-latin.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-afrikaans.conllu data/Islam/Islam-latin.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-afrikaans.conllu Islam-lithuanian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-afrikaans.conllu data/Islam/Islam-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-afrikaans.conllu Islam-marathi.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-afrikaans.conllu data/Islam/Islam-marathi.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-afrikaans.conllu Islam-classical_chinese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-afrikaans.conllu data/Islam/Islam-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-north_sami.conllu Islam-basque.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-north_sami.conllu data/Islam/Islam-basque.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-north_sami.conllu Islam-irish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-north_sami.conllu data/Islam/Islam-irish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-north_sami.conllu Islam-latin.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-north_sami.conllu data/Islam/Islam-latin.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-north_sami.conllu Islam-lithuanian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-north_sami.conllu data/Islam/Islam-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-north_sami.conllu Islam-marathi.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-north_sami.conllu data/Islam/Islam-marathi.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-north_sami.conllu Islam-classical_chinese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-north_sami.conllu data/Islam/Islam-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-basque.conllu Islam-irish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-basque.conllu data/Islam/Islam-irish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-basque.conllu Islam-latin.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-basque.conllu data/Islam/Islam-latin.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-basque.conllu Islam-lithuanian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-basque.conllu data/Islam/Islam-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-basque.conllu Islam-marathi.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-basque.conllu data/Islam/Islam-marathi.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-basque.conllu Islam-classical_chinese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-basque.conllu data/Islam/Islam-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-irish.conllu Islam-latin.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-irish.conllu data/Islam/Islam-latin.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-irish.conllu Islam-lithuanian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-irish.conllu data/Islam/Islam-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-irish.conllu Islam-marathi.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-irish.conllu data/Islam/Islam-marathi.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-irish.conllu Islam-classical_chinese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-irish.conllu data/Islam/Islam-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-latin.conllu Islam-lithuanian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-latin.conllu data/Islam/Islam-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-latin.conllu Islam-marathi.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-latin.conllu data/Islam/Islam-marathi.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-latin.conllu Islam-classical_chinese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-latin.conllu data/Islam/Islam-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-lithuanian.conllu Islam-marathi.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-lithuanian.conllu data/Islam/Islam-marathi.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-lithuanian.conllu Islam-classical_chinese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-lithuanian.conllu data/Islam/Islam-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-marathi.conllu Islam-classical_chinese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-marathi.conllu data/Islam/Islam-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-belarusian.conllu Islam-bulgarian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-belarusian.conllu data/Islam/Islam-bulgarian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-belarusian.conllu Islam-catalan.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-belarusian.conllu data/Islam/Islam-catalan.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-belarusian.conllu Islam-welsh.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-belarusian.conllu data/Islam/Islam-welsh.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-belarusian.conllu Islam-estonian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-belarusian.conllu data/Islam/Islam-estonian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-belarusian.conllu Islam-persian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-belarusian.conllu data/Islam/Islam-persian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-belarusian.conllu Islam-galician.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-belarusian.conllu data/Islam/Islam-galician.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-belarusian.conllu Islam-korean.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-belarusian.conllu data/Islam/Islam-korean.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-belarusian.conllu Islam-croatian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-belarusian.conllu data/Islam/Islam-croatian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-belarusian.conllu Islam-indonesian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-belarusian.conllu data/Islam/Islam-indonesian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-belarusian.conllu Islam-italian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-belarusian.conllu data/Islam/Islam-italian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-belarusian.conllu Islam-hebrew.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-belarusian.conllu data/Islam/Islam-hebrew.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-belarusian.conllu Islam-latvian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-belarusian.conllu data/Islam/Islam-latvian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-belarusian.conllu Islam-romanian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-belarusian.conllu data/Islam/Islam-romanian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-belarusian.conllu Islam-slovenian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-belarusian.conllu data/Islam/Islam-slovenian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-belarusian.conllu Islam-serbian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-belarusian.conllu data/Islam/Islam-serbian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-belarusian.conllu Islam-tamil.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-belarusian.conllu data/Islam/Islam-tamil.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-belarusian.conllu Islam-ukrainian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-belarusian.conllu data/Islam/Islam-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-belarusian.conllu Islam-urdu.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-belarusian.conllu data/Islam/Islam-urdu.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-belarusian.conllu Islam-vietnamese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-belarusian.conllu data/Islam/Islam-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-belarusian.conllu Islam-wolof.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-belarusian.conllu data/Islam/Islam-wolof.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-bulgarian.conllu Islam-catalan.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-bulgarian.conllu data/Islam/Islam-catalan.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-bulgarian.conllu Islam-welsh.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-bulgarian.conllu data/Islam/Islam-welsh.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-bulgarian.conllu Islam-estonian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-bulgarian.conllu data/Islam/Islam-estonian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-bulgarian.conllu Islam-persian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-bulgarian.conllu data/Islam/Islam-persian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-bulgarian.conllu Islam-galician.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-bulgarian.conllu data/Islam/Islam-galician.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-bulgarian.conllu Islam-korean.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-bulgarian.conllu data/Islam/Islam-korean.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-bulgarian.conllu Islam-croatian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-bulgarian.conllu data/Islam/Islam-croatian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-bulgarian.conllu Islam-indonesian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-bulgarian.conllu data/Islam/Islam-indonesian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-bulgarian.conllu Islam-italian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-bulgarian.conllu data/Islam/Islam-italian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-bulgarian.conllu Islam-hebrew.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-bulgarian.conllu data/Islam/Islam-hebrew.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-bulgarian.conllu Islam-latvian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-bulgarian.conllu data/Islam/Islam-latvian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-bulgarian.conllu Islam-romanian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-bulgarian.conllu data/Islam/Islam-romanian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-bulgarian.conllu Islam-slovenian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-bulgarian.conllu data/Islam/Islam-slovenian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-bulgarian.conllu Islam-serbian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-bulgarian.conllu data/Islam/Islam-serbian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-bulgarian.conllu Islam-tamil.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-bulgarian.conllu data/Islam/Islam-tamil.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-bulgarian.conllu Islam-ukrainian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-bulgarian.conllu data/Islam/Islam-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-bulgarian.conllu Islam-urdu.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-bulgarian.conllu data/Islam/Islam-urdu.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-bulgarian.conllu Islam-vietnamese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-bulgarian.conllu data/Islam/Islam-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-bulgarian.conllu Islam-wolof.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-bulgarian.conllu data/Islam/Islam-wolof.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-catalan.conllu Islam-welsh.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-catalan.conllu data/Islam/Islam-welsh.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-catalan.conllu Islam-estonian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-catalan.conllu data/Islam/Islam-estonian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-catalan.conllu Islam-persian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-catalan.conllu data/Islam/Islam-persian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-catalan.conllu Islam-galician.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-catalan.conllu data/Islam/Islam-galician.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-catalan.conllu Islam-korean.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-catalan.conllu data/Islam/Islam-korean.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-catalan.conllu Islam-croatian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-catalan.conllu data/Islam/Islam-croatian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-catalan.conllu Islam-indonesian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-catalan.conllu data/Islam/Islam-indonesian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-catalan.conllu Islam-italian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-catalan.conllu data/Islam/Islam-italian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-catalan.conllu Islam-hebrew.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-catalan.conllu data/Islam/Islam-hebrew.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-catalan.conllu Islam-latvian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-catalan.conllu data/Islam/Islam-latvian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-catalan.conllu Islam-romanian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-catalan.conllu data/Islam/Islam-romanian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-catalan.conllu Islam-slovenian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-catalan.conllu data/Islam/Islam-slovenian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-catalan.conllu Islam-serbian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-catalan.conllu data/Islam/Islam-serbian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-catalan.conllu Islam-tamil.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-catalan.conllu data/Islam/Islam-tamil.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-catalan.conllu Islam-ukrainian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-catalan.conllu data/Islam/Islam-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-catalan.conllu Islam-urdu.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-catalan.conllu data/Islam/Islam-urdu.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-catalan.conllu Islam-vietnamese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-catalan.conllu data/Islam/Islam-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-catalan.conllu Islam-wolof.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-catalan.conllu data/Islam/Islam-wolof.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-welsh.conllu Islam-estonian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-welsh.conllu data/Islam/Islam-estonian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-welsh.conllu Islam-persian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-welsh.conllu data/Islam/Islam-persian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-welsh.conllu Islam-galician.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-welsh.conllu data/Islam/Islam-galician.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-welsh.conllu Islam-korean.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-welsh.conllu data/Islam/Islam-korean.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-welsh.conllu Islam-croatian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-welsh.conllu data/Islam/Islam-croatian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-welsh.conllu Islam-indonesian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-welsh.conllu data/Islam/Islam-indonesian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-welsh.conllu Islam-italian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-welsh.conllu data/Islam/Islam-italian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-welsh.conllu Islam-hebrew.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-welsh.conllu data/Islam/Islam-hebrew.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-welsh.conllu Islam-latvian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-welsh.conllu data/Islam/Islam-latvian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-welsh.conllu Islam-romanian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-welsh.conllu data/Islam/Islam-romanian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-welsh.conllu Islam-slovenian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-welsh.conllu data/Islam/Islam-slovenian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-welsh.conllu Islam-serbian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-welsh.conllu data/Islam/Islam-serbian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-welsh.conllu Islam-tamil.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-welsh.conllu data/Islam/Islam-tamil.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-welsh.conllu Islam-ukrainian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-welsh.conllu data/Islam/Islam-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-welsh.conllu Islam-urdu.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-welsh.conllu data/Islam/Islam-urdu.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-welsh.conllu Islam-vietnamese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-welsh.conllu data/Islam/Islam-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-welsh.conllu Islam-wolof.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-welsh.conllu data/Islam/Islam-wolof.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-estonian.conllu Islam-persian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-estonian.conllu data/Islam/Islam-persian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-estonian.conllu Islam-galician.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-estonian.conllu data/Islam/Islam-galician.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-estonian.conllu Islam-korean.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-estonian.conllu data/Islam/Islam-korean.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-estonian.conllu Islam-croatian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-estonian.conllu data/Islam/Islam-croatian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-estonian.conllu Islam-indonesian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-estonian.conllu data/Islam/Islam-indonesian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-estonian.conllu Islam-italian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-estonian.conllu data/Islam/Islam-italian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-estonian.conllu Islam-hebrew.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-estonian.conllu data/Islam/Islam-hebrew.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-estonian.conllu Islam-latvian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-estonian.conllu data/Islam/Islam-latvian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-estonian.conllu Islam-romanian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-estonian.conllu data/Islam/Islam-romanian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-estonian.conllu Islam-slovenian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-estonian.conllu data/Islam/Islam-slovenian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-estonian.conllu Islam-serbian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-estonian.conllu data/Islam/Islam-serbian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-estonian.conllu Islam-tamil.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-estonian.conllu data/Islam/Islam-tamil.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-estonian.conllu Islam-ukrainian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-estonian.conllu data/Islam/Islam-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-estonian.conllu Islam-urdu.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-estonian.conllu data/Islam/Islam-urdu.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-estonian.conllu Islam-vietnamese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-estonian.conllu data/Islam/Islam-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-estonian.conllu Islam-wolof.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-estonian.conllu data/Islam/Islam-wolof.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-persian.conllu Islam-galician.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-persian.conllu data/Islam/Islam-galician.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-persian.conllu Islam-korean.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-persian.conllu data/Islam/Islam-korean.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-persian.conllu Islam-croatian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-persian.conllu data/Islam/Islam-croatian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-persian.conllu Islam-indonesian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-persian.conllu data/Islam/Islam-indonesian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-persian.conllu Islam-italian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-persian.conllu data/Islam/Islam-italian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-persian.conllu Islam-hebrew.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-persian.conllu data/Islam/Islam-hebrew.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-persian.conllu Islam-latvian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-persian.conllu data/Islam/Islam-latvian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-persian.conllu Islam-romanian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-persian.conllu data/Islam/Islam-romanian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-persian.conllu Islam-slovenian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-persian.conllu data/Islam/Islam-slovenian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-persian.conllu Islam-serbian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-persian.conllu data/Islam/Islam-serbian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-persian.conllu Islam-tamil.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-persian.conllu data/Islam/Islam-tamil.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-persian.conllu Islam-ukrainian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-persian.conllu data/Islam/Islam-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-persian.conllu Islam-urdu.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-persian.conllu data/Islam/Islam-urdu.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-persian.conllu Islam-vietnamese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-persian.conllu data/Islam/Islam-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-persian.conllu Islam-wolof.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-persian.conllu data/Islam/Islam-wolof.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-galician.conllu Islam-korean.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-galician.conllu data/Islam/Islam-korean.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-galician.conllu Islam-croatian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-galician.conllu data/Islam/Islam-croatian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-galician.conllu Islam-indonesian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-galician.conllu data/Islam/Islam-indonesian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-galician.conllu Islam-italian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-galician.conllu data/Islam/Islam-italian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-galician.conllu Islam-hebrew.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-galician.conllu data/Islam/Islam-hebrew.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-galician.conllu Islam-latvian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-galician.conllu data/Islam/Islam-latvian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-galician.conllu Islam-romanian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-galician.conllu data/Islam/Islam-romanian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-galician.conllu Islam-slovenian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-galician.conllu data/Islam/Islam-slovenian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-galician.conllu Islam-serbian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-galician.conllu data/Islam/Islam-serbian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-galician.conllu Islam-tamil.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-galician.conllu data/Islam/Islam-tamil.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-galician.conllu Islam-ukrainian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-galician.conllu data/Islam/Islam-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-galician.conllu Islam-urdu.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-galician.conllu data/Islam/Islam-urdu.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-galician.conllu Islam-vietnamese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-galician.conllu data/Islam/Islam-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-galician.conllu Islam-wolof.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-galician.conllu data/Islam/Islam-wolof.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-korean.conllu Islam-croatian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-korean.conllu data/Islam/Islam-croatian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-korean.conllu Islam-indonesian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-korean.conllu data/Islam/Islam-indonesian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-korean.conllu Islam-italian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-korean.conllu data/Islam/Islam-italian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-korean.conllu Islam-hebrew.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-korean.conllu data/Islam/Islam-hebrew.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-korean.conllu Islam-latvian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-korean.conllu data/Islam/Islam-latvian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-korean.conllu Islam-romanian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-korean.conllu data/Islam/Islam-romanian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-korean.conllu Islam-slovenian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-korean.conllu data/Islam/Islam-slovenian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-korean.conllu Islam-serbian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-korean.conllu data/Islam/Islam-serbian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-korean.conllu Islam-tamil.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-korean.conllu data/Islam/Islam-tamil.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-korean.conllu Islam-ukrainian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-korean.conllu data/Islam/Islam-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-korean.conllu Islam-urdu.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-korean.conllu data/Islam/Islam-urdu.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-korean.conllu Islam-vietnamese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-korean.conllu data/Islam/Islam-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-korean.conllu Islam-wolof.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-korean.conllu data/Islam/Islam-wolof.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-croatian.conllu Islam-indonesian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-croatian.conllu data/Islam/Islam-indonesian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-croatian.conllu Islam-italian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-croatian.conllu data/Islam/Islam-italian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-croatian.conllu Islam-hebrew.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-croatian.conllu data/Islam/Islam-hebrew.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-croatian.conllu Islam-latvian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-croatian.conllu data/Islam/Islam-latvian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-croatian.conllu Islam-romanian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-croatian.conllu data/Islam/Islam-romanian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-croatian.conllu Islam-slovenian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-croatian.conllu data/Islam/Islam-slovenian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-croatian.conllu Islam-serbian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-croatian.conllu data/Islam/Islam-serbian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-croatian.conllu Islam-tamil.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-croatian.conllu data/Islam/Islam-tamil.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-croatian.conllu Islam-ukrainian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-croatian.conllu data/Islam/Islam-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-croatian.conllu Islam-urdu.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-croatian.conllu data/Islam/Islam-urdu.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-croatian.conllu Islam-vietnamese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-croatian.conllu data/Islam/Islam-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-croatian.conllu Islam-wolof.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-croatian.conllu data/Islam/Islam-wolof.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-indonesian.conllu Islam-italian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-indonesian.conllu data/Islam/Islam-italian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-indonesian.conllu Islam-hebrew.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-indonesian.conllu data/Islam/Islam-hebrew.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-indonesian.conllu Islam-latvian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-indonesian.conllu data/Islam/Islam-latvian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-indonesian.conllu Islam-romanian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-indonesian.conllu data/Islam/Islam-romanian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-indonesian.conllu Islam-slovenian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-indonesian.conllu data/Islam/Islam-slovenian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-indonesian.conllu Islam-serbian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-indonesian.conllu data/Islam/Islam-serbian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-indonesian.conllu Islam-tamil.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-indonesian.conllu data/Islam/Islam-tamil.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-indonesian.conllu Islam-ukrainian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-indonesian.conllu data/Islam/Islam-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-indonesian.conllu Islam-urdu.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-indonesian.conllu data/Islam/Islam-urdu.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-indonesian.conllu Islam-vietnamese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-indonesian.conllu data/Islam/Islam-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-indonesian.conllu Islam-wolof.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-indonesian.conllu data/Islam/Islam-wolof.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-italian.conllu Islam-hebrew.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-italian.conllu data/Islam/Islam-hebrew.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-italian.conllu Islam-latvian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-italian.conllu data/Islam/Islam-latvian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-italian.conllu Islam-romanian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-italian.conllu data/Islam/Islam-romanian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-italian.conllu Islam-slovenian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-italian.conllu data/Islam/Islam-slovenian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-italian.conllu Islam-serbian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-italian.conllu data/Islam/Islam-serbian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-italian.conllu Islam-tamil.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-italian.conllu data/Islam/Islam-tamil.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-italian.conllu Islam-ukrainian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-italian.conllu data/Islam/Islam-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-italian.conllu Islam-urdu.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-italian.conllu data/Islam/Islam-urdu.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-italian.conllu Islam-vietnamese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-italian.conllu data/Islam/Islam-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-italian.conllu Islam-wolof.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-italian.conllu data/Islam/Islam-wolof.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-hebrew.conllu Islam-latvian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-hebrew.conllu data/Islam/Islam-latvian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-hebrew.conllu Islam-romanian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-hebrew.conllu data/Islam/Islam-romanian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-hebrew.conllu Islam-slovenian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-hebrew.conllu data/Islam/Islam-slovenian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-hebrew.conllu Islam-serbian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-hebrew.conllu data/Islam/Islam-serbian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-hebrew.conllu Islam-tamil.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-hebrew.conllu data/Islam/Islam-tamil.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-hebrew.conllu Islam-ukrainian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-hebrew.conllu data/Islam/Islam-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-hebrew.conllu Islam-urdu.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-hebrew.conllu data/Islam/Islam-urdu.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-hebrew.conllu Islam-vietnamese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-hebrew.conllu data/Islam/Islam-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-hebrew.conllu Islam-wolof.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-hebrew.conllu data/Islam/Islam-wolof.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-latvian.conllu Islam-romanian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-latvian.conllu data/Islam/Islam-romanian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-latvian.conllu Islam-slovenian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-latvian.conllu data/Islam/Islam-slovenian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-latvian.conllu Islam-serbian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-latvian.conllu data/Islam/Islam-serbian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-latvian.conllu Islam-tamil.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-latvian.conllu data/Islam/Islam-tamil.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-latvian.conllu Islam-ukrainian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-latvian.conllu data/Islam/Islam-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-latvian.conllu Islam-urdu.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-latvian.conllu data/Islam/Islam-urdu.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-latvian.conllu Islam-vietnamese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-latvian.conllu data/Islam/Islam-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-latvian.conllu Islam-wolof.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-latvian.conllu data/Islam/Islam-wolof.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-romanian.conllu Islam-slovenian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-romanian.conllu data/Islam/Islam-slovenian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-romanian.conllu Islam-serbian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-romanian.conllu data/Islam/Islam-serbian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-romanian.conllu Islam-tamil.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-romanian.conllu data/Islam/Islam-tamil.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-romanian.conllu Islam-ukrainian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-romanian.conllu data/Islam/Islam-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-romanian.conllu Islam-urdu.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-romanian.conllu data/Islam/Islam-urdu.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-romanian.conllu Islam-vietnamese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-romanian.conllu data/Islam/Islam-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-romanian.conllu Islam-wolof.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-romanian.conllu data/Islam/Islam-wolof.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-slovenian.conllu Islam-serbian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-slovenian.conllu data/Islam/Islam-serbian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-slovenian.conllu Islam-tamil.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-slovenian.conllu data/Islam/Islam-tamil.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-slovenian.conllu Islam-ukrainian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-slovenian.conllu data/Islam/Islam-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-slovenian.conllu Islam-urdu.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-slovenian.conllu data/Islam/Islam-urdu.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-slovenian.conllu Islam-vietnamese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-slovenian.conllu data/Islam/Islam-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-slovenian.conllu Islam-wolof.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-slovenian.conllu data/Islam/Islam-wolof.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-serbian.conllu Islam-tamil.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-serbian.conllu data/Islam/Islam-tamil.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-serbian.conllu Islam-ukrainian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-serbian.conllu data/Islam/Islam-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-serbian.conllu Islam-urdu.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-serbian.conllu data/Islam/Islam-urdu.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-serbian.conllu Islam-vietnamese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-serbian.conllu data/Islam/Islam-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-serbian.conllu Islam-wolof.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-serbian.conllu data/Islam/Islam-wolof.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-tamil.conllu Islam-ukrainian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-tamil.conllu data/Islam/Islam-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-tamil.conllu Islam-urdu.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-tamil.conllu data/Islam/Islam-urdu.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-tamil.conllu Islam-vietnamese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-tamil.conllu data/Islam/Islam-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-tamil.conllu Islam-wolof.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-tamil.conllu data/Islam/Islam-wolof.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-ukrainian.conllu Islam-urdu.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-ukrainian.conllu data/Islam/Islam-urdu.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-ukrainian.conllu Islam-vietnamese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-ukrainian.conllu data/Islam/Islam-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-ukrainian.conllu Islam-wolof.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-ukrainian.conllu data/Islam/Islam-wolof.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-urdu.conllu Islam-vietnamese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-urdu.conllu data/Islam/Islam-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-urdu.conllu Islam-wolof.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-urdu.conllu data/Islam/Islam-wolof.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-vietnamese.conllu Islam-wolof.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-vietnamese.conllu data/Islam/Islam-wolof.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-czech.conllu Islam-german.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-czech.conllu data/Islam/Islam-german.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-czech.conllu Islam-greek.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-czech.conllu data/Islam/Islam-greek.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-czech.conllu Islam-hindi.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-czech.conllu data/Islam/Islam-hindi.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-czech.conllu Islam-dutch.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-czech.conllu data/Islam/Islam-dutch.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-czech.conllu Islam-polish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-czech.conllu data/Islam/Islam-polish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-czech.conllu Islam-portuguese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-czech.conllu data/Islam/Islam-portuguese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-czech.conllu Islam-russian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-czech.conllu data/Islam/Islam-russian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-czech.conllu Islam-sanskrit.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-czech.conllu data/Islam/Islam-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-czech.conllu Islam-slovak.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-czech.conllu data/Islam/Islam-slovak.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-czech.conllu Islam-swedish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-czech.conllu data/Islam/Islam-swedish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-czech.conllu Islam-telugu.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-czech.conllu data/Islam/Islam-telugu.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-czech.conllu Islam-chinese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-czech.conllu data/Islam/Islam-chinese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-german.conllu Islam-greek.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-german.conllu data/Islam/Islam-greek.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-german.conllu Islam-hindi.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-german.conllu data/Islam/Islam-hindi.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-german.conllu Islam-dutch.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-german.conllu data/Islam/Islam-dutch.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-german.conllu Islam-polish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-german.conllu data/Islam/Islam-polish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-german.conllu Islam-portuguese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-german.conllu data/Islam/Islam-portuguese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-german.conllu Islam-russian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-german.conllu data/Islam/Islam-russian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-german.conllu Islam-sanskrit.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-german.conllu data/Islam/Islam-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-german.conllu Islam-slovak.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-german.conllu data/Islam/Islam-slovak.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-german.conllu Islam-swedish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-german.conllu data/Islam/Islam-swedish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-german.conllu Islam-telugu.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-german.conllu data/Islam/Islam-telugu.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-german.conllu Islam-chinese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-german.conllu data/Islam/Islam-chinese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-greek.conllu Islam-hindi.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-greek.conllu data/Islam/Islam-hindi.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-greek.conllu Islam-dutch.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-greek.conllu data/Islam/Islam-dutch.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-greek.conllu Islam-polish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-greek.conllu data/Islam/Islam-polish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-greek.conllu Islam-portuguese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-greek.conllu data/Islam/Islam-portuguese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-greek.conllu Islam-russian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-greek.conllu data/Islam/Islam-russian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-greek.conllu Islam-sanskrit.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-greek.conllu data/Islam/Islam-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-greek.conllu Islam-slovak.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-greek.conllu data/Islam/Islam-slovak.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-greek.conllu Islam-swedish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-greek.conllu data/Islam/Islam-swedish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-greek.conllu Islam-telugu.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-greek.conllu data/Islam/Islam-telugu.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-greek.conllu Islam-chinese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-greek.conllu data/Islam/Islam-chinese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-hindi.conllu Islam-dutch.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-hindi.conllu data/Islam/Islam-dutch.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-hindi.conllu Islam-polish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-hindi.conllu data/Islam/Islam-polish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-hindi.conllu Islam-portuguese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-hindi.conllu data/Islam/Islam-portuguese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-hindi.conllu Islam-russian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-hindi.conllu data/Islam/Islam-russian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-hindi.conllu Islam-sanskrit.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-hindi.conllu data/Islam/Islam-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-hindi.conllu Islam-slovak.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-hindi.conllu data/Islam/Islam-slovak.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-hindi.conllu Islam-swedish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-hindi.conllu data/Islam/Islam-swedish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-hindi.conllu Islam-telugu.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-hindi.conllu data/Islam/Islam-telugu.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-hindi.conllu Islam-chinese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-hindi.conllu data/Islam/Islam-chinese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-dutch.conllu Islam-polish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-dutch.conllu data/Islam/Islam-polish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-dutch.conllu Islam-portuguese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-dutch.conllu data/Islam/Islam-portuguese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-dutch.conllu Islam-russian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-dutch.conllu data/Islam/Islam-russian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-dutch.conllu Islam-sanskrit.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-dutch.conllu data/Islam/Islam-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-dutch.conllu Islam-slovak.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-dutch.conllu data/Islam/Islam-slovak.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-dutch.conllu Islam-swedish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-dutch.conllu data/Islam/Islam-swedish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-dutch.conllu Islam-telugu.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-dutch.conllu data/Islam/Islam-telugu.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-dutch.conllu Islam-chinese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-dutch.conllu data/Islam/Islam-chinese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-polish.conllu Islam-portuguese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-polish.conllu data/Islam/Islam-portuguese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-polish.conllu Islam-russian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-polish.conllu data/Islam/Islam-russian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-polish.conllu Islam-sanskrit.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-polish.conllu data/Islam/Islam-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-polish.conllu Islam-slovak.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-polish.conllu data/Islam/Islam-slovak.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-polish.conllu Islam-swedish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-polish.conllu data/Islam/Islam-swedish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-polish.conllu Islam-telugu.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-polish.conllu data/Islam/Islam-telugu.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-polish.conllu Islam-chinese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-polish.conllu data/Islam/Islam-chinese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-portuguese.conllu Islam-russian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-portuguese.conllu data/Islam/Islam-russian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-portuguese.conllu Islam-sanskrit.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-portuguese.conllu data/Islam/Islam-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-portuguese.conllu Islam-slovak.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-portuguese.conllu data/Islam/Islam-slovak.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-portuguese.conllu Islam-swedish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-portuguese.conllu data/Islam/Islam-swedish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-portuguese.conllu Islam-telugu.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-portuguese.conllu data/Islam/Islam-telugu.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-portuguese.conllu Islam-chinese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-portuguese.conllu data/Islam/Islam-chinese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-russian.conllu Islam-sanskrit.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-russian.conllu data/Islam/Islam-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-russian.conllu Islam-slovak.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-russian.conllu data/Islam/Islam-slovak.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-russian.conllu Islam-swedish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-russian.conllu data/Islam/Islam-swedish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-russian.conllu Islam-telugu.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-russian.conllu data/Islam/Islam-telugu.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-russian.conllu Islam-chinese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-russian.conllu data/Islam/Islam-chinese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-sanskrit.conllu Islam-slovak.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-sanskrit.conllu data/Islam/Islam-slovak.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-sanskrit.conllu Islam-swedish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-sanskrit.conllu data/Islam/Islam-swedish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-sanskrit.conllu Islam-telugu.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-sanskrit.conllu data/Islam/Islam-telugu.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-sanskrit.conllu Islam-chinese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-sanskrit.conllu data/Islam/Islam-chinese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-slovak.conllu Islam-swedish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-slovak.conllu data/Islam/Islam-swedish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-slovak.conllu Islam-telugu.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-slovak.conllu data/Islam/Islam-telugu.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-slovak.conllu Islam-chinese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-slovak.conllu data/Islam/Islam-chinese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-swedish.conllu Islam-telugu.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-swedish.conllu data/Islam/Islam-telugu.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-swedish.conllu Islam-chinese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-swedish.conllu data/Islam/Islam-chinese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-telugu.conllu Islam-chinese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-telugu.conllu data/Islam/Islam-chinese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-english.conllu Islam-arabic.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-english.conllu data/Islam/Islam-arabic.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-english.conllu Islam-danish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-english.conllu data/Islam/Islam-danish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-english.conllu Islam-spanish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-english.conllu data/Islam/Islam-spanish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-english.conllu Islam-french.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-english.conllu data/Islam/Islam-french.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-english.conllu Islam-armenian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-english.conllu data/Islam/Islam-armenian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-english.conllu Islam-kazakh.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-english.conllu data/Islam/Islam-kazakh.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-english.conllu Islam-hungarian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-english.conllu data/Islam/Islam-hungarian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-english.conllu Islam-japanese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-english.conllu data/Islam/Islam-japanese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-english.conllu Islam-finnish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-english.conllu data/Islam/Islam-finnish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-english.conllu Islam-turkish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-english.conllu data/Islam/Islam-turkish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-english.conllu Islam-uyghur.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-english.conllu data/Islam/Islam-uyghur.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-arabic.conllu Islam-danish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-arabic.conllu data/Islam/Islam-danish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-arabic.conllu Islam-spanish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-arabic.conllu data/Islam/Islam-spanish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-arabic.conllu Islam-french.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-arabic.conllu data/Islam/Islam-french.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-arabic.conllu Islam-armenian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-arabic.conllu data/Islam/Islam-armenian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-arabic.conllu Islam-kazakh.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-arabic.conllu data/Islam/Islam-kazakh.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-arabic.conllu Islam-hungarian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-arabic.conllu data/Islam/Islam-hungarian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-arabic.conllu Islam-japanese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-arabic.conllu data/Islam/Islam-japanese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-arabic.conllu Islam-finnish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-arabic.conllu data/Islam/Islam-finnish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-arabic.conllu Islam-turkish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-arabic.conllu data/Islam/Islam-turkish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-arabic.conllu Islam-uyghur.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-arabic.conllu data/Islam/Islam-uyghur.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-danish.conllu Islam-spanish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-danish.conllu data/Islam/Islam-spanish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-danish.conllu Islam-french.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-danish.conllu data/Islam/Islam-french.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-danish.conllu Islam-armenian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-danish.conllu data/Islam/Islam-armenian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-danish.conllu Islam-kazakh.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-danish.conllu data/Islam/Islam-kazakh.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-danish.conllu Islam-hungarian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-danish.conllu data/Islam/Islam-hungarian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-danish.conllu Islam-japanese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-danish.conllu data/Islam/Islam-japanese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-danish.conllu Islam-finnish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-danish.conllu data/Islam/Islam-finnish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-danish.conllu Islam-turkish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-danish.conllu data/Islam/Islam-turkish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-danish.conllu Islam-uyghur.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-danish.conllu data/Islam/Islam-uyghur.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-spanish.conllu Islam-french.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-spanish.conllu data/Islam/Islam-french.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-spanish.conllu Islam-armenian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-spanish.conllu data/Islam/Islam-armenian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-spanish.conllu Islam-kazakh.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-spanish.conllu data/Islam/Islam-kazakh.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-spanish.conllu Islam-hungarian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-spanish.conllu data/Islam/Islam-hungarian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-spanish.conllu Islam-japanese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-spanish.conllu data/Islam/Islam-japanese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-spanish.conllu Islam-finnish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-spanish.conllu data/Islam/Islam-finnish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-spanish.conllu Islam-turkish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-spanish.conllu data/Islam/Islam-turkish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-spanish.conllu Islam-uyghur.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-spanish.conllu data/Islam/Islam-uyghur.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-french.conllu Islam-armenian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-french.conllu data/Islam/Islam-armenian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-french.conllu Islam-kazakh.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-french.conllu data/Islam/Islam-kazakh.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-french.conllu Islam-hungarian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-french.conllu data/Islam/Islam-hungarian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-french.conllu Islam-japanese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-french.conllu data/Islam/Islam-japanese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-french.conllu Islam-finnish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-french.conllu data/Islam/Islam-finnish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-french.conllu Islam-turkish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-french.conllu data/Islam/Islam-turkish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-french.conllu Islam-uyghur.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-french.conllu data/Islam/Islam-uyghur.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-armenian.conllu Islam-kazakh.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-armenian.conllu data/Islam/Islam-kazakh.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-armenian.conllu Islam-hungarian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-armenian.conllu data/Islam/Islam-hungarian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-armenian.conllu Islam-japanese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-armenian.conllu data/Islam/Islam-japanese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-armenian.conllu Islam-finnish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-armenian.conllu data/Islam/Islam-finnish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-armenian.conllu Islam-turkish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-armenian.conllu data/Islam/Islam-turkish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-armenian.conllu Islam-uyghur.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-armenian.conllu data/Islam/Islam-uyghur.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-kazakh.conllu Islam-hungarian.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-kazakh.conllu data/Islam/Islam-hungarian.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-kazakh.conllu Islam-japanese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-kazakh.conllu data/Islam/Islam-japanese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-kazakh.conllu Islam-finnish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-kazakh.conllu data/Islam/Islam-finnish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-kazakh.conllu Islam-turkish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-kazakh.conllu data/Islam/Islam-turkish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-kazakh.conllu Islam-uyghur.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-kazakh.conllu data/Islam/Islam-uyghur.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-hungarian.conllu Islam-japanese.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-hungarian.conllu data/Islam/Islam-japanese.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-hungarian.conllu Islam-finnish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-hungarian.conllu data/Islam/Islam-finnish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-hungarian.conllu Islam-turkish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-hungarian.conllu data/Islam/Islam-turkish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-hungarian.conllu Islam-uyghur.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-hungarian.conllu data/Islam/Islam-uyghur.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-japanese.conllu Islam-finnish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-japanese.conllu data/Islam/Islam-finnish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-japanese.conllu Islam-turkish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-japanese.conllu data/Islam/Islam-turkish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-japanese.conllu Islam-uyghur.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-japanese.conllu data/Islam/Islam-uyghur.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-finnish.conllu Islam-turkish.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-finnish.conllu data/Islam/Islam-turkish.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-finnish.conllu Islam-uyghur.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-finnish.conllu data/Islam/Islam-uyghur.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
echo Islam-turkish.conllu Islam-uyghur.conllu >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
gfud cosine-similarity data/Islam/Islam-turkish.conllu data/Islam/Islam-uyghur.conllu DEPREL >> cosine-sim-per-topic/Islam-cosine-sim.txt ; 
} 
topic_combinations