#! /bin/bash 
function topic_combinations { 
echo Jesus-north_sami.conllu Jesus-old_church_slavonic.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-north_sami.conllu data/Jesus/Jesus-old_church_slavonic.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-north_sami.conllu Jesus-wolof.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-north_sami.conllu data/Jesus/Jesus-wolof.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-old_church_slavonic.conllu Jesus-wolof.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-old_church_slavonic.conllu data/Jesus/Jesus-wolof.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-welsh.conllu Jesus-irish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-welsh.conllu data/Jesus/Jesus-irish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-welsh.conllu Jesus-scottish_gaelic.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-welsh.conllu data/Jesus/Jesus-scottish_gaelic.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-welsh.conllu Jesus-gothic.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-welsh.conllu data/Jesus/Jesus-gothic.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-welsh.conllu Jesus-latvian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-welsh.conllu data/Jesus/Jesus-latvian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-welsh.conllu Jesus-maltese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-welsh.conllu data/Jesus/Jesus-maltese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-welsh.conllu Jesus-marathi.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-welsh.conllu data/Jesus/Jesus-marathi.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-welsh.conllu Jesus-japanese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-welsh.conllu data/Jesus/Jesus-japanese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-welsh.conllu Jesus-sanskrit.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-welsh.conllu data/Jesus/Jesus-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-welsh.conllu Jesus-telugu.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-welsh.conllu data/Jesus/Jesus-telugu.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-welsh.conllu Jesus-uyghur.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-welsh.conllu data/Jesus/Jesus-uyghur.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-welsh.conllu Jesus-classical_chinese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-welsh.conllu data/Jesus/Jesus-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-irish.conllu Jesus-scottish_gaelic.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-irish.conllu data/Jesus/Jesus-scottish_gaelic.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-irish.conllu Jesus-gothic.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-irish.conllu data/Jesus/Jesus-gothic.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-irish.conllu Jesus-latvian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-irish.conllu data/Jesus/Jesus-latvian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-irish.conllu Jesus-maltese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-irish.conllu data/Jesus/Jesus-maltese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-irish.conllu Jesus-marathi.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-irish.conllu data/Jesus/Jesus-marathi.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-irish.conllu Jesus-japanese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-irish.conllu data/Jesus/Jesus-japanese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-irish.conllu Jesus-sanskrit.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-irish.conllu data/Jesus/Jesus-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-irish.conllu Jesus-telugu.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-irish.conllu data/Jesus/Jesus-telugu.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-irish.conllu Jesus-uyghur.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-irish.conllu data/Jesus/Jesus-uyghur.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-irish.conllu Jesus-classical_chinese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-irish.conllu data/Jesus/Jesus-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-scottish_gaelic.conllu Jesus-gothic.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-scottish_gaelic.conllu data/Jesus/Jesus-gothic.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-scottish_gaelic.conllu Jesus-latvian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-scottish_gaelic.conllu data/Jesus/Jesus-latvian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-scottish_gaelic.conllu Jesus-maltese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-scottish_gaelic.conllu data/Jesus/Jesus-maltese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-scottish_gaelic.conllu Jesus-marathi.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-scottish_gaelic.conllu data/Jesus/Jesus-marathi.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-scottish_gaelic.conllu Jesus-japanese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-scottish_gaelic.conllu data/Jesus/Jesus-japanese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-scottish_gaelic.conllu Jesus-sanskrit.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-scottish_gaelic.conllu data/Jesus/Jesus-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-scottish_gaelic.conllu Jesus-telugu.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-scottish_gaelic.conllu data/Jesus/Jesus-telugu.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-scottish_gaelic.conllu Jesus-uyghur.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-scottish_gaelic.conllu data/Jesus/Jesus-uyghur.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-scottish_gaelic.conllu Jesus-classical_chinese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-scottish_gaelic.conllu data/Jesus/Jesus-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-gothic.conllu Jesus-latvian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-gothic.conllu data/Jesus/Jesus-latvian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-gothic.conllu Jesus-maltese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-gothic.conllu data/Jesus/Jesus-maltese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-gothic.conllu Jesus-marathi.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-gothic.conllu data/Jesus/Jesus-marathi.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-gothic.conllu Jesus-japanese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-gothic.conllu data/Jesus/Jesus-japanese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-gothic.conllu Jesus-sanskrit.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-gothic.conllu data/Jesus/Jesus-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-gothic.conllu Jesus-telugu.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-gothic.conllu data/Jesus/Jesus-telugu.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-gothic.conllu Jesus-uyghur.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-gothic.conllu data/Jesus/Jesus-uyghur.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-gothic.conllu Jesus-classical_chinese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-gothic.conllu data/Jesus/Jesus-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-latvian.conllu Jesus-maltese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-latvian.conllu data/Jesus/Jesus-maltese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-latvian.conllu Jesus-marathi.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-latvian.conllu data/Jesus/Jesus-marathi.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-latvian.conllu Jesus-japanese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-latvian.conllu data/Jesus/Jesus-japanese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-latvian.conllu Jesus-sanskrit.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-latvian.conllu data/Jesus/Jesus-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-latvian.conllu Jesus-telugu.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-latvian.conllu data/Jesus/Jesus-telugu.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-latvian.conllu Jesus-uyghur.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-latvian.conllu data/Jesus/Jesus-uyghur.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-latvian.conllu Jesus-classical_chinese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-latvian.conllu data/Jesus/Jesus-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-maltese.conllu Jesus-marathi.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-maltese.conllu data/Jesus/Jesus-marathi.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-maltese.conllu Jesus-japanese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-maltese.conllu data/Jesus/Jesus-japanese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-maltese.conllu Jesus-sanskrit.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-maltese.conllu data/Jesus/Jesus-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-maltese.conllu Jesus-telugu.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-maltese.conllu data/Jesus/Jesus-telugu.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-maltese.conllu Jesus-uyghur.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-maltese.conllu data/Jesus/Jesus-uyghur.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-maltese.conllu Jesus-classical_chinese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-maltese.conllu data/Jesus/Jesus-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-marathi.conllu Jesus-japanese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-marathi.conllu data/Jesus/Jesus-japanese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-marathi.conllu Jesus-sanskrit.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-marathi.conllu data/Jesus/Jesus-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-marathi.conllu Jesus-telugu.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-marathi.conllu data/Jesus/Jesus-telugu.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-marathi.conllu Jesus-uyghur.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-marathi.conllu data/Jesus/Jesus-uyghur.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-marathi.conllu Jesus-classical_chinese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-marathi.conllu data/Jesus/Jesus-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-japanese.conllu Jesus-sanskrit.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-japanese.conllu data/Jesus/Jesus-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-japanese.conllu Jesus-telugu.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-japanese.conllu data/Jesus/Jesus-telugu.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-japanese.conllu Jesus-uyghur.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-japanese.conllu data/Jesus/Jesus-uyghur.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-japanese.conllu Jesus-classical_chinese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-japanese.conllu data/Jesus/Jesus-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-sanskrit.conllu Jesus-telugu.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-sanskrit.conllu data/Jesus/Jesus-telugu.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-sanskrit.conllu Jesus-uyghur.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-sanskrit.conllu data/Jesus/Jesus-uyghur.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-sanskrit.conllu Jesus-classical_chinese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-sanskrit.conllu data/Jesus/Jesus-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-telugu.conllu Jesus-uyghur.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-telugu.conllu data/Jesus/Jesus-uyghur.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-telugu.conllu Jesus-classical_chinese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-telugu.conllu data/Jesus/Jesus-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-uyghur.conllu Jesus-classical_chinese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-uyghur.conllu data/Jesus/Jesus-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-bulgarian.conllu Jesus-czech.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-bulgarian.conllu data/Jesus/Jesus-czech.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-bulgarian.conllu Jesus-estonian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-bulgarian.conllu data/Jesus/Jesus-estonian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-bulgarian.conllu Jesus-greek.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-bulgarian.conllu data/Jesus/Jesus-greek.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-bulgarian.conllu Jesus-basque.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-bulgarian.conllu data/Jesus/Jesus-basque.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-bulgarian.conllu Jesus-hindi.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-bulgarian.conllu data/Jesus/Jesus-hindi.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-bulgarian.conllu Jesus-croatian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-bulgarian.conllu data/Jesus/Jesus-croatian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-bulgarian.conllu Jesus-hebrew.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-bulgarian.conllu data/Jesus/Jesus-hebrew.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-bulgarian.conllu Jesus-kazakh.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-bulgarian.conllu data/Jesus/Jesus-kazakh.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-bulgarian.conllu Jesus-latin.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-bulgarian.conllu data/Jesus/Jesus-latin.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-bulgarian.conllu Jesus-lithuanian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-bulgarian.conllu data/Jesus/Jesus-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-bulgarian.conllu Jesus-dutch.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-bulgarian.conllu data/Jesus/Jesus-dutch.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-bulgarian.conllu Jesus-polish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-bulgarian.conllu data/Jesus/Jesus-polish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-bulgarian.conllu Jesus-slovak.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-bulgarian.conllu data/Jesus/Jesus-slovak.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-bulgarian.conllu Jesus-slovenian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-bulgarian.conllu data/Jesus/Jesus-slovenian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-bulgarian.conllu Jesus-turkish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-bulgarian.conllu data/Jesus/Jesus-turkish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-bulgarian.conllu Jesus-urdu.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-bulgarian.conllu data/Jesus/Jesus-urdu.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-bulgarian.conllu Jesus-vietnamese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-bulgarian.conllu data/Jesus/Jesus-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-bulgarian.conllu Jesus-chinese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-bulgarian.conllu data/Jesus/Jesus-chinese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-czech.conllu Jesus-estonian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-czech.conllu data/Jesus/Jesus-estonian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-czech.conllu Jesus-greek.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-czech.conllu data/Jesus/Jesus-greek.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-czech.conllu Jesus-basque.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-czech.conllu data/Jesus/Jesus-basque.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-czech.conllu Jesus-hindi.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-czech.conllu data/Jesus/Jesus-hindi.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-czech.conllu Jesus-croatian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-czech.conllu data/Jesus/Jesus-croatian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-czech.conllu Jesus-hebrew.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-czech.conllu data/Jesus/Jesus-hebrew.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-czech.conllu Jesus-kazakh.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-czech.conllu data/Jesus/Jesus-kazakh.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-czech.conllu Jesus-latin.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-czech.conllu data/Jesus/Jesus-latin.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-czech.conllu Jesus-lithuanian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-czech.conllu data/Jesus/Jesus-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-czech.conllu Jesus-dutch.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-czech.conllu data/Jesus/Jesus-dutch.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-czech.conllu Jesus-polish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-czech.conllu data/Jesus/Jesus-polish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-czech.conllu Jesus-slovak.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-czech.conllu data/Jesus/Jesus-slovak.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-czech.conllu Jesus-slovenian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-czech.conllu data/Jesus/Jesus-slovenian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-czech.conllu Jesus-turkish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-czech.conllu data/Jesus/Jesus-turkish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-czech.conllu Jesus-urdu.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-czech.conllu data/Jesus/Jesus-urdu.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-czech.conllu Jesus-vietnamese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-czech.conllu data/Jesus/Jesus-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-czech.conllu Jesus-chinese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-czech.conllu data/Jesus/Jesus-chinese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-estonian.conllu Jesus-greek.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-estonian.conllu data/Jesus/Jesus-greek.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-estonian.conllu Jesus-basque.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-estonian.conllu data/Jesus/Jesus-basque.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-estonian.conllu Jesus-hindi.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-estonian.conllu data/Jesus/Jesus-hindi.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-estonian.conllu Jesus-croatian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-estonian.conllu data/Jesus/Jesus-croatian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-estonian.conllu Jesus-hebrew.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-estonian.conllu data/Jesus/Jesus-hebrew.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-estonian.conllu Jesus-kazakh.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-estonian.conllu data/Jesus/Jesus-kazakh.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-estonian.conllu Jesus-latin.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-estonian.conllu data/Jesus/Jesus-latin.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-estonian.conllu Jesus-lithuanian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-estonian.conllu data/Jesus/Jesus-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-estonian.conllu Jesus-dutch.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-estonian.conllu data/Jesus/Jesus-dutch.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-estonian.conllu Jesus-polish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-estonian.conllu data/Jesus/Jesus-polish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-estonian.conllu Jesus-slovak.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-estonian.conllu data/Jesus/Jesus-slovak.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-estonian.conllu Jesus-slovenian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-estonian.conllu data/Jesus/Jesus-slovenian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-estonian.conllu Jesus-turkish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-estonian.conllu data/Jesus/Jesus-turkish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-estonian.conllu Jesus-urdu.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-estonian.conllu data/Jesus/Jesus-urdu.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-estonian.conllu Jesus-vietnamese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-estonian.conllu data/Jesus/Jesus-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-estonian.conllu Jesus-chinese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-estonian.conllu data/Jesus/Jesus-chinese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-greek.conllu Jesus-basque.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-greek.conllu data/Jesus/Jesus-basque.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-greek.conllu Jesus-hindi.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-greek.conllu data/Jesus/Jesus-hindi.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-greek.conllu Jesus-croatian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-greek.conllu data/Jesus/Jesus-croatian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-greek.conllu Jesus-hebrew.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-greek.conllu data/Jesus/Jesus-hebrew.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-greek.conllu Jesus-kazakh.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-greek.conllu data/Jesus/Jesus-kazakh.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-greek.conllu Jesus-latin.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-greek.conllu data/Jesus/Jesus-latin.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-greek.conllu Jesus-lithuanian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-greek.conllu data/Jesus/Jesus-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-greek.conllu Jesus-dutch.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-greek.conllu data/Jesus/Jesus-dutch.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-greek.conllu Jesus-polish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-greek.conllu data/Jesus/Jesus-polish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-greek.conllu Jesus-slovak.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-greek.conllu data/Jesus/Jesus-slovak.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-greek.conllu Jesus-slovenian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-greek.conllu data/Jesus/Jesus-slovenian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-greek.conllu Jesus-turkish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-greek.conllu data/Jesus/Jesus-turkish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-greek.conllu Jesus-urdu.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-greek.conllu data/Jesus/Jesus-urdu.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-greek.conllu Jesus-vietnamese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-greek.conllu data/Jesus/Jesus-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-greek.conllu Jesus-chinese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-greek.conllu data/Jesus/Jesus-chinese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-basque.conllu Jesus-hindi.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-basque.conllu data/Jesus/Jesus-hindi.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-basque.conllu Jesus-croatian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-basque.conllu data/Jesus/Jesus-croatian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-basque.conllu Jesus-hebrew.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-basque.conllu data/Jesus/Jesus-hebrew.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-basque.conllu Jesus-kazakh.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-basque.conllu data/Jesus/Jesus-kazakh.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-basque.conllu Jesus-latin.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-basque.conllu data/Jesus/Jesus-latin.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-basque.conllu Jesus-lithuanian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-basque.conllu data/Jesus/Jesus-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-basque.conllu Jesus-dutch.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-basque.conllu data/Jesus/Jesus-dutch.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-basque.conllu Jesus-polish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-basque.conllu data/Jesus/Jesus-polish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-basque.conllu Jesus-slovak.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-basque.conllu data/Jesus/Jesus-slovak.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-basque.conllu Jesus-slovenian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-basque.conllu data/Jesus/Jesus-slovenian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-basque.conllu Jesus-turkish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-basque.conllu data/Jesus/Jesus-turkish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-basque.conllu Jesus-urdu.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-basque.conllu data/Jesus/Jesus-urdu.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-basque.conllu Jesus-vietnamese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-basque.conllu data/Jesus/Jesus-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-basque.conllu Jesus-chinese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-basque.conllu data/Jesus/Jesus-chinese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-hindi.conllu Jesus-croatian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-hindi.conllu data/Jesus/Jesus-croatian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-hindi.conllu Jesus-hebrew.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-hindi.conllu data/Jesus/Jesus-hebrew.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-hindi.conllu Jesus-kazakh.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-hindi.conllu data/Jesus/Jesus-kazakh.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-hindi.conllu Jesus-latin.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-hindi.conllu data/Jesus/Jesus-latin.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-hindi.conllu Jesus-lithuanian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-hindi.conllu data/Jesus/Jesus-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-hindi.conllu Jesus-dutch.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-hindi.conllu data/Jesus/Jesus-dutch.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-hindi.conllu Jesus-polish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-hindi.conllu data/Jesus/Jesus-polish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-hindi.conllu Jesus-slovak.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-hindi.conllu data/Jesus/Jesus-slovak.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-hindi.conllu Jesus-slovenian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-hindi.conllu data/Jesus/Jesus-slovenian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-hindi.conllu Jesus-turkish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-hindi.conllu data/Jesus/Jesus-turkish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-hindi.conllu Jesus-urdu.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-hindi.conllu data/Jesus/Jesus-urdu.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-hindi.conllu Jesus-vietnamese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-hindi.conllu data/Jesus/Jesus-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-hindi.conllu Jesus-chinese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-hindi.conllu data/Jesus/Jesus-chinese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-croatian.conllu Jesus-hebrew.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-croatian.conllu data/Jesus/Jesus-hebrew.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-croatian.conllu Jesus-kazakh.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-croatian.conllu data/Jesus/Jesus-kazakh.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-croatian.conllu Jesus-latin.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-croatian.conllu data/Jesus/Jesus-latin.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-croatian.conllu Jesus-lithuanian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-croatian.conllu data/Jesus/Jesus-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-croatian.conllu Jesus-dutch.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-croatian.conllu data/Jesus/Jesus-dutch.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-croatian.conllu Jesus-polish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-croatian.conllu data/Jesus/Jesus-polish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-croatian.conllu Jesus-slovak.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-croatian.conllu data/Jesus/Jesus-slovak.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-croatian.conllu Jesus-slovenian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-croatian.conllu data/Jesus/Jesus-slovenian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-croatian.conllu Jesus-turkish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-croatian.conllu data/Jesus/Jesus-turkish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-croatian.conllu Jesus-urdu.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-croatian.conllu data/Jesus/Jesus-urdu.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-croatian.conllu Jesus-vietnamese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-croatian.conllu data/Jesus/Jesus-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-croatian.conllu Jesus-chinese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-croatian.conllu data/Jesus/Jesus-chinese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-hebrew.conllu Jesus-kazakh.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-hebrew.conllu data/Jesus/Jesus-kazakh.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-hebrew.conllu Jesus-latin.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-hebrew.conllu data/Jesus/Jesus-latin.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-hebrew.conllu Jesus-lithuanian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-hebrew.conllu data/Jesus/Jesus-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-hebrew.conllu Jesus-dutch.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-hebrew.conllu data/Jesus/Jesus-dutch.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-hebrew.conllu Jesus-polish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-hebrew.conllu data/Jesus/Jesus-polish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-hebrew.conllu Jesus-slovak.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-hebrew.conllu data/Jesus/Jesus-slovak.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-hebrew.conllu Jesus-slovenian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-hebrew.conllu data/Jesus/Jesus-slovenian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-hebrew.conllu Jesus-turkish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-hebrew.conllu data/Jesus/Jesus-turkish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-hebrew.conllu Jesus-urdu.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-hebrew.conllu data/Jesus/Jesus-urdu.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-hebrew.conllu Jesus-vietnamese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-hebrew.conllu data/Jesus/Jesus-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-hebrew.conllu Jesus-chinese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-hebrew.conllu data/Jesus/Jesus-chinese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-kazakh.conllu Jesus-latin.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-kazakh.conllu data/Jesus/Jesus-latin.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-kazakh.conllu Jesus-lithuanian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-kazakh.conllu data/Jesus/Jesus-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-kazakh.conllu Jesus-dutch.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-kazakh.conllu data/Jesus/Jesus-dutch.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-kazakh.conllu Jesus-polish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-kazakh.conllu data/Jesus/Jesus-polish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-kazakh.conllu Jesus-slovak.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-kazakh.conllu data/Jesus/Jesus-slovak.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-kazakh.conllu Jesus-slovenian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-kazakh.conllu data/Jesus/Jesus-slovenian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-kazakh.conllu Jesus-turkish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-kazakh.conllu data/Jesus/Jesus-turkish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-kazakh.conllu Jesus-urdu.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-kazakh.conllu data/Jesus/Jesus-urdu.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-kazakh.conllu Jesus-vietnamese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-kazakh.conllu data/Jesus/Jesus-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-kazakh.conllu Jesus-chinese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-kazakh.conllu data/Jesus/Jesus-chinese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-latin.conllu Jesus-lithuanian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-latin.conllu data/Jesus/Jesus-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-latin.conllu Jesus-dutch.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-latin.conllu data/Jesus/Jesus-dutch.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-latin.conllu Jesus-polish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-latin.conllu data/Jesus/Jesus-polish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-latin.conllu Jesus-slovak.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-latin.conllu data/Jesus/Jesus-slovak.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-latin.conllu Jesus-slovenian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-latin.conllu data/Jesus/Jesus-slovenian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-latin.conllu Jesus-turkish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-latin.conllu data/Jesus/Jesus-turkish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-latin.conllu Jesus-urdu.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-latin.conllu data/Jesus/Jesus-urdu.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-latin.conllu Jesus-vietnamese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-latin.conllu data/Jesus/Jesus-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-latin.conllu Jesus-chinese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-latin.conllu data/Jesus/Jesus-chinese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-lithuanian.conllu Jesus-dutch.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-lithuanian.conllu data/Jesus/Jesus-dutch.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-lithuanian.conllu Jesus-polish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-lithuanian.conllu data/Jesus/Jesus-polish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-lithuanian.conllu Jesus-slovak.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-lithuanian.conllu data/Jesus/Jesus-slovak.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-lithuanian.conllu Jesus-slovenian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-lithuanian.conllu data/Jesus/Jesus-slovenian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-lithuanian.conllu Jesus-turkish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-lithuanian.conllu data/Jesus/Jesus-turkish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-lithuanian.conllu Jesus-urdu.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-lithuanian.conllu data/Jesus/Jesus-urdu.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-lithuanian.conllu Jesus-vietnamese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-lithuanian.conllu data/Jesus/Jesus-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-lithuanian.conllu Jesus-chinese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-lithuanian.conllu data/Jesus/Jesus-chinese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-dutch.conllu Jesus-polish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-dutch.conllu data/Jesus/Jesus-polish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-dutch.conllu Jesus-slovak.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-dutch.conllu data/Jesus/Jesus-slovak.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-dutch.conllu Jesus-slovenian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-dutch.conllu data/Jesus/Jesus-slovenian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-dutch.conllu Jesus-turkish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-dutch.conllu data/Jesus/Jesus-turkish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-dutch.conllu Jesus-urdu.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-dutch.conllu data/Jesus/Jesus-urdu.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-dutch.conllu Jesus-vietnamese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-dutch.conllu data/Jesus/Jesus-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-dutch.conllu Jesus-chinese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-dutch.conllu data/Jesus/Jesus-chinese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-polish.conllu Jesus-slovak.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-polish.conllu data/Jesus/Jesus-slovak.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-polish.conllu Jesus-slovenian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-polish.conllu data/Jesus/Jesus-slovenian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-polish.conllu Jesus-turkish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-polish.conllu data/Jesus/Jesus-turkish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-polish.conllu Jesus-urdu.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-polish.conllu data/Jesus/Jesus-urdu.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-polish.conllu Jesus-vietnamese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-polish.conllu data/Jesus/Jesus-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-polish.conllu Jesus-chinese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-polish.conllu data/Jesus/Jesus-chinese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-slovak.conllu Jesus-slovenian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-slovak.conllu data/Jesus/Jesus-slovenian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-slovak.conllu Jesus-turkish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-slovak.conllu data/Jesus/Jesus-turkish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-slovak.conllu Jesus-urdu.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-slovak.conllu data/Jesus/Jesus-urdu.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-slovak.conllu Jesus-vietnamese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-slovak.conllu data/Jesus/Jesus-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-slovak.conllu Jesus-chinese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-slovak.conllu data/Jesus/Jesus-chinese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-slovenian.conllu Jesus-turkish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-slovenian.conllu data/Jesus/Jesus-turkish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-slovenian.conllu Jesus-urdu.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-slovenian.conllu data/Jesus/Jesus-urdu.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-slovenian.conllu Jesus-vietnamese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-slovenian.conllu data/Jesus/Jesus-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-slovenian.conllu Jesus-chinese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-slovenian.conllu data/Jesus/Jesus-chinese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-turkish.conllu Jesus-urdu.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-turkish.conllu data/Jesus/Jesus-urdu.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-turkish.conllu Jesus-vietnamese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-turkish.conllu data/Jesus/Jesus-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-turkish.conllu Jesus-chinese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-turkish.conllu data/Jesus/Jesus-chinese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-urdu.conllu Jesus-vietnamese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-urdu.conllu data/Jesus/Jesus-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-urdu.conllu Jesus-chinese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-urdu.conllu data/Jesus/Jesus-chinese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-vietnamese.conllu Jesus-chinese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-vietnamese.conllu data/Jesus/Jesus-chinese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-arabic.conllu Jesus-belarusian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-arabic.conllu data/Jesus/Jesus-belarusian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-arabic.conllu Jesus-catalan.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-arabic.conllu data/Jesus/Jesus-catalan.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-arabic.conllu Jesus-danish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-arabic.conllu data/Jesus/Jesus-danish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-arabic.conllu Jesus-french.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-arabic.conllu data/Jesus/Jesus-french.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-arabic.conllu Jesus-korean.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-arabic.conllu data/Jesus/Jesus-korean.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-arabic.conllu Jesus-italian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-arabic.conllu data/Jesus/Jesus-italian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-arabic.conllu Jesus-hungarian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-arabic.conllu data/Jesus/Jesus-hungarian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-arabic.conllu Jesus-portuguese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-arabic.conllu data/Jesus/Jesus-portuguese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-arabic.conllu Jesus-romanian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-arabic.conllu data/Jesus/Jesus-romanian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-arabic.conllu Jesus-serbian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-arabic.conllu data/Jesus/Jesus-serbian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-arabic.conllu Jesus-finnish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-arabic.conllu data/Jesus/Jesus-finnish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-arabic.conllu Jesus-tamil.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-arabic.conllu data/Jesus/Jesus-tamil.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-arabic.conllu Jesus-ukrainian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-arabic.conllu data/Jesus/Jesus-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-belarusian.conllu Jesus-catalan.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-belarusian.conllu data/Jesus/Jesus-catalan.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-belarusian.conllu Jesus-danish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-belarusian.conllu data/Jesus/Jesus-danish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-belarusian.conllu Jesus-french.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-belarusian.conllu data/Jesus/Jesus-french.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-belarusian.conllu Jesus-korean.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-belarusian.conllu data/Jesus/Jesus-korean.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-belarusian.conllu Jesus-italian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-belarusian.conllu data/Jesus/Jesus-italian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-belarusian.conllu Jesus-hungarian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-belarusian.conllu data/Jesus/Jesus-hungarian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-belarusian.conllu Jesus-portuguese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-belarusian.conllu data/Jesus/Jesus-portuguese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-belarusian.conllu Jesus-romanian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-belarusian.conllu data/Jesus/Jesus-romanian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-belarusian.conllu Jesus-serbian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-belarusian.conllu data/Jesus/Jesus-serbian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-belarusian.conllu Jesus-finnish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-belarusian.conllu data/Jesus/Jesus-finnish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-belarusian.conllu Jesus-tamil.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-belarusian.conllu data/Jesus/Jesus-tamil.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-belarusian.conllu Jesus-ukrainian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-belarusian.conllu data/Jesus/Jesus-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-catalan.conllu Jesus-danish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-catalan.conllu data/Jesus/Jesus-danish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-catalan.conllu Jesus-french.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-catalan.conllu data/Jesus/Jesus-french.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-catalan.conllu Jesus-korean.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-catalan.conllu data/Jesus/Jesus-korean.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-catalan.conllu Jesus-italian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-catalan.conllu data/Jesus/Jesus-italian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-catalan.conllu Jesus-hungarian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-catalan.conllu data/Jesus/Jesus-hungarian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-catalan.conllu Jesus-portuguese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-catalan.conllu data/Jesus/Jesus-portuguese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-catalan.conllu Jesus-romanian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-catalan.conllu data/Jesus/Jesus-romanian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-catalan.conllu Jesus-serbian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-catalan.conllu data/Jesus/Jesus-serbian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-catalan.conllu Jesus-finnish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-catalan.conllu data/Jesus/Jesus-finnish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-catalan.conllu Jesus-tamil.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-catalan.conllu data/Jesus/Jesus-tamil.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-catalan.conllu Jesus-ukrainian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-catalan.conllu data/Jesus/Jesus-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-danish.conllu Jesus-french.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-danish.conllu data/Jesus/Jesus-french.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-danish.conllu Jesus-korean.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-danish.conllu data/Jesus/Jesus-korean.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-danish.conllu Jesus-italian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-danish.conllu data/Jesus/Jesus-italian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-danish.conllu Jesus-hungarian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-danish.conllu data/Jesus/Jesus-hungarian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-danish.conllu Jesus-portuguese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-danish.conllu data/Jesus/Jesus-portuguese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-danish.conllu Jesus-romanian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-danish.conllu data/Jesus/Jesus-romanian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-danish.conllu Jesus-serbian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-danish.conllu data/Jesus/Jesus-serbian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-danish.conllu Jesus-finnish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-danish.conllu data/Jesus/Jesus-finnish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-danish.conllu Jesus-tamil.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-danish.conllu data/Jesus/Jesus-tamil.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-danish.conllu Jesus-ukrainian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-danish.conllu data/Jesus/Jesus-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-french.conllu Jesus-korean.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-french.conllu data/Jesus/Jesus-korean.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-french.conllu Jesus-italian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-french.conllu data/Jesus/Jesus-italian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-french.conllu Jesus-hungarian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-french.conllu data/Jesus/Jesus-hungarian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-french.conllu Jesus-portuguese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-french.conllu data/Jesus/Jesus-portuguese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-french.conllu Jesus-romanian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-french.conllu data/Jesus/Jesus-romanian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-french.conllu Jesus-serbian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-french.conllu data/Jesus/Jesus-serbian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-french.conllu Jesus-finnish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-french.conllu data/Jesus/Jesus-finnish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-french.conllu Jesus-tamil.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-french.conllu data/Jesus/Jesus-tamil.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-french.conllu Jesus-ukrainian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-french.conllu data/Jesus/Jesus-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-korean.conllu Jesus-italian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-korean.conllu data/Jesus/Jesus-italian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-korean.conllu Jesus-hungarian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-korean.conllu data/Jesus/Jesus-hungarian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-korean.conllu Jesus-portuguese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-korean.conllu data/Jesus/Jesus-portuguese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-korean.conllu Jesus-romanian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-korean.conllu data/Jesus/Jesus-romanian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-korean.conllu Jesus-serbian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-korean.conllu data/Jesus/Jesus-serbian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-korean.conllu Jesus-finnish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-korean.conllu data/Jesus/Jesus-finnish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-korean.conllu Jesus-tamil.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-korean.conllu data/Jesus/Jesus-tamil.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-korean.conllu Jesus-ukrainian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-korean.conllu data/Jesus/Jesus-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-italian.conllu Jesus-hungarian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-italian.conllu data/Jesus/Jesus-hungarian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-italian.conllu Jesus-portuguese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-italian.conllu data/Jesus/Jesus-portuguese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-italian.conllu Jesus-romanian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-italian.conllu data/Jesus/Jesus-romanian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-italian.conllu Jesus-serbian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-italian.conllu data/Jesus/Jesus-serbian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-italian.conllu Jesus-finnish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-italian.conllu data/Jesus/Jesus-finnish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-italian.conllu Jesus-tamil.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-italian.conllu data/Jesus/Jesus-tamil.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-italian.conllu Jesus-ukrainian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-italian.conllu data/Jesus/Jesus-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-hungarian.conllu Jesus-portuguese.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-hungarian.conllu data/Jesus/Jesus-portuguese.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-hungarian.conllu Jesus-romanian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-hungarian.conllu data/Jesus/Jesus-romanian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-hungarian.conllu Jesus-serbian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-hungarian.conllu data/Jesus/Jesus-serbian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-hungarian.conllu Jesus-finnish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-hungarian.conllu data/Jesus/Jesus-finnish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-hungarian.conllu Jesus-tamil.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-hungarian.conllu data/Jesus/Jesus-tamil.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-hungarian.conllu Jesus-ukrainian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-hungarian.conllu data/Jesus/Jesus-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-portuguese.conllu Jesus-romanian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-portuguese.conllu data/Jesus/Jesus-romanian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-portuguese.conllu Jesus-serbian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-portuguese.conllu data/Jesus/Jesus-serbian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-portuguese.conllu Jesus-finnish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-portuguese.conllu data/Jesus/Jesus-finnish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-portuguese.conllu Jesus-tamil.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-portuguese.conllu data/Jesus/Jesus-tamil.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-portuguese.conllu Jesus-ukrainian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-portuguese.conllu data/Jesus/Jesus-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-romanian.conllu Jesus-serbian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-romanian.conllu data/Jesus/Jesus-serbian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-romanian.conllu Jesus-finnish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-romanian.conllu data/Jesus/Jesus-finnish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-romanian.conllu Jesus-tamil.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-romanian.conllu data/Jesus/Jesus-tamil.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-romanian.conllu Jesus-ukrainian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-romanian.conllu data/Jesus/Jesus-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-serbian.conllu Jesus-finnish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-serbian.conllu data/Jesus/Jesus-finnish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-serbian.conllu Jesus-tamil.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-serbian.conllu data/Jesus/Jesus-tamil.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-serbian.conllu Jesus-ukrainian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-serbian.conllu data/Jesus/Jesus-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-finnish.conllu Jesus-tamil.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-finnish.conllu data/Jesus/Jesus-tamil.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-finnish.conllu Jesus-ukrainian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-finnish.conllu data/Jesus/Jesus-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-tamil.conllu Jesus-ukrainian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-tamil.conllu data/Jesus/Jesus-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-english.conllu Jesus-afrikaans.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-english.conllu data/Jesus/Jesus-afrikaans.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-english.conllu Jesus-german.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-english.conllu data/Jesus/Jesus-german.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-english.conllu Jesus-spanish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-english.conllu data/Jesus/Jesus-spanish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-english.conllu Jesus-persian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-english.conllu data/Jesus/Jesus-persian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-english.conllu Jesus-galician.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-english.conllu data/Jesus/Jesus-galician.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-english.conllu Jesus-armenian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-english.conllu data/Jesus/Jesus-armenian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-english.conllu Jesus-indonesian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-english.conllu data/Jesus/Jesus-indonesian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-english.conllu Jesus-russian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-english.conllu data/Jesus/Jesus-russian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-english.conllu Jesus-swedish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-english.conllu data/Jesus/Jesus-swedish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-afrikaans.conllu Jesus-german.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-afrikaans.conllu data/Jesus/Jesus-german.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-afrikaans.conllu Jesus-spanish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-afrikaans.conllu data/Jesus/Jesus-spanish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-afrikaans.conllu Jesus-persian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-afrikaans.conllu data/Jesus/Jesus-persian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-afrikaans.conllu Jesus-galician.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-afrikaans.conllu data/Jesus/Jesus-galician.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-afrikaans.conllu Jesus-armenian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-afrikaans.conllu data/Jesus/Jesus-armenian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-afrikaans.conllu Jesus-indonesian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-afrikaans.conllu data/Jesus/Jesus-indonesian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-afrikaans.conllu Jesus-russian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-afrikaans.conllu data/Jesus/Jesus-russian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-afrikaans.conllu Jesus-swedish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-afrikaans.conllu data/Jesus/Jesus-swedish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-german.conllu Jesus-spanish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-german.conllu data/Jesus/Jesus-spanish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-german.conllu Jesus-persian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-german.conllu data/Jesus/Jesus-persian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-german.conllu Jesus-galician.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-german.conllu data/Jesus/Jesus-galician.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-german.conllu Jesus-armenian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-german.conllu data/Jesus/Jesus-armenian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-german.conllu Jesus-indonesian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-german.conllu data/Jesus/Jesus-indonesian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-german.conllu Jesus-russian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-german.conllu data/Jesus/Jesus-russian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-german.conllu Jesus-swedish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-german.conllu data/Jesus/Jesus-swedish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-spanish.conllu Jesus-persian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-spanish.conllu data/Jesus/Jesus-persian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-spanish.conllu Jesus-galician.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-spanish.conllu data/Jesus/Jesus-galician.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-spanish.conllu Jesus-armenian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-spanish.conllu data/Jesus/Jesus-armenian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-spanish.conllu Jesus-indonesian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-spanish.conllu data/Jesus/Jesus-indonesian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-spanish.conllu Jesus-russian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-spanish.conllu data/Jesus/Jesus-russian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-spanish.conllu Jesus-swedish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-spanish.conllu data/Jesus/Jesus-swedish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-persian.conllu Jesus-galician.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-persian.conllu data/Jesus/Jesus-galician.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-persian.conllu Jesus-armenian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-persian.conllu data/Jesus/Jesus-armenian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-persian.conllu Jesus-indonesian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-persian.conllu data/Jesus/Jesus-indonesian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-persian.conllu Jesus-russian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-persian.conllu data/Jesus/Jesus-russian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-persian.conllu Jesus-swedish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-persian.conllu data/Jesus/Jesus-swedish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-galician.conllu Jesus-armenian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-galician.conllu data/Jesus/Jesus-armenian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-galician.conllu Jesus-indonesian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-galician.conllu data/Jesus/Jesus-indonesian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-galician.conllu Jesus-russian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-galician.conllu data/Jesus/Jesus-russian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-galician.conllu Jesus-swedish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-galician.conllu data/Jesus/Jesus-swedish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-armenian.conllu Jesus-indonesian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-armenian.conllu data/Jesus/Jesus-indonesian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-armenian.conllu Jesus-russian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-armenian.conllu data/Jesus/Jesus-russian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-armenian.conllu Jesus-swedish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-armenian.conllu data/Jesus/Jesus-swedish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-indonesian.conllu Jesus-russian.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-indonesian.conllu data/Jesus/Jesus-russian.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-indonesian.conllu Jesus-swedish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-indonesian.conllu data/Jesus/Jesus-swedish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
echo Jesus-russian.conllu Jesus-swedish.conllu >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
gfud cosine-similarity data/Jesus/Jesus-russian.conllu data/Jesus/Jesus-swedish.conllu DEPREL >> cosine-sim-per-topic/Jesus-cosine-sim.txt ; 
} 
topic_combinations