#! /bin/bash 
function topic_combinations { 
echo Julius_Caesar-kazakh.conllu Julius_Caesar-marathi.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-kazakh.conllu data/Julius_Caesar/Julius_Caesar-marathi.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-kazakh.conllu Julius_Caesar-sanskrit.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-kazakh.conllu data/Julius_Caesar/Julius_Caesar-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-kazakh.conllu Julius_Caesar-telugu.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-kazakh.conllu data/Julius_Caesar/Julius_Caesar-telugu.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-kazakh.conllu Julius_Caesar-urdu.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-kazakh.conllu data/Julius_Caesar/Julius_Caesar-urdu.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-kazakh.conllu Julius_Caesar-uyghur.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-kazakh.conllu data/Julius_Caesar/Julius_Caesar-uyghur.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-kazakh.conllu Julius_Caesar-wolof.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-kazakh.conllu data/Julius_Caesar/Julius_Caesar-wolof.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-marathi.conllu Julius_Caesar-sanskrit.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-marathi.conllu data/Julius_Caesar/Julius_Caesar-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-marathi.conllu Julius_Caesar-telugu.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-marathi.conllu data/Julius_Caesar/Julius_Caesar-telugu.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-marathi.conllu Julius_Caesar-urdu.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-marathi.conllu data/Julius_Caesar/Julius_Caesar-urdu.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-marathi.conllu Julius_Caesar-uyghur.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-marathi.conllu data/Julius_Caesar/Julius_Caesar-uyghur.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-marathi.conllu Julius_Caesar-wolof.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-marathi.conllu data/Julius_Caesar/Julius_Caesar-wolof.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-sanskrit.conllu Julius_Caesar-telugu.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-sanskrit.conllu data/Julius_Caesar/Julius_Caesar-telugu.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-sanskrit.conllu Julius_Caesar-urdu.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-sanskrit.conllu data/Julius_Caesar/Julius_Caesar-urdu.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-sanskrit.conllu Julius_Caesar-uyghur.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-sanskrit.conllu data/Julius_Caesar/Julius_Caesar-uyghur.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-sanskrit.conllu Julius_Caesar-wolof.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-sanskrit.conllu data/Julius_Caesar/Julius_Caesar-wolof.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-telugu.conllu Julius_Caesar-urdu.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-telugu.conllu data/Julius_Caesar/Julius_Caesar-urdu.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-telugu.conllu Julius_Caesar-uyghur.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-telugu.conllu data/Julius_Caesar/Julius_Caesar-uyghur.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-telugu.conllu Julius_Caesar-wolof.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-telugu.conllu data/Julius_Caesar/Julius_Caesar-wolof.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-urdu.conllu Julius_Caesar-uyghur.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-urdu.conllu data/Julius_Caesar/Julius_Caesar-uyghur.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-urdu.conllu Julius_Caesar-wolof.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-urdu.conllu data/Julius_Caesar/Julius_Caesar-wolof.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-uyghur.conllu Julius_Caesar-wolof.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-uyghur.conllu data/Julius_Caesar/Julius_Caesar-wolof.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-arabic.conllu Julius_Caesar-welsh.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-arabic.conllu data/Julius_Caesar/Julius_Caesar-welsh.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-arabic.conllu Julius_Caesar-estonian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-arabic.conllu data/Julius_Caesar/Julius_Caesar-estonian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-arabic.conllu Julius_Caesar-scottish_gaelic.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-arabic.conllu data/Julius_Caesar/Julius_Caesar-scottish_gaelic.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-arabic.conllu Julius_Caesar-gothic.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-arabic.conllu data/Julius_Caesar/Julius_Caesar-gothic.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-arabic.conllu Julius_Caesar-hindi.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-arabic.conllu data/Julius_Caesar/Julius_Caesar-hindi.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-arabic.conllu Julius_Caesar-indonesian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-arabic.conllu data/Julius_Caesar/Julius_Caesar-indonesian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-arabic.conllu Julius_Caesar-latvian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-arabic.conllu data/Julius_Caesar/Julius_Caesar-latvian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-arabic.conllu Julius_Caesar-lithuanian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-arabic.conllu data/Julius_Caesar/Julius_Caesar-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-welsh.conllu Julius_Caesar-estonian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-welsh.conllu data/Julius_Caesar/Julius_Caesar-estonian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-welsh.conllu Julius_Caesar-scottish_gaelic.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-welsh.conllu data/Julius_Caesar/Julius_Caesar-scottish_gaelic.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-welsh.conllu Julius_Caesar-gothic.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-welsh.conllu data/Julius_Caesar/Julius_Caesar-gothic.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-welsh.conllu Julius_Caesar-hindi.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-welsh.conllu data/Julius_Caesar/Julius_Caesar-hindi.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-welsh.conllu Julius_Caesar-indonesian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-welsh.conllu data/Julius_Caesar/Julius_Caesar-indonesian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-welsh.conllu Julius_Caesar-latvian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-welsh.conllu data/Julius_Caesar/Julius_Caesar-latvian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-welsh.conllu Julius_Caesar-lithuanian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-welsh.conllu data/Julius_Caesar/Julius_Caesar-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-estonian.conllu Julius_Caesar-scottish_gaelic.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-estonian.conllu data/Julius_Caesar/Julius_Caesar-scottish_gaelic.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-estonian.conllu Julius_Caesar-gothic.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-estonian.conllu data/Julius_Caesar/Julius_Caesar-gothic.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-estonian.conllu Julius_Caesar-hindi.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-estonian.conllu data/Julius_Caesar/Julius_Caesar-hindi.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-estonian.conllu Julius_Caesar-indonesian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-estonian.conllu data/Julius_Caesar/Julius_Caesar-indonesian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-estonian.conllu Julius_Caesar-latvian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-estonian.conllu data/Julius_Caesar/Julius_Caesar-latvian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-estonian.conllu Julius_Caesar-lithuanian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-estonian.conllu data/Julius_Caesar/Julius_Caesar-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-scottish_gaelic.conllu Julius_Caesar-gothic.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-scottish_gaelic.conllu data/Julius_Caesar/Julius_Caesar-gothic.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-scottish_gaelic.conllu Julius_Caesar-hindi.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-scottish_gaelic.conllu data/Julius_Caesar/Julius_Caesar-hindi.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-scottish_gaelic.conllu Julius_Caesar-indonesian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-scottish_gaelic.conllu data/Julius_Caesar/Julius_Caesar-indonesian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-scottish_gaelic.conllu Julius_Caesar-latvian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-scottish_gaelic.conllu data/Julius_Caesar/Julius_Caesar-latvian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-scottish_gaelic.conllu Julius_Caesar-lithuanian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-scottish_gaelic.conllu data/Julius_Caesar/Julius_Caesar-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-gothic.conllu Julius_Caesar-hindi.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-gothic.conllu data/Julius_Caesar/Julius_Caesar-hindi.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-gothic.conllu Julius_Caesar-indonesian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-gothic.conllu data/Julius_Caesar/Julius_Caesar-indonesian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-gothic.conllu Julius_Caesar-latvian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-gothic.conllu data/Julius_Caesar/Julius_Caesar-latvian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-gothic.conllu Julius_Caesar-lithuanian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-gothic.conllu data/Julius_Caesar/Julius_Caesar-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-hindi.conllu Julius_Caesar-indonesian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-hindi.conllu data/Julius_Caesar/Julius_Caesar-indonesian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-hindi.conllu Julius_Caesar-latvian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-hindi.conllu data/Julius_Caesar/Julius_Caesar-latvian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-hindi.conllu Julius_Caesar-lithuanian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-hindi.conllu data/Julius_Caesar/Julius_Caesar-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-indonesian.conllu Julius_Caesar-latvian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-indonesian.conllu data/Julius_Caesar/Julius_Caesar-latvian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-indonesian.conllu Julius_Caesar-lithuanian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-indonesian.conllu data/Julius_Caesar/Julius_Caesar-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-latvian.conllu Julius_Caesar-lithuanian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-latvian.conllu data/Julius_Caesar/Julius_Caesar-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-afrikaans.conllu Julius_Caesar-belarusian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-afrikaans.conllu data/Julius_Caesar/Julius_Caesar-belarusian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-afrikaans.conllu Julius_Caesar-catalan.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-afrikaans.conllu data/Julius_Caesar/Julius_Caesar-catalan.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-afrikaans.conllu Julius_Caesar-danish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-afrikaans.conllu data/Julius_Caesar/Julius_Caesar-danish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-afrikaans.conllu Julius_Caesar-basque.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-afrikaans.conllu data/Julius_Caesar/Julius_Caesar-basque.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-afrikaans.conllu Julius_Caesar-irish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-afrikaans.conllu data/Julius_Caesar/Julius_Caesar-irish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-afrikaans.conllu Julius_Caesar-galician.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-afrikaans.conllu data/Julius_Caesar/Julius_Caesar-galician.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-afrikaans.conllu Julius_Caesar-croatian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-afrikaans.conllu data/Julius_Caesar/Julius_Caesar-croatian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-afrikaans.conllu Julius_Caesar-hebrew.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-afrikaans.conllu data/Julius_Caesar/Julius_Caesar-hebrew.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-afrikaans.conllu Julius_Caesar-latin.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-afrikaans.conllu data/Julius_Caesar/Julius_Caesar-latin.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-afrikaans.conllu Julius_Caesar-japanese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-afrikaans.conllu data/Julius_Caesar/Julius_Caesar-japanese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-afrikaans.conllu Julius_Caesar-serbian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-afrikaans.conllu data/Julius_Caesar/Julius_Caesar-serbian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-afrikaans.conllu Julius_Caesar-swedish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-afrikaans.conllu data/Julius_Caesar/Julius_Caesar-swedish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-afrikaans.conllu Julius_Caesar-tamil.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-afrikaans.conllu data/Julius_Caesar/Julius_Caesar-tamil.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-afrikaans.conllu Julius_Caesar-chinese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-afrikaans.conllu data/Julius_Caesar/Julius_Caesar-chinese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-belarusian.conllu Julius_Caesar-catalan.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-belarusian.conllu data/Julius_Caesar/Julius_Caesar-catalan.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-belarusian.conllu Julius_Caesar-danish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-belarusian.conllu data/Julius_Caesar/Julius_Caesar-danish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-belarusian.conllu Julius_Caesar-basque.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-belarusian.conllu data/Julius_Caesar/Julius_Caesar-basque.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-belarusian.conllu Julius_Caesar-irish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-belarusian.conllu data/Julius_Caesar/Julius_Caesar-irish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-belarusian.conllu Julius_Caesar-galician.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-belarusian.conllu data/Julius_Caesar/Julius_Caesar-galician.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-belarusian.conllu Julius_Caesar-croatian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-belarusian.conllu data/Julius_Caesar/Julius_Caesar-croatian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-belarusian.conllu Julius_Caesar-hebrew.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-belarusian.conllu data/Julius_Caesar/Julius_Caesar-hebrew.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-belarusian.conllu Julius_Caesar-latin.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-belarusian.conllu data/Julius_Caesar/Julius_Caesar-latin.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-belarusian.conllu Julius_Caesar-japanese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-belarusian.conllu data/Julius_Caesar/Julius_Caesar-japanese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-belarusian.conllu Julius_Caesar-serbian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-belarusian.conllu data/Julius_Caesar/Julius_Caesar-serbian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-belarusian.conllu Julius_Caesar-swedish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-belarusian.conllu data/Julius_Caesar/Julius_Caesar-swedish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-belarusian.conllu Julius_Caesar-tamil.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-belarusian.conllu data/Julius_Caesar/Julius_Caesar-tamil.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-belarusian.conllu Julius_Caesar-chinese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-belarusian.conllu data/Julius_Caesar/Julius_Caesar-chinese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-catalan.conllu Julius_Caesar-danish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-catalan.conllu data/Julius_Caesar/Julius_Caesar-danish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-catalan.conllu Julius_Caesar-basque.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-catalan.conllu data/Julius_Caesar/Julius_Caesar-basque.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-catalan.conllu Julius_Caesar-irish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-catalan.conllu data/Julius_Caesar/Julius_Caesar-irish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-catalan.conllu Julius_Caesar-galician.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-catalan.conllu data/Julius_Caesar/Julius_Caesar-galician.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-catalan.conllu Julius_Caesar-croatian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-catalan.conllu data/Julius_Caesar/Julius_Caesar-croatian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-catalan.conllu Julius_Caesar-hebrew.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-catalan.conllu data/Julius_Caesar/Julius_Caesar-hebrew.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-catalan.conllu Julius_Caesar-latin.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-catalan.conllu data/Julius_Caesar/Julius_Caesar-latin.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-catalan.conllu Julius_Caesar-japanese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-catalan.conllu data/Julius_Caesar/Julius_Caesar-japanese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-catalan.conllu Julius_Caesar-serbian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-catalan.conllu data/Julius_Caesar/Julius_Caesar-serbian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-catalan.conllu Julius_Caesar-swedish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-catalan.conllu data/Julius_Caesar/Julius_Caesar-swedish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-catalan.conllu Julius_Caesar-tamil.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-catalan.conllu data/Julius_Caesar/Julius_Caesar-tamil.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-catalan.conllu Julius_Caesar-chinese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-catalan.conllu data/Julius_Caesar/Julius_Caesar-chinese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-danish.conllu Julius_Caesar-basque.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-danish.conllu data/Julius_Caesar/Julius_Caesar-basque.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-danish.conllu Julius_Caesar-irish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-danish.conllu data/Julius_Caesar/Julius_Caesar-irish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-danish.conllu Julius_Caesar-galician.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-danish.conllu data/Julius_Caesar/Julius_Caesar-galician.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-danish.conllu Julius_Caesar-croatian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-danish.conllu data/Julius_Caesar/Julius_Caesar-croatian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-danish.conllu Julius_Caesar-hebrew.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-danish.conllu data/Julius_Caesar/Julius_Caesar-hebrew.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-danish.conllu Julius_Caesar-latin.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-danish.conllu data/Julius_Caesar/Julius_Caesar-latin.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-danish.conllu Julius_Caesar-japanese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-danish.conllu data/Julius_Caesar/Julius_Caesar-japanese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-danish.conllu Julius_Caesar-serbian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-danish.conllu data/Julius_Caesar/Julius_Caesar-serbian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-danish.conllu Julius_Caesar-swedish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-danish.conllu data/Julius_Caesar/Julius_Caesar-swedish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-danish.conllu Julius_Caesar-tamil.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-danish.conllu data/Julius_Caesar/Julius_Caesar-tamil.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-danish.conllu Julius_Caesar-chinese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-danish.conllu data/Julius_Caesar/Julius_Caesar-chinese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-basque.conllu Julius_Caesar-irish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-basque.conllu data/Julius_Caesar/Julius_Caesar-irish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-basque.conllu Julius_Caesar-galician.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-basque.conllu data/Julius_Caesar/Julius_Caesar-galician.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-basque.conllu Julius_Caesar-croatian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-basque.conllu data/Julius_Caesar/Julius_Caesar-croatian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-basque.conllu Julius_Caesar-hebrew.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-basque.conllu data/Julius_Caesar/Julius_Caesar-hebrew.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-basque.conllu Julius_Caesar-latin.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-basque.conllu data/Julius_Caesar/Julius_Caesar-latin.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-basque.conllu Julius_Caesar-japanese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-basque.conllu data/Julius_Caesar/Julius_Caesar-japanese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-basque.conllu Julius_Caesar-serbian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-basque.conllu data/Julius_Caesar/Julius_Caesar-serbian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-basque.conllu Julius_Caesar-swedish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-basque.conllu data/Julius_Caesar/Julius_Caesar-swedish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-basque.conllu Julius_Caesar-tamil.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-basque.conllu data/Julius_Caesar/Julius_Caesar-tamil.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-basque.conllu Julius_Caesar-chinese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-basque.conllu data/Julius_Caesar/Julius_Caesar-chinese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-irish.conllu Julius_Caesar-galician.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-irish.conllu data/Julius_Caesar/Julius_Caesar-galician.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-irish.conllu Julius_Caesar-croatian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-irish.conllu data/Julius_Caesar/Julius_Caesar-croatian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-irish.conllu Julius_Caesar-hebrew.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-irish.conllu data/Julius_Caesar/Julius_Caesar-hebrew.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-irish.conllu Julius_Caesar-latin.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-irish.conllu data/Julius_Caesar/Julius_Caesar-latin.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-irish.conllu Julius_Caesar-japanese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-irish.conllu data/Julius_Caesar/Julius_Caesar-japanese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-irish.conllu Julius_Caesar-serbian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-irish.conllu data/Julius_Caesar/Julius_Caesar-serbian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-irish.conllu Julius_Caesar-swedish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-irish.conllu data/Julius_Caesar/Julius_Caesar-swedish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-irish.conllu Julius_Caesar-tamil.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-irish.conllu data/Julius_Caesar/Julius_Caesar-tamil.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-irish.conllu Julius_Caesar-chinese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-irish.conllu data/Julius_Caesar/Julius_Caesar-chinese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-galician.conllu Julius_Caesar-croatian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-galician.conllu data/Julius_Caesar/Julius_Caesar-croatian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-galician.conllu Julius_Caesar-hebrew.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-galician.conllu data/Julius_Caesar/Julius_Caesar-hebrew.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-galician.conllu Julius_Caesar-latin.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-galician.conllu data/Julius_Caesar/Julius_Caesar-latin.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-galician.conllu Julius_Caesar-japanese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-galician.conllu data/Julius_Caesar/Julius_Caesar-japanese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-galician.conllu Julius_Caesar-serbian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-galician.conllu data/Julius_Caesar/Julius_Caesar-serbian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-galician.conllu Julius_Caesar-swedish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-galician.conllu data/Julius_Caesar/Julius_Caesar-swedish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-galician.conllu Julius_Caesar-tamil.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-galician.conllu data/Julius_Caesar/Julius_Caesar-tamil.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-galician.conllu Julius_Caesar-chinese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-galician.conllu data/Julius_Caesar/Julius_Caesar-chinese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-croatian.conllu Julius_Caesar-hebrew.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-croatian.conllu data/Julius_Caesar/Julius_Caesar-hebrew.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-croatian.conllu Julius_Caesar-latin.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-croatian.conllu data/Julius_Caesar/Julius_Caesar-latin.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-croatian.conllu Julius_Caesar-japanese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-croatian.conllu data/Julius_Caesar/Julius_Caesar-japanese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-croatian.conllu Julius_Caesar-serbian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-croatian.conllu data/Julius_Caesar/Julius_Caesar-serbian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-croatian.conllu Julius_Caesar-swedish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-croatian.conllu data/Julius_Caesar/Julius_Caesar-swedish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-croatian.conllu Julius_Caesar-tamil.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-croatian.conllu data/Julius_Caesar/Julius_Caesar-tamil.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-croatian.conllu Julius_Caesar-chinese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-croatian.conllu data/Julius_Caesar/Julius_Caesar-chinese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-hebrew.conllu Julius_Caesar-latin.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-hebrew.conllu data/Julius_Caesar/Julius_Caesar-latin.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-hebrew.conllu Julius_Caesar-japanese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-hebrew.conllu data/Julius_Caesar/Julius_Caesar-japanese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-hebrew.conllu Julius_Caesar-serbian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-hebrew.conllu data/Julius_Caesar/Julius_Caesar-serbian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-hebrew.conllu Julius_Caesar-swedish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-hebrew.conllu data/Julius_Caesar/Julius_Caesar-swedish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-hebrew.conllu Julius_Caesar-tamil.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-hebrew.conllu data/Julius_Caesar/Julius_Caesar-tamil.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-hebrew.conllu Julius_Caesar-chinese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-hebrew.conllu data/Julius_Caesar/Julius_Caesar-chinese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-latin.conllu Julius_Caesar-japanese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-latin.conllu data/Julius_Caesar/Julius_Caesar-japanese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-latin.conllu Julius_Caesar-serbian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-latin.conllu data/Julius_Caesar/Julius_Caesar-serbian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-latin.conllu Julius_Caesar-swedish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-latin.conllu data/Julius_Caesar/Julius_Caesar-swedish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-latin.conllu Julius_Caesar-tamil.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-latin.conllu data/Julius_Caesar/Julius_Caesar-tamil.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-latin.conllu Julius_Caesar-chinese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-latin.conllu data/Julius_Caesar/Julius_Caesar-chinese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-japanese.conllu Julius_Caesar-serbian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-japanese.conllu data/Julius_Caesar/Julius_Caesar-serbian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-japanese.conllu Julius_Caesar-swedish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-japanese.conllu data/Julius_Caesar/Julius_Caesar-swedish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-japanese.conllu Julius_Caesar-tamil.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-japanese.conllu data/Julius_Caesar/Julius_Caesar-tamil.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-japanese.conllu Julius_Caesar-chinese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-japanese.conllu data/Julius_Caesar/Julius_Caesar-chinese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-serbian.conllu Julius_Caesar-swedish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-serbian.conllu data/Julius_Caesar/Julius_Caesar-swedish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-serbian.conllu Julius_Caesar-tamil.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-serbian.conllu data/Julius_Caesar/Julius_Caesar-tamil.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-serbian.conllu Julius_Caesar-chinese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-serbian.conllu data/Julius_Caesar/Julius_Caesar-chinese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-swedish.conllu Julius_Caesar-tamil.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-swedish.conllu data/Julius_Caesar/Julius_Caesar-tamil.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-swedish.conllu Julius_Caesar-chinese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-swedish.conllu data/Julius_Caesar/Julius_Caesar-chinese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-tamil.conllu Julius_Caesar-chinese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-tamil.conllu data/Julius_Caesar/Julius_Caesar-chinese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-english.conllu Julius_Caesar-bulgarian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-english.conllu data/Julius_Caesar/Julius_Caesar-bulgarian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-english.conllu Julius_Caesar-czech.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-english.conllu data/Julius_Caesar/Julius_Caesar-czech.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-english.conllu Julius_Caesar-german.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-english.conllu data/Julius_Caesar/Julius_Caesar-german.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-english.conllu Julius_Caesar-greek.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-english.conllu data/Julius_Caesar/Julius_Caesar-greek.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-english.conllu Julius_Caesar-persian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-english.conllu data/Julius_Caesar/Julius_Caesar-persian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-english.conllu Julius_Caesar-hungarian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-english.conllu data/Julius_Caesar/Julius_Caesar-hungarian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-english.conllu Julius_Caesar-dutch.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-english.conllu data/Julius_Caesar/Julius_Caesar-dutch.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-english.conllu Julius_Caesar-polish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-english.conllu data/Julius_Caesar/Julius_Caesar-polish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-english.conllu Julius_Caesar-portuguese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-english.conllu data/Julius_Caesar/Julius_Caesar-portuguese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-english.conllu Julius_Caesar-romanian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-english.conllu data/Julius_Caesar/Julius_Caesar-romanian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-english.conllu Julius_Caesar-slovak.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-english.conllu data/Julius_Caesar/Julius_Caesar-slovak.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-english.conllu Julius_Caesar-slovenian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-english.conllu data/Julius_Caesar/Julius_Caesar-slovenian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-english.conllu Julius_Caesar-finnish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-english.conllu data/Julius_Caesar/Julius_Caesar-finnish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-english.conllu Julius_Caesar-turkish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-english.conllu data/Julius_Caesar/Julius_Caesar-turkish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-english.conllu Julius_Caesar-ukrainian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-english.conllu data/Julius_Caesar/Julius_Caesar-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-english.conllu Julius_Caesar-vietnamese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-english.conllu data/Julius_Caesar/Julius_Caesar-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-bulgarian.conllu Julius_Caesar-czech.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-bulgarian.conllu data/Julius_Caesar/Julius_Caesar-czech.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-bulgarian.conllu Julius_Caesar-german.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-bulgarian.conllu data/Julius_Caesar/Julius_Caesar-german.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-bulgarian.conllu Julius_Caesar-greek.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-bulgarian.conllu data/Julius_Caesar/Julius_Caesar-greek.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-bulgarian.conllu Julius_Caesar-persian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-bulgarian.conllu data/Julius_Caesar/Julius_Caesar-persian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-bulgarian.conllu Julius_Caesar-hungarian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-bulgarian.conllu data/Julius_Caesar/Julius_Caesar-hungarian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-bulgarian.conllu Julius_Caesar-dutch.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-bulgarian.conllu data/Julius_Caesar/Julius_Caesar-dutch.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-bulgarian.conllu Julius_Caesar-polish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-bulgarian.conllu data/Julius_Caesar/Julius_Caesar-polish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-bulgarian.conllu Julius_Caesar-portuguese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-bulgarian.conllu data/Julius_Caesar/Julius_Caesar-portuguese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-bulgarian.conllu Julius_Caesar-romanian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-bulgarian.conllu data/Julius_Caesar/Julius_Caesar-romanian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-bulgarian.conllu Julius_Caesar-slovak.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-bulgarian.conllu data/Julius_Caesar/Julius_Caesar-slovak.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-bulgarian.conllu Julius_Caesar-slovenian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-bulgarian.conllu data/Julius_Caesar/Julius_Caesar-slovenian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-bulgarian.conllu Julius_Caesar-finnish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-bulgarian.conllu data/Julius_Caesar/Julius_Caesar-finnish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-bulgarian.conllu Julius_Caesar-turkish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-bulgarian.conllu data/Julius_Caesar/Julius_Caesar-turkish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-bulgarian.conllu Julius_Caesar-ukrainian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-bulgarian.conllu data/Julius_Caesar/Julius_Caesar-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-bulgarian.conllu Julius_Caesar-vietnamese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-bulgarian.conllu data/Julius_Caesar/Julius_Caesar-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-czech.conllu Julius_Caesar-german.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-czech.conllu data/Julius_Caesar/Julius_Caesar-german.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-czech.conllu Julius_Caesar-greek.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-czech.conllu data/Julius_Caesar/Julius_Caesar-greek.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-czech.conllu Julius_Caesar-persian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-czech.conllu data/Julius_Caesar/Julius_Caesar-persian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-czech.conllu Julius_Caesar-hungarian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-czech.conllu data/Julius_Caesar/Julius_Caesar-hungarian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-czech.conllu Julius_Caesar-dutch.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-czech.conllu data/Julius_Caesar/Julius_Caesar-dutch.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-czech.conllu Julius_Caesar-polish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-czech.conllu data/Julius_Caesar/Julius_Caesar-polish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-czech.conllu Julius_Caesar-portuguese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-czech.conllu data/Julius_Caesar/Julius_Caesar-portuguese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-czech.conllu Julius_Caesar-romanian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-czech.conllu data/Julius_Caesar/Julius_Caesar-romanian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-czech.conllu Julius_Caesar-slovak.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-czech.conllu data/Julius_Caesar/Julius_Caesar-slovak.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-czech.conllu Julius_Caesar-slovenian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-czech.conllu data/Julius_Caesar/Julius_Caesar-slovenian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-czech.conllu Julius_Caesar-finnish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-czech.conllu data/Julius_Caesar/Julius_Caesar-finnish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-czech.conllu Julius_Caesar-turkish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-czech.conllu data/Julius_Caesar/Julius_Caesar-turkish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-czech.conllu Julius_Caesar-ukrainian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-czech.conllu data/Julius_Caesar/Julius_Caesar-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-czech.conllu Julius_Caesar-vietnamese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-czech.conllu data/Julius_Caesar/Julius_Caesar-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-german.conllu Julius_Caesar-greek.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-german.conllu data/Julius_Caesar/Julius_Caesar-greek.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-german.conllu Julius_Caesar-persian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-german.conllu data/Julius_Caesar/Julius_Caesar-persian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-german.conllu Julius_Caesar-hungarian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-german.conllu data/Julius_Caesar/Julius_Caesar-hungarian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-german.conllu Julius_Caesar-dutch.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-german.conllu data/Julius_Caesar/Julius_Caesar-dutch.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-german.conllu Julius_Caesar-polish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-german.conllu data/Julius_Caesar/Julius_Caesar-polish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-german.conllu Julius_Caesar-portuguese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-german.conllu data/Julius_Caesar/Julius_Caesar-portuguese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-german.conllu Julius_Caesar-romanian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-german.conllu data/Julius_Caesar/Julius_Caesar-romanian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-german.conllu Julius_Caesar-slovak.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-german.conllu data/Julius_Caesar/Julius_Caesar-slovak.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-german.conllu Julius_Caesar-slovenian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-german.conllu data/Julius_Caesar/Julius_Caesar-slovenian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-german.conllu Julius_Caesar-finnish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-german.conllu data/Julius_Caesar/Julius_Caesar-finnish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-german.conllu Julius_Caesar-turkish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-german.conllu data/Julius_Caesar/Julius_Caesar-turkish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-german.conllu Julius_Caesar-ukrainian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-german.conllu data/Julius_Caesar/Julius_Caesar-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-german.conllu Julius_Caesar-vietnamese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-german.conllu data/Julius_Caesar/Julius_Caesar-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-greek.conllu Julius_Caesar-persian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-greek.conllu data/Julius_Caesar/Julius_Caesar-persian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-greek.conllu Julius_Caesar-hungarian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-greek.conllu data/Julius_Caesar/Julius_Caesar-hungarian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-greek.conllu Julius_Caesar-dutch.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-greek.conllu data/Julius_Caesar/Julius_Caesar-dutch.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-greek.conllu Julius_Caesar-polish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-greek.conllu data/Julius_Caesar/Julius_Caesar-polish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-greek.conllu Julius_Caesar-portuguese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-greek.conllu data/Julius_Caesar/Julius_Caesar-portuguese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-greek.conllu Julius_Caesar-romanian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-greek.conllu data/Julius_Caesar/Julius_Caesar-romanian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-greek.conllu Julius_Caesar-slovak.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-greek.conllu data/Julius_Caesar/Julius_Caesar-slovak.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-greek.conllu Julius_Caesar-slovenian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-greek.conllu data/Julius_Caesar/Julius_Caesar-slovenian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-greek.conllu Julius_Caesar-finnish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-greek.conllu data/Julius_Caesar/Julius_Caesar-finnish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-greek.conllu Julius_Caesar-turkish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-greek.conllu data/Julius_Caesar/Julius_Caesar-turkish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-greek.conllu Julius_Caesar-ukrainian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-greek.conllu data/Julius_Caesar/Julius_Caesar-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-greek.conllu Julius_Caesar-vietnamese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-greek.conllu data/Julius_Caesar/Julius_Caesar-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-persian.conllu Julius_Caesar-hungarian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-persian.conllu data/Julius_Caesar/Julius_Caesar-hungarian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-persian.conllu Julius_Caesar-dutch.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-persian.conllu data/Julius_Caesar/Julius_Caesar-dutch.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-persian.conllu Julius_Caesar-polish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-persian.conllu data/Julius_Caesar/Julius_Caesar-polish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-persian.conllu Julius_Caesar-portuguese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-persian.conllu data/Julius_Caesar/Julius_Caesar-portuguese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-persian.conllu Julius_Caesar-romanian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-persian.conllu data/Julius_Caesar/Julius_Caesar-romanian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-persian.conllu Julius_Caesar-slovak.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-persian.conllu data/Julius_Caesar/Julius_Caesar-slovak.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-persian.conllu Julius_Caesar-slovenian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-persian.conllu data/Julius_Caesar/Julius_Caesar-slovenian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-persian.conllu Julius_Caesar-finnish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-persian.conllu data/Julius_Caesar/Julius_Caesar-finnish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-persian.conllu Julius_Caesar-turkish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-persian.conllu data/Julius_Caesar/Julius_Caesar-turkish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-persian.conllu Julius_Caesar-ukrainian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-persian.conllu data/Julius_Caesar/Julius_Caesar-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-persian.conllu Julius_Caesar-vietnamese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-persian.conllu data/Julius_Caesar/Julius_Caesar-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-hungarian.conllu Julius_Caesar-dutch.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-hungarian.conllu data/Julius_Caesar/Julius_Caesar-dutch.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-hungarian.conllu Julius_Caesar-polish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-hungarian.conllu data/Julius_Caesar/Julius_Caesar-polish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-hungarian.conllu Julius_Caesar-portuguese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-hungarian.conllu data/Julius_Caesar/Julius_Caesar-portuguese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-hungarian.conllu Julius_Caesar-romanian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-hungarian.conllu data/Julius_Caesar/Julius_Caesar-romanian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-hungarian.conllu Julius_Caesar-slovak.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-hungarian.conllu data/Julius_Caesar/Julius_Caesar-slovak.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-hungarian.conllu Julius_Caesar-slovenian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-hungarian.conllu data/Julius_Caesar/Julius_Caesar-slovenian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-hungarian.conllu Julius_Caesar-finnish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-hungarian.conllu data/Julius_Caesar/Julius_Caesar-finnish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-hungarian.conllu Julius_Caesar-turkish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-hungarian.conllu data/Julius_Caesar/Julius_Caesar-turkish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-hungarian.conllu Julius_Caesar-ukrainian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-hungarian.conllu data/Julius_Caesar/Julius_Caesar-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-hungarian.conllu Julius_Caesar-vietnamese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-hungarian.conllu data/Julius_Caesar/Julius_Caesar-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-dutch.conllu Julius_Caesar-polish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-dutch.conllu data/Julius_Caesar/Julius_Caesar-polish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-dutch.conllu Julius_Caesar-portuguese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-dutch.conllu data/Julius_Caesar/Julius_Caesar-portuguese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-dutch.conllu Julius_Caesar-romanian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-dutch.conllu data/Julius_Caesar/Julius_Caesar-romanian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-dutch.conllu Julius_Caesar-slovak.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-dutch.conllu data/Julius_Caesar/Julius_Caesar-slovak.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-dutch.conllu Julius_Caesar-slovenian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-dutch.conllu data/Julius_Caesar/Julius_Caesar-slovenian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-dutch.conllu Julius_Caesar-finnish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-dutch.conllu data/Julius_Caesar/Julius_Caesar-finnish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-dutch.conllu Julius_Caesar-turkish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-dutch.conllu data/Julius_Caesar/Julius_Caesar-turkish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-dutch.conllu Julius_Caesar-ukrainian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-dutch.conllu data/Julius_Caesar/Julius_Caesar-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-dutch.conllu Julius_Caesar-vietnamese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-dutch.conllu data/Julius_Caesar/Julius_Caesar-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-polish.conllu Julius_Caesar-portuguese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-polish.conllu data/Julius_Caesar/Julius_Caesar-portuguese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-polish.conllu Julius_Caesar-romanian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-polish.conllu data/Julius_Caesar/Julius_Caesar-romanian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-polish.conllu Julius_Caesar-slovak.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-polish.conllu data/Julius_Caesar/Julius_Caesar-slovak.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-polish.conllu Julius_Caesar-slovenian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-polish.conllu data/Julius_Caesar/Julius_Caesar-slovenian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-polish.conllu Julius_Caesar-finnish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-polish.conllu data/Julius_Caesar/Julius_Caesar-finnish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-polish.conllu Julius_Caesar-turkish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-polish.conllu data/Julius_Caesar/Julius_Caesar-turkish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-polish.conllu Julius_Caesar-ukrainian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-polish.conllu data/Julius_Caesar/Julius_Caesar-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-polish.conllu Julius_Caesar-vietnamese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-polish.conllu data/Julius_Caesar/Julius_Caesar-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-portuguese.conllu Julius_Caesar-romanian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-portuguese.conllu data/Julius_Caesar/Julius_Caesar-romanian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-portuguese.conllu Julius_Caesar-slovak.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-portuguese.conllu data/Julius_Caesar/Julius_Caesar-slovak.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-portuguese.conllu Julius_Caesar-slovenian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-portuguese.conllu data/Julius_Caesar/Julius_Caesar-slovenian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-portuguese.conllu Julius_Caesar-finnish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-portuguese.conllu data/Julius_Caesar/Julius_Caesar-finnish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-portuguese.conllu Julius_Caesar-turkish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-portuguese.conllu data/Julius_Caesar/Julius_Caesar-turkish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-portuguese.conllu Julius_Caesar-ukrainian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-portuguese.conllu data/Julius_Caesar/Julius_Caesar-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-portuguese.conllu Julius_Caesar-vietnamese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-portuguese.conllu data/Julius_Caesar/Julius_Caesar-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-romanian.conllu Julius_Caesar-slovak.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-romanian.conllu data/Julius_Caesar/Julius_Caesar-slovak.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-romanian.conllu Julius_Caesar-slovenian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-romanian.conllu data/Julius_Caesar/Julius_Caesar-slovenian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-romanian.conllu Julius_Caesar-finnish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-romanian.conllu data/Julius_Caesar/Julius_Caesar-finnish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-romanian.conllu Julius_Caesar-turkish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-romanian.conllu data/Julius_Caesar/Julius_Caesar-turkish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-romanian.conllu Julius_Caesar-ukrainian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-romanian.conllu data/Julius_Caesar/Julius_Caesar-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-romanian.conllu Julius_Caesar-vietnamese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-romanian.conllu data/Julius_Caesar/Julius_Caesar-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-slovak.conllu Julius_Caesar-slovenian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-slovak.conllu data/Julius_Caesar/Julius_Caesar-slovenian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-slovak.conllu Julius_Caesar-finnish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-slovak.conllu data/Julius_Caesar/Julius_Caesar-finnish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-slovak.conllu Julius_Caesar-turkish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-slovak.conllu data/Julius_Caesar/Julius_Caesar-turkish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-slovak.conllu Julius_Caesar-ukrainian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-slovak.conllu data/Julius_Caesar/Julius_Caesar-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-slovak.conllu Julius_Caesar-vietnamese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-slovak.conllu data/Julius_Caesar/Julius_Caesar-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-slovenian.conllu Julius_Caesar-finnish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-slovenian.conllu data/Julius_Caesar/Julius_Caesar-finnish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-slovenian.conllu Julius_Caesar-turkish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-slovenian.conllu data/Julius_Caesar/Julius_Caesar-turkish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-slovenian.conllu Julius_Caesar-ukrainian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-slovenian.conllu data/Julius_Caesar/Julius_Caesar-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-slovenian.conllu Julius_Caesar-vietnamese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-slovenian.conllu data/Julius_Caesar/Julius_Caesar-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-finnish.conllu Julius_Caesar-turkish.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-finnish.conllu data/Julius_Caesar/Julius_Caesar-turkish.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-finnish.conllu Julius_Caesar-ukrainian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-finnish.conllu data/Julius_Caesar/Julius_Caesar-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-finnish.conllu Julius_Caesar-vietnamese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-finnish.conllu data/Julius_Caesar/Julius_Caesar-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-turkish.conllu Julius_Caesar-ukrainian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-turkish.conllu data/Julius_Caesar/Julius_Caesar-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-turkish.conllu Julius_Caesar-vietnamese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-turkish.conllu data/Julius_Caesar/Julius_Caesar-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-ukrainian.conllu Julius_Caesar-vietnamese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-ukrainian.conllu data/Julius_Caesar/Julius_Caesar-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-spanish.conllu Julius_Caesar-french.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-spanish.conllu data/Julius_Caesar/Julius_Caesar-french.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-spanish.conllu Julius_Caesar-korean.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-spanish.conllu data/Julius_Caesar/Julius_Caesar-korean.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-spanish.conllu Julius_Caesar-armenian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-spanish.conllu data/Julius_Caesar/Julius_Caesar-armenian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-spanish.conllu Julius_Caesar-italian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-spanish.conllu data/Julius_Caesar/Julius_Caesar-italian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-spanish.conllu Julius_Caesar-russian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-spanish.conllu data/Julius_Caesar/Julius_Caesar-russian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-spanish.conllu Julius_Caesar-classical_chinese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-spanish.conllu data/Julius_Caesar/Julius_Caesar-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-french.conllu Julius_Caesar-korean.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-french.conllu data/Julius_Caesar/Julius_Caesar-korean.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-french.conllu Julius_Caesar-armenian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-french.conllu data/Julius_Caesar/Julius_Caesar-armenian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-french.conllu Julius_Caesar-italian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-french.conllu data/Julius_Caesar/Julius_Caesar-italian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-french.conllu Julius_Caesar-russian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-french.conllu data/Julius_Caesar/Julius_Caesar-russian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-french.conllu Julius_Caesar-classical_chinese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-french.conllu data/Julius_Caesar/Julius_Caesar-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-korean.conllu Julius_Caesar-armenian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-korean.conllu data/Julius_Caesar/Julius_Caesar-armenian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-korean.conllu Julius_Caesar-italian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-korean.conllu data/Julius_Caesar/Julius_Caesar-italian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-korean.conllu Julius_Caesar-russian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-korean.conllu data/Julius_Caesar/Julius_Caesar-russian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-korean.conllu Julius_Caesar-classical_chinese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-korean.conllu data/Julius_Caesar/Julius_Caesar-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-armenian.conllu Julius_Caesar-italian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-armenian.conllu data/Julius_Caesar/Julius_Caesar-italian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-armenian.conllu Julius_Caesar-russian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-armenian.conllu data/Julius_Caesar/Julius_Caesar-russian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-armenian.conllu Julius_Caesar-classical_chinese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-armenian.conllu data/Julius_Caesar/Julius_Caesar-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-italian.conllu Julius_Caesar-russian.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-italian.conllu data/Julius_Caesar/Julius_Caesar-russian.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-italian.conllu Julius_Caesar-classical_chinese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-italian.conllu data/Julius_Caesar/Julius_Caesar-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
echo Julius_Caesar-russian.conllu Julius_Caesar-classical_chinese.conllu >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
gfud cosine-similarity data/Julius_Caesar/Julius_Caesar-russian.conllu data/Julius_Caesar/Julius_Caesar-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Julius_Caesar-cosine-sim.txt ; 
} 
topic_combinations