#! /bin/bash 
function topic_combinations { 
echo Koran-belarusian.conllu Koran-latin.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-belarusian.conllu data/Koran/Koran-latin.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-belarusian.conllu Koran-slovenian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-belarusian.conllu data/Koran/Koran-slovenian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-belarusian.conllu Koran-wolof.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-belarusian.conllu data/Koran/Koran-wolof.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-latin.conllu Koran-slovenian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-latin.conllu data/Koran/Koran-slovenian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-latin.conllu Koran-wolof.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-latin.conllu data/Koran/Koran-wolof.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-slovenian.conllu Koran-wolof.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-slovenian.conllu data/Koran/Koran-wolof.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-afrikaans.conllu Koran-bulgarian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-afrikaans.conllu data/Koran/Koran-bulgarian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-afrikaans.conllu Koran-welsh.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-afrikaans.conllu data/Koran/Koran-welsh.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-afrikaans.conllu Koran-danish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-afrikaans.conllu data/Koran/Koran-danish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-afrikaans.conllu Koran-estonian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-afrikaans.conllu data/Koran/Koran-estonian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-afrikaans.conllu Koran-basque.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-afrikaans.conllu data/Koran/Koran-basque.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-afrikaans.conllu Koran-korean.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-afrikaans.conllu data/Koran/Koran-korean.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-afrikaans.conllu Koran-lithuanian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-afrikaans.conllu data/Koran/Koran-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-afrikaans.conllu Koran-hungarian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-afrikaans.conllu data/Koran/Koran-hungarian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-afrikaans.conllu Koran-maltese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-afrikaans.conllu data/Koran/Koran-maltese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-afrikaans.conllu Koran-marathi.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-afrikaans.conllu data/Koran/Koran-marathi.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-afrikaans.conllu Koran-romanian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-afrikaans.conllu data/Koran/Koran-romanian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-afrikaans.conllu Koran-sanskrit.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-afrikaans.conllu data/Koran/Koran-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-afrikaans.conllu Koran-slovak.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-afrikaans.conllu data/Koran/Koran-slovak.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-afrikaans.conllu Koran-serbian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-afrikaans.conllu data/Koran/Koran-serbian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-afrikaans.conllu Koran-vietnamese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-afrikaans.conllu data/Koran/Koran-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-bulgarian.conllu Koran-welsh.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-bulgarian.conllu data/Koran/Koran-welsh.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-bulgarian.conllu Koran-danish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-bulgarian.conllu data/Koran/Koran-danish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-bulgarian.conllu Koran-estonian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-bulgarian.conllu data/Koran/Koran-estonian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-bulgarian.conllu Koran-basque.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-bulgarian.conllu data/Koran/Koran-basque.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-bulgarian.conllu Koran-korean.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-bulgarian.conllu data/Koran/Koran-korean.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-bulgarian.conllu Koran-lithuanian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-bulgarian.conllu data/Koran/Koran-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-bulgarian.conllu Koran-hungarian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-bulgarian.conllu data/Koran/Koran-hungarian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-bulgarian.conllu Koran-maltese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-bulgarian.conllu data/Koran/Koran-maltese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-bulgarian.conllu Koran-marathi.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-bulgarian.conllu data/Koran/Koran-marathi.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-bulgarian.conllu Koran-romanian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-bulgarian.conllu data/Koran/Koran-romanian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-bulgarian.conllu Koran-sanskrit.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-bulgarian.conllu data/Koran/Koran-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-bulgarian.conllu Koran-slovak.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-bulgarian.conllu data/Koran/Koran-slovak.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-bulgarian.conllu Koran-serbian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-bulgarian.conllu data/Koran/Koran-serbian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-bulgarian.conllu Koran-vietnamese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-bulgarian.conllu data/Koran/Koran-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-welsh.conllu Koran-danish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-welsh.conllu data/Koran/Koran-danish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-welsh.conllu Koran-estonian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-welsh.conllu data/Koran/Koran-estonian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-welsh.conllu Koran-basque.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-welsh.conllu data/Koran/Koran-basque.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-welsh.conllu Koran-korean.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-welsh.conllu data/Koran/Koran-korean.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-welsh.conllu Koran-lithuanian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-welsh.conllu data/Koran/Koran-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-welsh.conllu Koran-hungarian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-welsh.conllu data/Koran/Koran-hungarian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-welsh.conllu Koran-maltese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-welsh.conllu data/Koran/Koran-maltese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-welsh.conllu Koran-marathi.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-welsh.conllu data/Koran/Koran-marathi.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-welsh.conllu Koran-romanian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-welsh.conllu data/Koran/Koran-romanian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-welsh.conllu Koran-sanskrit.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-welsh.conllu data/Koran/Koran-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-welsh.conllu Koran-slovak.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-welsh.conllu data/Koran/Koran-slovak.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-welsh.conllu Koran-serbian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-welsh.conllu data/Koran/Koran-serbian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-welsh.conllu Koran-vietnamese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-welsh.conllu data/Koran/Koran-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-danish.conllu Koran-estonian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-danish.conllu data/Koran/Koran-estonian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-danish.conllu Koran-basque.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-danish.conllu data/Koran/Koran-basque.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-danish.conllu Koran-korean.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-danish.conllu data/Koran/Koran-korean.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-danish.conllu Koran-lithuanian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-danish.conllu data/Koran/Koran-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-danish.conllu Koran-hungarian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-danish.conllu data/Koran/Koran-hungarian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-danish.conllu Koran-maltese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-danish.conllu data/Koran/Koran-maltese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-danish.conllu Koran-marathi.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-danish.conllu data/Koran/Koran-marathi.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-danish.conllu Koran-romanian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-danish.conllu data/Koran/Koran-romanian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-danish.conllu Koran-sanskrit.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-danish.conllu data/Koran/Koran-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-danish.conllu Koran-slovak.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-danish.conllu data/Koran/Koran-slovak.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-danish.conllu Koran-serbian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-danish.conllu data/Koran/Koran-serbian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-danish.conllu Koran-vietnamese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-danish.conllu data/Koran/Koran-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-estonian.conllu Koran-basque.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-estonian.conllu data/Koran/Koran-basque.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-estonian.conllu Koran-korean.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-estonian.conllu data/Koran/Koran-korean.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-estonian.conllu Koran-lithuanian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-estonian.conllu data/Koran/Koran-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-estonian.conllu Koran-hungarian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-estonian.conllu data/Koran/Koran-hungarian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-estonian.conllu Koran-maltese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-estonian.conllu data/Koran/Koran-maltese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-estonian.conllu Koran-marathi.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-estonian.conllu data/Koran/Koran-marathi.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-estonian.conllu Koran-romanian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-estonian.conllu data/Koran/Koran-romanian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-estonian.conllu Koran-sanskrit.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-estonian.conllu data/Koran/Koran-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-estonian.conllu Koran-slovak.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-estonian.conllu data/Koran/Koran-slovak.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-estonian.conllu Koran-serbian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-estonian.conllu data/Koran/Koran-serbian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-estonian.conllu Koran-vietnamese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-estonian.conllu data/Koran/Koran-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-basque.conllu Koran-korean.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-basque.conllu data/Koran/Koran-korean.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-basque.conllu Koran-lithuanian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-basque.conllu data/Koran/Koran-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-basque.conllu Koran-hungarian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-basque.conllu data/Koran/Koran-hungarian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-basque.conllu Koran-maltese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-basque.conllu data/Koran/Koran-maltese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-basque.conllu Koran-marathi.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-basque.conllu data/Koran/Koran-marathi.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-basque.conllu Koran-romanian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-basque.conllu data/Koran/Koran-romanian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-basque.conllu Koran-sanskrit.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-basque.conllu data/Koran/Koran-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-basque.conllu Koran-slovak.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-basque.conllu data/Koran/Koran-slovak.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-basque.conllu Koran-serbian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-basque.conllu data/Koran/Koran-serbian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-basque.conllu Koran-vietnamese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-basque.conllu data/Koran/Koran-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-korean.conllu Koran-lithuanian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-korean.conllu data/Koran/Koran-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-korean.conllu Koran-hungarian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-korean.conllu data/Koran/Koran-hungarian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-korean.conllu Koran-maltese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-korean.conllu data/Koran/Koran-maltese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-korean.conllu Koran-marathi.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-korean.conllu data/Koran/Koran-marathi.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-korean.conllu Koran-romanian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-korean.conllu data/Koran/Koran-romanian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-korean.conllu Koran-sanskrit.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-korean.conllu data/Koran/Koran-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-korean.conllu Koran-slovak.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-korean.conllu data/Koran/Koran-slovak.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-korean.conllu Koran-serbian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-korean.conllu data/Koran/Koran-serbian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-korean.conllu Koran-vietnamese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-korean.conllu data/Koran/Koran-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-lithuanian.conllu Koran-hungarian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-lithuanian.conllu data/Koran/Koran-hungarian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-lithuanian.conllu Koran-maltese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-lithuanian.conllu data/Koran/Koran-maltese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-lithuanian.conllu Koran-marathi.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-lithuanian.conllu data/Koran/Koran-marathi.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-lithuanian.conllu Koran-romanian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-lithuanian.conllu data/Koran/Koran-romanian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-lithuanian.conllu Koran-sanskrit.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-lithuanian.conllu data/Koran/Koran-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-lithuanian.conllu Koran-slovak.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-lithuanian.conllu data/Koran/Koran-slovak.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-lithuanian.conllu Koran-serbian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-lithuanian.conllu data/Koran/Koran-serbian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-lithuanian.conllu Koran-vietnamese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-lithuanian.conllu data/Koran/Koran-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-hungarian.conllu Koran-maltese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-hungarian.conllu data/Koran/Koran-maltese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-hungarian.conllu Koran-marathi.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-hungarian.conllu data/Koran/Koran-marathi.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-hungarian.conllu Koran-romanian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-hungarian.conllu data/Koran/Koran-romanian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-hungarian.conllu Koran-sanskrit.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-hungarian.conllu data/Koran/Koran-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-hungarian.conllu Koran-slovak.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-hungarian.conllu data/Koran/Koran-slovak.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-hungarian.conllu Koran-serbian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-hungarian.conllu data/Koran/Koran-serbian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-hungarian.conllu Koran-vietnamese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-hungarian.conllu data/Koran/Koran-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-maltese.conllu Koran-marathi.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-maltese.conllu data/Koran/Koran-marathi.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-maltese.conllu Koran-romanian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-maltese.conllu data/Koran/Koran-romanian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-maltese.conllu Koran-sanskrit.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-maltese.conllu data/Koran/Koran-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-maltese.conllu Koran-slovak.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-maltese.conllu data/Koran/Koran-slovak.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-maltese.conllu Koran-serbian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-maltese.conllu data/Koran/Koran-serbian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-maltese.conllu Koran-vietnamese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-maltese.conllu data/Koran/Koran-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-marathi.conllu Koran-romanian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-marathi.conllu data/Koran/Koran-romanian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-marathi.conllu Koran-sanskrit.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-marathi.conllu data/Koran/Koran-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-marathi.conllu Koran-slovak.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-marathi.conllu data/Koran/Koran-slovak.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-marathi.conllu Koran-serbian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-marathi.conllu data/Koran/Koran-serbian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-marathi.conllu Koran-vietnamese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-marathi.conllu data/Koran/Koran-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-romanian.conllu Koran-sanskrit.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-romanian.conllu data/Koran/Koran-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-romanian.conllu Koran-slovak.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-romanian.conllu data/Koran/Koran-slovak.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-romanian.conllu Koran-serbian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-romanian.conllu data/Koran/Koran-serbian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-romanian.conllu Koran-vietnamese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-romanian.conllu data/Koran/Koran-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-sanskrit.conllu Koran-slovak.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-sanskrit.conllu data/Koran/Koran-slovak.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-sanskrit.conllu Koran-serbian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-sanskrit.conllu data/Koran/Koran-serbian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-sanskrit.conllu Koran-vietnamese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-sanskrit.conllu data/Koran/Koran-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-slovak.conllu Koran-serbian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-slovak.conllu data/Koran/Koran-serbian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-slovak.conllu Koran-vietnamese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-slovak.conllu data/Koran/Koran-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-serbian.conllu Koran-vietnamese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-serbian.conllu data/Koran/Koran-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-catalan.conllu Koran-german.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-catalan.conllu data/Koran/Koran-german.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-catalan.conllu Koran-greek.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-catalan.conllu data/Koran/Koran-greek.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-catalan.conllu Koran-irish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-catalan.conllu data/Koran/Koran-irish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-catalan.conllu Koran-galician.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-catalan.conllu data/Koran/Koran-galician.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-catalan.conllu Koran-armenian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-catalan.conllu data/Koran/Koran-armenian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-catalan.conllu Koran-croatian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-catalan.conllu data/Koran/Koran-croatian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-catalan.conllu Koran-indonesian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-catalan.conllu data/Koran/Koran-indonesian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-catalan.conllu Koran-italian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-catalan.conllu data/Koran/Koran-italian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-catalan.conllu Koran-hebrew.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-catalan.conllu data/Koran/Koran-hebrew.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-catalan.conllu Koran-latvian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-catalan.conllu data/Koran/Koran-latvian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-catalan.conllu Koran-dutch.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-catalan.conllu data/Koran/Koran-dutch.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-catalan.conllu Koran-japanese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-catalan.conllu data/Koran/Koran-japanese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-catalan.conllu Koran-portuguese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-catalan.conllu data/Koran/Koran-portuguese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-catalan.conllu Koran-russian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-catalan.conllu data/Koran/Koran-russian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-catalan.conllu Koran-swedish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-catalan.conllu data/Koran/Koran-swedish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-catalan.conllu Koran-tamil.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-catalan.conllu data/Koran/Koran-tamil.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-catalan.conllu Koran-telugu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-catalan.conllu data/Koran/Koran-telugu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-catalan.conllu Koran-ukrainian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-catalan.conllu data/Koran/Koran-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-catalan.conllu Koran-urdu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-catalan.conllu data/Koran/Koran-urdu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-catalan.conllu Koran-uyghur.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-catalan.conllu data/Koran/Koran-uyghur.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-catalan.conllu Koran-classical_chinese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-catalan.conllu data/Koran/Koran-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-german.conllu Koran-greek.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-german.conllu data/Koran/Koran-greek.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-german.conllu Koran-irish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-german.conllu data/Koran/Koran-irish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-german.conllu Koran-galician.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-german.conllu data/Koran/Koran-galician.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-german.conllu Koran-armenian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-german.conllu data/Koran/Koran-armenian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-german.conllu Koran-croatian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-german.conllu data/Koran/Koran-croatian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-german.conllu Koran-indonesian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-german.conllu data/Koran/Koran-indonesian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-german.conllu Koran-italian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-german.conllu data/Koran/Koran-italian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-german.conllu Koran-hebrew.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-german.conllu data/Koran/Koran-hebrew.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-german.conllu Koran-latvian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-german.conllu data/Koran/Koran-latvian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-german.conllu Koran-dutch.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-german.conllu data/Koran/Koran-dutch.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-german.conllu Koran-japanese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-german.conllu data/Koran/Koran-japanese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-german.conllu Koran-portuguese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-german.conllu data/Koran/Koran-portuguese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-german.conllu Koran-russian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-german.conllu data/Koran/Koran-russian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-german.conllu Koran-swedish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-german.conllu data/Koran/Koran-swedish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-german.conllu Koran-tamil.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-german.conllu data/Koran/Koran-tamil.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-german.conllu Koran-telugu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-german.conllu data/Koran/Koran-telugu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-german.conllu Koran-ukrainian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-german.conllu data/Koran/Koran-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-german.conllu Koran-urdu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-german.conllu data/Koran/Koran-urdu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-german.conllu Koran-uyghur.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-german.conllu data/Koran/Koran-uyghur.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-german.conllu Koran-classical_chinese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-german.conllu data/Koran/Koran-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-greek.conllu Koran-irish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-greek.conllu data/Koran/Koran-irish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-greek.conllu Koran-galician.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-greek.conllu data/Koran/Koran-galician.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-greek.conllu Koran-armenian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-greek.conllu data/Koran/Koran-armenian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-greek.conllu Koran-croatian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-greek.conllu data/Koran/Koran-croatian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-greek.conllu Koran-indonesian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-greek.conllu data/Koran/Koran-indonesian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-greek.conllu Koran-italian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-greek.conllu data/Koran/Koran-italian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-greek.conllu Koran-hebrew.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-greek.conllu data/Koran/Koran-hebrew.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-greek.conllu Koran-latvian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-greek.conllu data/Koran/Koran-latvian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-greek.conllu Koran-dutch.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-greek.conllu data/Koran/Koran-dutch.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-greek.conllu Koran-japanese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-greek.conllu data/Koran/Koran-japanese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-greek.conllu Koran-portuguese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-greek.conllu data/Koran/Koran-portuguese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-greek.conllu Koran-russian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-greek.conllu data/Koran/Koran-russian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-greek.conllu Koran-swedish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-greek.conllu data/Koran/Koran-swedish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-greek.conllu Koran-tamil.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-greek.conllu data/Koran/Koran-tamil.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-greek.conllu Koran-telugu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-greek.conllu data/Koran/Koran-telugu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-greek.conllu Koran-ukrainian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-greek.conllu data/Koran/Koran-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-greek.conllu Koran-urdu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-greek.conllu data/Koran/Koran-urdu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-greek.conllu Koran-uyghur.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-greek.conllu data/Koran/Koran-uyghur.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-greek.conllu Koran-classical_chinese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-greek.conllu data/Koran/Koran-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-irish.conllu Koran-galician.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-irish.conllu data/Koran/Koran-galician.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-irish.conllu Koran-armenian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-irish.conllu data/Koran/Koran-armenian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-irish.conllu Koran-croatian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-irish.conllu data/Koran/Koran-croatian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-irish.conllu Koran-indonesian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-irish.conllu data/Koran/Koran-indonesian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-irish.conllu Koran-italian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-irish.conllu data/Koran/Koran-italian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-irish.conllu Koran-hebrew.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-irish.conllu data/Koran/Koran-hebrew.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-irish.conllu Koran-latvian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-irish.conllu data/Koran/Koran-latvian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-irish.conllu Koran-dutch.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-irish.conllu data/Koran/Koran-dutch.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-irish.conllu Koran-japanese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-irish.conllu data/Koran/Koran-japanese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-irish.conllu Koran-portuguese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-irish.conllu data/Koran/Koran-portuguese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-irish.conllu Koran-russian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-irish.conllu data/Koran/Koran-russian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-irish.conllu Koran-swedish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-irish.conllu data/Koran/Koran-swedish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-irish.conllu Koran-tamil.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-irish.conllu data/Koran/Koran-tamil.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-irish.conllu Koran-telugu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-irish.conllu data/Koran/Koran-telugu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-irish.conllu Koran-ukrainian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-irish.conllu data/Koran/Koran-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-irish.conllu Koran-urdu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-irish.conllu data/Koran/Koran-urdu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-irish.conllu Koran-uyghur.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-irish.conllu data/Koran/Koran-uyghur.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-irish.conllu Koran-classical_chinese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-irish.conllu data/Koran/Koran-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-galician.conllu Koran-armenian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-galician.conllu data/Koran/Koran-armenian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-galician.conllu Koran-croatian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-galician.conllu data/Koran/Koran-croatian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-galician.conllu Koran-indonesian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-galician.conllu data/Koran/Koran-indonesian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-galician.conllu Koran-italian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-galician.conllu data/Koran/Koran-italian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-galician.conllu Koran-hebrew.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-galician.conllu data/Koran/Koran-hebrew.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-galician.conllu Koran-latvian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-galician.conllu data/Koran/Koran-latvian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-galician.conllu Koran-dutch.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-galician.conllu data/Koran/Koran-dutch.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-galician.conllu Koran-japanese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-galician.conllu data/Koran/Koran-japanese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-galician.conllu Koran-portuguese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-galician.conllu data/Koran/Koran-portuguese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-galician.conllu Koran-russian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-galician.conllu data/Koran/Koran-russian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-galician.conllu Koran-swedish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-galician.conllu data/Koran/Koran-swedish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-galician.conllu Koran-tamil.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-galician.conllu data/Koran/Koran-tamil.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-galician.conllu Koran-telugu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-galician.conllu data/Koran/Koran-telugu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-galician.conllu Koran-ukrainian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-galician.conllu data/Koran/Koran-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-galician.conllu Koran-urdu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-galician.conllu data/Koran/Koran-urdu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-galician.conllu Koran-uyghur.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-galician.conllu data/Koran/Koran-uyghur.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-galician.conllu Koran-classical_chinese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-galician.conllu data/Koran/Koran-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-armenian.conllu Koran-croatian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-armenian.conllu data/Koran/Koran-croatian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-armenian.conllu Koran-indonesian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-armenian.conllu data/Koran/Koran-indonesian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-armenian.conllu Koran-italian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-armenian.conllu data/Koran/Koran-italian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-armenian.conllu Koran-hebrew.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-armenian.conllu data/Koran/Koran-hebrew.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-armenian.conllu Koran-latvian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-armenian.conllu data/Koran/Koran-latvian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-armenian.conllu Koran-dutch.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-armenian.conllu data/Koran/Koran-dutch.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-armenian.conllu Koran-japanese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-armenian.conllu data/Koran/Koran-japanese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-armenian.conllu Koran-portuguese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-armenian.conllu data/Koran/Koran-portuguese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-armenian.conllu Koran-russian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-armenian.conllu data/Koran/Koran-russian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-armenian.conllu Koran-swedish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-armenian.conllu data/Koran/Koran-swedish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-armenian.conllu Koran-tamil.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-armenian.conllu data/Koran/Koran-tamil.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-armenian.conllu Koran-telugu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-armenian.conllu data/Koran/Koran-telugu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-armenian.conllu Koran-ukrainian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-armenian.conllu data/Koran/Koran-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-armenian.conllu Koran-urdu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-armenian.conllu data/Koran/Koran-urdu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-armenian.conllu Koran-uyghur.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-armenian.conllu data/Koran/Koran-uyghur.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-armenian.conllu Koran-classical_chinese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-armenian.conllu data/Koran/Koran-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-croatian.conllu Koran-indonesian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-croatian.conllu data/Koran/Koran-indonesian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-croatian.conllu Koran-italian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-croatian.conllu data/Koran/Koran-italian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-croatian.conllu Koran-hebrew.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-croatian.conllu data/Koran/Koran-hebrew.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-croatian.conllu Koran-latvian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-croatian.conllu data/Koran/Koran-latvian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-croatian.conllu Koran-dutch.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-croatian.conllu data/Koran/Koran-dutch.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-croatian.conllu Koran-japanese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-croatian.conllu data/Koran/Koran-japanese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-croatian.conllu Koran-portuguese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-croatian.conllu data/Koran/Koran-portuguese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-croatian.conllu Koran-russian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-croatian.conllu data/Koran/Koran-russian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-croatian.conllu Koran-swedish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-croatian.conllu data/Koran/Koran-swedish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-croatian.conllu Koran-tamil.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-croatian.conllu data/Koran/Koran-tamil.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-croatian.conllu Koran-telugu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-croatian.conllu data/Koran/Koran-telugu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-croatian.conllu Koran-ukrainian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-croatian.conllu data/Koran/Koran-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-croatian.conllu Koran-urdu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-croatian.conllu data/Koran/Koran-urdu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-croatian.conllu Koran-uyghur.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-croatian.conllu data/Koran/Koran-uyghur.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-croatian.conllu Koran-classical_chinese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-croatian.conllu data/Koran/Koran-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-indonesian.conllu Koran-italian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-indonesian.conllu data/Koran/Koran-italian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-indonesian.conllu Koran-hebrew.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-indonesian.conllu data/Koran/Koran-hebrew.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-indonesian.conllu Koran-latvian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-indonesian.conllu data/Koran/Koran-latvian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-indonesian.conllu Koran-dutch.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-indonesian.conllu data/Koran/Koran-dutch.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-indonesian.conllu Koran-japanese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-indonesian.conllu data/Koran/Koran-japanese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-indonesian.conllu Koran-portuguese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-indonesian.conllu data/Koran/Koran-portuguese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-indonesian.conllu Koran-russian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-indonesian.conllu data/Koran/Koran-russian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-indonesian.conllu Koran-swedish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-indonesian.conllu data/Koran/Koran-swedish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-indonesian.conllu Koran-tamil.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-indonesian.conllu data/Koran/Koran-tamil.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-indonesian.conllu Koran-telugu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-indonesian.conllu data/Koran/Koran-telugu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-indonesian.conllu Koran-ukrainian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-indonesian.conllu data/Koran/Koran-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-indonesian.conllu Koran-urdu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-indonesian.conllu data/Koran/Koran-urdu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-indonesian.conllu Koran-uyghur.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-indonesian.conllu data/Koran/Koran-uyghur.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-indonesian.conllu Koran-classical_chinese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-indonesian.conllu data/Koran/Koran-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-italian.conllu Koran-hebrew.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-italian.conllu data/Koran/Koran-hebrew.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-italian.conllu Koran-latvian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-italian.conllu data/Koran/Koran-latvian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-italian.conllu Koran-dutch.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-italian.conllu data/Koran/Koran-dutch.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-italian.conllu Koran-japanese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-italian.conllu data/Koran/Koran-japanese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-italian.conllu Koran-portuguese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-italian.conllu data/Koran/Koran-portuguese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-italian.conllu Koran-russian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-italian.conllu data/Koran/Koran-russian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-italian.conllu Koran-swedish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-italian.conllu data/Koran/Koran-swedish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-italian.conllu Koran-tamil.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-italian.conllu data/Koran/Koran-tamil.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-italian.conllu Koran-telugu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-italian.conllu data/Koran/Koran-telugu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-italian.conllu Koran-ukrainian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-italian.conllu data/Koran/Koran-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-italian.conllu Koran-urdu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-italian.conllu data/Koran/Koran-urdu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-italian.conllu Koran-uyghur.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-italian.conllu data/Koran/Koran-uyghur.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-italian.conllu Koran-classical_chinese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-italian.conllu data/Koran/Koran-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-hebrew.conllu Koran-latvian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-hebrew.conllu data/Koran/Koran-latvian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-hebrew.conllu Koran-dutch.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-hebrew.conllu data/Koran/Koran-dutch.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-hebrew.conllu Koran-japanese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-hebrew.conllu data/Koran/Koran-japanese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-hebrew.conllu Koran-portuguese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-hebrew.conllu data/Koran/Koran-portuguese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-hebrew.conllu Koran-russian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-hebrew.conllu data/Koran/Koran-russian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-hebrew.conllu Koran-swedish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-hebrew.conllu data/Koran/Koran-swedish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-hebrew.conllu Koran-tamil.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-hebrew.conllu data/Koran/Koran-tamil.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-hebrew.conllu Koran-telugu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-hebrew.conllu data/Koran/Koran-telugu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-hebrew.conllu Koran-ukrainian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-hebrew.conllu data/Koran/Koran-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-hebrew.conllu Koran-urdu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-hebrew.conllu data/Koran/Koran-urdu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-hebrew.conllu Koran-uyghur.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-hebrew.conllu data/Koran/Koran-uyghur.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-hebrew.conllu Koran-classical_chinese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-hebrew.conllu data/Koran/Koran-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-latvian.conllu Koran-dutch.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-latvian.conllu data/Koran/Koran-dutch.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-latvian.conllu Koran-japanese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-latvian.conllu data/Koran/Koran-japanese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-latvian.conllu Koran-portuguese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-latvian.conllu data/Koran/Koran-portuguese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-latvian.conllu Koran-russian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-latvian.conllu data/Koran/Koran-russian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-latvian.conllu Koran-swedish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-latvian.conllu data/Koran/Koran-swedish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-latvian.conllu Koran-tamil.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-latvian.conllu data/Koran/Koran-tamil.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-latvian.conllu Koran-telugu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-latvian.conllu data/Koran/Koran-telugu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-latvian.conllu Koran-ukrainian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-latvian.conllu data/Koran/Koran-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-latvian.conllu Koran-urdu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-latvian.conllu data/Koran/Koran-urdu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-latvian.conllu Koran-uyghur.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-latvian.conllu data/Koran/Koran-uyghur.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-latvian.conllu Koran-classical_chinese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-latvian.conllu data/Koran/Koran-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-dutch.conllu Koran-japanese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-dutch.conllu data/Koran/Koran-japanese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-dutch.conllu Koran-portuguese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-dutch.conllu data/Koran/Koran-portuguese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-dutch.conllu Koran-russian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-dutch.conllu data/Koran/Koran-russian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-dutch.conllu Koran-swedish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-dutch.conllu data/Koran/Koran-swedish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-dutch.conllu Koran-tamil.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-dutch.conllu data/Koran/Koran-tamil.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-dutch.conllu Koran-telugu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-dutch.conllu data/Koran/Koran-telugu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-dutch.conllu Koran-ukrainian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-dutch.conllu data/Koran/Koran-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-dutch.conllu Koran-urdu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-dutch.conllu data/Koran/Koran-urdu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-dutch.conllu Koran-uyghur.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-dutch.conllu data/Koran/Koran-uyghur.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-dutch.conllu Koran-classical_chinese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-dutch.conllu data/Koran/Koran-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-japanese.conllu Koran-portuguese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-japanese.conllu data/Koran/Koran-portuguese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-japanese.conllu Koran-russian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-japanese.conllu data/Koran/Koran-russian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-japanese.conllu Koran-swedish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-japanese.conllu data/Koran/Koran-swedish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-japanese.conllu Koran-tamil.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-japanese.conllu data/Koran/Koran-tamil.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-japanese.conllu Koran-telugu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-japanese.conllu data/Koran/Koran-telugu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-japanese.conllu Koran-ukrainian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-japanese.conllu data/Koran/Koran-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-japanese.conllu Koran-urdu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-japanese.conllu data/Koran/Koran-urdu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-japanese.conllu Koran-uyghur.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-japanese.conllu data/Koran/Koran-uyghur.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-japanese.conllu Koran-classical_chinese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-japanese.conllu data/Koran/Koran-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-portuguese.conllu Koran-russian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-portuguese.conllu data/Koran/Koran-russian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-portuguese.conllu Koran-swedish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-portuguese.conllu data/Koran/Koran-swedish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-portuguese.conllu Koran-tamil.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-portuguese.conllu data/Koran/Koran-tamil.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-portuguese.conllu Koran-telugu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-portuguese.conllu data/Koran/Koran-telugu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-portuguese.conllu Koran-ukrainian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-portuguese.conllu data/Koran/Koran-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-portuguese.conllu Koran-urdu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-portuguese.conllu data/Koran/Koran-urdu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-portuguese.conllu Koran-uyghur.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-portuguese.conllu data/Koran/Koran-uyghur.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-portuguese.conllu Koran-classical_chinese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-portuguese.conllu data/Koran/Koran-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-russian.conllu Koran-swedish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-russian.conllu data/Koran/Koran-swedish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-russian.conllu Koran-tamil.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-russian.conllu data/Koran/Koran-tamil.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-russian.conllu Koran-telugu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-russian.conllu data/Koran/Koran-telugu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-russian.conllu Koran-ukrainian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-russian.conllu data/Koran/Koran-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-russian.conllu Koran-urdu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-russian.conllu data/Koran/Koran-urdu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-russian.conllu Koran-uyghur.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-russian.conllu data/Koran/Koran-uyghur.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-russian.conllu Koran-classical_chinese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-russian.conllu data/Koran/Koran-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-swedish.conllu Koran-tamil.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-swedish.conllu data/Koran/Koran-tamil.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-swedish.conllu Koran-telugu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-swedish.conllu data/Koran/Koran-telugu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-swedish.conllu Koran-ukrainian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-swedish.conllu data/Koran/Koran-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-swedish.conllu Koran-urdu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-swedish.conllu data/Koran/Koran-urdu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-swedish.conllu Koran-uyghur.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-swedish.conllu data/Koran/Koran-uyghur.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-swedish.conllu Koran-classical_chinese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-swedish.conllu data/Koran/Koran-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-tamil.conllu Koran-telugu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-tamil.conllu data/Koran/Koran-telugu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-tamil.conllu Koran-ukrainian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-tamil.conllu data/Koran/Koran-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-tamil.conllu Koran-urdu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-tamil.conllu data/Koran/Koran-urdu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-tamil.conllu Koran-uyghur.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-tamil.conllu data/Koran/Koran-uyghur.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-tamil.conllu Koran-classical_chinese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-tamil.conllu data/Koran/Koran-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-telugu.conllu Koran-ukrainian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-telugu.conllu data/Koran/Koran-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-telugu.conllu Koran-urdu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-telugu.conllu data/Koran/Koran-urdu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-telugu.conllu Koran-uyghur.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-telugu.conllu data/Koran/Koran-uyghur.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-telugu.conllu Koran-classical_chinese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-telugu.conllu data/Koran/Koran-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-ukrainian.conllu Koran-urdu.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-ukrainian.conllu data/Koran/Koran-urdu.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-ukrainian.conllu Koran-uyghur.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-ukrainian.conllu data/Koran/Koran-uyghur.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-ukrainian.conllu Koran-classical_chinese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-ukrainian.conllu data/Koran/Koran-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-urdu.conllu Koran-uyghur.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-urdu.conllu data/Koran/Koran-uyghur.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-urdu.conllu Koran-classical_chinese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-urdu.conllu data/Koran/Koran-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-uyghur.conllu Koran-classical_chinese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-uyghur.conllu data/Koran/Koran-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-arabic.conllu Koran-czech.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-arabic.conllu data/Koran/Koran-czech.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-arabic.conllu Koran-spanish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-arabic.conllu data/Koran/Koran-spanish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-arabic.conllu Koran-kazakh.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-arabic.conllu data/Koran/Koran-kazakh.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-arabic.conllu Koran-polish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-arabic.conllu data/Koran/Koran-polish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-arabic.conllu Koran-chinese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-arabic.conllu data/Koran/Koran-chinese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-czech.conllu Koran-spanish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-czech.conllu data/Koran/Koran-spanish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-czech.conllu Koran-kazakh.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-czech.conllu data/Koran/Koran-kazakh.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-czech.conllu Koran-polish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-czech.conllu data/Koran/Koran-polish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-czech.conllu Koran-chinese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-czech.conllu data/Koran/Koran-chinese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-spanish.conllu Koran-kazakh.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-spanish.conllu data/Koran/Koran-kazakh.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-spanish.conllu Koran-polish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-spanish.conllu data/Koran/Koran-polish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-spanish.conllu Koran-chinese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-spanish.conllu data/Koran/Koran-chinese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-kazakh.conllu Koran-polish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-kazakh.conllu data/Koran/Koran-polish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-kazakh.conllu Koran-chinese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-kazakh.conllu data/Koran/Koran-chinese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-polish.conllu Koran-chinese.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-polish.conllu data/Koran/Koran-chinese.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-english.conllu Koran-persian.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-english.conllu data/Koran/Koran-persian.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-english.conllu Koran-french.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-english.conllu data/Koran/Koran-french.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-english.conllu Koran-hindi.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-english.conllu data/Koran/Koran-hindi.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-english.conllu Koran-finnish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-english.conllu data/Koran/Koran-finnish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-english.conllu Koran-turkish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-english.conllu data/Koran/Koran-turkish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-persian.conllu Koran-french.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-persian.conllu data/Koran/Koran-french.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-persian.conllu Koran-hindi.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-persian.conllu data/Koran/Koran-hindi.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-persian.conllu Koran-finnish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-persian.conllu data/Koran/Koran-finnish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-persian.conllu Koran-turkish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-persian.conllu data/Koran/Koran-turkish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-french.conllu Koran-hindi.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-french.conllu data/Koran/Koran-hindi.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-french.conllu Koran-finnish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-french.conllu data/Koran/Koran-finnish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-french.conllu Koran-turkish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-french.conllu data/Koran/Koran-turkish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-hindi.conllu Koran-finnish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-hindi.conllu data/Koran/Koran-finnish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-hindi.conllu Koran-turkish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-hindi.conllu data/Koran/Koran-turkish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
echo Koran-finnish.conllu Koran-turkish.conllu >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
gfud cosine-similarity data/Koran/Koran-finnish.conllu data/Koran/Koran-turkish.conllu DEPREL >> cosine-sim-per-topic/Koran-cosine-sim.txt ; 
} 
topic_combinations