#! /bin/bash 
function topic_combinations { 
echo Moon-north_sami.conllu Moon-scottish_gaelic.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-north_sami.conllu data/Moon/Moon-scottish_gaelic.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-north_sami.conllu Moon-old_church_slavonic.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-north_sami.conllu data/Moon/Moon-old_church_slavonic.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-scottish_gaelic.conllu Moon-old_church_slavonic.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-scottish_gaelic.conllu data/Moon/Moon-old_church_slavonic.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-welsh.conllu Moon-hindi.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-welsh.conllu data/Moon/Moon-hindi.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-welsh.conllu Moon-latin.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-welsh.conllu data/Moon/Moon-latin.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-welsh.conllu Moon-maltese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-welsh.conllu data/Moon/Moon-maltese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-welsh.conllu Moon-tamil.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-welsh.conllu data/Moon/Moon-tamil.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-welsh.conllu Moon-telugu.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-welsh.conllu data/Moon/Moon-telugu.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-welsh.conllu Moon-urdu.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-welsh.conllu data/Moon/Moon-urdu.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-welsh.conllu Moon-classical_chinese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-welsh.conllu data/Moon/Moon-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-hindi.conllu Moon-latin.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-hindi.conllu data/Moon/Moon-latin.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-hindi.conllu Moon-maltese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-hindi.conllu data/Moon/Moon-maltese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-hindi.conllu Moon-tamil.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-hindi.conllu data/Moon/Moon-tamil.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-hindi.conllu Moon-telugu.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-hindi.conllu data/Moon/Moon-telugu.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-hindi.conllu Moon-urdu.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-hindi.conllu data/Moon/Moon-urdu.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-hindi.conllu Moon-classical_chinese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-hindi.conllu data/Moon/Moon-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-latin.conllu Moon-maltese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-latin.conllu data/Moon/Moon-maltese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-latin.conllu Moon-tamil.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-latin.conllu data/Moon/Moon-tamil.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-latin.conllu Moon-telugu.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-latin.conllu data/Moon/Moon-telugu.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-latin.conllu Moon-urdu.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-latin.conllu data/Moon/Moon-urdu.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-latin.conllu Moon-classical_chinese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-latin.conllu data/Moon/Moon-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-maltese.conllu Moon-tamil.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-maltese.conllu data/Moon/Moon-tamil.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-maltese.conllu Moon-telugu.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-maltese.conllu data/Moon/Moon-telugu.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-maltese.conllu Moon-urdu.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-maltese.conllu data/Moon/Moon-urdu.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-maltese.conllu Moon-classical_chinese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-maltese.conllu data/Moon/Moon-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-tamil.conllu Moon-telugu.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-tamil.conllu data/Moon/Moon-telugu.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-tamil.conllu Moon-urdu.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-tamil.conllu data/Moon/Moon-urdu.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-tamil.conllu Moon-classical_chinese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-tamil.conllu data/Moon/Moon-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-telugu.conllu Moon-urdu.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-telugu.conllu data/Moon/Moon-urdu.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-telugu.conllu Moon-classical_chinese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-telugu.conllu data/Moon/Moon-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-urdu.conllu Moon-classical_chinese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-urdu.conllu data/Moon/Moon-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-arabic.conllu Moon-bulgarian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-arabic.conllu data/Moon/Moon-bulgarian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-arabic.conllu Moon-czech.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-arabic.conllu data/Moon/Moon-czech.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-arabic.conllu Moon-estonian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-arabic.conllu data/Moon/Moon-estonian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-arabic.conllu Moon-greek.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-arabic.conllu data/Moon/Moon-greek.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-arabic.conllu Moon-spanish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-arabic.conllu data/Moon/Moon-spanish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-arabic.conllu Moon-persian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-arabic.conllu data/Moon/Moon-persian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-arabic.conllu Moon-irish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-arabic.conllu data/Moon/Moon-irish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-arabic.conllu Moon-korean.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-arabic.conllu data/Moon/Moon-korean.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-arabic.conllu Moon-hebrew.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-arabic.conllu data/Moon/Moon-hebrew.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-arabic.conllu Moon-kazakh.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-arabic.conllu data/Moon/Moon-kazakh.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-arabic.conllu Moon-latvian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-arabic.conllu data/Moon/Moon-latvian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-arabic.conllu Moon-lithuanian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-arabic.conllu data/Moon/Moon-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-arabic.conllu Moon-marathi.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-arabic.conllu data/Moon/Moon-marathi.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-arabic.conllu Moon-dutch.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-arabic.conllu data/Moon/Moon-dutch.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-arabic.conllu Moon-slovenian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-arabic.conllu data/Moon/Moon-slovenian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-arabic.conllu Moon-serbian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-arabic.conllu data/Moon/Moon-serbian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-arabic.conllu Moon-swedish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-arabic.conllu data/Moon/Moon-swedish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-arabic.conllu Moon-ukrainian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-arabic.conllu data/Moon/Moon-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-bulgarian.conllu Moon-czech.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-bulgarian.conllu data/Moon/Moon-czech.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-bulgarian.conllu Moon-estonian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-bulgarian.conllu data/Moon/Moon-estonian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-bulgarian.conllu Moon-greek.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-bulgarian.conllu data/Moon/Moon-greek.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-bulgarian.conllu Moon-spanish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-bulgarian.conllu data/Moon/Moon-spanish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-bulgarian.conllu Moon-persian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-bulgarian.conllu data/Moon/Moon-persian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-bulgarian.conllu Moon-irish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-bulgarian.conllu data/Moon/Moon-irish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-bulgarian.conllu Moon-korean.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-bulgarian.conllu data/Moon/Moon-korean.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-bulgarian.conllu Moon-hebrew.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-bulgarian.conllu data/Moon/Moon-hebrew.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-bulgarian.conllu Moon-kazakh.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-bulgarian.conllu data/Moon/Moon-kazakh.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-bulgarian.conllu Moon-latvian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-bulgarian.conllu data/Moon/Moon-latvian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-bulgarian.conllu Moon-lithuanian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-bulgarian.conllu data/Moon/Moon-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-bulgarian.conllu Moon-marathi.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-bulgarian.conllu data/Moon/Moon-marathi.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-bulgarian.conllu Moon-dutch.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-bulgarian.conllu data/Moon/Moon-dutch.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-bulgarian.conllu Moon-slovenian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-bulgarian.conllu data/Moon/Moon-slovenian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-bulgarian.conllu Moon-serbian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-bulgarian.conllu data/Moon/Moon-serbian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-bulgarian.conllu Moon-swedish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-bulgarian.conllu data/Moon/Moon-swedish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-bulgarian.conllu Moon-ukrainian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-bulgarian.conllu data/Moon/Moon-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-czech.conllu Moon-estonian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-czech.conllu data/Moon/Moon-estonian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-czech.conllu Moon-greek.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-czech.conllu data/Moon/Moon-greek.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-czech.conllu Moon-spanish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-czech.conllu data/Moon/Moon-spanish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-czech.conllu Moon-persian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-czech.conllu data/Moon/Moon-persian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-czech.conllu Moon-irish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-czech.conllu data/Moon/Moon-irish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-czech.conllu Moon-korean.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-czech.conllu data/Moon/Moon-korean.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-czech.conllu Moon-hebrew.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-czech.conllu data/Moon/Moon-hebrew.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-czech.conllu Moon-kazakh.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-czech.conllu data/Moon/Moon-kazakh.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-czech.conllu Moon-latvian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-czech.conllu data/Moon/Moon-latvian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-czech.conllu Moon-lithuanian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-czech.conllu data/Moon/Moon-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-czech.conllu Moon-marathi.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-czech.conllu data/Moon/Moon-marathi.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-czech.conllu Moon-dutch.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-czech.conllu data/Moon/Moon-dutch.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-czech.conllu Moon-slovenian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-czech.conllu data/Moon/Moon-slovenian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-czech.conllu Moon-serbian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-czech.conllu data/Moon/Moon-serbian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-czech.conllu Moon-swedish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-czech.conllu data/Moon/Moon-swedish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-czech.conllu Moon-ukrainian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-czech.conllu data/Moon/Moon-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-estonian.conllu Moon-greek.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-estonian.conllu data/Moon/Moon-greek.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-estonian.conllu Moon-spanish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-estonian.conllu data/Moon/Moon-spanish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-estonian.conllu Moon-persian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-estonian.conllu data/Moon/Moon-persian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-estonian.conllu Moon-irish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-estonian.conllu data/Moon/Moon-irish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-estonian.conllu Moon-korean.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-estonian.conllu data/Moon/Moon-korean.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-estonian.conllu Moon-hebrew.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-estonian.conllu data/Moon/Moon-hebrew.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-estonian.conllu Moon-kazakh.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-estonian.conllu data/Moon/Moon-kazakh.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-estonian.conllu Moon-latvian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-estonian.conllu data/Moon/Moon-latvian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-estonian.conllu Moon-lithuanian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-estonian.conllu data/Moon/Moon-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-estonian.conllu Moon-marathi.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-estonian.conllu data/Moon/Moon-marathi.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-estonian.conllu Moon-dutch.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-estonian.conllu data/Moon/Moon-dutch.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-estonian.conllu Moon-slovenian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-estonian.conllu data/Moon/Moon-slovenian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-estonian.conllu Moon-serbian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-estonian.conllu data/Moon/Moon-serbian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-estonian.conllu Moon-swedish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-estonian.conllu data/Moon/Moon-swedish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-estonian.conllu Moon-ukrainian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-estonian.conllu data/Moon/Moon-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-greek.conllu Moon-spanish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-greek.conllu data/Moon/Moon-spanish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-greek.conllu Moon-persian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-greek.conllu data/Moon/Moon-persian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-greek.conllu Moon-irish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-greek.conllu data/Moon/Moon-irish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-greek.conllu Moon-korean.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-greek.conllu data/Moon/Moon-korean.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-greek.conllu Moon-hebrew.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-greek.conllu data/Moon/Moon-hebrew.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-greek.conllu Moon-kazakh.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-greek.conllu data/Moon/Moon-kazakh.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-greek.conllu Moon-latvian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-greek.conllu data/Moon/Moon-latvian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-greek.conllu Moon-lithuanian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-greek.conllu data/Moon/Moon-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-greek.conllu Moon-marathi.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-greek.conllu data/Moon/Moon-marathi.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-greek.conllu Moon-dutch.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-greek.conllu data/Moon/Moon-dutch.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-greek.conllu Moon-slovenian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-greek.conllu data/Moon/Moon-slovenian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-greek.conllu Moon-serbian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-greek.conllu data/Moon/Moon-serbian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-greek.conllu Moon-swedish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-greek.conllu data/Moon/Moon-swedish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-greek.conllu Moon-ukrainian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-greek.conllu data/Moon/Moon-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-spanish.conllu Moon-persian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-spanish.conllu data/Moon/Moon-persian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-spanish.conllu Moon-irish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-spanish.conllu data/Moon/Moon-irish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-spanish.conllu Moon-korean.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-spanish.conllu data/Moon/Moon-korean.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-spanish.conllu Moon-hebrew.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-spanish.conllu data/Moon/Moon-hebrew.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-spanish.conllu Moon-kazakh.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-spanish.conllu data/Moon/Moon-kazakh.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-spanish.conllu Moon-latvian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-spanish.conllu data/Moon/Moon-latvian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-spanish.conllu Moon-lithuanian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-spanish.conllu data/Moon/Moon-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-spanish.conllu Moon-marathi.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-spanish.conllu data/Moon/Moon-marathi.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-spanish.conllu Moon-dutch.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-spanish.conllu data/Moon/Moon-dutch.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-spanish.conllu Moon-slovenian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-spanish.conllu data/Moon/Moon-slovenian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-spanish.conllu Moon-serbian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-spanish.conllu data/Moon/Moon-serbian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-spanish.conllu Moon-swedish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-spanish.conllu data/Moon/Moon-swedish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-spanish.conllu Moon-ukrainian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-spanish.conllu data/Moon/Moon-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-persian.conllu Moon-irish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-persian.conllu data/Moon/Moon-irish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-persian.conllu Moon-korean.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-persian.conllu data/Moon/Moon-korean.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-persian.conllu Moon-hebrew.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-persian.conllu data/Moon/Moon-hebrew.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-persian.conllu Moon-kazakh.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-persian.conllu data/Moon/Moon-kazakh.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-persian.conllu Moon-latvian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-persian.conllu data/Moon/Moon-latvian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-persian.conllu Moon-lithuanian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-persian.conllu data/Moon/Moon-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-persian.conllu Moon-marathi.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-persian.conllu data/Moon/Moon-marathi.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-persian.conllu Moon-dutch.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-persian.conllu data/Moon/Moon-dutch.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-persian.conllu Moon-slovenian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-persian.conllu data/Moon/Moon-slovenian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-persian.conllu Moon-serbian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-persian.conllu data/Moon/Moon-serbian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-persian.conllu Moon-swedish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-persian.conllu data/Moon/Moon-swedish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-persian.conllu Moon-ukrainian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-persian.conllu data/Moon/Moon-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-irish.conllu Moon-korean.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-irish.conllu data/Moon/Moon-korean.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-irish.conllu Moon-hebrew.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-irish.conllu data/Moon/Moon-hebrew.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-irish.conllu Moon-kazakh.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-irish.conllu data/Moon/Moon-kazakh.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-irish.conllu Moon-latvian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-irish.conllu data/Moon/Moon-latvian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-irish.conllu Moon-lithuanian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-irish.conllu data/Moon/Moon-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-irish.conllu Moon-marathi.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-irish.conllu data/Moon/Moon-marathi.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-irish.conllu Moon-dutch.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-irish.conllu data/Moon/Moon-dutch.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-irish.conllu Moon-slovenian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-irish.conllu data/Moon/Moon-slovenian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-irish.conllu Moon-serbian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-irish.conllu data/Moon/Moon-serbian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-irish.conllu Moon-swedish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-irish.conllu data/Moon/Moon-swedish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-irish.conllu Moon-ukrainian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-irish.conllu data/Moon/Moon-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-korean.conllu Moon-hebrew.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-korean.conllu data/Moon/Moon-hebrew.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-korean.conllu Moon-kazakh.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-korean.conllu data/Moon/Moon-kazakh.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-korean.conllu Moon-latvian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-korean.conllu data/Moon/Moon-latvian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-korean.conllu Moon-lithuanian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-korean.conllu data/Moon/Moon-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-korean.conllu Moon-marathi.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-korean.conllu data/Moon/Moon-marathi.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-korean.conllu Moon-dutch.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-korean.conllu data/Moon/Moon-dutch.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-korean.conllu Moon-slovenian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-korean.conllu data/Moon/Moon-slovenian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-korean.conllu Moon-serbian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-korean.conllu data/Moon/Moon-serbian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-korean.conllu Moon-swedish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-korean.conllu data/Moon/Moon-swedish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-korean.conllu Moon-ukrainian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-korean.conllu data/Moon/Moon-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-hebrew.conllu Moon-kazakh.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-hebrew.conllu data/Moon/Moon-kazakh.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-hebrew.conllu Moon-latvian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-hebrew.conllu data/Moon/Moon-latvian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-hebrew.conllu Moon-lithuanian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-hebrew.conllu data/Moon/Moon-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-hebrew.conllu Moon-marathi.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-hebrew.conllu data/Moon/Moon-marathi.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-hebrew.conllu Moon-dutch.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-hebrew.conllu data/Moon/Moon-dutch.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-hebrew.conllu Moon-slovenian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-hebrew.conllu data/Moon/Moon-slovenian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-hebrew.conllu Moon-serbian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-hebrew.conllu data/Moon/Moon-serbian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-hebrew.conllu Moon-swedish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-hebrew.conllu data/Moon/Moon-swedish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-hebrew.conllu Moon-ukrainian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-hebrew.conllu data/Moon/Moon-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-kazakh.conllu Moon-latvian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-kazakh.conllu data/Moon/Moon-latvian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-kazakh.conllu Moon-lithuanian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-kazakh.conllu data/Moon/Moon-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-kazakh.conllu Moon-marathi.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-kazakh.conllu data/Moon/Moon-marathi.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-kazakh.conllu Moon-dutch.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-kazakh.conllu data/Moon/Moon-dutch.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-kazakh.conllu Moon-slovenian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-kazakh.conllu data/Moon/Moon-slovenian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-kazakh.conllu Moon-serbian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-kazakh.conllu data/Moon/Moon-serbian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-kazakh.conllu Moon-swedish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-kazakh.conllu data/Moon/Moon-swedish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-kazakh.conllu Moon-ukrainian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-kazakh.conllu data/Moon/Moon-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-latvian.conllu Moon-lithuanian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-latvian.conllu data/Moon/Moon-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-latvian.conllu Moon-marathi.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-latvian.conllu data/Moon/Moon-marathi.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-latvian.conllu Moon-dutch.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-latvian.conllu data/Moon/Moon-dutch.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-latvian.conllu Moon-slovenian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-latvian.conllu data/Moon/Moon-slovenian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-latvian.conllu Moon-serbian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-latvian.conllu data/Moon/Moon-serbian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-latvian.conllu Moon-swedish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-latvian.conllu data/Moon/Moon-swedish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-latvian.conllu Moon-ukrainian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-latvian.conllu data/Moon/Moon-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-lithuanian.conllu Moon-marathi.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-lithuanian.conllu data/Moon/Moon-marathi.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-lithuanian.conllu Moon-dutch.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-lithuanian.conllu data/Moon/Moon-dutch.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-lithuanian.conllu Moon-slovenian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-lithuanian.conllu data/Moon/Moon-slovenian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-lithuanian.conllu Moon-serbian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-lithuanian.conllu data/Moon/Moon-serbian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-lithuanian.conllu Moon-swedish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-lithuanian.conllu data/Moon/Moon-swedish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-lithuanian.conllu Moon-ukrainian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-lithuanian.conllu data/Moon/Moon-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-marathi.conllu Moon-dutch.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-marathi.conllu data/Moon/Moon-dutch.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-marathi.conllu Moon-slovenian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-marathi.conllu data/Moon/Moon-slovenian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-marathi.conllu Moon-serbian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-marathi.conllu data/Moon/Moon-serbian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-marathi.conllu Moon-swedish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-marathi.conllu data/Moon/Moon-swedish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-marathi.conllu Moon-ukrainian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-marathi.conllu data/Moon/Moon-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-dutch.conllu Moon-slovenian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-dutch.conllu data/Moon/Moon-slovenian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-dutch.conllu Moon-serbian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-dutch.conllu data/Moon/Moon-serbian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-dutch.conllu Moon-swedish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-dutch.conllu data/Moon/Moon-swedish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-dutch.conllu Moon-ukrainian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-dutch.conllu data/Moon/Moon-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-slovenian.conllu Moon-serbian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-slovenian.conllu data/Moon/Moon-serbian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-slovenian.conllu Moon-swedish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-slovenian.conllu data/Moon/Moon-swedish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-slovenian.conllu Moon-ukrainian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-slovenian.conllu data/Moon/Moon-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-serbian.conllu Moon-swedish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-serbian.conllu data/Moon/Moon-swedish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-serbian.conllu Moon-ukrainian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-serbian.conllu data/Moon/Moon-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-swedish.conllu Moon-ukrainian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-swedish.conllu data/Moon/Moon-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-afrikaans.conllu Moon-belarusian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-afrikaans.conllu data/Moon/Moon-belarusian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-afrikaans.conllu Moon-catalan.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-afrikaans.conllu data/Moon/Moon-catalan.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-afrikaans.conllu Moon-danish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-afrikaans.conllu data/Moon/Moon-danish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-afrikaans.conllu Moon-basque.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-afrikaans.conllu data/Moon/Moon-basque.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-afrikaans.conllu Moon-galician.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-afrikaans.conllu data/Moon/Moon-galician.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-afrikaans.conllu Moon-armenian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-afrikaans.conllu data/Moon/Moon-armenian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-afrikaans.conllu Moon-indonesian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-afrikaans.conllu data/Moon/Moon-indonesian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-afrikaans.conllu Moon-italian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-afrikaans.conllu data/Moon/Moon-italian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-afrikaans.conllu Moon-japanese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-afrikaans.conllu data/Moon/Moon-japanese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-afrikaans.conllu Moon-polish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-afrikaans.conllu data/Moon/Moon-polish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-afrikaans.conllu Moon-portuguese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-afrikaans.conllu data/Moon/Moon-portuguese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-afrikaans.conllu Moon-romanian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-afrikaans.conllu data/Moon/Moon-romanian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-afrikaans.conllu Moon-russian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-afrikaans.conllu data/Moon/Moon-russian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-afrikaans.conllu Moon-sanskrit.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-afrikaans.conllu data/Moon/Moon-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-afrikaans.conllu Moon-slovak.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-afrikaans.conllu data/Moon/Moon-slovak.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-afrikaans.conllu Moon-finnish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-afrikaans.conllu data/Moon/Moon-finnish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-afrikaans.conllu Moon-turkish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-afrikaans.conllu data/Moon/Moon-turkish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-afrikaans.conllu Moon-vietnamese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-afrikaans.conllu data/Moon/Moon-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-afrikaans.conllu Moon-chinese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-afrikaans.conllu data/Moon/Moon-chinese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-belarusian.conllu Moon-catalan.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-belarusian.conllu data/Moon/Moon-catalan.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-belarusian.conllu Moon-danish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-belarusian.conllu data/Moon/Moon-danish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-belarusian.conllu Moon-basque.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-belarusian.conllu data/Moon/Moon-basque.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-belarusian.conllu Moon-galician.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-belarusian.conllu data/Moon/Moon-galician.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-belarusian.conllu Moon-armenian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-belarusian.conllu data/Moon/Moon-armenian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-belarusian.conllu Moon-indonesian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-belarusian.conllu data/Moon/Moon-indonesian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-belarusian.conllu Moon-italian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-belarusian.conllu data/Moon/Moon-italian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-belarusian.conllu Moon-japanese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-belarusian.conllu data/Moon/Moon-japanese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-belarusian.conllu Moon-polish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-belarusian.conllu data/Moon/Moon-polish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-belarusian.conllu Moon-portuguese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-belarusian.conllu data/Moon/Moon-portuguese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-belarusian.conllu Moon-romanian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-belarusian.conllu data/Moon/Moon-romanian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-belarusian.conllu Moon-russian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-belarusian.conllu data/Moon/Moon-russian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-belarusian.conllu Moon-sanskrit.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-belarusian.conllu data/Moon/Moon-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-belarusian.conllu Moon-slovak.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-belarusian.conllu data/Moon/Moon-slovak.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-belarusian.conllu Moon-finnish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-belarusian.conllu data/Moon/Moon-finnish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-belarusian.conllu Moon-turkish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-belarusian.conllu data/Moon/Moon-turkish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-belarusian.conllu Moon-vietnamese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-belarusian.conllu data/Moon/Moon-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-belarusian.conllu Moon-chinese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-belarusian.conllu data/Moon/Moon-chinese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-catalan.conllu Moon-danish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-catalan.conllu data/Moon/Moon-danish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-catalan.conllu Moon-basque.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-catalan.conllu data/Moon/Moon-basque.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-catalan.conllu Moon-galician.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-catalan.conllu data/Moon/Moon-galician.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-catalan.conllu Moon-armenian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-catalan.conllu data/Moon/Moon-armenian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-catalan.conllu Moon-indonesian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-catalan.conllu data/Moon/Moon-indonesian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-catalan.conllu Moon-italian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-catalan.conllu data/Moon/Moon-italian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-catalan.conllu Moon-japanese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-catalan.conllu data/Moon/Moon-japanese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-catalan.conllu Moon-polish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-catalan.conllu data/Moon/Moon-polish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-catalan.conllu Moon-portuguese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-catalan.conllu data/Moon/Moon-portuguese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-catalan.conllu Moon-romanian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-catalan.conllu data/Moon/Moon-romanian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-catalan.conllu Moon-russian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-catalan.conllu data/Moon/Moon-russian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-catalan.conllu Moon-sanskrit.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-catalan.conllu data/Moon/Moon-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-catalan.conllu Moon-slovak.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-catalan.conllu data/Moon/Moon-slovak.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-catalan.conllu Moon-finnish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-catalan.conllu data/Moon/Moon-finnish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-catalan.conllu Moon-turkish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-catalan.conllu data/Moon/Moon-turkish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-catalan.conllu Moon-vietnamese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-catalan.conllu data/Moon/Moon-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-catalan.conllu Moon-chinese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-catalan.conllu data/Moon/Moon-chinese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-danish.conllu Moon-basque.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-danish.conllu data/Moon/Moon-basque.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-danish.conllu Moon-galician.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-danish.conllu data/Moon/Moon-galician.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-danish.conllu Moon-armenian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-danish.conllu data/Moon/Moon-armenian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-danish.conllu Moon-indonesian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-danish.conllu data/Moon/Moon-indonesian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-danish.conllu Moon-italian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-danish.conllu data/Moon/Moon-italian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-danish.conllu Moon-japanese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-danish.conllu data/Moon/Moon-japanese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-danish.conllu Moon-polish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-danish.conllu data/Moon/Moon-polish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-danish.conllu Moon-portuguese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-danish.conllu data/Moon/Moon-portuguese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-danish.conllu Moon-romanian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-danish.conllu data/Moon/Moon-romanian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-danish.conllu Moon-russian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-danish.conllu data/Moon/Moon-russian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-danish.conllu Moon-sanskrit.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-danish.conllu data/Moon/Moon-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-danish.conllu Moon-slovak.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-danish.conllu data/Moon/Moon-slovak.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-danish.conllu Moon-finnish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-danish.conllu data/Moon/Moon-finnish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-danish.conllu Moon-turkish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-danish.conllu data/Moon/Moon-turkish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-danish.conllu Moon-vietnamese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-danish.conllu data/Moon/Moon-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-danish.conllu Moon-chinese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-danish.conllu data/Moon/Moon-chinese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-basque.conllu Moon-galician.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-basque.conllu data/Moon/Moon-galician.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-basque.conllu Moon-armenian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-basque.conllu data/Moon/Moon-armenian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-basque.conllu Moon-indonesian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-basque.conllu data/Moon/Moon-indonesian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-basque.conllu Moon-italian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-basque.conllu data/Moon/Moon-italian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-basque.conllu Moon-japanese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-basque.conllu data/Moon/Moon-japanese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-basque.conllu Moon-polish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-basque.conllu data/Moon/Moon-polish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-basque.conllu Moon-portuguese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-basque.conllu data/Moon/Moon-portuguese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-basque.conllu Moon-romanian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-basque.conllu data/Moon/Moon-romanian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-basque.conllu Moon-russian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-basque.conllu data/Moon/Moon-russian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-basque.conllu Moon-sanskrit.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-basque.conllu data/Moon/Moon-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-basque.conllu Moon-slovak.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-basque.conllu data/Moon/Moon-slovak.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-basque.conllu Moon-finnish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-basque.conllu data/Moon/Moon-finnish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-basque.conllu Moon-turkish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-basque.conllu data/Moon/Moon-turkish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-basque.conllu Moon-vietnamese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-basque.conllu data/Moon/Moon-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-basque.conllu Moon-chinese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-basque.conllu data/Moon/Moon-chinese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-galician.conllu Moon-armenian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-galician.conllu data/Moon/Moon-armenian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-galician.conllu Moon-indonesian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-galician.conllu data/Moon/Moon-indonesian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-galician.conllu Moon-italian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-galician.conllu data/Moon/Moon-italian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-galician.conllu Moon-japanese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-galician.conllu data/Moon/Moon-japanese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-galician.conllu Moon-polish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-galician.conllu data/Moon/Moon-polish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-galician.conllu Moon-portuguese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-galician.conllu data/Moon/Moon-portuguese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-galician.conllu Moon-romanian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-galician.conllu data/Moon/Moon-romanian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-galician.conllu Moon-russian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-galician.conllu data/Moon/Moon-russian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-galician.conllu Moon-sanskrit.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-galician.conllu data/Moon/Moon-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-galician.conllu Moon-slovak.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-galician.conllu data/Moon/Moon-slovak.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-galician.conllu Moon-finnish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-galician.conllu data/Moon/Moon-finnish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-galician.conllu Moon-turkish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-galician.conllu data/Moon/Moon-turkish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-galician.conllu Moon-vietnamese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-galician.conllu data/Moon/Moon-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-galician.conllu Moon-chinese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-galician.conllu data/Moon/Moon-chinese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-armenian.conllu Moon-indonesian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-armenian.conllu data/Moon/Moon-indonesian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-armenian.conllu Moon-italian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-armenian.conllu data/Moon/Moon-italian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-armenian.conllu Moon-japanese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-armenian.conllu data/Moon/Moon-japanese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-armenian.conllu Moon-polish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-armenian.conllu data/Moon/Moon-polish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-armenian.conllu Moon-portuguese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-armenian.conllu data/Moon/Moon-portuguese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-armenian.conllu Moon-romanian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-armenian.conllu data/Moon/Moon-romanian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-armenian.conllu Moon-russian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-armenian.conllu data/Moon/Moon-russian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-armenian.conllu Moon-sanskrit.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-armenian.conllu data/Moon/Moon-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-armenian.conllu Moon-slovak.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-armenian.conllu data/Moon/Moon-slovak.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-armenian.conllu Moon-finnish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-armenian.conllu data/Moon/Moon-finnish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-armenian.conllu Moon-turkish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-armenian.conllu data/Moon/Moon-turkish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-armenian.conllu Moon-vietnamese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-armenian.conllu data/Moon/Moon-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-armenian.conllu Moon-chinese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-armenian.conllu data/Moon/Moon-chinese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-indonesian.conllu Moon-italian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-indonesian.conllu data/Moon/Moon-italian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-indonesian.conllu Moon-japanese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-indonesian.conllu data/Moon/Moon-japanese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-indonesian.conllu Moon-polish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-indonesian.conllu data/Moon/Moon-polish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-indonesian.conllu Moon-portuguese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-indonesian.conllu data/Moon/Moon-portuguese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-indonesian.conllu Moon-romanian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-indonesian.conllu data/Moon/Moon-romanian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-indonesian.conllu Moon-russian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-indonesian.conllu data/Moon/Moon-russian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-indonesian.conllu Moon-sanskrit.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-indonesian.conllu data/Moon/Moon-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-indonesian.conllu Moon-slovak.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-indonesian.conllu data/Moon/Moon-slovak.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-indonesian.conllu Moon-finnish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-indonesian.conllu data/Moon/Moon-finnish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-indonesian.conllu Moon-turkish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-indonesian.conllu data/Moon/Moon-turkish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-indonesian.conllu Moon-vietnamese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-indonesian.conllu data/Moon/Moon-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-indonesian.conllu Moon-chinese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-indonesian.conllu data/Moon/Moon-chinese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-italian.conllu Moon-japanese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-italian.conllu data/Moon/Moon-japanese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-italian.conllu Moon-polish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-italian.conllu data/Moon/Moon-polish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-italian.conllu Moon-portuguese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-italian.conllu data/Moon/Moon-portuguese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-italian.conllu Moon-romanian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-italian.conllu data/Moon/Moon-romanian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-italian.conllu Moon-russian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-italian.conllu data/Moon/Moon-russian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-italian.conllu Moon-sanskrit.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-italian.conllu data/Moon/Moon-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-italian.conllu Moon-slovak.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-italian.conllu data/Moon/Moon-slovak.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-italian.conllu Moon-finnish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-italian.conllu data/Moon/Moon-finnish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-italian.conllu Moon-turkish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-italian.conllu data/Moon/Moon-turkish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-italian.conllu Moon-vietnamese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-italian.conllu data/Moon/Moon-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-italian.conllu Moon-chinese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-italian.conllu data/Moon/Moon-chinese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-japanese.conllu Moon-polish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-japanese.conllu data/Moon/Moon-polish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-japanese.conllu Moon-portuguese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-japanese.conllu data/Moon/Moon-portuguese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-japanese.conllu Moon-romanian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-japanese.conllu data/Moon/Moon-romanian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-japanese.conllu Moon-russian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-japanese.conllu data/Moon/Moon-russian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-japanese.conllu Moon-sanskrit.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-japanese.conllu data/Moon/Moon-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-japanese.conllu Moon-slovak.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-japanese.conllu data/Moon/Moon-slovak.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-japanese.conllu Moon-finnish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-japanese.conllu data/Moon/Moon-finnish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-japanese.conllu Moon-turkish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-japanese.conllu data/Moon/Moon-turkish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-japanese.conllu Moon-vietnamese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-japanese.conllu data/Moon/Moon-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-japanese.conllu Moon-chinese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-japanese.conllu data/Moon/Moon-chinese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-polish.conllu Moon-portuguese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-polish.conllu data/Moon/Moon-portuguese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-polish.conllu Moon-romanian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-polish.conllu data/Moon/Moon-romanian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-polish.conllu Moon-russian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-polish.conllu data/Moon/Moon-russian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-polish.conllu Moon-sanskrit.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-polish.conllu data/Moon/Moon-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-polish.conllu Moon-slovak.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-polish.conllu data/Moon/Moon-slovak.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-polish.conllu Moon-finnish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-polish.conllu data/Moon/Moon-finnish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-polish.conllu Moon-turkish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-polish.conllu data/Moon/Moon-turkish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-polish.conllu Moon-vietnamese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-polish.conllu data/Moon/Moon-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-polish.conllu Moon-chinese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-polish.conllu data/Moon/Moon-chinese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-portuguese.conllu Moon-romanian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-portuguese.conllu data/Moon/Moon-romanian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-portuguese.conllu Moon-russian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-portuguese.conllu data/Moon/Moon-russian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-portuguese.conllu Moon-sanskrit.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-portuguese.conllu data/Moon/Moon-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-portuguese.conllu Moon-slovak.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-portuguese.conllu data/Moon/Moon-slovak.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-portuguese.conllu Moon-finnish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-portuguese.conllu data/Moon/Moon-finnish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-portuguese.conllu Moon-turkish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-portuguese.conllu data/Moon/Moon-turkish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-portuguese.conllu Moon-vietnamese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-portuguese.conllu data/Moon/Moon-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-portuguese.conllu Moon-chinese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-portuguese.conllu data/Moon/Moon-chinese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-romanian.conllu Moon-russian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-romanian.conllu data/Moon/Moon-russian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-romanian.conllu Moon-sanskrit.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-romanian.conllu data/Moon/Moon-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-romanian.conllu Moon-slovak.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-romanian.conllu data/Moon/Moon-slovak.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-romanian.conllu Moon-finnish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-romanian.conllu data/Moon/Moon-finnish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-romanian.conllu Moon-turkish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-romanian.conllu data/Moon/Moon-turkish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-romanian.conllu Moon-vietnamese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-romanian.conllu data/Moon/Moon-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-romanian.conllu Moon-chinese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-romanian.conllu data/Moon/Moon-chinese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-russian.conllu Moon-sanskrit.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-russian.conllu data/Moon/Moon-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-russian.conllu Moon-slovak.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-russian.conllu data/Moon/Moon-slovak.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-russian.conllu Moon-finnish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-russian.conllu data/Moon/Moon-finnish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-russian.conllu Moon-turkish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-russian.conllu data/Moon/Moon-turkish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-russian.conllu Moon-vietnamese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-russian.conllu data/Moon/Moon-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-russian.conllu Moon-chinese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-russian.conllu data/Moon/Moon-chinese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-sanskrit.conllu Moon-slovak.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-sanskrit.conllu data/Moon/Moon-slovak.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-sanskrit.conllu Moon-finnish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-sanskrit.conllu data/Moon/Moon-finnish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-sanskrit.conllu Moon-turkish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-sanskrit.conllu data/Moon/Moon-turkish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-sanskrit.conllu Moon-vietnamese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-sanskrit.conllu data/Moon/Moon-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-sanskrit.conllu Moon-chinese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-sanskrit.conllu data/Moon/Moon-chinese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-slovak.conllu Moon-finnish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-slovak.conllu data/Moon/Moon-finnish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-slovak.conllu Moon-turkish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-slovak.conllu data/Moon/Moon-turkish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-slovak.conllu Moon-vietnamese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-slovak.conllu data/Moon/Moon-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-slovak.conllu Moon-chinese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-slovak.conllu data/Moon/Moon-chinese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-finnish.conllu Moon-turkish.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-finnish.conllu data/Moon/Moon-turkish.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-finnish.conllu Moon-vietnamese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-finnish.conllu data/Moon/Moon-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-finnish.conllu Moon-chinese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-finnish.conllu data/Moon/Moon-chinese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-turkish.conllu Moon-vietnamese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-turkish.conllu data/Moon/Moon-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-turkish.conllu Moon-chinese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-turkish.conllu data/Moon/Moon-chinese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-vietnamese.conllu Moon-chinese.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-vietnamese.conllu data/Moon/Moon-chinese.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-english.conllu Moon-german.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-english.conllu data/Moon/Moon-german.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-english.conllu Moon-french.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-english.conllu data/Moon/Moon-french.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-english.conllu Moon-croatian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-english.conllu data/Moon/Moon-croatian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-english.conllu Moon-hungarian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-english.conllu data/Moon/Moon-hungarian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-german.conllu Moon-french.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-german.conllu data/Moon/Moon-french.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-german.conllu Moon-croatian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-german.conllu data/Moon/Moon-croatian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-german.conllu Moon-hungarian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-german.conllu data/Moon/Moon-hungarian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-french.conllu Moon-croatian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-french.conllu data/Moon/Moon-croatian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-french.conllu Moon-hungarian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-french.conllu data/Moon/Moon-hungarian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
echo Moon-croatian.conllu Moon-hungarian.conllu >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
gfud cosine-similarity data/Moon/Moon-croatian.conllu data/Moon/Moon-hungarian.conllu DEPREL >> cosine-sim-per-topic/Moon-cosine-sim.txt ; 
} 
topic_combinations