#! /bin/bash 
function topic_combinations { 
echo Moses-welsh.conllu Moses-estonian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-welsh.conllu data/Moses/Moses-estonian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-welsh.conllu Moses-basque.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-welsh.conllu data/Moses/Moses-basque.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-welsh.conllu Moses-scottish_gaelic.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-welsh.conllu data/Moses/Moses-scottish_gaelic.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-welsh.conllu Moses-hindi.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-welsh.conllu data/Moses/Moses-hindi.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-welsh.conllu Moses-marathi.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-welsh.conllu data/Moses/Moses-marathi.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-estonian.conllu Moses-basque.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-estonian.conllu data/Moses/Moses-basque.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-estonian.conllu Moses-scottish_gaelic.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-estonian.conllu data/Moses/Moses-scottish_gaelic.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-estonian.conllu Moses-hindi.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-estonian.conllu data/Moses/Moses-hindi.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-estonian.conllu Moses-marathi.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-estonian.conllu data/Moses/Moses-marathi.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-basque.conllu Moses-scottish_gaelic.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-basque.conllu data/Moses/Moses-scottish_gaelic.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-basque.conllu Moses-hindi.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-basque.conllu data/Moses/Moses-hindi.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-basque.conllu Moses-marathi.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-basque.conllu data/Moses/Moses-marathi.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-scottish_gaelic.conllu Moses-hindi.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-scottish_gaelic.conllu data/Moses/Moses-hindi.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-scottish_gaelic.conllu Moses-marathi.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-scottish_gaelic.conllu data/Moses/Moses-marathi.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-hindi.conllu Moses-marathi.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-hindi.conllu data/Moses/Moses-marathi.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-afrikaans.conllu Moses-danish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-afrikaans.conllu data/Moses/Moses-danish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-afrikaans.conllu Moses-greek.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-afrikaans.conllu data/Moses/Moses-greek.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-afrikaans.conllu Moses-irish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-afrikaans.conllu data/Moses/Moses-irish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-afrikaans.conllu Moses-galician.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-afrikaans.conllu data/Moses/Moses-galician.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-afrikaans.conllu Moses-korean.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-afrikaans.conllu data/Moses/Moses-korean.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-afrikaans.conllu Moses-latin.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-afrikaans.conllu data/Moses/Moses-latin.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-afrikaans.conllu Moses-latvian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-afrikaans.conllu data/Moses/Moses-latvian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-afrikaans.conllu Moses-lithuanian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-afrikaans.conllu data/Moses/Moses-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-afrikaans.conllu Moses-hungarian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-afrikaans.conllu data/Moses/Moses-hungarian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-afrikaans.conllu Moses-slovak.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-afrikaans.conllu data/Moses/Moses-slovak.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-afrikaans.conllu Moses-tamil.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-afrikaans.conllu data/Moses/Moses-tamil.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-afrikaans.conllu Moses-ukrainian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-afrikaans.conllu data/Moses/Moses-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-afrikaans.conllu Moses-chinese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-afrikaans.conllu data/Moses/Moses-chinese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-danish.conllu Moses-greek.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-danish.conllu data/Moses/Moses-greek.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-danish.conllu Moses-irish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-danish.conllu data/Moses/Moses-irish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-danish.conllu Moses-galician.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-danish.conllu data/Moses/Moses-galician.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-danish.conllu Moses-korean.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-danish.conllu data/Moses/Moses-korean.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-danish.conllu Moses-latin.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-danish.conllu data/Moses/Moses-latin.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-danish.conllu Moses-latvian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-danish.conllu data/Moses/Moses-latvian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-danish.conllu Moses-lithuanian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-danish.conllu data/Moses/Moses-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-danish.conllu Moses-hungarian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-danish.conllu data/Moses/Moses-hungarian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-danish.conllu Moses-slovak.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-danish.conllu data/Moses/Moses-slovak.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-danish.conllu Moses-tamil.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-danish.conllu data/Moses/Moses-tamil.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-danish.conllu Moses-ukrainian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-danish.conllu data/Moses/Moses-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-danish.conllu Moses-chinese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-danish.conllu data/Moses/Moses-chinese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-greek.conllu Moses-irish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-greek.conllu data/Moses/Moses-irish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-greek.conllu Moses-galician.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-greek.conllu data/Moses/Moses-galician.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-greek.conllu Moses-korean.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-greek.conllu data/Moses/Moses-korean.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-greek.conllu Moses-latin.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-greek.conllu data/Moses/Moses-latin.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-greek.conllu Moses-latvian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-greek.conllu data/Moses/Moses-latvian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-greek.conllu Moses-lithuanian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-greek.conllu data/Moses/Moses-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-greek.conllu Moses-hungarian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-greek.conllu data/Moses/Moses-hungarian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-greek.conllu Moses-slovak.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-greek.conllu data/Moses/Moses-slovak.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-greek.conllu Moses-tamil.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-greek.conllu data/Moses/Moses-tamil.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-greek.conllu Moses-ukrainian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-greek.conllu data/Moses/Moses-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-greek.conllu Moses-chinese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-greek.conllu data/Moses/Moses-chinese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-irish.conllu Moses-galician.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-irish.conllu data/Moses/Moses-galician.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-irish.conllu Moses-korean.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-irish.conllu data/Moses/Moses-korean.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-irish.conllu Moses-latin.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-irish.conllu data/Moses/Moses-latin.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-irish.conllu Moses-latvian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-irish.conllu data/Moses/Moses-latvian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-irish.conllu Moses-lithuanian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-irish.conllu data/Moses/Moses-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-irish.conllu Moses-hungarian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-irish.conllu data/Moses/Moses-hungarian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-irish.conllu Moses-slovak.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-irish.conllu data/Moses/Moses-slovak.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-irish.conllu Moses-tamil.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-irish.conllu data/Moses/Moses-tamil.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-irish.conllu Moses-ukrainian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-irish.conllu data/Moses/Moses-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-irish.conllu Moses-chinese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-irish.conllu data/Moses/Moses-chinese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-galician.conllu Moses-korean.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-galician.conllu data/Moses/Moses-korean.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-galician.conllu Moses-latin.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-galician.conllu data/Moses/Moses-latin.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-galician.conllu Moses-latvian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-galician.conllu data/Moses/Moses-latvian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-galician.conllu Moses-lithuanian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-galician.conllu data/Moses/Moses-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-galician.conllu Moses-hungarian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-galician.conllu data/Moses/Moses-hungarian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-galician.conllu Moses-slovak.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-galician.conllu data/Moses/Moses-slovak.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-galician.conllu Moses-tamil.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-galician.conllu data/Moses/Moses-tamil.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-galician.conllu Moses-ukrainian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-galician.conllu data/Moses/Moses-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-galician.conllu Moses-chinese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-galician.conllu data/Moses/Moses-chinese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-korean.conllu Moses-latin.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-korean.conllu data/Moses/Moses-latin.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-korean.conllu Moses-latvian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-korean.conllu data/Moses/Moses-latvian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-korean.conllu Moses-lithuanian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-korean.conllu data/Moses/Moses-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-korean.conllu Moses-hungarian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-korean.conllu data/Moses/Moses-hungarian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-korean.conllu Moses-slovak.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-korean.conllu data/Moses/Moses-slovak.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-korean.conllu Moses-tamil.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-korean.conllu data/Moses/Moses-tamil.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-korean.conllu Moses-ukrainian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-korean.conllu data/Moses/Moses-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-korean.conllu Moses-chinese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-korean.conllu data/Moses/Moses-chinese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-latin.conllu Moses-latvian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-latin.conllu data/Moses/Moses-latvian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-latin.conllu Moses-lithuanian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-latin.conllu data/Moses/Moses-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-latin.conllu Moses-hungarian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-latin.conllu data/Moses/Moses-hungarian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-latin.conllu Moses-slovak.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-latin.conllu data/Moses/Moses-slovak.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-latin.conllu Moses-tamil.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-latin.conllu data/Moses/Moses-tamil.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-latin.conllu Moses-ukrainian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-latin.conllu data/Moses/Moses-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-latin.conllu Moses-chinese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-latin.conllu data/Moses/Moses-chinese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-latvian.conllu Moses-lithuanian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-latvian.conllu data/Moses/Moses-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-latvian.conllu Moses-hungarian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-latvian.conllu data/Moses/Moses-hungarian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-latvian.conllu Moses-slovak.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-latvian.conllu data/Moses/Moses-slovak.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-latvian.conllu Moses-tamil.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-latvian.conllu data/Moses/Moses-tamil.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-latvian.conllu Moses-ukrainian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-latvian.conllu data/Moses/Moses-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-latvian.conllu Moses-chinese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-latvian.conllu data/Moses/Moses-chinese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-lithuanian.conllu Moses-hungarian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-lithuanian.conllu data/Moses/Moses-hungarian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-lithuanian.conllu Moses-slovak.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-lithuanian.conllu data/Moses/Moses-slovak.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-lithuanian.conllu Moses-tamil.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-lithuanian.conllu data/Moses/Moses-tamil.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-lithuanian.conllu Moses-ukrainian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-lithuanian.conllu data/Moses/Moses-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-lithuanian.conllu Moses-chinese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-lithuanian.conllu data/Moses/Moses-chinese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-hungarian.conllu Moses-slovak.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-hungarian.conllu data/Moses/Moses-slovak.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-hungarian.conllu Moses-tamil.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-hungarian.conllu data/Moses/Moses-tamil.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-hungarian.conllu Moses-ukrainian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-hungarian.conllu data/Moses/Moses-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-hungarian.conllu Moses-chinese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-hungarian.conllu data/Moses/Moses-chinese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-slovak.conllu Moses-tamil.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-slovak.conllu data/Moses/Moses-tamil.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-slovak.conllu Moses-ukrainian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-slovak.conllu data/Moses/Moses-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-slovak.conllu Moses-chinese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-slovak.conllu data/Moses/Moses-chinese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-tamil.conllu Moses-ukrainian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-tamil.conllu data/Moses/Moses-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-tamil.conllu Moses-chinese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-tamil.conllu data/Moses/Moses-chinese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-ukrainian.conllu Moses-chinese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-ukrainian.conllu data/Moses/Moses-chinese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-arabic.conllu Moses-belarusian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-arabic.conllu data/Moses/Moses-belarusian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-arabic.conllu Moses-bulgarian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-arabic.conllu data/Moses/Moses-bulgarian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-arabic.conllu Moses-catalan.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-arabic.conllu data/Moses/Moses-catalan.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-arabic.conllu Moses-czech.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-arabic.conllu data/Moses/Moses-czech.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-arabic.conllu Moses-german.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-arabic.conllu data/Moses/Moses-german.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-arabic.conllu Moses-spanish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-arabic.conllu data/Moses/Moses-spanish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-arabic.conllu Moses-armenian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-arabic.conllu data/Moses/Moses-armenian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-arabic.conllu Moses-croatian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-arabic.conllu data/Moses/Moses-croatian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-arabic.conllu Moses-hebrew.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-arabic.conllu data/Moses/Moses-hebrew.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-arabic.conllu Moses-kazakh.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-arabic.conllu data/Moses/Moses-kazakh.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-arabic.conllu Moses-dutch.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-arabic.conllu data/Moses/Moses-dutch.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-arabic.conllu Moses-japanese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-arabic.conllu data/Moses/Moses-japanese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-arabic.conllu Moses-polish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-arabic.conllu data/Moses/Moses-polish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-arabic.conllu Moses-portuguese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-arabic.conllu data/Moses/Moses-portuguese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-arabic.conllu Moses-romanian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-arabic.conllu data/Moses/Moses-romanian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-arabic.conllu Moses-russian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-arabic.conllu data/Moses/Moses-russian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-arabic.conllu Moses-serbian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-arabic.conllu data/Moses/Moses-serbian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-arabic.conllu Moses-finnish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-arabic.conllu data/Moses/Moses-finnish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-arabic.conllu Moses-swedish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-arabic.conllu data/Moses/Moses-swedish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-arabic.conllu Moses-turkish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-arabic.conllu data/Moses/Moses-turkish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-arabic.conllu Moses-urdu.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-arabic.conllu data/Moses/Moses-urdu.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-arabic.conllu Moses-vietnamese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-arabic.conllu data/Moses/Moses-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-belarusian.conllu Moses-bulgarian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-belarusian.conllu data/Moses/Moses-bulgarian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-belarusian.conllu Moses-catalan.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-belarusian.conllu data/Moses/Moses-catalan.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-belarusian.conllu Moses-czech.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-belarusian.conllu data/Moses/Moses-czech.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-belarusian.conllu Moses-german.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-belarusian.conllu data/Moses/Moses-german.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-belarusian.conllu Moses-spanish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-belarusian.conllu data/Moses/Moses-spanish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-belarusian.conllu Moses-armenian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-belarusian.conllu data/Moses/Moses-armenian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-belarusian.conllu Moses-croatian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-belarusian.conllu data/Moses/Moses-croatian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-belarusian.conllu Moses-hebrew.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-belarusian.conllu data/Moses/Moses-hebrew.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-belarusian.conllu Moses-kazakh.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-belarusian.conllu data/Moses/Moses-kazakh.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-belarusian.conllu Moses-dutch.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-belarusian.conllu data/Moses/Moses-dutch.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-belarusian.conllu Moses-japanese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-belarusian.conllu data/Moses/Moses-japanese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-belarusian.conllu Moses-polish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-belarusian.conllu data/Moses/Moses-polish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-belarusian.conllu Moses-portuguese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-belarusian.conllu data/Moses/Moses-portuguese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-belarusian.conllu Moses-romanian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-belarusian.conllu data/Moses/Moses-romanian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-belarusian.conllu Moses-russian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-belarusian.conllu data/Moses/Moses-russian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-belarusian.conllu Moses-serbian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-belarusian.conllu data/Moses/Moses-serbian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-belarusian.conllu Moses-finnish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-belarusian.conllu data/Moses/Moses-finnish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-belarusian.conllu Moses-swedish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-belarusian.conllu data/Moses/Moses-swedish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-belarusian.conllu Moses-turkish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-belarusian.conllu data/Moses/Moses-turkish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-belarusian.conllu Moses-urdu.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-belarusian.conllu data/Moses/Moses-urdu.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-belarusian.conllu Moses-vietnamese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-belarusian.conllu data/Moses/Moses-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-bulgarian.conllu Moses-catalan.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-bulgarian.conllu data/Moses/Moses-catalan.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-bulgarian.conllu Moses-czech.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-bulgarian.conllu data/Moses/Moses-czech.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-bulgarian.conllu Moses-german.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-bulgarian.conllu data/Moses/Moses-german.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-bulgarian.conllu Moses-spanish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-bulgarian.conllu data/Moses/Moses-spanish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-bulgarian.conllu Moses-armenian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-bulgarian.conllu data/Moses/Moses-armenian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-bulgarian.conllu Moses-croatian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-bulgarian.conllu data/Moses/Moses-croatian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-bulgarian.conllu Moses-hebrew.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-bulgarian.conllu data/Moses/Moses-hebrew.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-bulgarian.conllu Moses-kazakh.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-bulgarian.conllu data/Moses/Moses-kazakh.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-bulgarian.conllu Moses-dutch.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-bulgarian.conllu data/Moses/Moses-dutch.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-bulgarian.conllu Moses-japanese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-bulgarian.conllu data/Moses/Moses-japanese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-bulgarian.conllu Moses-polish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-bulgarian.conllu data/Moses/Moses-polish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-bulgarian.conllu Moses-portuguese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-bulgarian.conllu data/Moses/Moses-portuguese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-bulgarian.conllu Moses-romanian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-bulgarian.conllu data/Moses/Moses-romanian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-bulgarian.conllu Moses-russian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-bulgarian.conllu data/Moses/Moses-russian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-bulgarian.conllu Moses-serbian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-bulgarian.conllu data/Moses/Moses-serbian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-bulgarian.conllu Moses-finnish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-bulgarian.conllu data/Moses/Moses-finnish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-bulgarian.conllu Moses-swedish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-bulgarian.conllu data/Moses/Moses-swedish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-bulgarian.conllu Moses-turkish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-bulgarian.conllu data/Moses/Moses-turkish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-bulgarian.conllu Moses-urdu.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-bulgarian.conllu data/Moses/Moses-urdu.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-bulgarian.conllu Moses-vietnamese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-bulgarian.conllu data/Moses/Moses-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-catalan.conllu Moses-czech.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-catalan.conllu data/Moses/Moses-czech.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-catalan.conllu Moses-german.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-catalan.conllu data/Moses/Moses-german.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-catalan.conllu Moses-spanish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-catalan.conllu data/Moses/Moses-spanish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-catalan.conllu Moses-armenian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-catalan.conllu data/Moses/Moses-armenian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-catalan.conllu Moses-croatian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-catalan.conllu data/Moses/Moses-croatian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-catalan.conllu Moses-hebrew.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-catalan.conllu data/Moses/Moses-hebrew.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-catalan.conllu Moses-kazakh.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-catalan.conllu data/Moses/Moses-kazakh.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-catalan.conllu Moses-dutch.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-catalan.conllu data/Moses/Moses-dutch.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-catalan.conllu Moses-japanese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-catalan.conllu data/Moses/Moses-japanese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-catalan.conllu Moses-polish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-catalan.conllu data/Moses/Moses-polish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-catalan.conllu Moses-portuguese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-catalan.conllu data/Moses/Moses-portuguese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-catalan.conllu Moses-romanian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-catalan.conllu data/Moses/Moses-romanian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-catalan.conllu Moses-russian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-catalan.conllu data/Moses/Moses-russian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-catalan.conllu Moses-serbian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-catalan.conllu data/Moses/Moses-serbian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-catalan.conllu Moses-finnish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-catalan.conllu data/Moses/Moses-finnish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-catalan.conllu Moses-swedish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-catalan.conllu data/Moses/Moses-swedish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-catalan.conllu Moses-turkish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-catalan.conllu data/Moses/Moses-turkish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-catalan.conllu Moses-urdu.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-catalan.conllu data/Moses/Moses-urdu.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-catalan.conllu Moses-vietnamese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-catalan.conllu data/Moses/Moses-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-czech.conllu Moses-german.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-czech.conllu data/Moses/Moses-german.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-czech.conllu Moses-spanish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-czech.conllu data/Moses/Moses-spanish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-czech.conllu Moses-armenian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-czech.conllu data/Moses/Moses-armenian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-czech.conllu Moses-croatian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-czech.conllu data/Moses/Moses-croatian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-czech.conllu Moses-hebrew.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-czech.conllu data/Moses/Moses-hebrew.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-czech.conllu Moses-kazakh.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-czech.conllu data/Moses/Moses-kazakh.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-czech.conllu Moses-dutch.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-czech.conllu data/Moses/Moses-dutch.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-czech.conllu Moses-japanese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-czech.conllu data/Moses/Moses-japanese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-czech.conllu Moses-polish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-czech.conllu data/Moses/Moses-polish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-czech.conllu Moses-portuguese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-czech.conllu data/Moses/Moses-portuguese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-czech.conllu Moses-romanian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-czech.conllu data/Moses/Moses-romanian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-czech.conllu Moses-russian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-czech.conllu data/Moses/Moses-russian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-czech.conllu Moses-serbian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-czech.conllu data/Moses/Moses-serbian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-czech.conllu Moses-finnish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-czech.conllu data/Moses/Moses-finnish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-czech.conllu Moses-swedish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-czech.conllu data/Moses/Moses-swedish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-czech.conllu Moses-turkish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-czech.conllu data/Moses/Moses-turkish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-czech.conllu Moses-urdu.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-czech.conllu data/Moses/Moses-urdu.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-czech.conllu Moses-vietnamese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-czech.conllu data/Moses/Moses-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-german.conllu Moses-spanish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-german.conllu data/Moses/Moses-spanish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-german.conllu Moses-armenian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-german.conllu data/Moses/Moses-armenian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-german.conllu Moses-croatian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-german.conllu data/Moses/Moses-croatian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-german.conllu Moses-hebrew.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-german.conllu data/Moses/Moses-hebrew.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-german.conllu Moses-kazakh.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-german.conllu data/Moses/Moses-kazakh.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-german.conllu Moses-dutch.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-german.conllu data/Moses/Moses-dutch.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-german.conllu Moses-japanese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-german.conllu data/Moses/Moses-japanese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-german.conllu Moses-polish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-german.conllu data/Moses/Moses-polish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-german.conllu Moses-portuguese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-german.conllu data/Moses/Moses-portuguese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-german.conllu Moses-romanian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-german.conllu data/Moses/Moses-romanian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-german.conllu Moses-russian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-german.conllu data/Moses/Moses-russian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-german.conllu Moses-serbian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-german.conllu data/Moses/Moses-serbian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-german.conllu Moses-finnish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-german.conllu data/Moses/Moses-finnish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-german.conllu Moses-swedish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-german.conllu data/Moses/Moses-swedish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-german.conllu Moses-turkish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-german.conllu data/Moses/Moses-turkish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-german.conllu Moses-urdu.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-german.conllu data/Moses/Moses-urdu.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-german.conllu Moses-vietnamese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-german.conllu data/Moses/Moses-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-spanish.conllu Moses-armenian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-spanish.conllu data/Moses/Moses-armenian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-spanish.conllu Moses-croatian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-spanish.conllu data/Moses/Moses-croatian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-spanish.conllu Moses-hebrew.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-spanish.conllu data/Moses/Moses-hebrew.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-spanish.conllu Moses-kazakh.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-spanish.conllu data/Moses/Moses-kazakh.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-spanish.conllu Moses-dutch.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-spanish.conllu data/Moses/Moses-dutch.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-spanish.conllu Moses-japanese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-spanish.conllu data/Moses/Moses-japanese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-spanish.conllu Moses-polish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-spanish.conllu data/Moses/Moses-polish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-spanish.conllu Moses-portuguese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-spanish.conllu data/Moses/Moses-portuguese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-spanish.conllu Moses-romanian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-spanish.conllu data/Moses/Moses-romanian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-spanish.conllu Moses-russian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-spanish.conllu data/Moses/Moses-russian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-spanish.conllu Moses-serbian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-spanish.conllu data/Moses/Moses-serbian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-spanish.conllu Moses-finnish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-spanish.conllu data/Moses/Moses-finnish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-spanish.conllu Moses-swedish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-spanish.conllu data/Moses/Moses-swedish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-spanish.conllu Moses-turkish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-spanish.conllu data/Moses/Moses-turkish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-spanish.conllu Moses-urdu.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-spanish.conllu data/Moses/Moses-urdu.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-spanish.conllu Moses-vietnamese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-spanish.conllu data/Moses/Moses-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-armenian.conllu Moses-croatian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-armenian.conllu data/Moses/Moses-croatian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-armenian.conllu Moses-hebrew.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-armenian.conllu data/Moses/Moses-hebrew.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-armenian.conllu Moses-kazakh.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-armenian.conllu data/Moses/Moses-kazakh.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-armenian.conllu Moses-dutch.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-armenian.conllu data/Moses/Moses-dutch.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-armenian.conllu Moses-japanese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-armenian.conllu data/Moses/Moses-japanese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-armenian.conllu Moses-polish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-armenian.conllu data/Moses/Moses-polish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-armenian.conllu Moses-portuguese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-armenian.conllu data/Moses/Moses-portuguese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-armenian.conllu Moses-romanian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-armenian.conllu data/Moses/Moses-romanian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-armenian.conllu Moses-russian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-armenian.conllu data/Moses/Moses-russian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-armenian.conllu Moses-serbian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-armenian.conllu data/Moses/Moses-serbian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-armenian.conllu Moses-finnish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-armenian.conllu data/Moses/Moses-finnish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-armenian.conllu Moses-swedish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-armenian.conllu data/Moses/Moses-swedish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-armenian.conllu Moses-turkish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-armenian.conllu data/Moses/Moses-turkish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-armenian.conllu Moses-urdu.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-armenian.conllu data/Moses/Moses-urdu.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-armenian.conllu Moses-vietnamese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-armenian.conllu data/Moses/Moses-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-croatian.conllu Moses-hebrew.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-croatian.conllu data/Moses/Moses-hebrew.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-croatian.conllu Moses-kazakh.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-croatian.conllu data/Moses/Moses-kazakh.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-croatian.conllu Moses-dutch.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-croatian.conllu data/Moses/Moses-dutch.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-croatian.conllu Moses-japanese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-croatian.conllu data/Moses/Moses-japanese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-croatian.conllu Moses-polish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-croatian.conllu data/Moses/Moses-polish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-croatian.conllu Moses-portuguese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-croatian.conllu data/Moses/Moses-portuguese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-croatian.conllu Moses-romanian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-croatian.conllu data/Moses/Moses-romanian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-croatian.conllu Moses-russian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-croatian.conllu data/Moses/Moses-russian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-croatian.conllu Moses-serbian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-croatian.conllu data/Moses/Moses-serbian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-croatian.conllu Moses-finnish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-croatian.conllu data/Moses/Moses-finnish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-croatian.conllu Moses-swedish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-croatian.conllu data/Moses/Moses-swedish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-croatian.conllu Moses-turkish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-croatian.conllu data/Moses/Moses-turkish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-croatian.conllu Moses-urdu.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-croatian.conllu data/Moses/Moses-urdu.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-croatian.conllu Moses-vietnamese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-croatian.conllu data/Moses/Moses-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-hebrew.conllu Moses-kazakh.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-hebrew.conllu data/Moses/Moses-kazakh.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-hebrew.conllu Moses-dutch.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-hebrew.conllu data/Moses/Moses-dutch.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-hebrew.conllu Moses-japanese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-hebrew.conllu data/Moses/Moses-japanese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-hebrew.conllu Moses-polish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-hebrew.conllu data/Moses/Moses-polish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-hebrew.conllu Moses-portuguese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-hebrew.conllu data/Moses/Moses-portuguese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-hebrew.conllu Moses-romanian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-hebrew.conllu data/Moses/Moses-romanian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-hebrew.conllu Moses-russian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-hebrew.conllu data/Moses/Moses-russian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-hebrew.conllu Moses-serbian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-hebrew.conllu data/Moses/Moses-serbian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-hebrew.conllu Moses-finnish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-hebrew.conllu data/Moses/Moses-finnish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-hebrew.conllu Moses-swedish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-hebrew.conllu data/Moses/Moses-swedish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-hebrew.conllu Moses-turkish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-hebrew.conllu data/Moses/Moses-turkish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-hebrew.conllu Moses-urdu.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-hebrew.conllu data/Moses/Moses-urdu.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-hebrew.conllu Moses-vietnamese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-hebrew.conllu data/Moses/Moses-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-kazakh.conllu Moses-dutch.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-kazakh.conllu data/Moses/Moses-dutch.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-kazakh.conllu Moses-japanese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-kazakh.conllu data/Moses/Moses-japanese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-kazakh.conllu Moses-polish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-kazakh.conllu data/Moses/Moses-polish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-kazakh.conllu Moses-portuguese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-kazakh.conllu data/Moses/Moses-portuguese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-kazakh.conllu Moses-romanian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-kazakh.conllu data/Moses/Moses-romanian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-kazakh.conllu Moses-russian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-kazakh.conllu data/Moses/Moses-russian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-kazakh.conllu Moses-serbian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-kazakh.conllu data/Moses/Moses-serbian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-kazakh.conllu Moses-finnish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-kazakh.conllu data/Moses/Moses-finnish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-kazakh.conllu Moses-swedish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-kazakh.conllu data/Moses/Moses-swedish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-kazakh.conllu Moses-turkish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-kazakh.conllu data/Moses/Moses-turkish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-kazakh.conllu Moses-urdu.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-kazakh.conllu data/Moses/Moses-urdu.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-kazakh.conllu Moses-vietnamese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-kazakh.conllu data/Moses/Moses-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-dutch.conllu Moses-japanese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-dutch.conllu data/Moses/Moses-japanese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-dutch.conllu Moses-polish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-dutch.conllu data/Moses/Moses-polish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-dutch.conllu Moses-portuguese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-dutch.conllu data/Moses/Moses-portuguese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-dutch.conllu Moses-romanian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-dutch.conllu data/Moses/Moses-romanian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-dutch.conllu Moses-russian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-dutch.conllu data/Moses/Moses-russian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-dutch.conllu Moses-serbian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-dutch.conllu data/Moses/Moses-serbian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-dutch.conllu Moses-finnish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-dutch.conllu data/Moses/Moses-finnish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-dutch.conllu Moses-swedish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-dutch.conllu data/Moses/Moses-swedish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-dutch.conllu Moses-turkish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-dutch.conllu data/Moses/Moses-turkish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-dutch.conllu Moses-urdu.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-dutch.conllu data/Moses/Moses-urdu.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-dutch.conllu Moses-vietnamese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-dutch.conllu data/Moses/Moses-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-japanese.conllu Moses-polish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-japanese.conllu data/Moses/Moses-polish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-japanese.conllu Moses-portuguese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-japanese.conllu data/Moses/Moses-portuguese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-japanese.conllu Moses-romanian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-japanese.conllu data/Moses/Moses-romanian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-japanese.conllu Moses-russian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-japanese.conllu data/Moses/Moses-russian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-japanese.conllu Moses-serbian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-japanese.conllu data/Moses/Moses-serbian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-japanese.conllu Moses-finnish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-japanese.conllu data/Moses/Moses-finnish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-japanese.conllu Moses-swedish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-japanese.conllu data/Moses/Moses-swedish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-japanese.conllu Moses-turkish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-japanese.conllu data/Moses/Moses-turkish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-japanese.conllu Moses-urdu.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-japanese.conllu data/Moses/Moses-urdu.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-japanese.conllu Moses-vietnamese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-japanese.conllu data/Moses/Moses-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-polish.conllu Moses-portuguese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-polish.conllu data/Moses/Moses-portuguese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-polish.conllu Moses-romanian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-polish.conllu data/Moses/Moses-romanian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-polish.conllu Moses-russian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-polish.conllu data/Moses/Moses-russian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-polish.conllu Moses-serbian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-polish.conllu data/Moses/Moses-serbian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-polish.conllu Moses-finnish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-polish.conllu data/Moses/Moses-finnish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-polish.conllu Moses-swedish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-polish.conllu data/Moses/Moses-swedish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-polish.conllu Moses-turkish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-polish.conllu data/Moses/Moses-turkish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-polish.conllu Moses-urdu.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-polish.conllu data/Moses/Moses-urdu.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-polish.conllu Moses-vietnamese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-polish.conllu data/Moses/Moses-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-portuguese.conllu Moses-romanian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-portuguese.conllu data/Moses/Moses-romanian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-portuguese.conllu Moses-russian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-portuguese.conllu data/Moses/Moses-russian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-portuguese.conllu Moses-serbian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-portuguese.conllu data/Moses/Moses-serbian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-portuguese.conllu Moses-finnish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-portuguese.conllu data/Moses/Moses-finnish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-portuguese.conllu Moses-swedish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-portuguese.conllu data/Moses/Moses-swedish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-portuguese.conllu Moses-turkish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-portuguese.conllu data/Moses/Moses-turkish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-portuguese.conllu Moses-urdu.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-portuguese.conllu data/Moses/Moses-urdu.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-portuguese.conllu Moses-vietnamese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-portuguese.conllu data/Moses/Moses-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-romanian.conllu Moses-russian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-romanian.conllu data/Moses/Moses-russian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-romanian.conllu Moses-serbian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-romanian.conllu data/Moses/Moses-serbian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-romanian.conllu Moses-finnish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-romanian.conllu data/Moses/Moses-finnish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-romanian.conllu Moses-swedish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-romanian.conllu data/Moses/Moses-swedish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-romanian.conllu Moses-turkish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-romanian.conllu data/Moses/Moses-turkish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-romanian.conllu Moses-urdu.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-romanian.conllu data/Moses/Moses-urdu.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-romanian.conllu Moses-vietnamese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-romanian.conllu data/Moses/Moses-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-russian.conllu Moses-serbian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-russian.conllu data/Moses/Moses-serbian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-russian.conllu Moses-finnish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-russian.conllu data/Moses/Moses-finnish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-russian.conllu Moses-swedish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-russian.conllu data/Moses/Moses-swedish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-russian.conllu Moses-turkish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-russian.conllu data/Moses/Moses-turkish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-russian.conllu Moses-urdu.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-russian.conllu data/Moses/Moses-urdu.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-russian.conllu Moses-vietnamese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-russian.conllu data/Moses/Moses-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-serbian.conllu Moses-finnish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-serbian.conllu data/Moses/Moses-finnish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-serbian.conllu Moses-swedish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-serbian.conllu data/Moses/Moses-swedish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-serbian.conllu Moses-turkish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-serbian.conllu data/Moses/Moses-turkish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-serbian.conllu Moses-urdu.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-serbian.conllu data/Moses/Moses-urdu.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-serbian.conllu Moses-vietnamese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-serbian.conllu data/Moses/Moses-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-finnish.conllu Moses-swedish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-finnish.conllu data/Moses/Moses-swedish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-finnish.conllu Moses-turkish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-finnish.conllu data/Moses/Moses-turkish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-finnish.conllu Moses-urdu.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-finnish.conllu data/Moses/Moses-urdu.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-finnish.conllu Moses-vietnamese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-finnish.conllu data/Moses/Moses-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-swedish.conllu Moses-turkish.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-swedish.conllu data/Moses/Moses-turkish.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-swedish.conllu Moses-urdu.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-swedish.conllu data/Moses/Moses-urdu.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-swedish.conllu Moses-vietnamese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-swedish.conllu data/Moses/Moses-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-turkish.conllu Moses-urdu.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-turkish.conllu data/Moses/Moses-urdu.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-turkish.conllu Moses-vietnamese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-turkish.conllu data/Moses/Moses-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-urdu.conllu Moses-vietnamese.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-urdu.conllu data/Moses/Moses-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-english.conllu Moses-french.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-english.conllu data/Moses/Moses-french.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-english.conllu Moses-indonesian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-english.conllu data/Moses/Moses-indonesian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-english.conllu Moses-italian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-english.conllu data/Moses/Moses-italian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-english.conllu Moses-slovenian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-english.conllu data/Moses/Moses-slovenian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-french.conllu Moses-indonesian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-french.conllu data/Moses/Moses-indonesian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-french.conllu Moses-italian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-french.conllu data/Moses/Moses-italian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-french.conllu Moses-slovenian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-french.conllu data/Moses/Moses-slovenian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-indonesian.conllu Moses-italian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-indonesian.conllu data/Moses/Moses-italian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-indonesian.conllu Moses-slovenian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-indonesian.conllu data/Moses/Moses-slovenian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
echo Moses-italian.conllu Moses-slovenian.conllu >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
gfud cosine-similarity data/Moses/Moses-italian.conllu data/Moses/Moses-slovenian.conllu DEPREL >> cosine-sim-per-topic/Moses-cosine-sim.txt ; 
} 
topic_combinations