#! /bin/bash 
function topic_combinations { 
echo Paris-north_sami.conllu Paris-scottish_gaelic.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-north_sami.conllu data/Paris/Paris-scottish_gaelic.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-north_sami.conllu Paris-gothic.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-north_sami.conllu data/Paris/Paris-gothic.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-north_sami.conllu Paris-old_church_slavonic.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-north_sami.conllu data/Paris/Paris-old_church_slavonic.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-north_sami.conllu Paris-telugu.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-north_sami.conllu data/Paris/Paris-telugu.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-north_sami.conllu Paris-uyghur.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-north_sami.conllu data/Paris/Paris-uyghur.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-north_sami.conllu Paris-classical_chinese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-north_sami.conllu data/Paris/Paris-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-north_sami.conllu Paris-wolof.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-north_sami.conllu data/Paris/Paris-wolof.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-scottish_gaelic.conllu Paris-gothic.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-scottish_gaelic.conllu data/Paris/Paris-gothic.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-scottish_gaelic.conllu Paris-old_church_slavonic.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-scottish_gaelic.conllu data/Paris/Paris-old_church_slavonic.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-scottish_gaelic.conllu Paris-telugu.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-scottish_gaelic.conllu data/Paris/Paris-telugu.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-scottish_gaelic.conllu Paris-uyghur.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-scottish_gaelic.conllu data/Paris/Paris-uyghur.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-scottish_gaelic.conllu Paris-classical_chinese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-scottish_gaelic.conllu data/Paris/Paris-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-scottish_gaelic.conllu Paris-wolof.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-scottish_gaelic.conllu data/Paris/Paris-wolof.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-gothic.conllu Paris-old_church_slavonic.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-gothic.conllu data/Paris/Paris-old_church_slavonic.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-gothic.conllu Paris-telugu.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-gothic.conllu data/Paris/Paris-telugu.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-gothic.conllu Paris-uyghur.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-gothic.conllu data/Paris/Paris-uyghur.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-gothic.conllu Paris-classical_chinese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-gothic.conllu data/Paris/Paris-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-gothic.conllu Paris-wolof.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-gothic.conllu data/Paris/Paris-wolof.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-old_church_slavonic.conllu Paris-telugu.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-old_church_slavonic.conllu data/Paris/Paris-telugu.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-old_church_slavonic.conllu Paris-uyghur.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-old_church_slavonic.conllu data/Paris/Paris-uyghur.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-old_church_slavonic.conllu Paris-classical_chinese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-old_church_slavonic.conllu data/Paris/Paris-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-old_church_slavonic.conllu Paris-wolof.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-old_church_slavonic.conllu data/Paris/Paris-wolof.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-telugu.conllu Paris-uyghur.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-telugu.conllu data/Paris/Paris-uyghur.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-telugu.conllu Paris-classical_chinese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-telugu.conllu data/Paris/Paris-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-telugu.conllu Paris-wolof.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-telugu.conllu data/Paris/Paris-wolof.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-uyghur.conllu Paris-classical_chinese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-uyghur.conllu data/Paris/Paris-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-uyghur.conllu Paris-wolof.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-uyghur.conllu data/Paris/Paris-wolof.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-classical_chinese.conllu Paris-wolof.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-classical_chinese.conllu data/Paris/Paris-wolof.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-welsh.conllu Paris-estonian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-welsh.conllu data/Paris/Paris-estonian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-welsh.conllu Paris-irish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-welsh.conllu data/Paris/Paris-irish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-welsh.conllu Paris-hindi.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-welsh.conllu data/Paris/Paris-hindi.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-welsh.conllu Paris-kazakh.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-welsh.conllu data/Paris/Paris-kazakh.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-welsh.conllu Paris-romanian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-welsh.conllu data/Paris/Paris-romanian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-welsh.conllu Paris-tamil.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-welsh.conllu data/Paris/Paris-tamil.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-welsh.conllu Paris-urdu.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-welsh.conllu data/Paris/Paris-urdu.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-estonian.conllu Paris-irish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-estonian.conllu data/Paris/Paris-irish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-estonian.conllu Paris-hindi.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-estonian.conllu data/Paris/Paris-hindi.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-estonian.conllu Paris-kazakh.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-estonian.conllu data/Paris/Paris-kazakh.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-estonian.conllu Paris-romanian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-estonian.conllu data/Paris/Paris-romanian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-estonian.conllu Paris-tamil.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-estonian.conllu data/Paris/Paris-tamil.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-estonian.conllu Paris-urdu.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-estonian.conllu data/Paris/Paris-urdu.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-irish.conllu Paris-hindi.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-irish.conllu data/Paris/Paris-hindi.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-irish.conllu Paris-kazakh.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-irish.conllu data/Paris/Paris-kazakh.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-irish.conllu Paris-romanian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-irish.conllu data/Paris/Paris-romanian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-irish.conllu Paris-tamil.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-irish.conllu data/Paris/Paris-tamil.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-irish.conllu Paris-urdu.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-irish.conllu data/Paris/Paris-urdu.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-hindi.conllu Paris-kazakh.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-hindi.conllu data/Paris/Paris-kazakh.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-hindi.conllu Paris-romanian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-hindi.conllu data/Paris/Paris-romanian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-hindi.conllu Paris-tamil.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-hindi.conllu data/Paris/Paris-tamil.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-hindi.conllu Paris-urdu.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-hindi.conllu data/Paris/Paris-urdu.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-kazakh.conllu Paris-romanian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-kazakh.conllu data/Paris/Paris-romanian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-kazakh.conllu Paris-tamil.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-kazakh.conllu data/Paris/Paris-tamil.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-kazakh.conllu Paris-urdu.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-kazakh.conllu data/Paris/Paris-urdu.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-romanian.conllu Paris-tamil.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-romanian.conllu data/Paris/Paris-tamil.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-romanian.conllu Paris-urdu.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-romanian.conllu data/Paris/Paris-urdu.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-tamil.conllu Paris-urdu.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-tamil.conllu data/Paris/Paris-urdu.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-belarusian.conllu Paris-greek.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-belarusian.conllu data/Paris/Paris-greek.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-belarusian.conllu Paris-spanish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-belarusian.conllu data/Paris/Paris-spanish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-belarusian.conllu Paris-basque.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-belarusian.conllu data/Paris/Paris-basque.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-belarusian.conllu Paris-galician.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-belarusian.conllu data/Paris/Paris-galician.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-belarusian.conllu Paris-korean.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-belarusian.conllu data/Paris/Paris-korean.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-belarusian.conllu Paris-latin.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-belarusian.conllu data/Paris/Paris-latin.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-belarusian.conllu Paris-latvian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-belarusian.conllu data/Paris/Paris-latvian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-belarusian.conllu Paris-lithuanian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-belarusian.conllu data/Paris/Paris-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-belarusian.conllu Paris-maltese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-belarusian.conllu data/Paris/Paris-maltese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-belarusian.conllu Paris-marathi.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-belarusian.conllu data/Paris/Paris-marathi.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-belarusian.conllu Paris-polish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-belarusian.conllu data/Paris/Paris-polish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-belarusian.conllu Paris-slovenian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-belarusian.conllu data/Paris/Paris-slovenian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-belarusian.conllu Paris-serbian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-belarusian.conllu data/Paris/Paris-serbian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-belarusian.conllu Paris-finnish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-belarusian.conllu data/Paris/Paris-finnish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-belarusian.conllu Paris-swedish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-belarusian.conllu data/Paris/Paris-swedish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-belarusian.conllu Paris-turkish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-belarusian.conllu data/Paris/Paris-turkish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-greek.conllu Paris-spanish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-greek.conllu data/Paris/Paris-spanish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-greek.conllu Paris-basque.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-greek.conllu data/Paris/Paris-basque.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-greek.conllu Paris-galician.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-greek.conllu data/Paris/Paris-galician.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-greek.conllu Paris-korean.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-greek.conllu data/Paris/Paris-korean.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-greek.conllu Paris-latin.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-greek.conllu data/Paris/Paris-latin.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-greek.conllu Paris-latvian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-greek.conllu data/Paris/Paris-latvian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-greek.conllu Paris-lithuanian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-greek.conllu data/Paris/Paris-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-greek.conllu Paris-maltese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-greek.conllu data/Paris/Paris-maltese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-greek.conllu Paris-marathi.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-greek.conllu data/Paris/Paris-marathi.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-greek.conllu Paris-polish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-greek.conllu data/Paris/Paris-polish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-greek.conllu Paris-slovenian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-greek.conllu data/Paris/Paris-slovenian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-greek.conllu Paris-serbian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-greek.conllu data/Paris/Paris-serbian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-greek.conllu Paris-finnish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-greek.conllu data/Paris/Paris-finnish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-greek.conllu Paris-swedish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-greek.conllu data/Paris/Paris-swedish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-greek.conllu Paris-turkish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-greek.conllu data/Paris/Paris-turkish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-spanish.conllu Paris-basque.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-spanish.conllu data/Paris/Paris-basque.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-spanish.conllu Paris-galician.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-spanish.conllu data/Paris/Paris-galician.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-spanish.conllu Paris-korean.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-spanish.conllu data/Paris/Paris-korean.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-spanish.conllu Paris-latin.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-spanish.conllu data/Paris/Paris-latin.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-spanish.conllu Paris-latvian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-spanish.conllu data/Paris/Paris-latvian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-spanish.conllu Paris-lithuanian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-spanish.conllu data/Paris/Paris-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-spanish.conllu Paris-maltese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-spanish.conllu data/Paris/Paris-maltese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-spanish.conllu Paris-marathi.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-spanish.conllu data/Paris/Paris-marathi.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-spanish.conllu Paris-polish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-spanish.conllu data/Paris/Paris-polish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-spanish.conllu Paris-slovenian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-spanish.conllu data/Paris/Paris-slovenian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-spanish.conllu Paris-serbian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-spanish.conllu data/Paris/Paris-serbian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-spanish.conllu Paris-finnish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-spanish.conllu data/Paris/Paris-finnish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-spanish.conllu Paris-swedish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-spanish.conllu data/Paris/Paris-swedish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-spanish.conllu Paris-turkish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-spanish.conllu data/Paris/Paris-turkish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-basque.conllu Paris-galician.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-basque.conllu data/Paris/Paris-galician.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-basque.conllu Paris-korean.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-basque.conllu data/Paris/Paris-korean.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-basque.conllu Paris-latin.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-basque.conllu data/Paris/Paris-latin.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-basque.conllu Paris-latvian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-basque.conllu data/Paris/Paris-latvian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-basque.conllu Paris-lithuanian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-basque.conllu data/Paris/Paris-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-basque.conllu Paris-maltese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-basque.conllu data/Paris/Paris-maltese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-basque.conllu Paris-marathi.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-basque.conllu data/Paris/Paris-marathi.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-basque.conllu Paris-polish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-basque.conllu data/Paris/Paris-polish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-basque.conllu Paris-slovenian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-basque.conllu data/Paris/Paris-slovenian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-basque.conllu Paris-serbian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-basque.conllu data/Paris/Paris-serbian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-basque.conllu Paris-finnish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-basque.conllu data/Paris/Paris-finnish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-basque.conllu Paris-swedish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-basque.conllu data/Paris/Paris-swedish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-basque.conllu Paris-turkish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-basque.conllu data/Paris/Paris-turkish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-galician.conllu Paris-korean.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-galician.conllu data/Paris/Paris-korean.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-galician.conllu Paris-latin.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-galician.conllu data/Paris/Paris-latin.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-galician.conllu Paris-latvian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-galician.conllu data/Paris/Paris-latvian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-galician.conllu Paris-lithuanian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-galician.conllu data/Paris/Paris-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-galician.conllu Paris-maltese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-galician.conllu data/Paris/Paris-maltese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-galician.conllu Paris-marathi.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-galician.conllu data/Paris/Paris-marathi.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-galician.conllu Paris-polish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-galician.conllu data/Paris/Paris-polish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-galician.conllu Paris-slovenian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-galician.conllu data/Paris/Paris-slovenian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-galician.conllu Paris-serbian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-galician.conllu data/Paris/Paris-serbian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-galician.conllu Paris-finnish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-galician.conllu data/Paris/Paris-finnish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-galician.conllu Paris-swedish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-galician.conllu data/Paris/Paris-swedish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-galician.conllu Paris-turkish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-galician.conllu data/Paris/Paris-turkish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-korean.conllu Paris-latin.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-korean.conllu data/Paris/Paris-latin.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-korean.conllu Paris-latvian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-korean.conllu data/Paris/Paris-latvian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-korean.conllu Paris-lithuanian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-korean.conllu data/Paris/Paris-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-korean.conllu Paris-maltese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-korean.conllu data/Paris/Paris-maltese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-korean.conllu Paris-marathi.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-korean.conllu data/Paris/Paris-marathi.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-korean.conllu Paris-polish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-korean.conllu data/Paris/Paris-polish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-korean.conllu Paris-slovenian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-korean.conllu data/Paris/Paris-slovenian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-korean.conllu Paris-serbian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-korean.conllu data/Paris/Paris-serbian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-korean.conllu Paris-finnish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-korean.conllu data/Paris/Paris-finnish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-korean.conllu Paris-swedish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-korean.conllu data/Paris/Paris-swedish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-korean.conllu Paris-turkish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-korean.conllu data/Paris/Paris-turkish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-latin.conllu Paris-latvian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-latin.conllu data/Paris/Paris-latvian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-latin.conllu Paris-lithuanian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-latin.conllu data/Paris/Paris-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-latin.conllu Paris-maltese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-latin.conllu data/Paris/Paris-maltese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-latin.conllu Paris-marathi.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-latin.conllu data/Paris/Paris-marathi.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-latin.conllu Paris-polish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-latin.conllu data/Paris/Paris-polish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-latin.conllu Paris-slovenian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-latin.conllu data/Paris/Paris-slovenian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-latin.conllu Paris-serbian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-latin.conllu data/Paris/Paris-serbian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-latin.conllu Paris-finnish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-latin.conllu data/Paris/Paris-finnish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-latin.conllu Paris-swedish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-latin.conllu data/Paris/Paris-swedish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-latin.conllu Paris-turkish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-latin.conllu data/Paris/Paris-turkish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-latvian.conllu Paris-lithuanian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-latvian.conllu data/Paris/Paris-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-latvian.conllu Paris-maltese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-latvian.conllu data/Paris/Paris-maltese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-latvian.conllu Paris-marathi.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-latvian.conllu data/Paris/Paris-marathi.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-latvian.conllu Paris-polish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-latvian.conllu data/Paris/Paris-polish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-latvian.conllu Paris-slovenian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-latvian.conllu data/Paris/Paris-slovenian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-latvian.conllu Paris-serbian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-latvian.conllu data/Paris/Paris-serbian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-latvian.conllu Paris-finnish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-latvian.conllu data/Paris/Paris-finnish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-latvian.conllu Paris-swedish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-latvian.conllu data/Paris/Paris-swedish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-latvian.conllu Paris-turkish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-latvian.conllu data/Paris/Paris-turkish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-lithuanian.conllu Paris-maltese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-lithuanian.conllu data/Paris/Paris-maltese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-lithuanian.conllu Paris-marathi.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-lithuanian.conllu data/Paris/Paris-marathi.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-lithuanian.conllu Paris-polish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-lithuanian.conllu data/Paris/Paris-polish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-lithuanian.conllu Paris-slovenian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-lithuanian.conllu data/Paris/Paris-slovenian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-lithuanian.conllu Paris-serbian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-lithuanian.conllu data/Paris/Paris-serbian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-lithuanian.conllu Paris-finnish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-lithuanian.conllu data/Paris/Paris-finnish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-lithuanian.conllu Paris-swedish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-lithuanian.conllu data/Paris/Paris-swedish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-lithuanian.conllu Paris-turkish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-lithuanian.conllu data/Paris/Paris-turkish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-maltese.conllu Paris-marathi.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-maltese.conllu data/Paris/Paris-marathi.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-maltese.conllu Paris-polish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-maltese.conllu data/Paris/Paris-polish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-maltese.conllu Paris-slovenian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-maltese.conllu data/Paris/Paris-slovenian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-maltese.conllu Paris-serbian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-maltese.conllu data/Paris/Paris-serbian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-maltese.conllu Paris-finnish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-maltese.conllu data/Paris/Paris-finnish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-maltese.conllu Paris-swedish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-maltese.conllu data/Paris/Paris-swedish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-maltese.conllu Paris-turkish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-maltese.conllu data/Paris/Paris-turkish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-marathi.conllu Paris-polish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-marathi.conllu data/Paris/Paris-polish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-marathi.conllu Paris-slovenian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-marathi.conllu data/Paris/Paris-slovenian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-marathi.conllu Paris-serbian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-marathi.conllu data/Paris/Paris-serbian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-marathi.conllu Paris-finnish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-marathi.conllu data/Paris/Paris-finnish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-marathi.conllu Paris-swedish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-marathi.conllu data/Paris/Paris-swedish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-marathi.conllu Paris-turkish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-marathi.conllu data/Paris/Paris-turkish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-polish.conllu Paris-slovenian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-polish.conllu data/Paris/Paris-slovenian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-polish.conllu Paris-serbian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-polish.conllu data/Paris/Paris-serbian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-polish.conllu Paris-finnish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-polish.conllu data/Paris/Paris-finnish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-polish.conllu Paris-swedish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-polish.conllu data/Paris/Paris-swedish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-polish.conllu Paris-turkish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-polish.conllu data/Paris/Paris-turkish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-slovenian.conllu Paris-serbian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-slovenian.conllu data/Paris/Paris-serbian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-slovenian.conllu Paris-finnish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-slovenian.conllu data/Paris/Paris-finnish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-slovenian.conllu Paris-swedish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-slovenian.conllu data/Paris/Paris-swedish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-slovenian.conllu Paris-turkish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-slovenian.conllu data/Paris/Paris-turkish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-serbian.conllu Paris-finnish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-serbian.conllu data/Paris/Paris-finnish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-serbian.conllu Paris-swedish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-serbian.conllu data/Paris/Paris-swedish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-serbian.conllu Paris-turkish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-serbian.conllu data/Paris/Paris-turkish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-finnish.conllu Paris-swedish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-finnish.conllu data/Paris/Paris-swedish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-finnish.conllu Paris-turkish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-finnish.conllu data/Paris/Paris-turkish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-swedish.conllu Paris-turkish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-swedish.conllu data/Paris/Paris-turkish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-afrikaans.conllu Paris-arabic.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-afrikaans.conllu data/Paris/Paris-arabic.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-afrikaans.conllu Paris-bulgarian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-afrikaans.conllu data/Paris/Paris-bulgarian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-afrikaans.conllu Paris-catalan.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-afrikaans.conllu data/Paris/Paris-catalan.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-afrikaans.conllu Paris-danish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-afrikaans.conllu data/Paris/Paris-danish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-afrikaans.conllu Paris-persian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-afrikaans.conllu data/Paris/Paris-persian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-afrikaans.conllu Paris-armenian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-afrikaans.conllu data/Paris/Paris-armenian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-afrikaans.conllu Paris-croatian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-afrikaans.conllu data/Paris/Paris-croatian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-afrikaans.conllu Paris-indonesian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-afrikaans.conllu data/Paris/Paris-indonesian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-afrikaans.conllu Paris-italian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-afrikaans.conllu data/Paris/Paris-italian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-afrikaans.conllu Paris-hungarian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-afrikaans.conllu data/Paris/Paris-hungarian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-afrikaans.conllu Paris-dutch.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-afrikaans.conllu data/Paris/Paris-dutch.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-afrikaans.conllu Paris-japanese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-afrikaans.conllu data/Paris/Paris-japanese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-afrikaans.conllu Paris-russian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-afrikaans.conllu data/Paris/Paris-russian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-afrikaans.conllu Paris-slovak.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-afrikaans.conllu data/Paris/Paris-slovak.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-afrikaans.conllu Paris-ukrainian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-afrikaans.conllu data/Paris/Paris-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-afrikaans.conllu Paris-chinese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-afrikaans.conllu data/Paris/Paris-chinese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-arabic.conllu Paris-bulgarian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-arabic.conllu data/Paris/Paris-bulgarian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-arabic.conllu Paris-catalan.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-arabic.conllu data/Paris/Paris-catalan.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-arabic.conllu Paris-danish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-arabic.conllu data/Paris/Paris-danish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-arabic.conllu Paris-persian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-arabic.conllu data/Paris/Paris-persian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-arabic.conllu Paris-armenian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-arabic.conllu data/Paris/Paris-armenian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-arabic.conllu Paris-croatian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-arabic.conllu data/Paris/Paris-croatian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-arabic.conllu Paris-indonesian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-arabic.conllu data/Paris/Paris-indonesian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-arabic.conllu Paris-italian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-arabic.conllu data/Paris/Paris-italian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-arabic.conllu Paris-hungarian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-arabic.conllu data/Paris/Paris-hungarian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-arabic.conllu Paris-dutch.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-arabic.conllu data/Paris/Paris-dutch.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-arabic.conllu Paris-japanese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-arabic.conllu data/Paris/Paris-japanese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-arabic.conllu Paris-russian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-arabic.conllu data/Paris/Paris-russian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-arabic.conllu Paris-slovak.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-arabic.conllu data/Paris/Paris-slovak.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-arabic.conllu Paris-ukrainian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-arabic.conllu data/Paris/Paris-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-arabic.conllu Paris-chinese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-arabic.conllu data/Paris/Paris-chinese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-bulgarian.conllu Paris-catalan.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-bulgarian.conllu data/Paris/Paris-catalan.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-bulgarian.conllu Paris-danish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-bulgarian.conllu data/Paris/Paris-danish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-bulgarian.conllu Paris-persian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-bulgarian.conllu data/Paris/Paris-persian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-bulgarian.conllu Paris-armenian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-bulgarian.conllu data/Paris/Paris-armenian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-bulgarian.conllu Paris-croatian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-bulgarian.conllu data/Paris/Paris-croatian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-bulgarian.conllu Paris-indonesian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-bulgarian.conllu data/Paris/Paris-indonesian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-bulgarian.conllu Paris-italian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-bulgarian.conllu data/Paris/Paris-italian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-bulgarian.conllu Paris-hungarian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-bulgarian.conllu data/Paris/Paris-hungarian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-bulgarian.conllu Paris-dutch.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-bulgarian.conllu data/Paris/Paris-dutch.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-bulgarian.conllu Paris-japanese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-bulgarian.conllu data/Paris/Paris-japanese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-bulgarian.conllu Paris-russian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-bulgarian.conllu data/Paris/Paris-russian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-bulgarian.conllu Paris-slovak.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-bulgarian.conllu data/Paris/Paris-slovak.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-bulgarian.conllu Paris-ukrainian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-bulgarian.conllu data/Paris/Paris-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-bulgarian.conllu Paris-chinese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-bulgarian.conllu data/Paris/Paris-chinese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-catalan.conllu Paris-danish.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-catalan.conllu data/Paris/Paris-danish.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-catalan.conllu Paris-persian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-catalan.conllu data/Paris/Paris-persian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-catalan.conllu Paris-armenian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-catalan.conllu data/Paris/Paris-armenian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-catalan.conllu Paris-croatian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-catalan.conllu data/Paris/Paris-croatian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-catalan.conllu Paris-indonesian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-catalan.conllu data/Paris/Paris-indonesian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-catalan.conllu Paris-italian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-catalan.conllu data/Paris/Paris-italian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-catalan.conllu Paris-hungarian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-catalan.conllu data/Paris/Paris-hungarian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-catalan.conllu Paris-dutch.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-catalan.conllu data/Paris/Paris-dutch.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-catalan.conllu Paris-japanese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-catalan.conllu data/Paris/Paris-japanese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-catalan.conllu Paris-russian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-catalan.conllu data/Paris/Paris-russian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-catalan.conllu Paris-slovak.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-catalan.conllu data/Paris/Paris-slovak.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-catalan.conllu Paris-ukrainian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-catalan.conllu data/Paris/Paris-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-catalan.conllu Paris-chinese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-catalan.conllu data/Paris/Paris-chinese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-danish.conllu Paris-persian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-danish.conllu data/Paris/Paris-persian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-danish.conllu Paris-armenian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-danish.conllu data/Paris/Paris-armenian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-danish.conllu Paris-croatian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-danish.conllu data/Paris/Paris-croatian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-danish.conllu Paris-indonesian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-danish.conllu data/Paris/Paris-indonesian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-danish.conllu Paris-italian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-danish.conllu data/Paris/Paris-italian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-danish.conllu Paris-hungarian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-danish.conllu data/Paris/Paris-hungarian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-danish.conllu Paris-dutch.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-danish.conllu data/Paris/Paris-dutch.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-danish.conllu Paris-japanese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-danish.conllu data/Paris/Paris-japanese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-danish.conllu Paris-russian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-danish.conllu data/Paris/Paris-russian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-danish.conllu Paris-slovak.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-danish.conllu data/Paris/Paris-slovak.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-danish.conllu Paris-ukrainian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-danish.conllu data/Paris/Paris-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-danish.conllu Paris-chinese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-danish.conllu data/Paris/Paris-chinese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-persian.conllu Paris-armenian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-persian.conllu data/Paris/Paris-armenian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-persian.conllu Paris-croatian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-persian.conllu data/Paris/Paris-croatian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-persian.conllu Paris-indonesian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-persian.conllu data/Paris/Paris-indonesian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-persian.conllu Paris-italian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-persian.conllu data/Paris/Paris-italian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-persian.conllu Paris-hungarian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-persian.conllu data/Paris/Paris-hungarian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-persian.conllu Paris-dutch.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-persian.conllu data/Paris/Paris-dutch.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-persian.conllu Paris-japanese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-persian.conllu data/Paris/Paris-japanese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-persian.conllu Paris-russian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-persian.conllu data/Paris/Paris-russian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-persian.conllu Paris-slovak.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-persian.conllu data/Paris/Paris-slovak.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-persian.conllu Paris-ukrainian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-persian.conllu data/Paris/Paris-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-persian.conllu Paris-chinese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-persian.conllu data/Paris/Paris-chinese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-armenian.conllu Paris-croatian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-armenian.conllu data/Paris/Paris-croatian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-armenian.conllu Paris-indonesian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-armenian.conllu data/Paris/Paris-indonesian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-armenian.conllu Paris-italian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-armenian.conllu data/Paris/Paris-italian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-armenian.conllu Paris-hungarian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-armenian.conllu data/Paris/Paris-hungarian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-armenian.conllu Paris-dutch.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-armenian.conllu data/Paris/Paris-dutch.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-armenian.conllu Paris-japanese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-armenian.conllu data/Paris/Paris-japanese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-armenian.conllu Paris-russian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-armenian.conllu data/Paris/Paris-russian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-armenian.conllu Paris-slovak.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-armenian.conllu data/Paris/Paris-slovak.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-armenian.conllu Paris-ukrainian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-armenian.conllu data/Paris/Paris-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-armenian.conllu Paris-chinese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-armenian.conllu data/Paris/Paris-chinese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-croatian.conllu Paris-indonesian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-croatian.conllu data/Paris/Paris-indonesian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-croatian.conllu Paris-italian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-croatian.conllu data/Paris/Paris-italian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-croatian.conllu Paris-hungarian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-croatian.conllu data/Paris/Paris-hungarian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-croatian.conllu Paris-dutch.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-croatian.conllu data/Paris/Paris-dutch.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-croatian.conllu Paris-japanese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-croatian.conllu data/Paris/Paris-japanese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-croatian.conllu Paris-russian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-croatian.conllu data/Paris/Paris-russian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-croatian.conllu Paris-slovak.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-croatian.conllu data/Paris/Paris-slovak.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-croatian.conllu Paris-ukrainian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-croatian.conllu data/Paris/Paris-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-croatian.conllu Paris-chinese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-croatian.conllu data/Paris/Paris-chinese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-indonesian.conllu Paris-italian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-indonesian.conllu data/Paris/Paris-italian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-indonesian.conllu Paris-hungarian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-indonesian.conllu data/Paris/Paris-hungarian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-indonesian.conllu Paris-dutch.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-indonesian.conllu data/Paris/Paris-dutch.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-indonesian.conllu Paris-japanese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-indonesian.conllu data/Paris/Paris-japanese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-indonesian.conllu Paris-russian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-indonesian.conllu data/Paris/Paris-russian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-indonesian.conllu Paris-slovak.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-indonesian.conllu data/Paris/Paris-slovak.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-indonesian.conllu Paris-ukrainian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-indonesian.conllu data/Paris/Paris-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-indonesian.conllu Paris-chinese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-indonesian.conllu data/Paris/Paris-chinese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-italian.conllu Paris-hungarian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-italian.conllu data/Paris/Paris-hungarian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-italian.conllu Paris-dutch.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-italian.conllu data/Paris/Paris-dutch.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-italian.conllu Paris-japanese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-italian.conllu data/Paris/Paris-japanese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-italian.conllu Paris-russian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-italian.conllu data/Paris/Paris-russian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-italian.conllu Paris-slovak.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-italian.conllu data/Paris/Paris-slovak.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-italian.conllu Paris-ukrainian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-italian.conllu data/Paris/Paris-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-italian.conllu Paris-chinese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-italian.conllu data/Paris/Paris-chinese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-hungarian.conllu Paris-dutch.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-hungarian.conllu data/Paris/Paris-dutch.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-hungarian.conllu Paris-japanese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-hungarian.conllu data/Paris/Paris-japanese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-hungarian.conllu Paris-russian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-hungarian.conllu data/Paris/Paris-russian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-hungarian.conllu Paris-slovak.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-hungarian.conllu data/Paris/Paris-slovak.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-hungarian.conllu Paris-ukrainian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-hungarian.conllu data/Paris/Paris-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-hungarian.conllu Paris-chinese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-hungarian.conllu data/Paris/Paris-chinese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-dutch.conllu Paris-japanese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-dutch.conllu data/Paris/Paris-japanese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-dutch.conllu Paris-russian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-dutch.conllu data/Paris/Paris-russian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-dutch.conllu Paris-slovak.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-dutch.conllu data/Paris/Paris-slovak.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-dutch.conllu Paris-ukrainian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-dutch.conllu data/Paris/Paris-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-dutch.conllu Paris-chinese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-dutch.conllu data/Paris/Paris-chinese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-japanese.conllu Paris-russian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-japanese.conllu data/Paris/Paris-russian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-japanese.conllu Paris-slovak.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-japanese.conllu data/Paris/Paris-slovak.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-japanese.conllu Paris-ukrainian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-japanese.conllu data/Paris/Paris-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-japanese.conllu Paris-chinese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-japanese.conllu data/Paris/Paris-chinese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-russian.conllu Paris-slovak.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-russian.conllu data/Paris/Paris-slovak.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-russian.conllu Paris-ukrainian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-russian.conllu data/Paris/Paris-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-russian.conllu Paris-chinese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-russian.conllu data/Paris/Paris-chinese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-slovak.conllu Paris-ukrainian.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-slovak.conllu data/Paris/Paris-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-slovak.conllu Paris-chinese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-slovak.conllu data/Paris/Paris-chinese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-ukrainian.conllu Paris-chinese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-ukrainian.conllu data/Paris/Paris-chinese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-english.conllu Paris-czech.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-english.conllu data/Paris/Paris-czech.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-english.conllu Paris-german.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-english.conllu data/Paris/Paris-german.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-english.conllu Paris-french.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-english.conllu data/Paris/Paris-french.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-english.conllu Paris-hebrew.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-english.conllu data/Paris/Paris-hebrew.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-english.conllu Paris-portuguese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-english.conllu data/Paris/Paris-portuguese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-english.conllu Paris-vietnamese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-english.conllu data/Paris/Paris-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-czech.conllu Paris-german.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-czech.conllu data/Paris/Paris-german.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-czech.conllu Paris-french.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-czech.conllu data/Paris/Paris-french.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-czech.conllu Paris-hebrew.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-czech.conllu data/Paris/Paris-hebrew.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-czech.conllu Paris-portuguese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-czech.conllu data/Paris/Paris-portuguese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-czech.conllu Paris-vietnamese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-czech.conllu data/Paris/Paris-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-german.conllu Paris-french.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-german.conllu data/Paris/Paris-french.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-german.conllu Paris-hebrew.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-german.conllu data/Paris/Paris-hebrew.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-german.conllu Paris-portuguese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-german.conllu data/Paris/Paris-portuguese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-german.conllu Paris-vietnamese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-german.conllu data/Paris/Paris-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-french.conllu Paris-hebrew.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-french.conllu data/Paris/Paris-hebrew.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-french.conllu Paris-portuguese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-french.conllu data/Paris/Paris-portuguese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-french.conllu Paris-vietnamese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-french.conllu data/Paris/Paris-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-hebrew.conllu Paris-portuguese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-hebrew.conllu data/Paris/Paris-portuguese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-hebrew.conllu Paris-vietnamese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-hebrew.conllu data/Paris/Paris-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
echo Paris-portuguese.conllu Paris-vietnamese.conllu >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
gfud cosine-similarity data/Paris/Paris-portuguese.conllu data/Paris/Paris-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Paris-cosine-sim.txt ; 
} 
topic_combinations