#! /bin/bash 
function topic_combinations { 
echo Rice-belarusian.conllu Rice-welsh.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-belarusian.conllu data/Rice/Rice-welsh.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-belarusian.conllu Rice-greek.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-belarusian.conllu data/Rice/Rice-greek.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-belarusian.conllu Rice-irish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-belarusian.conllu data/Rice/Rice-irish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-belarusian.conllu Rice-latin.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-belarusian.conllu data/Rice/Rice-latin.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-belarusian.conllu Rice-lithuanian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-belarusian.conllu data/Rice/Rice-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-belarusian.conllu Rice-polish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-belarusian.conllu data/Rice/Rice-polish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-belarusian.conllu Rice-romanian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-belarusian.conllu data/Rice/Rice-romanian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-belarusian.conllu Rice-slovak.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-belarusian.conllu data/Rice/Rice-slovak.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-welsh.conllu Rice-greek.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-welsh.conllu data/Rice/Rice-greek.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-welsh.conllu Rice-irish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-welsh.conllu data/Rice/Rice-irish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-welsh.conllu Rice-latin.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-welsh.conllu data/Rice/Rice-latin.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-welsh.conllu Rice-lithuanian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-welsh.conllu data/Rice/Rice-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-welsh.conllu Rice-polish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-welsh.conllu data/Rice/Rice-polish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-welsh.conllu Rice-romanian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-welsh.conllu data/Rice/Rice-romanian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-welsh.conllu Rice-slovak.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-welsh.conllu data/Rice/Rice-slovak.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-greek.conllu Rice-irish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-greek.conllu data/Rice/Rice-irish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-greek.conllu Rice-latin.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-greek.conllu data/Rice/Rice-latin.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-greek.conllu Rice-lithuanian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-greek.conllu data/Rice/Rice-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-greek.conllu Rice-polish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-greek.conllu data/Rice/Rice-polish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-greek.conllu Rice-romanian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-greek.conllu data/Rice/Rice-romanian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-greek.conllu Rice-slovak.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-greek.conllu data/Rice/Rice-slovak.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-irish.conllu Rice-latin.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-irish.conllu data/Rice/Rice-latin.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-irish.conllu Rice-lithuanian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-irish.conllu data/Rice/Rice-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-irish.conllu Rice-polish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-irish.conllu data/Rice/Rice-polish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-irish.conllu Rice-romanian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-irish.conllu data/Rice/Rice-romanian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-irish.conllu Rice-slovak.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-irish.conllu data/Rice/Rice-slovak.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-latin.conllu Rice-lithuanian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-latin.conllu data/Rice/Rice-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-latin.conllu Rice-polish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-latin.conllu data/Rice/Rice-polish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-latin.conllu Rice-romanian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-latin.conllu data/Rice/Rice-romanian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-latin.conllu Rice-slovak.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-latin.conllu data/Rice/Rice-slovak.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-lithuanian.conllu Rice-polish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-lithuanian.conllu data/Rice/Rice-polish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-lithuanian.conllu Rice-romanian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-lithuanian.conllu data/Rice/Rice-romanian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-lithuanian.conllu Rice-slovak.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-lithuanian.conllu data/Rice/Rice-slovak.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-polish.conllu Rice-romanian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-polish.conllu data/Rice/Rice-romanian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-polish.conllu Rice-slovak.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-polish.conllu data/Rice/Rice-slovak.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-romanian.conllu Rice-slovak.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-romanian.conllu data/Rice/Rice-slovak.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-afrikaans.conllu Rice-arabic.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-afrikaans.conllu data/Rice/Rice-arabic.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-afrikaans.conllu Rice-danish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-afrikaans.conllu data/Rice/Rice-danish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-afrikaans.conllu Rice-estonian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-afrikaans.conllu data/Rice/Rice-estonian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-afrikaans.conllu Rice-galician.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-afrikaans.conllu data/Rice/Rice-galician.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-afrikaans.conllu Rice-korean.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-afrikaans.conllu data/Rice/Rice-korean.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-afrikaans.conllu Rice-armenian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-afrikaans.conllu data/Rice/Rice-armenian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-afrikaans.conllu Rice-hindi.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-afrikaans.conllu data/Rice/Rice-hindi.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-afrikaans.conllu Rice-croatian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-afrikaans.conllu data/Rice/Rice-croatian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-afrikaans.conllu Rice-indonesian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-afrikaans.conllu data/Rice/Rice-indonesian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-afrikaans.conllu Rice-hebrew.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-afrikaans.conllu data/Rice/Rice-hebrew.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-afrikaans.conllu Rice-latvian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-afrikaans.conllu data/Rice/Rice-latvian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-afrikaans.conllu Rice-hungarian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-afrikaans.conllu data/Rice/Rice-hungarian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-afrikaans.conllu Rice-marathi.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-afrikaans.conllu data/Rice/Rice-marathi.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-afrikaans.conllu Rice-dutch.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-afrikaans.conllu data/Rice/Rice-dutch.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-afrikaans.conllu Rice-portuguese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-afrikaans.conllu data/Rice/Rice-portuguese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-afrikaans.conllu Rice-sanskrit.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-afrikaans.conllu data/Rice/Rice-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-afrikaans.conllu Rice-finnish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-afrikaans.conllu data/Rice/Rice-finnish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-afrikaans.conllu Rice-telugu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-afrikaans.conllu data/Rice/Rice-telugu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-afrikaans.conllu Rice-turkish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-afrikaans.conllu data/Rice/Rice-turkish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-afrikaans.conllu Rice-urdu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-afrikaans.conllu data/Rice/Rice-urdu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-arabic.conllu Rice-danish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-arabic.conllu data/Rice/Rice-danish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-arabic.conllu Rice-estonian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-arabic.conllu data/Rice/Rice-estonian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-arabic.conllu Rice-galician.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-arabic.conllu data/Rice/Rice-galician.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-arabic.conllu Rice-korean.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-arabic.conllu data/Rice/Rice-korean.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-arabic.conllu Rice-armenian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-arabic.conllu data/Rice/Rice-armenian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-arabic.conllu Rice-hindi.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-arabic.conllu data/Rice/Rice-hindi.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-arabic.conllu Rice-croatian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-arabic.conllu data/Rice/Rice-croatian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-arabic.conllu Rice-indonesian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-arabic.conllu data/Rice/Rice-indonesian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-arabic.conllu Rice-hebrew.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-arabic.conllu data/Rice/Rice-hebrew.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-arabic.conllu Rice-latvian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-arabic.conllu data/Rice/Rice-latvian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-arabic.conllu Rice-hungarian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-arabic.conllu data/Rice/Rice-hungarian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-arabic.conllu Rice-marathi.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-arabic.conllu data/Rice/Rice-marathi.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-arabic.conllu Rice-dutch.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-arabic.conllu data/Rice/Rice-dutch.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-arabic.conllu Rice-portuguese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-arabic.conllu data/Rice/Rice-portuguese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-arabic.conllu Rice-sanskrit.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-arabic.conllu data/Rice/Rice-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-arabic.conllu Rice-finnish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-arabic.conllu data/Rice/Rice-finnish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-arabic.conllu Rice-telugu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-arabic.conllu data/Rice/Rice-telugu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-arabic.conllu Rice-turkish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-arabic.conllu data/Rice/Rice-turkish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-arabic.conllu Rice-urdu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-arabic.conllu data/Rice/Rice-urdu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-danish.conllu Rice-estonian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-danish.conllu data/Rice/Rice-estonian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-danish.conllu Rice-galician.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-danish.conllu data/Rice/Rice-galician.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-danish.conllu Rice-korean.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-danish.conllu data/Rice/Rice-korean.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-danish.conllu Rice-armenian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-danish.conllu data/Rice/Rice-armenian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-danish.conllu Rice-hindi.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-danish.conllu data/Rice/Rice-hindi.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-danish.conllu Rice-croatian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-danish.conllu data/Rice/Rice-croatian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-danish.conllu Rice-indonesian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-danish.conllu data/Rice/Rice-indonesian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-danish.conllu Rice-hebrew.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-danish.conllu data/Rice/Rice-hebrew.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-danish.conllu Rice-latvian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-danish.conllu data/Rice/Rice-latvian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-danish.conllu Rice-hungarian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-danish.conllu data/Rice/Rice-hungarian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-danish.conllu Rice-marathi.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-danish.conllu data/Rice/Rice-marathi.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-danish.conllu Rice-dutch.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-danish.conllu data/Rice/Rice-dutch.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-danish.conllu Rice-portuguese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-danish.conllu data/Rice/Rice-portuguese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-danish.conllu Rice-sanskrit.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-danish.conllu data/Rice/Rice-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-danish.conllu Rice-finnish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-danish.conllu data/Rice/Rice-finnish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-danish.conllu Rice-telugu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-danish.conllu data/Rice/Rice-telugu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-danish.conllu Rice-turkish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-danish.conllu data/Rice/Rice-turkish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-danish.conllu Rice-urdu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-danish.conllu data/Rice/Rice-urdu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-estonian.conllu Rice-galician.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-estonian.conllu data/Rice/Rice-galician.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-estonian.conllu Rice-korean.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-estonian.conllu data/Rice/Rice-korean.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-estonian.conllu Rice-armenian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-estonian.conllu data/Rice/Rice-armenian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-estonian.conllu Rice-hindi.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-estonian.conllu data/Rice/Rice-hindi.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-estonian.conllu Rice-croatian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-estonian.conllu data/Rice/Rice-croatian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-estonian.conllu Rice-indonesian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-estonian.conllu data/Rice/Rice-indonesian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-estonian.conllu Rice-hebrew.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-estonian.conllu data/Rice/Rice-hebrew.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-estonian.conllu Rice-latvian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-estonian.conllu data/Rice/Rice-latvian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-estonian.conllu Rice-hungarian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-estonian.conllu data/Rice/Rice-hungarian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-estonian.conllu Rice-marathi.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-estonian.conllu data/Rice/Rice-marathi.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-estonian.conllu Rice-dutch.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-estonian.conllu data/Rice/Rice-dutch.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-estonian.conllu Rice-portuguese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-estonian.conllu data/Rice/Rice-portuguese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-estonian.conllu Rice-sanskrit.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-estonian.conllu data/Rice/Rice-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-estonian.conllu Rice-finnish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-estonian.conllu data/Rice/Rice-finnish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-estonian.conllu Rice-telugu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-estonian.conllu data/Rice/Rice-telugu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-estonian.conllu Rice-turkish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-estonian.conllu data/Rice/Rice-turkish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-estonian.conllu Rice-urdu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-estonian.conllu data/Rice/Rice-urdu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-galician.conllu Rice-korean.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-galician.conllu data/Rice/Rice-korean.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-galician.conllu Rice-armenian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-galician.conllu data/Rice/Rice-armenian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-galician.conllu Rice-hindi.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-galician.conllu data/Rice/Rice-hindi.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-galician.conllu Rice-croatian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-galician.conllu data/Rice/Rice-croatian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-galician.conllu Rice-indonesian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-galician.conllu data/Rice/Rice-indonesian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-galician.conllu Rice-hebrew.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-galician.conllu data/Rice/Rice-hebrew.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-galician.conllu Rice-latvian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-galician.conllu data/Rice/Rice-latvian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-galician.conllu Rice-hungarian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-galician.conllu data/Rice/Rice-hungarian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-galician.conllu Rice-marathi.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-galician.conllu data/Rice/Rice-marathi.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-galician.conllu Rice-dutch.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-galician.conllu data/Rice/Rice-dutch.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-galician.conllu Rice-portuguese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-galician.conllu data/Rice/Rice-portuguese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-galician.conllu Rice-sanskrit.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-galician.conllu data/Rice/Rice-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-galician.conllu Rice-finnish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-galician.conllu data/Rice/Rice-finnish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-galician.conllu Rice-telugu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-galician.conllu data/Rice/Rice-telugu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-galician.conllu Rice-turkish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-galician.conllu data/Rice/Rice-turkish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-galician.conllu Rice-urdu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-galician.conllu data/Rice/Rice-urdu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-korean.conllu Rice-armenian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-korean.conllu data/Rice/Rice-armenian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-korean.conllu Rice-hindi.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-korean.conllu data/Rice/Rice-hindi.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-korean.conllu Rice-croatian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-korean.conllu data/Rice/Rice-croatian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-korean.conllu Rice-indonesian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-korean.conllu data/Rice/Rice-indonesian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-korean.conllu Rice-hebrew.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-korean.conllu data/Rice/Rice-hebrew.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-korean.conllu Rice-latvian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-korean.conllu data/Rice/Rice-latvian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-korean.conllu Rice-hungarian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-korean.conllu data/Rice/Rice-hungarian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-korean.conllu Rice-marathi.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-korean.conllu data/Rice/Rice-marathi.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-korean.conllu Rice-dutch.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-korean.conllu data/Rice/Rice-dutch.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-korean.conllu Rice-portuguese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-korean.conllu data/Rice/Rice-portuguese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-korean.conllu Rice-sanskrit.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-korean.conllu data/Rice/Rice-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-korean.conllu Rice-finnish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-korean.conllu data/Rice/Rice-finnish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-korean.conllu Rice-telugu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-korean.conllu data/Rice/Rice-telugu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-korean.conllu Rice-turkish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-korean.conllu data/Rice/Rice-turkish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-korean.conllu Rice-urdu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-korean.conllu data/Rice/Rice-urdu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-armenian.conllu Rice-hindi.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-armenian.conllu data/Rice/Rice-hindi.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-armenian.conllu Rice-croatian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-armenian.conllu data/Rice/Rice-croatian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-armenian.conllu Rice-indonesian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-armenian.conllu data/Rice/Rice-indonesian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-armenian.conllu Rice-hebrew.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-armenian.conllu data/Rice/Rice-hebrew.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-armenian.conllu Rice-latvian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-armenian.conllu data/Rice/Rice-latvian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-armenian.conllu Rice-hungarian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-armenian.conllu data/Rice/Rice-hungarian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-armenian.conllu Rice-marathi.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-armenian.conllu data/Rice/Rice-marathi.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-armenian.conllu Rice-dutch.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-armenian.conllu data/Rice/Rice-dutch.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-armenian.conllu Rice-portuguese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-armenian.conllu data/Rice/Rice-portuguese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-armenian.conllu Rice-sanskrit.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-armenian.conllu data/Rice/Rice-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-armenian.conllu Rice-finnish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-armenian.conllu data/Rice/Rice-finnish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-armenian.conllu Rice-telugu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-armenian.conllu data/Rice/Rice-telugu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-armenian.conllu Rice-turkish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-armenian.conllu data/Rice/Rice-turkish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-armenian.conllu Rice-urdu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-armenian.conllu data/Rice/Rice-urdu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-hindi.conllu Rice-croatian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-hindi.conllu data/Rice/Rice-croatian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-hindi.conllu Rice-indonesian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-hindi.conllu data/Rice/Rice-indonesian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-hindi.conllu Rice-hebrew.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-hindi.conllu data/Rice/Rice-hebrew.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-hindi.conllu Rice-latvian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-hindi.conllu data/Rice/Rice-latvian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-hindi.conllu Rice-hungarian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-hindi.conllu data/Rice/Rice-hungarian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-hindi.conllu Rice-marathi.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-hindi.conllu data/Rice/Rice-marathi.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-hindi.conllu Rice-dutch.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-hindi.conllu data/Rice/Rice-dutch.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-hindi.conllu Rice-portuguese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-hindi.conllu data/Rice/Rice-portuguese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-hindi.conllu Rice-sanskrit.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-hindi.conllu data/Rice/Rice-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-hindi.conllu Rice-finnish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-hindi.conllu data/Rice/Rice-finnish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-hindi.conllu Rice-telugu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-hindi.conllu data/Rice/Rice-telugu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-hindi.conllu Rice-turkish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-hindi.conllu data/Rice/Rice-turkish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-hindi.conllu Rice-urdu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-hindi.conllu data/Rice/Rice-urdu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-croatian.conllu Rice-indonesian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-croatian.conllu data/Rice/Rice-indonesian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-croatian.conllu Rice-hebrew.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-croatian.conllu data/Rice/Rice-hebrew.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-croatian.conllu Rice-latvian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-croatian.conllu data/Rice/Rice-latvian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-croatian.conllu Rice-hungarian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-croatian.conllu data/Rice/Rice-hungarian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-croatian.conllu Rice-marathi.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-croatian.conllu data/Rice/Rice-marathi.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-croatian.conllu Rice-dutch.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-croatian.conllu data/Rice/Rice-dutch.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-croatian.conllu Rice-portuguese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-croatian.conllu data/Rice/Rice-portuguese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-croatian.conllu Rice-sanskrit.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-croatian.conllu data/Rice/Rice-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-croatian.conllu Rice-finnish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-croatian.conllu data/Rice/Rice-finnish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-croatian.conllu Rice-telugu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-croatian.conllu data/Rice/Rice-telugu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-croatian.conllu Rice-turkish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-croatian.conllu data/Rice/Rice-turkish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-croatian.conllu Rice-urdu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-croatian.conllu data/Rice/Rice-urdu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-indonesian.conllu Rice-hebrew.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-indonesian.conllu data/Rice/Rice-hebrew.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-indonesian.conllu Rice-latvian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-indonesian.conllu data/Rice/Rice-latvian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-indonesian.conllu Rice-hungarian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-indonesian.conllu data/Rice/Rice-hungarian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-indonesian.conllu Rice-marathi.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-indonesian.conllu data/Rice/Rice-marathi.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-indonesian.conllu Rice-dutch.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-indonesian.conllu data/Rice/Rice-dutch.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-indonesian.conllu Rice-portuguese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-indonesian.conllu data/Rice/Rice-portuguese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-indonesian.conllu Rice-sanskrit.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-indonesian.conllu data/Rice/Rice-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-indonesian.conllu Rice-finnish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-indonesian.conllu data/Rice/Rice-finnish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-indonesian.conllu Rice-telugu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-indonesian.conllu data/Rice/Rice-telugu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-indonesian.conllu Rice-turkish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-indonesian.conllu data/Rice/Rice-turkish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-indonesian.conllu Rice-urdu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-indonesian.conllu data/Rice/Rice-urdu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-hebrew.conllu Rice-latvian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-hebrew.conllu data/Rice/Rice-latvian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-hebrew.conllu Rice-hungarian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-hebrew.conllu data/Rice/Rice-hungarian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-hebrew.conllu Rice-marathi.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-hebrew.conllu data/Rice/Rice-marathi.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-hebrew.conllu Rice-dutch.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-hebrew.conllu data/Rice/Rice-dutch.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-hebrew.conllu Rice-portuguese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-hebrew.conllu data/Rice/Rice-portuguese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-hebrew.conllu Rice-sanskrit.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-hebrew.conllu data/Rice/Rice-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-hebrew.conllu Rice-finnish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-hebrew.conllu data/Rice/Rice-finnish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-hebrew.conllu Rice-telugu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-hebrew.conllu data/Rice/Rice-telugu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-hebrew.conllu Rice-turkish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-hebrew.conllu data/Rice/Rice-turkish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-hebrew.conllu Rice-urdu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-hebrew.conllu data/Rice/Rice-urdu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-latvian.conllu Rice-hungarian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-latvian.conllu data/Rice/Rice-hungarian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-latvian.conllu Rice-marathi.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-latvian.conllu data/Rice/Rice-marathi.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-latvian.conllu Rice-dutch.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-latvian.conllu data/Rice/Rice-dutch.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-latvian.conllu Rice-portuguese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-latvian.conllu data/Rice/Rice-portuguese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-latvian.conllu Rice-sanskrit.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-latvian.conllu data/Rice/Rice-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-latvian.conllu Rice-finnish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-latvian.conllu data/Rice/Rice-finnish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-latvian.conllu Rice-telugu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-latvian.conllu data/Rice/Rice-telugu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-latvian.conllu Rice-turkish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-latvian.conllu data/Rice/Rice-turkish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-latvian.conllu Rice-urdu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-latvian.conllu data/Rice/Rice-urdu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-hungarian.conllu Rice-marathi.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-hungarian.conllu data/Rice/Rice-marathi.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-hungarian.conllu Rice-dutch.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-hungarian.conllu data/Rice/Rice-dutch.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-hungarian.conllu Rice-portuguese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-hungarian.conllu data/Rice/Rice-portuguese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-hungarian.conllu Rice-sanskrit.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-hungarian.conllu data/Rice/Rice-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-hungarian.conllu Rice-finnish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-hungarian.conllu data/Rice/Rice-finnish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-hungarian.conllu Rice-telugu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-hungarian.conllu data/Rice/Rice-telugu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-hungarian.conllu Rice-turkish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-hungarian.conllu data/Rice/Rice-turkish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-hungarian.conllu Rice-urdu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-hungarian.conllu data/Rice/Rice-urdu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-marathi.conllu Rice-dutch.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-marathi.conllu data/Rice/Rice-dutch.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-marathi.conllu Rice-portuguese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-marathi.conllu data/Rice/Rice-portuguese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-marathi.conllu Rice-sanskrit.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-marathi.conllu data/Rice/Rice-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-marathi.conllu Rice-finnish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-marathi.conllu data/Rice/Rice-finnish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-marathi.conllu Rice-telugu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-marathi.conllu data/Rice/Rice-telugu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-marathi.conllu Rice-turkish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-marathi.conllu data/Rice/Rice-turkish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-marathi.conllu Rice-urdu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-marathi.conllu data/Rice/Rice-urdu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-dutch.conllu Rice-portuguese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-dutch.conllu data/Rice/Rice-portuguese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-dutch.conllu Rice-sanskrit.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-dutch.conllu data/Rice/Rice-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-dutch.conllu Rice-finnish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-dutch.conllu data/Rice/Rice-finnish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-dutch.conllu Rice-telugu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-dutch.conllu data/Rice/Rice-telugu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-dutch.conllu Rice-turkish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-dutch.conllu data/Rice/Rice-turkish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-dutch.conllu Rice-urdu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-dutch.conllu data/Rice/Rice-urdu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-portuguese.conllu Rice-sanskrit.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-portuguese.conllu data/Rice/Rice-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-portuguese.conllu Rice-finnish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-portuguese.conllu data/Rice/Rice-finnish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-portuguese.conllu Rice-telugu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-portuguese.conllu data/Rice/Rice-telugu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-portuguese.conllu Rice-turkish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-portuguese.conllu data/Rice/Rice-turkish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-portuguese.conllu Rice-urdu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-portuguese.conllu data/Rice/Rice-urdu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-sanskrit.conllu Rice-finnish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-sanskrit.conllu data/Rice/Rice-finnish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-sanskrit.conllu Rice-telugu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-sanskrit.conllu data/Rice/Rice-telugu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-sanskrit.conllu Rice-turkish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-sanskrit.conllu data/Rice/Rice-turkish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-sanskrit.conllu Rice-urdu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-sanskrit.conllu data/Rice/Rice-urdu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-finnish.conllu Rice-telugu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-finnish.conllu data/Rice/Rice-telugu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-finnish.conllu Rice-turkish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-finnish.conllu data/Rice/Rice-turkish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-finnish.conllu Rice-urdu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-finnish.conllu data/Rice/Rice-urdu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-telugu.conllu Rice-turkish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-telugu.conllu data/Rice/Rice-turkish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-telugu.conllu Rice-urdu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-telugu.conllu data/Rice/Rice-urdu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-turkish.conllu Rice-urdu.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-turkish.conllu data/Rice/Rice-urdu.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-bulgarian.conllu Rice-catalan.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-bulgarian.conllu data/Rice/Rice-catalan.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-bulgarian.conllu Rice-czech.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-bulgarian.conllu data/Rice/Rice-czech.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-bulgarian.conllu Rice-spanish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-bulgarian.conllu data/Rice/Rice-spanish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-bulgarian.conllu Rice-basque.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-bulgarian.conllu data/Rice/Rice-basque.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-bulgarian.conllu Rice-persian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-bulgarian.conllu data/Rice/Rice-persian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-bulgarian.conllu Rice-french.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-bulgarian.conllu data/Rice/Rice-french.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-bulgarian.conllu Rice-italian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-bulgarian.conllu data/Rice/Rice-italian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-bulgarian.conllu Rice-kazakh.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-bulgarian.conllu data/Rice/Rice-kazakh.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-bulgarian.conllu Rice-russian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-bulgarian.conllu data/Rice/Rice-russian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-bulgarian.conllu Rice-slovenian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-bulgarian.conllu data/Rice/Rice-slovenian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-bulgarian.conllu Rice-serbian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-bulgarian.conllu data/Rice/Rice-serbian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-bulgarian.conllu Rice-swedish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-bulgarian.conllu data/Rice/Rice-swedish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-bulgarian.conllu Rice-tamil.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-bulgarian.conllu data/Rice/Rice-tamil.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-bulgarian.conllu Rice-ukrainian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-bulgarian.conllu data/Rice/Rice-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-bulgarian.conllu Rice-vietnamese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-bulgarian.conllu data/Rice/Rice-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-bulgarian.conllu Rice-classical_chinese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-bulgarian.conllu data/Rice/Rice-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-bulgarian.conllu Rice-chinese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-bulgarian.conllu data/Rice/Rice-chinese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-catalan.conllu Rice-czech.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-catalan.conllu data/Rice/Rice-czech.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-catalan.conllu Rice-spanish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-catalan.conllu data/Rice/Rice-spanish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-catalan.conllu Rice-basque.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-catalan.conllu data/Rice/Rice-basque.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-catalan.conllu Rice-persian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-catalan.conllu data/Rice/Rice-persian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-catalan.conllu Rice-french.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-catalan.conllu data/Rice/Rice-french.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-catalan.conllu Rice-italian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-catalan.conllu data/Rice/Rice-italian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-catalan.conllu Rice-kazakh.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-catalan.conllu data/Rice/Rice-kazakh.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-catalan.conllu Rice-russian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-catalan.conllu data/Rice/Rice-russian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-catalan.conllu Rice-slovenian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-catalan.conllu data/Rice/Rice-slovenian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-catalan.conllu Rice-serbian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-catalan.conllu data/Rice/Rice-serbian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-catalan.conllu Rice-swedish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-catalan.conllu data/Rice/Rice-swedish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-catalan.conllu Rice-tamil.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-catalan.conllu data/Rice/Rice-tamil.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-catalan.conllu Rice-ukrainian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-catalan.conllu data/Rice/Rice-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-catalan.conllu Rice-vietnamese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-catalan.conllu data/Rice/Rice-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-catalan.conllu Rice-classical_chinese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-catalan.conllu data/Rice/Rice-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-catalan.conllu Rice-chinese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-catalan.conllu data/Rice/Rice-chinese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-czech.conllu Rice-spanish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-czech.conllu data/Rice/Rice-spanish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-czech.conllu Rice-basque.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-czech.conllu data/Rice/Rice-basque.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-czech.conllu Rice-persian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-czech.conllu data/Rice/Rice-persian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-czech.conllu Rice-french.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-czech.conllu data/Rice/Rice-french.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-czech.conllu Rice-italian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-czech.conllu data/Rice/Rice-italian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-czech.conllu Rice-kazakh.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-czech.conllu data/Rice/Rice-kazakh.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-czech.conllu Rice-russian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-czech.conllu data/Rice/Rice-russian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-czech.conllu Rice-slovenian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-czech.conllu data/Rice/Rice-slovenian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-czech.conllu Rice-serbian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-czech.conllu data/Rice/Rice-serbian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-czech.conllu Rice-swedish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-czech.conllu data/Rice/Rice-swedish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-czech.conllu Rice-tamil.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-czech.conllu data/Rice/Rice-tamil.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-czech.conllu Rice-ukrainian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-czech.conllu data/Rice/Rice-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-czech.conllu Rice-vietnamese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-czech.conllu data/Rice/Rice-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-czech.conllu Rice-classical_chinese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-czech.conllu data/Rice/Rice-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-czech.conllu Rice-chinese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-czech.conllu data/Rice/Rice-chinese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-spanish.conllu Rice-basque.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-spanish.conllu data/Rice/Rice-basque.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-spanish.conllu Rice-persian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-spanish.conllu data/Rice/Rice-persian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-spanish.conllu Rice-french.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-spanish.conllu data/Rice/Rice-french.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-spanish.conllu Rice-italian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-spanish.conllu data/Rice/Rice-italian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-spanish.conllu Rice-kazakh.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-spanish.conllu data/Rice/Rice-kazakh.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-spanish.conllu Rice-russian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-spanish.conllu data/Rice/Rice-russian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-spanish.conllu Rice-slovenian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-spanish.conllu data/Rice/Rice-slovenian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-spanish.conllu Rice-serbian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-spanish.conllu data/Rice/Rice-serbian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-spanish.conllu Rice-swedish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-spanish.conllu data/Rice/Rice-swedish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-spanish.conllu Rice-tamil.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-spanish.conllu data/Rice/Rice-tamil.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-spanish.conllu Rice-ukrainian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-spanish.conllu data/Rice/Rice-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-spanish.conllu Rice-vietnamese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-spanish.conllu data/Rice/Rice-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-spanish.conllu Rice-classical_chinese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-spanish.conllu data/Rice/Rice-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-spanish.conllu Rice-chinese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-spanish.conllu data/Rice/Rice-chinese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-basque.conllu Rice-persian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-basque.conllu data/Rice/Rice-persian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-basque.conllu Rice-french.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-basque.conllu data/Rice/Rice-french.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-basque.conllu Rice-italian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-basque.conllu data/Rice/Rice-italian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-basque.conllu Rice-kazakh.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-basque.conllu data/Rice/Rice-kazakh.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-basque.conllu Rice-russian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-basque.conllu data/Rice/Rice-russian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-basque.conllu Rice-slovenian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-basque.conllu data/Rice/Rice-slovenian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-basque.conllu Rice-serbian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-basque.conllu data/Rice/Rice-serbian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-basque.conllu Rice-swedish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-basque.conllu data/Rice/Rice-swedish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-basque.conllu Rice-tamil.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-basque.conllu data/Rice/Rice-tamil.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-basque.conllu Rice-ukrainian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-basque.conllu data/Rice/Rice-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-basque.conllu Rice-vietnamese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-basque.conllu data/Rice/Rice-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-basque.conllu Rice-classical_chinese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-basque.conllu data/Rice/Rice-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-basque.conllu Rice-chinese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-basque.conllu data/Rice/Rice-chinese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-persian.conllu Rice-french.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-persian.conllu data/Rice/Rice-french.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-persian.conllu Rice-italian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-persian.conllu data/Rice/Rice-italian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-persian.conllu Rice-kazakh.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-persian.conllu data/Rice/Rice-kazakh.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-persian.conllu Rice-russian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-persian.conllu data/Rice/Rice-russian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-persian.conllu Rice-slovenian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-persian.conllu data/Rice/Rice-slovenian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-persian.conllu Rice-serbian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-persian.conllu data/Rice/Rice-serbian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-persian.conllu Rice-swedish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-persian.conllu data/Rice/Rice-swedish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-persian.conllu Rice-tamil.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-persian.conllu data/Rice/Rice-tamil.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-persian.conllu Rice-ukrainian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-persian.conllu data/Rice/Rice-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-persian.conllu Rice-vietnamese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-persian.conllu data/Rice/Rice-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-persian.conllu Rice-classical_chinese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-persian.conllu data/Rice/Rice-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-persian.conllu Rice-chinese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-persian.conllu data/Rice/Rice-chinese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-french.conllu Rice-italian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-french.conllu data/Rice/Rice-italian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-french.conllu Rice-kazakh.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-french.conllu data/Rice/Rice-kazakh.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-french.conllu Rice-russian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-french.conllu data/Rice/Rice-russian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-french.conllu Rice-slovenian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-french.conllu data/Rice/Rice-slovenian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-french.conllu Rice-serbian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-french.conllu data/Rice/Rice-serbian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-french.conllu Rice-swedish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-french.conllu data/Rice/Rice-swedish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-french.conllu Rice-tamil.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-french.conllu data/Rice/Rice-tamil.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-french.conllu Rice-ukrainian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-french.conllu data/Rice/Rice-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-french.conllu Rice-vietnamese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-french.conllu data/Rice/Rice-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-french.conllu Rice-classical_chinese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-french.conllu data/Rice/Rice-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-french.conllu Rice-chinese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-french.conllu data/Rice/Rice-chinese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-italian.conllu Rice-kazakh.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-italian.conllu data/Rice/Rice-kazakh.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-italian.conllu Rice-russian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-italian.conllu data/Rice/Rice-russian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-italian.conllu Rice-slovenian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-italian.conllu data/Rice/Rice-slovenian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-italian.conllu Rice-serbian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-italian.conllu data/Rice/Rice-serbian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-italian.conllu Rice-swedish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-italian.conllu data/Rice/Rice-swedish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-italian.conllu Rice-tamil.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-italian.conllu data/Rice/Rice-tamil.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-italian.conllu Rice-ukrainian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-italian.conllu data/Rice/Rice-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-italian.conllu Rice-vietnamese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-italian.conllu data/Rice/Rice-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-italian.conllu Rice-classical_chinese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-italian.conllu data/Rice/Rice-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-italian.conllu Rice-chinese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-italian.conllu data/Rice/Rice-chinese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-kazakh.conllu Rice-russian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-kazakh.conllu data/Rice/Rice-russian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-kazakh.conllu Rice-slovenian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-kazakh.conllu data/Rice/Rice-slovenian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-kazakh.conllu Rice-serbian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-kazakh.conllu data/Rice/Rice-serbian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-kazakh.conllu Rice-swedish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-kazakh.conllu data/Rice/Rice-swedish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-kazakh.conllu Rice-tamil.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-kazakh.conllu data/Rice/Rice-tamil.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-kazakh.conllu Rice-ukrainian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-kazakh.conllu data/Rice/Rice-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-kazakh.conllu Rice-vietnamese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-kazakh.conllu data/Rice/Rice-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-kazakh.conllu Rice-classical_chinese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-kazakh.conllu data/Rice/Rice-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-kazakh.conllu Rice-chinese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-kazakh.conllu data/Rice/Rice-chinese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-russian.conllu Rice-slovenian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-russian.conllu data/Rice/Rice-slovenian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-russian.conllu Rice-serbian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-russian.conllu data/Rice/Rice-serbian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-russian.conllu Rice-swedish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-russian.conllu data/Rice/Rice-swedish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-russian.conllu Rice-tamil.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-russian.conllu data/Rice/Rice-tamil.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-russian.conllu Rice-ukrainian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-russian.conllu data/Rice/Rice-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-russian.conllu Rice-vietnamese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-russian.conllu data/Rice/Rice-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-russian.conllu Rice-classical_chinese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-russian.conllu data/Rice/Rice-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-russian.conllu Rice-chinese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-russian.conllu data/Rice/Rice-chinese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-slovenian.conllu Rice-serbian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-slovenian.conllu data/Rice/Rice-serbian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-slovenian.conllu Rice-swedish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-slovenian.conllu data/Rice/Rice-swedish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-slovenian.conllu Rice-tamil.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-slovenian.conllu data/Rice/Rice-tamil.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-slovenian.conllu Rice-ukrainian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-slovenian.conllu data/Rice/Rice-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-slovenian.conllu Rice-vietnamese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-slovenian.conllu data/Rice/Rice-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-slovenian.conllu Rice-classical_chinese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-slovenian.conllu data/Rice/Rice-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-slovenian.conllu Rice-chinese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-slovenian.conllu data/Rice/Rice-chinese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-serbian.conllu Rice-swedish.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-serbian.conllu data/Rice/Rice-swedish.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-serbian.conllu Rice-tamil.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-serbian.conllu data/Rice/Rice-tamil.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-serbian.conllu Rice-ukrainian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-serbian.conllu data/Rice/Rice-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-serbian.conllu Rice-vietnamese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-serbian.conllu data/Rice/Rice-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-serbian.conllu Rice-classical_chinese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-serbian.conllu data/Rice/Rice-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-serbian.conllu Rice-chinese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-serbian.conllu data/Rice/Rice-chinese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-swedish.conllu Rice-tamil.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-swedish.conllu data/Rice/Rice-tamil.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-swedish.conllu Rice-ukrainian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-swedish.conllu data/Rice/Rice-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-swedish.conllu Rice-vietnamese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-swedish.conllu data/Rice/Rice-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-swedish.conllu Rice-classical_chinese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-swedish.conllu data/Rice/Rice-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-swedish.conllu Rice-chinese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-swedish.conllu data/Rice/Rice-chinese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-tamil.conllu Rice-ukrainian.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-tamil.conllu data/Rice/Rice-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-tamil.conllu Rice-vietnamese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-tamil.conllu data/Rice/Rice-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-tamil.conllu Rice-classical_chinese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-tamil.conllu data/Rice/Rice-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-tamil.conllu Rice-chinese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-tamil.conllu data/Rice/Rice-chinese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-ukrainian.conllu Rice-vietnamese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-ukrainian.conllu data/Rice/Rice-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-ukrainian.conllu Rice-classical_chinese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-ukrainian.conllu data/Rice/Rice-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-ukrainian.conllu Rice-chinese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-ukrainian.conllu data/Rice/Rice-chinese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-vietnamese.conllu Rice-classical_chinese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-vietnamese.conllu data/Rice/Rice-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-vietnamese.conllu Rice-chinese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-vietnamese.conllu data/Rice/Rice-chinese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-classical_chinese.conllu Rice-chinese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-classical_chinese.conllu data/Rice/Rice-chinese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
echo Rice-english.conllu Rice-japanese.conllu >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
gfud cosine-similarity data/Rice/Rice-english.conllu data/Rice/Rice-japanese.conllu DEPREL >> cosine-sim-per-topic/Rice-cosine-sim.txt ; 
} 
topic_combinations