#! /bin/bash 
function topic_combinations { 
echo Russia-scottish_gaelic.conllu Russia-gothic.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-scottish_gaelic.conllu data/Russia/Russia-gothic.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-scottish_gaelic.conllu Russia-sanskrit.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-scottish_gaelic.conllu data/Russia/Russia-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-scottish_gaelic.conllu Russia-urdu.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-scottish_gaelic.conllu data/Russia/Russia-urdu.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-scottish_gaelic.conllu Russia-uyghur.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-scottish_gaelic.conllu data/Russia/Russia-uyghur.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-scottish_gaelic.conllu Russia-wolof.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-scottish_gaelic.conllu data/Russia/Russia-wolof.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-gothic.conllu Russia-sanskrit.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-gothic.conllu data/Russia/Russia-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-gothic.conllu Russia-urdu.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-gothic.conllu data/Russia/Russia-urdu.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-gothic.conllu Russia-uyghur.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-gothic.conllu data/Russia/Russia-uyghur.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-gothic.conllu Russia-wolof.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-gothic.conllu data/Russia/Russia-wolof.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-sanskrit.conllu Russia-urdu.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-sanskrit.conllu data/Russia/Russia-urdu.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-sanskrit.conllu Russia-uyghur.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-sanskrit.conllu data/Russia/Russia-uyghur.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-sanskrit.conllu Russia-wolof.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-sanskrit.conllu data/Russia/Russia-wolof.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-urdu.conllu Russia-uyghur.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-urdu.conllu data/Russia/Russia-uyghur.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-urdu.conllu Russia-wolof.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-urdu.conllu data/Russia/Russia-wolof.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-uyghur.conllu Russia-wolof.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-uyghur.conllu data/Russia/Russia-wolof.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-north_sami.conllu Russia-irish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-north_sami.conllu data/Russia/Russia-irish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-north_sami.conllu Russia-hindi.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-north_sami.conllu data/Russia/Russia-hindi.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-north_sami.conllu Russia-maltese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-north_sami.conllu data/Russia/Russia-maltese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-north_sami.conllu Russia-marathi.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-north_sami.conllu data/Russia/Russia-marathi.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-north_sami.conllu Russia-slovenian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-north_sami.conllu data/Russia/Russia-slovenian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-irish.conllu Russia-hindi.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-irish.conllu data/Russia/Russia-hindi.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-irish.conllu Russia-maltese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-irish.conllu data/Russia/Russia-maltese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-irish.conllu Russia-marathi.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-irish.conllu data/Russia/Russia-marathi.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-irish.conllu Russia-slovenian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-irish.conllu data/Russia/Russia-slovenian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-hindi.conllu Russia-maltese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-hindi.conllu data/Russia/Russia-maltese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-hindi.conllu Russia-marathi.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-hindi.conllu data/Russia/Russia-marathi.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-hindi.conllu Russia-slovenian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-hindi.conllu data/Russia/Russia-slovenian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-maltese.conllu Russia-marathi.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-maltese.conllu data/Russia/Russia-marathi.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-maltese.conllu Russia-slovenian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-maltese.conllu data/Russia/Russia-slovenian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-marathi.conllu Russia-slovenian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-marathi.conllu data/Russia/Russia-slovenian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-belarusian.conllu Russia-welsh.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-belarusian.conllu data/Russia/Russia-welsh.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-belarusian.conllu Russia-estonian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-belarusian.conllu data/Russia/Russia-estonian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-belarusian.conllu Russia-greek.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-belarusian.conllu data/Russia/Russia-greek.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-belarusian.conllu Russia-galician.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-belarusian.conllu data/Russia/Russia-galician.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-belarusian.conllu Russia-croatian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-belarusian.conllu data/Russia/Russia-croatian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-belarusian.conllu Russia-hebrew.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-belarusian.conllu data/Russia/Russia-hebrew.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-belarusian.conllu Russia-latin.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-belarusian.conllu data/Russia/Russia-latin.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-belarusian.conllu Russia-lithuanian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-belarusian.conllu data/Russia/Russia-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-belarusian.conllu Russia-hungarian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-belarusian.conllu data/Russia/Russia-hungarian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-belarusian.conllu Russia-slovak.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-belarusian.conllu data/Russia/Russia-slovak.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-belarusian.conllu Russia-old_church_slavonic.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-belarusian.conllu data/Russia/Russia-old_church_slavonic.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-belarusian.conllu Russia-classical_chinese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-belarusian.conllu data/Russia/Russia-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-belarusian.conllu Russia-chinese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-belarusian.conllu data/Russia/Russia-chinese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-welsh.conllu Russia-estonian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-welsh.conllu data/Russia/Russia-estonian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-welsh.conllu Russia-greek.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-welsh.conllu data/Russia/Russia-greek.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-welsh.conllu Russia-galician.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-welsh.conllu data/Russia/Russia-galician.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-welsh.conllu Russia-croatian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-welsh.conllu data/Russia/Russia-croatian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-welsh.conllu Russia-hebrew.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-welsh.conllu data/Russia/Russia-hebrew.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-welsh.conllu Russia-latin.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-welsh.conllu data/Russia/Russia-latin.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-welsh.conllu Russia-lithuanian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-welsh.conllu data/Russia/Russia-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-welsh.conllu Russia-hungarian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-welsh.conllu data/Russia/Russia-hungarian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-welsh.conllu Russia-slovak.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-welsh.conllu data/Russia/Russia-slovak.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-welsh.conllu Russia-old_church_slavonic.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-welsh.conllu data/Russia/Russia-old_church_slavonic.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-welsh.conllu Russia-classical_chinese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-welsh.conllu data/Russia/Russia-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-welsh.conllu Russia-chinese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-welsh.conllu data/Russia/Russia-chinese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-estonian.conllu Russia-greek.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-estonian.conllu data/Russia/Russia-greek.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-estonian.conllu Russia-galician.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-estonian.conllu data/Russia/Russia-galician.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-estonian.conllu Russia-croatian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-estonian.conllu data/Russia/Russia-croatian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-estonian.conllu Russia-hebrew.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-estonian.conllu data/Russia/Russia-hebrew.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-estonian.conllu Russia-latin.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-estonian.conllu data/Russia/Russia-latin.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-estonian.conllu Russia-lithuanian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-estonian.conllu data/Russia/Russia-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-estonian.conllu Russia-hungarian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-estonian.conllu data/Russia/Russia-hungarian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-estonian.conllu Russia-slovak.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-estonian.conllu data/Russia/Russia-slovak.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-estonian.conllu Russia-old_church_slavonic.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-estonian.conllu data/Russia/Russia-old_church_slavonic.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-estonian.conllu Russia-classical_chinese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-estonian.conllu data/Russia/Russia-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-estonian.conllu Russia-chinese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-estonian.conllu data/Russia/Russia-chinese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-greek.conllu Russia-galician.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-greek.conllu data/Russia/Russia-galician.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-greek.conllu Russia-croatian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-greek.conllu data/Russia/Russia-croatian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-greek.conllu Russia-hebrew.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-greek.conllu data/Russia/Russia-hebrew.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-greek.conllu Russia-latin.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-greek.conllu data/Russia/Russia-latin.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-greek.conllu Russia-lithuanian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-greek.conllu data/Russia/Russia-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-greek.conllu Russia-hungarian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-greek.conllu data/Russia/Russia-hungarian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-greek.conllu Russia-slovak.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-greek.conllu data/Russia/Russia-slovak.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-greek.conllu Russia-old_church_slavonic.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-greek.conllu data/Russia/Russia-old_church_slavonic.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-greek.conllu Russia-classical_chinese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-greek.conllu data/Russia/Russia-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-greek.conllu Russia-chinese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-greek.conllu data/Russia/Russia-chinese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-galician.conllu Russia-croatian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-galician.conllu data/Russia/Russia-croatian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-galician.conllu Russia-hebrew.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-galician.conllu data/Russia/Russia-hebrew.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-galician.conllu Russia-latin.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-galician.conllu data/Russia/Russia-latin.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-galician.conllu Russia-lithuanian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-galician.conllu data/Russia/Russia-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-galician.conllu Russia-hungarian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-galician.conllu data/Russia/Russia-hungarian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-galician.conllu Russia-slovak.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-galician.conllu data/Russia/Russia-slovak.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-galician.conllu Russia-old_church_slavonic.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-galician.conllu data/Russia/Russia-old_church_slavonic.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-galician.conllu Russia-classical_chinese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-galician.conllu data/Russia/Russia-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-galician.conllu Russia-chinese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-galician.conllu data/Russia/Russia-chinese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-croatian.conllu Russia-hebrew.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-croatian.conllu data/Russia/Russia-hebrew.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-croatian.conllu Russia-latin.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-croatian.conllu data/Russia/Russia-latin.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-croatian.conllu Russia-lithuanian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-croatian.conllu data/Russia/Russia-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-croatian.conllu Russia-hungarian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-croatian.conllu data/Russia/Russia-hungarian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-croatian.conllu Russia-slovak.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-croatian.conllu data/Russia/Russia-slovak.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-croatian.conllu Russia-old_church_slavonic.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-croatian.conllu data/Russia/Russia-old_church_slavonic.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-croatian.conllu Russia-classical_chinese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-croatian.conllu data/Russia/Russia-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-croatian.conllu Russia-chinese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-croatian.conllu data/Russia/Russia-chinese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-hebrew.conllu Russia-latin.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-hebrew.conllu data/Russia/Russia-latin.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-hebrew.conllu Russia-lithuanian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-hebrew.conllu data/Russia/Russia-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-hebrew.conllu Russia-hungarian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-hebrew.conllu data/Russia/Russia-hungarian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-hebrew.conllu Russia-slovak.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-hebrew.conllu data/Russia/Russia-slovak.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-hebrew.conllu Russia-old_church_slavonic.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-hebrew.conllu data/Russia/Russia-old_church_slavonic.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-hebrew.conllu Russia-classical_chinese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-hebrew.conllu data/Russia/Russia-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-hebrew.conllu Russia-chinese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-hebrew.conllu data/Russia/Russia-chinese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-latin.conllu Russia-lithuanian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-latin.conllu data/Russia/Russia-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-latin.conllu Russia-hungarian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-latin.conllu data/Russia/Russia-hungarian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-latin.conllu Russia-slovak.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-latin.conllu data/Russia/Russia-slovak.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-latin.conllu Russia-old_church_slavonic.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-latin.conllu data/Russia/Russia-old_church_slavonic.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-latin.conllu Russia-classical_chinese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-latin.conllu data/Russia/Russia-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-latin.conllu Russia-chinese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-latin.conllu data/Russia/Russia-chinese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-lithuanian.conllu Russia-hungarian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-lithuanian.conllu data/Russia/Russia-hungarian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-lithuanian.conllu Russia-slovak.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-lithuanian.conllu data/Russia/Russia-slovak.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-lithuanian.conllu Russia-old_church_slavonic.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-lithuanian.conllu data/Russia/Russia-old_church_slavonic.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-lithuanian.conllu Russia-classical_chinese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-lithuanian.conllu data/Russia/Russia-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-lithuanian.conllu Russia-chinese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-lithuanian.conllu data/Russia/Russia-chinese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-hungarian.conllu Russia-slovak.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-hungarian.conllu data/Russia/Russia-slovak.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-hungarian.conllu Russia-old_church_slavonic.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-hungarian.conllu data/Russia/Russia-old_church_slavonic.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-hungarian.conllu Russia-classical_chinese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-hungarian.conllu data/Russia/Russia-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-hungarian.conllu Russia-chinese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-hungarian.conllu data/Russia/Russia-chinese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-slovak.conllu Russia-old_church_slavonic.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-slovak.conllu data/Russia/Russia-old_church_slavonic.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-slovak.conllu Russia-classical_chinese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-slovak.conllu data/Russia/Russia-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-slovak.conllu Russia-chinese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-slovak.conllu data/Russia/Russia-chinese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-old_church_slavonic.conllu Russia-classical_chinese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-old_church_slavonic.conllu data/Russia/Russia-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-old_church_slavonic.conllu Russia-chinese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-old_church_slavonic.conllu data/Russia/Russia-chinese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-classical_chinese.conllu Russia-chinese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-classical_chinese.conllu data/Russia/Russia-chinese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-afrikaans.conllu Russia-danish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-afrikaans.conllu data/Russia/Russia-danish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-afrikaans.conllu Russia-basque.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-afrikaans.conllu data/Russia/Russia-basque.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-afrikaans.conllu Russia-persian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-afrikaans.conllu data/Russia/Russia-persian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-afrikaans.conllu Russia-korean.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-afrikaans.conllu data/Russia/Russia-korean.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-afrikaans.conllu Russia-indonesian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-afrikaans.conllu data/Russia/Russia-indonesian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-afrikaans.conllu Russia-kazakh.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-afrikaans.conllu data/Russia/Russia-kazakh.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-afrikaans.conllu Russia-latvian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-afrikaans.conllu data/Russia/Russia-latvian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-afrikaans.conllu Russia-dutch.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-afrikaans.conllu data/Russia/Russia-dutch.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-afrikaans.conllu Russia-serbian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-afrikaans.conllu data/Russia/Russia-serbian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-afrikaans.conllu Russia-swedish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-afrikaans.conllu data/Russia/Russia-swedish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-afrikaans.conllu Russia-tamil.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-afrikaans.conllu data/Russia/Russia-tamil.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-afrikaans.conllu Russia-ukrainian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-afrikaans.conllu data/Russia/Russia-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-danish.conllu Russia-basque.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-danish.conllu data/Russia/Russia-basque.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-danish.conllu Russia-persian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-danish.conllu data/Russia/Russia-persian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-danish.conllu Russia-korean.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-danish.conllu data/Russia/Russia-korean.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-danish.conllu Russia-indonesian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-danish.conllu data/Russia/Russia-indonesian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-danish.conllu Russia-kazakh.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-danish.conllu data/Russia/Russia-kazakh.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-danish.conllu Russia-latvian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-danish.conllu data/Russia/Russia-latvian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-danish.conllu Russia-dutch.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-danish.conllu data/Russia/Russia-dutch.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-danish.conllu Russia-serbian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-danish.conllu data/Russia/Russia-serbian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-danish.conllu Russia-swedish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-danish.conllu data/Russia/Russia-swedish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-danish.conllu Russia-tamil.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-danish.conllu data/Russia/Russia-tamil.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-danish.conllu Russia-ukrainian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-danish.conllu data/Russia/Russia-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-basque.conllu Russia-persian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-basque.conllu data/Russia/Russia-persian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-basque.conllu Russia-korean.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-basque.conllu data/Russia/Russia-korean.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-basque.conllu Russia-indonesian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-basque.conllu data/Russia/Russia-indonesian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-basque.conllu Russia-kazakh.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-basque.conllu data/Russia/Russia-kazakh.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-basque.conllu Russia-latvian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-basque.conllu data/Russia/Russia-latvian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-basque.conllu Russia-dutch.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-basque.conllu data/Russia/Russia-dutch.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-basque.conllu Russia-serbian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-basque.conllu data/Russia/Russia-serbian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-basque.conllu Russia-swedish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-basque.conllu data/Russia/Russia-swedish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-basque.conllu Russia-tamil.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-basque.conllu data/Russia/Russia-tamil.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-basque.conllu Russia-ukrainian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-basque.conllu data/Russia/Russia-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-persian.conllu Russia-korean.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-persian.conllu data/Russia/Russia-korean.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-persian.conllu Russia-indonesian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-persian.conllu data/Russia/Russia-indonesian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-persian.conllu Russia-kazakh.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-persian.conllu data/Russia/Russia-kazakh.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-persian.conllu Russia-latvian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-persian.conllu data/Russia/Russia-latvian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-persian.conllu Russia-dutch.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-persian.conllu data/Russia/Russia-dutch.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-persian.conllu Russia-serbian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-persian.conllu data/Russia/Russia-serbian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-persian.conllu Russia-swedish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-persian.conllu data/Russia/Russia-swedish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-persian.conllu Russia-tamil.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-persian.conllu data/Russia/Russia-tamil.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-persian.conllu Russia-ukrainian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-persian.conllu data/Russia/Russia-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-korean.conllu Russia-indonesian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-korean.conllu data/Russia/Russia-indonesian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-korean.conllu Russia-kazakh.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-korean.conllu data/Russia/Russia-kazakh.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-korean.conllu Russia-latvian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-korean.conllu data/Russia/Russia-latvian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-korean.conllu Russia-dutch.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-korean.conllu data/Russia/Russia-dutch.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-korean.conllu Russia-serbian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-korean.conllu data/Russia/Russia-serbian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-korean.conllu Russia-swedish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-korean.conllu data/Russia/Russia-swedish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-korean.conllu Russia-tamil.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-korean.conllu data/Russia/Russia-tamil.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-korean.conllu Russia-ukrainian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-korean.conllu data/Russia/Russia-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-indonesian.conllu Russia-kazakh.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-indonesian.conllu data/Russia/Russia-kazakh.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-indonesian.conllu Russia-latvian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-indonesian.conllu data/Russia/Russia-latvian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-indonesian.conllu Russia-dutch.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-indonesian.conllu data/Russia/Russia-dutch.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-indonesian.conllu Russia-serbian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-indonesian.conllu data/Russia/Russia-serbian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-indonesian.conllu Russia-swedish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-indonesian.conllu data/Russia/Russia-swedish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-indonesian.conllu Russia-tamil.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-indonesian.conllu data/Russia/Russia-tamil.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-indonesian.conllu Russia-ukrainian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-indonesian.conllu data/Russia/Russia-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-kazakh.conllu Russia-latvian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-kazakh.conllu data/Russia/Russia-latvian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-kazakh.conllu Russia-dutch.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-kazakh.conllu data/Russia/Russia-dutch.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-kazakh.conllu Russia-serbian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-kazakh.conllu data/Russia/Russia-serbian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-kazakh.conllu Russia-swedish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-kazakh.conllu data/Russia/Russia-swedish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-kazakh.conllu Russia-tamil.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-kazakh.conllu data/Russia/Russia-tamil.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-kazakh.conllu Russia-ukrainian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-kazakh.conllu data/Russia/Russia-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-latvian.conllu Russia-dutch.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-latvian.conllu data/Russia/Russia-dutch.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-latvian.conllu Russia-serbian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-latvian.conllu data/Russia/Russia-serbian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-latvian.conllu Russia-swedish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-latvian.conllu data/Russia/Russia-swedish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-latvian.conllu Russia-tamil.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-latvian.conllu data/Russia/Russia-tamil.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-latvian.conllu Russia-ukrainian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-latvian.conllu data/Russia/Russia-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-dutch.conllu Russia-serbian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-dutch.conllu data/Russia/Russia-serbian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-dutch.conllu Russia-swedish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-dutch.conllu data/Russia/Russia-swedish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-dutch.conllu Russia-tamil.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-dutch.conllu data/Russia/Russia-tamil.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-dutch.conllu Russia-ukrainian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-dutch.conllu data/Russia/Russia-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-serbian.conllu Russia-swedish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-serbian.conllu data/Russia/Russia-swedish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-serbian.conllu Russia-tamil.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-serbian.conllu data/Russia/Russia-tamil.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-serbian.conllu Russia-ukrainian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-serbian.conllu data/Russia/Russia-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-swedish.conllu Russia-tamil.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-swedish.conllu data/Russia/Russia-tamil.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-swedish.conllu Russia-ukrainian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-swedish.conllu data/Russia/Russia-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-tamil.conllu Russia-ukrainian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-tamil.conllu data/Russia/Russia-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-english.conllu Russia-arabic.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-english.conllu data/Russia/Russia-arabic.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-english.conllu Russia-bulgarian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-english.conllu data/Russia/Russia-bulgarian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-english.conllu Russia-catalan.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-english.conllu data/Russia/Russia-catalan.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-english.conllu Russia-czech.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-english.conllu data/Russia/Russia-czech.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-english.conllu Russia-german.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-english.conllu data/Russia/Russia-german.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-english.conllu Russia-spanish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-english.conllu data/Russia/Russia-spanish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-english.conllu Russia-french.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-english.conllu data/Russia/Russia-french.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-english.conllu Russia-armenian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-english.conllu data/Russia/Russia-armenian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-english.conllu Russia-italian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-english.conllu data/Russia/Russia-italian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-english.conllu Russia-japanese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-english.conllu data/Russia/Russia-japanese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-english.conllu Russia-polish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-english.conllu data/Russia/Russia-polish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-english.conllu Russia-portuguese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-english.conllu data/Russia/Russia-portuguese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-english.conllu Russia-romanian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-english.conllu data/Russia/Russia-romanian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-english.conllu Russia-russian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-english.conllu data/Russia/Russia-russian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-english.conllu Russia-finnish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-english.conllu data/Russia/Russia-finnish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-english.conllu Russia-telugu.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-english.conllu data/Russia/Russia-telugu.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-english.conllu Russia-turkish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-english.conllu data/Russia/Russia-turkish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-english.conllu Russia-vietnamese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-english.conllu data/Russia/Russia-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-arabic.conllu Russia-bulgarian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-arabic.conllu data/Russia/Russia-bulgarian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-arabic.conllu Russia-catalan.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-arabic.conllu data/Russia/Russia-catalan.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-arabic.conllu Russia-czech.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-arabic.conllu data/Russia/Russia-czech.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-arabic.conllu Russia-german.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-arabic.conllu data/Russia/Russia-german.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-arabic.conllu Russia-spanish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-arabic.conllu data/Russia/Russia-spanish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-arabic.conllu Russia-french.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-arabic.conllu data/Russia/Russia-french.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-arabic.conllu Russia-armenian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-arabic.conllu data/Russia/Russia-armenian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-arabic.conllu Russia-italian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-arabic.conllu data/Russia/Russia-italian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-arabic.conllu Russia-japanese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-arabic.conllu data/Russia/Russia-japanese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-arabic.conllu Russia-polish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-arabic.conllu data/Russia/Russia-polish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-arabic.conllu Russia-portuguese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-arabic.conllu data/Russia/Russia-portuguese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-arabic.conllu Russia-romanian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-arabic.conllu data/Russia/Russia-romanian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-arabic.conllu Russia-russian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-arabic.conllu data/Russia/Russia-russian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-arabic.conllu Russia-finnish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-arabic.conllu data/Russia/Russia-finnish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-arabic.conllu Russia-telugu.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-arabic.conllu data/Russia/Russia-telugu.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-arabic.conllu Russia-turkish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-arabic.conllu data/Russia/Russia-turkish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-arabic.conllu Russia-vietnamese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-arabic.conllu data/Russia/Russia-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-bulgarian.conllu Russia-catalan.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-bulgarian.conllu data/Russia/Russia-catalan.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-bulgarian.conllu Russia-czech.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-bulgarian.conllu data/Russia/Russia-czech.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-bulgarian.conllu Russia-german.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-bulgarian.conllu data/Russia/Russia-german.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-bulgarian.conllu Russia-spanish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-bulgarian.conllu data/Russia/Russia-spanish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-bulgarian.conllu Russia-french.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-bulgarian.conllu data/Russia/Russia-french.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-bulgarian.conllu Russia-armenian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-bulgarian.conllu data/Russia/Russia-armenian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-bulgarian.conllu Russia-italian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-bulgarian.conllu data/Russia/Russia-italian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-bulgarian.conllu Russia-japanese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-bulgarian.conllu data/Russia/Russia-japanese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-bulgarian.conllu Russia-polish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-bulgarian.conllu data/Russia/Russia-polish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-bulgarian.conllu Russia-portuguese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-bulgarian.conllu data/Russia/Russia-portuguese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-bulgarian.conllu Russia-romanian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-bulgarian.conllu data/Russia/Russia-romanian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-bulgarian.conllu Russia-russian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-bulgarian.conllu data/Russia/Russia-russian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-bulgarian.conllu Russia-finnish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-bulgarian.conllu data/Russia/Russia-finnish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-bulgarian.conllu Russia-telugu.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-bulgarian.conllu data/Russia/Russia-telugu.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-bulgarian.conllu Russia-turkish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-bulgarian.conllu data/Russia/Russia-turkish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-bulgarian.conllu Russia-vietnamese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-bulgarian.conllu data/Russia/Russia-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-catalan.conllu Russia-czech.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-catalan.conllu data/Russia/Russia-czech.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-catalan.conllu Russia-german.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-catalan.conllu data/Russia/Russia-german.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-catalan.conllu Russia-spanish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-catalan.conllu data/Russia/Russia-spanish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-catalan.conllu Russia-french.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-catalan.conllu data/Russia/Russia-french.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-catalan.conllu Russia-armenian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-catalan.conllu data/Russia/Russia-armenian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-catalan.conllu Russia-italian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-catalan.conllu data/Russia/Russia-italian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-catalan.conllu Russia-japanese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-catalan.conllu data/Russia/Russia-japanese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-catalan.conllu Russia-polish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-catalan.conllu data/Russia/Russia-polish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-catalan.conllu Russia-portuguese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-catalan.conllu data/Russia/Russia-portuguese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-catalan.conllu Russia-romanian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-catalan.conllu data/Russia/Russia-romanian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-catalan.conllu Russia-russian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-catalan.conllu data/Russia/Russia-russian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-catalan.conllu Russia-finnish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-catalan.conllu data/Russia/Russia-finnish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-catalan.conllu Russia-telugu.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-catalan.conllu data/Russia/Russia-telugu.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-catalan.conllu Russia-turkish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-catalan.conllu data/Russia/Russia-turkish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-catalan.conllu Russia-vietnamese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-catalan.conllu data/Russia/Russia-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-czech.conllu Russia-german.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-czech.conllu data/Russia/Russia-german.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-czech.conllu Russia-spanish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-czech.conllu data/Russia/Russia-spanish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-czech.conllu Russia-french.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-czech.conllu data/Russia/Russia-french.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-czech.conllu Russia-armenian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-czech.conllu data/Russia/Russia-armenian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-czech.conllu Russia-italian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-czech.conllu data/Russia/Russia-italian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-czech.conllu Russia-japanese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-czech.conllu data/Russia/Russia-japanese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-czech.conllu Russia-polish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-czech.conllu data/Russia/Russia-polish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-czech.conllu Russia-portuguese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-czech.conllu data/Russia/Russia-portuguese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-czech.conllu Russia-romanian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-czech.conllu data/Russia/Russia-romanian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-czech.conllu Russia-russian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-czech.conllu data/Russia/Russia-russian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-czech.conllu Russia-finnish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-czech.conllu data/Russia/Russia-finnish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-czech.conllu Russia-telugu.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-czech.conllu data/Russia/Russia-telugu.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-czech.conllu Russia-turkish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-czech.conllu data/Russia/Russia-turkish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-czech.conllu Russia-vietnamese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-czech.conllu data/Russia/Russia-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-german.conllu Russia-spanish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-german.conllu data/Russia/Russia-spanish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-german.conllu Russia-french.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-german.conllu data/Russia/Russia-french.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-german.conllu Russia-armenian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-german.conllu data/Russia/Russia-armenian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-german.conllu Russia-italian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-german.conllu data/Russia/Russia-italian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-german.conllu Russia-japanese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-german.conllu data/Russia/Russia-japanese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-german.conllu Russia-polish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-german.conllu data/Russia/Russia-polish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-german.conllu Russia-portuguese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-german.conllu data/Russia/Russia-portuguese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-german.conllu Russia-romanian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-german.conllu data/Russia/Russia-romanian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-german.conllu Russia-russian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-german.conllu data/Russia/Russia-russian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-german.conllu Russia-finnish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-german.conllu data/Russia/Russia-finnish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-german.conllu Russia-telugu.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-german.conllu data/Russia/Russia-telugu.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-german.conllu Russia-turkish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-german.conllu data/Russia/Russia-turkish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-german.conllu Russia-vietnamese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-german.conllu data/Russia/Russia-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-spanish.conllu Russia-french.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-spanish.conllu data/Russia/Russia-french.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-spanish.conllu Russia-armenian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-spanish.conllu data/Russia/Russia-armenian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-spanish.conllu Russia-italian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-spanish.conllu data/Russia/Russia-italian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-spanish.conllu Russia-japanese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-spanish.conllu data/Russia/Russia-japanese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-spanish.conllu Russia-polish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-spanish.conllu data/Russia/Russia-polish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-spanish.conllu Russia-portuguese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-spanish.conllu data/Russia/Russia-portuguese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-spanish.conllu Russia-romanian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-spanish.conllu data/Russia/Russia-romanian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-spanish.conllu Russia-russian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-spanish.conllu data/Russia/Russia-russian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-spanish.conllu Russia-finnish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-spanish.conllu data/Russia/Russia-finnish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-spanish.conllu Russia-telugu.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-spanish.conllu data/Russia/Russia-telugu.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-spanish.conllu Russia-turkish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-spanish.conllu data/Russia/Russia-turkish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-spanish.conllu Russia-vietnamese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-spanish.conllu data/Russia/Russia-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-french.conllu Russia-armenian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-french.conllu data/Russia/Russia-armenian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-french.conllu Russia-italian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-french.conllu data/Russia/Russia-italian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-french.conllu Russia-japanese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-french.conllu data/Russia/Russia-japanese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-french.conllu Russia-polish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-french.conllu data/Russia/Russia-polish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-french.conllu Russia-portuguese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-french.conllu data/Russia/Russia-portuguese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-french.conllu Russia-romanian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-french.conllu data/Russia/Russia-romanian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-french.conllu Russia-russian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-french.conllu data/Russia/Russia-russian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-french.conllu Russia-finnish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-french.conllu data/Russia/Russia-finnish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-french.conllu Russia-telugu.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-french.conllu data/Russia/Russia-telugu.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-french.conllu Russia-turkish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-french.conllu data/Russia/Russia-turkish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-french.conllu Russia-vietnamese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-french.conllu data/Russia/Russia-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-armenian.conllu Russia-italian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-armenian.conllu data/Russia/Russia-italian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-armenian.conllu Russia-japanese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-armenian.conllu data/Russia/Russia-japanese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-armenian.conllu Russia-polish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-armenian.conllu data/Russia/Russia-polish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-armenian.conllu Russia-portuguese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-armenian.conllu data/Russia/Russia-portuguese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-armenian.conllu Russia-romanian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-armenian.conllu data/Russia/Russia-romanian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-armenian.conllu Russia-russian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-armenian.conllu data/Russia/Russia-russian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-armenian.conllu Russia-finnish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-armenian.conllu data/Russia/Russia-finnish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-armenian.conllu Russia-telugu.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-armenian.conllu data/Russia/Russia-telugu.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-armenian.conllu Russia-turkish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-armenian.conllu data/Russia/Russia-turkish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-armenian.conllu Russia-vietnamese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-armenian.conllu data/Russia/Russia-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-italian.conllu Russia-japanese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-italian.conllu data/Russia/Russia-japanese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-italian.conllu Russia-polish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-italian.conllu data/Russia/Russia-polish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-italian.conllu Russia-portuguese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-italian.conllu data/Russia/Russia-portuguese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-italian.conllu Russia-romanian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-italian.conllu data/Russia/Russia-romanian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-italian.conllu Russia-russian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-italian.conllu data/Russia/Russia-russian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-italian.conllu Russia-finnish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-italian.conllu data/Russia/Russia-finnish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-italian.conllu Russia-telugu.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-italian.conllu data/Russia/Russia-telugu.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-italian.conllu Russia-turkish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-italian.conllu data/Russia/Russia-turkish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-italian.conllu Russia-vietnamese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-italian.conllu data/Russia/Russia-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-japanese.conllu Russia-polish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-japanese.conllu data/Russia/Russia-polish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-japanese.conllu Russia-portuguese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-japanese.conllu data/Russia/Russia-portuguese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-japanese.conllu Russia-romanian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-japanese.conllu data/Russia/Russia-romanian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-japanese.conllu Russia-russian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-japanese.conllu data/Russia/Russia-russian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-japanese.conllu Russia-finnish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-japanese.conllu data/Russia/Russia-finnish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-japanese.conllu Russia-telugu.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-japanese.conllu data/Russia/Russia-telugu.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-japanese.conllu Russia-turkish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-japanese.conllu data/Russia/Russia-turkish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-japanese.conllu Russia-vietnamese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-japanese.conllu data/Russia/Russia-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-polish.conllu Russia-portuguese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-polish.conllu data/Russia/Russia-portuguese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-polish.conllu Russia-romanian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-polish.conllu data/Russia/Russia-romanian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-polish.conllu Russia-russian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-polish.conllu data/Russia/Russia-russian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-polish.conllu Russia-finnish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-polish.conllu data/Russia/Russia-finnish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-polish.conllu Russia-telugu.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-polish.conllu data/Russia/Russia-telugu.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-polish.conllu Russia-turkish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-polish.conllu data/Russia/Russia-turkish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-polish.conllu Russia-vietnamese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-polish.conllu data/Russia/Russia-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-portuguese.conllu Russia-romanian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-portuguese.conllu data/Russia/Russia-romanian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-portuguese.conllu Russia-russian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-portuguese.conllu data/Russia/Russia-russian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-portuguese.conllu Russia-finnish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-portuguese.conllu data/Russia/Russia-finnish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-portuguese.conllu Russia-telugu.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-portuguese.conllu data/Russia/Russia-telugu.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-portuguese.conllu Russia-turkish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-portuguese.conllu data/Russia/Russia-turkish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-portuguese.conllu Russia-vietnamese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-portuguese.conllu data/Russia/Russia-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-romanian.conllu Russia-russian.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-romanian.conllu data/Russia/Russia-russian.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-romanian.conllu Russia-finnish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-romanian.conllu data/Russia/Russia-finnish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-romanian.conllu Russia-telugu.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-romanian.conllu data/Russia/Russia-telugu.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-romanian.conllu Russia-turkish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-romanian.conllu data/Russia/Russia-turkish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-romanian.conllu Russia-vietnamese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-romanian.conllu data/Russia/Russia-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-russian.conllu Russia-finnish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-russian.conllu data/Russia/Russia-finnish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-russian.conllu Russia-telugu.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-russian.conllu data/Russia/Russia-telugu.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-russian.conllu Russia-turkish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-russian.conllu data/Russia/Russia-turkish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-russian.conllu Russia-vietnamese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-russian.conllu data/Russia/Russia-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-finnish.conllu Russia-telugu.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-finnish.conllu data/Russia/Russia-telugu.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-finnish.conllu Russia-turkish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-finnish.conllu data/Russia/Russia-turkish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-finnish.conllu Russia-vietnamese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-finnish.conllu data/Russia/Russia-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-telugu.conllu Russia-turkish.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-telugu.conllu data/Russia/Russia-turkish.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-telugu.conllu Russia-vietnamese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-telugu.conllu data/Russia/Russia-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
echo Russia-turkish.conllu Russia-vietnamese.conllu >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
gfud cosine-similarity data/Russia/Russia-turkish.conllu data/Russia/Russia-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Russia-cosine-sim.txt ; 
} 
topic_combinations