#! /bin/bash 
function topic_combinations { 
echo Sun-welsh.conllu Sun-scottish_gaelic.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-welsh.conllu data/Sun/Sun-scottish_gaelic.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-welsh.conllu Sun-gothic.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-welsh.conllu data/Sun/Sun-gothic.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-welsh.conllu Sun-old_church_slavonic.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-welsh.conllu data/Sun/Sun-old_church_slavonic.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-welsh.conllu Sun-uyghur.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-welsh.conllu data/Sun/Sun-uyghur.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-welsh.conllu Sun-wolof.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-welsh.conllu data/Sun/Sun-wolof.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-scottish_gaelic.conllu Sun-gothic.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-scottish_gaelic.conllu data/Sun/Sun-gothic.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-scottish_gaelic.conllu Sun-old_church_slavonic.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-scottish_gaelic.conllu data/Sun/Sun-old_church_slavonic.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-scottish_gaelic.conllu Sun-uyghur.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-scottish_gaelic.conllu data/Sun/Sun-uyghur.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-scottish_gaelic.conllu Sun-wolof.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-scottish_gaelic.conllu data/Sun/Sun-wolof.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-gothic.conllu Sun-old_church_slavonic.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-gothic.conllu data/Sun/Sun-old_church_slavonic.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-gothic.conllu Sun-uyghur.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-gothic.conllu data/Sun/Sun-uyghur.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-gothic.conllu Sun-wolof.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-gothic.conllu data/Sun/Sun-wolof.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-old_church_slavonic.conllu Sun-uyghur.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-old_church_slavonic.conllu data/Sun/Sun-uyghur.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-old_church_slavonic.conllu Sun-wolof.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-old_church_slavonic.conllu data/Sun/Sun-wolof.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-uyghur.conllu Sun-wolof.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-uyghur.conllu data/Sun/Sun-wolof.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-north_sami.conllu Sun-estonian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-north_sami.conllu data/Sun/Sun-estonian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-north_sami.conllu Sun-galician.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-north_sami.conllu data/Sun/Sun-galician.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-north_sami.conllu Sun-armenian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-north_sami.conllu data/Sun/Sun-armenian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-north_sami.conllu Sun-latin.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-north_sami.conllu data/Sun/Sun-latin.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-north_sami.conllu Sun-lithuanian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-north_sami.conllu data/Sun/Sun-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-north_sami.conllu Sun-maltese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-north_sami.conllu data/Sun/Sun-maltese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-north_sami.conllu Sun-sanskrit.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-north_sami.conllu data/Sun/Sun-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-north_sami.conllu Sun-slovenian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-north_sami.conllu data/Sun/Sun-slovenian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-north_sami.conllu Sun-telugu.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-north_sami.conllu data/Sun/Sun-telugu.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-north_sami.conllu Sun-urdu.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-north_sami.conllu data/Sun/Sun-urdu.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-north_sami.conllu Sun-classical_chinese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-north_sami.conllu data/Sun/Sun-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-estonian.conllu Sun-galician.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-estonian.conllu data/Sun/Sun-galician.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-estonian.conllu Sun-armenian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-estonian.conllu data/Sun/Sun-armenian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-estonian.conllu Sun-latin.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-estonian.conllu data/Sun/Sun-latin.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-estonian.conllu Sun-lithuanian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-estonian.conllu data/Sun/Sun-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-estonian.conllu Sun-maltese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-estonian.conllu data/Sun/Sun-maltese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-estonian.conllu Sun-sanskrit.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-estonian.conllu data/Sun/Sun-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-estonian.conllu Sun-slovenian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-estonian.conllu data/Sun/Sun-slovenian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-estonian.conllu Sun-telugu.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-estonian.conllu data/Sun/Sun-telugu.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-estonian.conllu Sun-urdu.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-estonian.conllu data/Sun/Sun-urdu.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-estonian.conllu Sun-classical_chinese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-estonian.conllu data/Sun/Sun-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-galician.conllu Sun-armenian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-galician.conllu data/Sun/Sun-armenian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-galician.conllu Sun-latin.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-galician.conllu data/Sun/Sun-latin.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-galician.conllu Sun-lithuanian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-galician.conllu data/Sun/Sun-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-galician.conllu Sun-maltese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-galician.conllu data/Sun/Sun-maltese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-galician.conllu Sun-sanskrit.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-galician.conllu data/Sun/Sun-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-galician.conllu Sun-slovenian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-galician.conllu data/Sun/Sun-slovenian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-galician.conllu Sun-telugu.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-galician.conllu data/Sun/Sun-telugu.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-galician.conllu Sun-urdu.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-galician.conllu data/Sun/Sun-urdu.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-galician.conllu Sun-classical_chinese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-galician.conllu data/Sun/Sun-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-armenian.conllu Sun-latin.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-armenian.conllu data/Sun/Sun-latin.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-armenian.conllu Sun-lithuanian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-armenian.conllu data/Sun/Sun-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-armenian.conllu Sun-maltese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-armenian.conllu data/Sun/Sun-maltese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-armenian.conllu Sun-sanskrit.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-armenian.conllu data/Sun/Sun-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-armenian.conllu Sun-slovenian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-armenian.conllu data/Sun/Sun-slovenian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-armenian.conllu Sun-telugu.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-armenian.conllu data/Sun/Sun-telugu.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-armenian.conllu Sun-urdu.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-armenian.conllu data/Sun/Sun-urdu.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-armenian.conllu Sun-classical_chinese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-armenian.conllu data/Sun/Sun-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-latin.conllu Sun-lithuanian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-latin.conllu data/Sun/Sun-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-latin.conllu Sun-maltese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-latin.conllu data/Sun/Sun-maltese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-latin.conllu Sun-sanskrit.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-latin.conllu data/Sun/Sun-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-latin.conllu Sun-slovenian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-latin.conllu data/Sun/Sun-slovenian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-latin.conllu Sun-telugu.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-latin.conllu data/Sun/Sun-telugu.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-latin.conllu Sun-urdu.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-latin.conllu data/Sun/Sun-urdu.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-latin.conllu Sun-classical_chinese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-latin.conllu data/Sun/Sun-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-lithuanian.conllu Sun-maltese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-lithuanian.conllu data/Sun/Sun-maltese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-lithuanian.conllu Sun-sanskrit.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-lithuanian.conllu data/Sun/Sun-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-lithuanian.conllu Sun-slovenian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-lithuanian.conllu data/Sun/Sun-slovenian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-lithuanian.conllu Sun-telugu.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-lithuanian.conllu data/Sun/Sun-telugu.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-lithuanian.conllu Sun-urdu.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-lithuanian.conllu data/Sun/Sun-urdu.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-lithuanian.conllu Sun-classical_chinese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-lithuanian.conllu data/Sun/Sun-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-maltese.conllu Sun-sanskrit.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-maltese.conllu data/Sun/Sun-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-maltese.conllu Sun-slovenian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-maltese.conllu data/Sun/Sun-slovenian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-maltese.conllu Sun-telugu.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-maltese.conllu data/Sun/Sun-telugu.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-maltese.conllu Sun-urdu.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-maltese.conllu data/Sun/Sun-urdu.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-maltese.conllu Sun-classical_chinese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-maltese.conllu data/Sun/Sun-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-sanskrit.conllu Sun-slovenian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-sanskrit.conllu data/Sun/Sun-slovenian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-sanskrit.conllu Sun-telugu.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-sanskrit.conllu data/Sun/Sun-telugu.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-sanskrit.conllu Sun-urdu.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-sanskrit.conllu data/Sun/Sun-urdu.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-sanskrit.conllu Sun-classical_chinese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-sanskrit.conllu data/Sun/Sun-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-slovenian.conllu Sun-telugu.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-slovenian.conllu data/Sun/Sun-telugu.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-slovenian.conllu Sun-urdu.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-slovenian.conllu data/Sun/Sun-urdu.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-slovenian.conllu Sun-classical_chinese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-slovenian.conllu data/Sun/Sun-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-telugu.conllu Sun-urdu.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-telugu.conllu data/Sun/Sun-urdu.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-telugu.conllu Sun-classical_chinese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-telugu.conllu data/Sun/Sun-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-urdu.conllu Sun-classical_chinese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-urdu.conllu data/Sun/Sun-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-afrikaans.conllu Sun-belarusian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-afrikaans.conllu data/Sun/Sun-belarusian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-afrikaans.conllu Sun-bulgarian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-afrikaans.conllu data/Sun/Sun-bulgarian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-afrikaans.conllu Sun-greek.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-afrikaans.conllu data/Sun/Sun-greek.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-afrikaans.conllu Sun-spanish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-afrikaans.conllu data/Sun/Sun-spanish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-afrikaans.conllu Sun-irish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-afrikaans.conllu data/Sun/Sun-irish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-afrikaans.conllu Sun-korean.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-afrikaans.conllu data/Sun/Sun-korean.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-afrikaans.conllu Sun-hindi.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-afrikaans.conllu data/Sun/Sun-hindi.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-afrikaans.conllu Sun-croatian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-afrikaans.conllu data/Sun/Sun-croatian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-afrikaans.conllu Sun-indonesian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-afrikaans.conllu data/Sun/Sun-indonesian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-afrikaans.conllu Sun-hebrew.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-afrikaans.conllu data/Sun/Sun-hebrew.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-afrikaans.conllu Sun-kazakh.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-afrikaans.conllu data/Sun/Sun-kazakh.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-afrikaans.conllu Sun-latvian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-afrikaans.conllu data/Sun/Sun-latvian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-afrikaans.conllu Sun-marathi.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-afrikaans.conllu data/Sun/Sun-marathi.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-afrikaans.conllu Sun-japanese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-afrikaans.conllu data/Sun/Sun-japanese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-afrikaans.conllu Sun-serbian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-afrikaans.conllu data/Sun/Sun-serbian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-afrikaans.conllu Sun-finnish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-afrikaans.conllu data/Sun/Sun-finnish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-afrikaans.conllu Sun-swedish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-afrikaans.conllu data/Sun/Sun-swedish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-afrikaans.conllu Sun-tamil.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-afrikaans.conllu data/Sun/Sun-tamil.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-afrikaans.conllu Sun-ukrainian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-afrikaans.conllu data/Sun/Sun-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-belarusian.conllu Sun-bulgarian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-belarusian.conllu data/Sun/Sun-bulgarian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-belarusian.conllu Sun-greek.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-belarusian.conllu data/Sun/Sun-greek.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-belarusian.conllu Sun-spanish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-belarusian.conllu data/Sun/Sun-spanish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-belarusian.conllu Sun-irish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-belarusian.conllu data/Sun/Sun-irish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-belarusian.conllu Sun-korean.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-belarusian.conllu data/Sun/Sun-korean.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-belarusian.conllu Sun-hindi.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-belarusian.conllu data/Sun/Sun-hindi.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-belarusian.conllu Sun-croatian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-belarusian.conllu data/Sun/Sun-croatian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-belarusian.conllu Sun-indonesian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-belarusian.conllu data/Sun/Sun-indonesian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-belarusian.conllu Sun-hebrew.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-belarusian.conllu data/Sun/Sun-hebrew.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-belarusian.conllu Sun-kazakh.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-belarusian.conllu data/Sun/Sun-kazakh.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-belarusian.conllu Sun-latvian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-belarusian.conllu data/Sun/Sun-latvian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-belarusian.conllu Sun-marathi.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-belarusian.conllu data/Sun/Sun-marathi.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-belarusian.conllu Sun-japanese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-belarusian.conllu data/Sun/Sun-japanese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-belarusian.conllu Sun-serbian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-belarusian.conllu data/Sun/Sun-serbian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-belarusian.conllu Sun-finnish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-belarusian.conllu data/Sun/Sun-finnish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-belarusian.conllu Sun-swedish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-belarusian.conllu data/Sun/Sun-swedish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-belarusian.conllu Sun-tamil.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-belarusian.conllu data/Sun/Sun-tamil.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-belarusian.conllu Sun-ukrainian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-belarusian.conllu data/Sun/Sun-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-bulgarian.conllu Sun-greek.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-bulgarian.conllu data/Sun/Sun-greek.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-bulgarian.conllu Sun-spanish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-bulgarian.conllu data/Sun/Sun-spanish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-bulgarian.conllu Sun-irish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-bulgarian.conllu data/Sun/Sun-irish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-bulgarian.conllu Sun-korean.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-bulgarian.conllu data/Sun/Sun-korean.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-bulgarian.conllu Sun-hindi.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-bulgarian.conllu data/Sun/Sun-hindi.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-bulgarian.conllu Sun-croatian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-bulgarian.conllu data/Sun/Sun-croatian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-bulgarian.conllu Sun-indonesian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-bulgarian.conllu data/Sun/Sun-indonesian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-bulgarian.conllu Sun-hebrew.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-bulgarian.conllu data/Sun/Sun-hebrew.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-bulgarian.conllu Sun-kazakh.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-bulgarian.conllu data/Sun/Sun-kazakh.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-bulgarian.conllu Sun-latvian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-bulgarian.conllu data/Sun/Sun-latvian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-bulgarian.conllu Sun-marathi.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-bulgarian.conllu data/Sun/Sun-marathi.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-bulgarian.conllu Sun-japanese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-bulgarian.conllu data/Sun/Sun-japanese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-bulgarian.conllu Sun-serbian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-bulgarian.conllu data/Sun/Sun-serbian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-bulgarian.conllu Sun-finnish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-bulgarian.conllu data/Sun/Sun-finnish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-bulgarian.conllu Sun-swedish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-bulgarian.conllu data/Sun/Sun-swedish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-bulgarian.conllu Sun-tamil.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-bulgarian.conllu data/Sun/Sun-tamil.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-bulgarian.conllu Sun-ukrainian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-bulgarian.conllu data/Sun/Sun-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-greek.conllu Sun-spanish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-greek.conllu data/Sun/Sun-spanish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-greek.conllu Sun-irish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-greek.conllu data/Sun/Sun-irish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-greek.conllu Sun-korean.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-greek.conllu data/Sun/Sun-korean.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-greek.conllu Sun-hindi.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-greek.conllu data/Sun/Sun-hindi.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-greek.conllu Sun-croatian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-greek.conllu data/Sun/Sun-croatian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-greek.conllu Sun-indonesian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-greek.conllu data/Sun/Sun-indonesian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-greek.conllu Sun-hebrew.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-greek.conllu data/Sun/Sun-hebrew.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-greek.conllu Sun-kazakh.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-greek.conllu data/Sun/Sun-kazakh.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-greek.conllu Sun-latvian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-greek.conllu data/Sun/Sun-latvian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-greek.conllu Sun-marathi.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-greek.conllu data/Sun/Sun-marathi.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-greek.conllu Sun-japanese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-greek.conllu data/Sun/Sun-japanese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-greek.conllu Sun-serbian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-greek.conllu data/Sun/Sun-serbian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-greek.conllu Sun-finnish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-greek.conllu data/Sun/Sun-finnish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-greek.conllu Sun-swedish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-greek.conllu data/Sun/Sun-swedish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-greek.conllu Sun-tamil.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-greek.conllu data/Sun/Sun-tamil.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-greek.conllu Sun-ukrainian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-greek.conllu data/Sun/Sun-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-spanish.conllu Sun-irish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-spanish.conllu data/Sun/Sun-irish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-spanish.conllu Sun-korean.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-spanish.conllu data/Sun/Sun-korean.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-spanish.conllu Sun-hindi.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-spanish.conllu data/Sun/Sun-hindi.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-spanish.conllu Sun-croatian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-spanish.conllu data/Sun/Sun-croatian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-spanish.conllu Sun-indonesian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-spanish.conllu data/Sun/Sun-indonesian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-spanish.conllu Sun-hebrew.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-spanish.conllu data/Sun/Sun-hebrew.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-spanish.conllu Sun-kazakh.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-spanish.conllu data/Sun/Sun-kazakh.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-spanish.conllu Sun-latvian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-spanish.conllu data/Sun/Sun-latvian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-spanish.conllu Sun-marathi.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-spanish.conllu data/Sun/Sun-marathi.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-spanish.conllu Sun-japanese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-spanish.conllu data/Sun/Sun-japanese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-spanish.conllu Sun-serbian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-spanish.conllu data/Sun/Sun-serbian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-spanish.conllu Sun-finnish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-spanish.conllu data/Sun/Sun-finnish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-spanish.conllu Sun-swedish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-spanish.conllu data/Sun/Sun-swedish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-spanish.conllu Sun-tamil.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-spanish.conllu data/Sun/Sun-tamil.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-spanish.conllu Sun-ukrainian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-spanish.conllu data/Sun/Sun-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-irish.conllu Sun-korean.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-irish.conllu data/Sun/Sun-korean.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-irish.conllu Sun-hindi.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-irish.conllu data/Sun/Sun-hindi.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-irish.conllu Sun-croatian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-irish.conllu data/Sun/Sun-croatian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-irish.conllu Sun-indonesian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-irish.conllu data/Sun/Sun-indonesian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-irish.conllu Sun-hebrew.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-irish.conllu data/Sun/Sun-hebrew.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-irish.conllu Sun-kazakh.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-irish.conllu data/Sun/Sun-kazakh.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-irish.conllu Sun-latvian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-irish.conllu data/Sun/Sun-latvian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-irish.conllu Sun-marathi.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-irish.conllu data/Sun/Sun-marathi.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-irish.conllu Sun-japanese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-irish.conllu data/Sun/Sun-japanese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-irish.conllu Sun-serbian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-irish.conllu data/Sun/Sun-serbian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-irish.conllu Sun-finnish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-irish.conllu data/Sun/Sun-finnish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-irish.conllu Sun-swedish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-irish.conllu data/Sun/Sun-swedish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-irish.conllu Sun-tamil.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-irish.conllu data/Sun/Sun-tamil.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-irish.conllu Sun-ukrainian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-irish.conllu data/Sun/Sun-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-korean.conllu Sun-hindi.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-korean.conllu data/Sun/Sun-hindi.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-korean.conllu Sun-croatian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-korean.conllu data/Sun/Sun-croatian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-korean.conllu Sun-indonesian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-korean.conllu data/Sun/Sun-indonesian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-korean.conllu Sun-hebrew.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-korean.conllu data/Sun/Sun-hebrew.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-korean.conllu Sun-kazakh.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-korean.conllu data/Sun/Sun-kazakh.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-korean.conllu Sun-latvian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-korean.conllu data/Sun/Sun-latvian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-korean.conllu Sun-marathi.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-korean.conllu data/Sun/Sun-marathi.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-korean.conllu Sun-japanese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-korean.conllu data/Sun/Sun-japanese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-korean.conllu Sun-serbian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-korean.conllu data/Sun/Sun-serbian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-korean.conllu Sun-finnish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-korean.conllu data/Sun/Sun-finnish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-korean.conllu Sun-swedish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-korean.conllu data/Sun/Sun-swedish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-korean.conllu Sun-tamil.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-korean.conllu data/Sun/Sun-tamil.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-korean.conllu Sun-ukrainian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-korean.conllu data/Sun/Sun-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-hindi.conllu Sun-croatian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-hindi.conllu data/Sun/Sun-croatian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-hindi.conllu Sun-indonesian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-hindi.conllu data/Sun/Sun-indonesian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-hindi.conllu Sun-hebrew.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-hindi.conllu data/Sun/Sun-hebrew.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-hindi.conllu Sun-kazakh.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-hindi.conllu data/Sun/Sun-kazakh.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-hindi.conllu Sun-latvian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-hindi.conllu data/Sun/Sun-latvian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-hindi.conllu Sun-marathi.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-hindi.conllu data/Sun/Sun-marathi.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-hindi.conllu Sun-japanese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-hindi.conllu data/Sun/Sun-japanese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-hindi.conllu Sun-serbian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-hindi.conllu data/Sun/Sun-serbian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-hindi.conllu Sun-finnish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-hindi.conllu data/Sun/Sun-finnish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-hindi.conllu Sun-swedish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-hindi.conllu data/Sun/Sun-swedish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-hindi.conllu Sun-tamil.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-hindi.conllu data/Sun/Sun-tamil.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-hindi.conllu Sun-ukrainian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-hindi.conllu data/Sun/Sun-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-croatian.conllu Sun-indonesian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-croatian.conllu data/Sun/Sun-indonesian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-croatian.conllu Sun-hebrew.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-croatian.conllu data/Sun/Sun-hebrew.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-croatian.conllu Sun-kazakh.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-croatian.conllu data/Sun/Sun-kazakh.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-croatian.conllu Sun-latvian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-croatian.conllu data/Sun/Sun-latvian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-croatian.conllu Sun-marathi.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-croatian.conllu data/Sun/Sun-marathi.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-croatian.conllu Sun-japanese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-croatian.conllu data/Sun/Sun-japanese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-croatian.conllu Sun-serbian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-croatian.conllu data/Sun/Sun-serbian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-croatian.conllu Sun-finnish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-croatian.conllu data/Sun/Sun-finnish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-croatian.conllu Sun-swedish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-croatian.conllu data/Sun/Sun-swedish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-croatian.conllu Sun-tamil.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-croatian.conllu data/Sun/Sun-tamil.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-croatian.conllu Sun-ukrainian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-croatian.conllu data/Sun/Sun-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-indonesian.conllu Sun-hebrew.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-indonesian.conllu data/Sun/Sun-hebrew.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-indonesian.conllu Sun-kazakh.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-indonesian.conllu data/Sun/Sun-kazakh.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-indonesian.conllu Sun-latvian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-indonesian.conllu data/Sun/Sun-latvian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-indonesian.conllu Sun-marathi.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-indonesian.conllu data/Sun/Sun-marathi.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-indonesian.conllu Sun-japanese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-indonesian.conllu data/Sun/Sun-japanese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-indonesian.conllu Sun-serbian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-indonesian.conllu data/Sun/Sun-serbian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-indonesian.conllu Sun-finnish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-indonesian.conllu data/Sun/Sun-finnish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-indonesian.conllu Sun-swedish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-indonesian.conllu data/Sun/Sun-swedish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-indonesian.conllu Sun-tamil.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-indonesian.conllu data/Sun/Sun-tamil.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-indonesian.conllu Sun-ukrainian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-indonesian.conllu data/Sun/Sun-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-hebrew.conllu Sun-kazakh.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-hebrew.conllu data/Sun/Sun-kazakh.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-hebrew.conllu Sun-latvian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-hebrew.conllu data/Sun/Sun-latvian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-hebrew.conllu Sun-marathi.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-hebrew.conllu data/Sun/Sun-marathi.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-hebrew.conllu Sun-japanese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-hebrew.conllu data/Sun/Sun-japanese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-hebrew.conllu Sun-serbian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-hebrew.conllu data/Sun/Sun-serbian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-hebrew.conllu Sun-finnish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-hebrew.conllu data/Sun/Sun-finnish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-hebrew.conllu Sun-swedish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-hebrew.conllu data/Sun/Sun-swedish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-hebrew.conllu Sun-tamil.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-hebrew.conllu data/Sun/Sun-tamil.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-hebrew.conllu Sun-ukrainian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-hebrew.conllu data/Sun/Sun-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-kazakh.conllu Sun-latvian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-kazakh.conllu data/Sun/Sun-latvian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-kazakh.conllu Sun-marathi.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-kazakh.conllu data/Sun/Sun-marathi.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-kazakh.conllu Sun-japanese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-kazakh.conllu data/Sun/Sun-japanese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-kazakh.conllu Sun-serbian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-kazakh.conllu data/Sun/Sun-serbian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-kazakh.conllu Sun-finnish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-kazakh.conllu data/Sun/Sun-finnish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-kazakh.conllu Sun-swedish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-kazakh.conllu data/Sun/Sun-swedish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-kazakh.conllu Sun-tamil.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-kazakh.conllu data/Sun/Sun-tamil.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-kazakh.conllu Sun-ukrainian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-kazakh.conllu data/Sun/Sun-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-latvian.conllu Sun-marathi.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-latvian.conllu data/Sun/Sun-marathi.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-latvian.conllu Sun-japanese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-latvian.conllu data/Sun/Sun-japanese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-latvian.conllu Sun-serbian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-latvian.conllu data/Sun/Sun-serbian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-latvian.conllu Sun-finnish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-latvian.conllu data/Sun/Sun-finnish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-latvian.conllu Sun-swedish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-latvian.conllu data/Sun/Sun-swedish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-latvian.conllu Sun-tamil.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-latvian.conllu data/Sun/Sun-tamil.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-latvian.conllu Sun-ukrainian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-latvian.conllu data/Sun/Sun-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-marathi.conllu Sun-japanese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-marathi.conllu data/Sun/Sun-japanese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-marathi.conllu Sun-serbian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-marathi.conllu data/Sun/Sun-serbian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-marathi.conllu Sun-finnish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-marathi.conllu data/Sun/Sun-finnish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-marathi.conllu Sun-swedish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-marathi.conllu data/Sun/Sun-swedish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-marathi.conllu Sun-tamil.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-marathi.conllu data/Sun/Sun-tamil.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-marathi.conllu Sun-ukrainian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-marathi.conllu data/Sun/Sun-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-japanese.conllu Sun-serbian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-japanese.conllu data/Sun/Sun-serbian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-japanese.conllu Sun-finnish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-japanese.conllu data/Sun/Sun-finnish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-japanese.conllu Sun-swedish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-japanese.conllu data/Sun/Sun-swedish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-japanese.conllu Sun-tamil.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-japanese.conllu data/Sun/Sun-tamil.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-japanese.conllu Sun-ukrainian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-japanese.conllu data/Sun/Sun-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-serbian.conllu Sun-finnish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-serbian.conllu data/Sun/Sun-finnish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-serbian.conllu Sun-swedish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-serbian.conllu data/Sun/Sun-swedish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-serbian.conllu Sun-tamil.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-serbian.conllu data/Sun/Sun-tamil.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-serbian.conllu Sun-ukrainian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-serbian.conllu data/Sun/Sun-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-finnish.conllu Sun-swedish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-finnish.conllu data/Sun/Sun-swedish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-finnish.conllu Sun-tamil.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-finnish.conllu data/Sun/Sun-tamil.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-finnish.conllu Sun-ukrainian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-finnish.conllu data/Sun/Sun-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-swedish.conllu Sun-tamil.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-swedish.conllu data/Sun/Sun-tamil.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-swedish.conllu Sun-ukrainian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-swedish.conllu data/Sun/Sun-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-tamil.conllu Sun-ukrainian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-tamil.conllu data/Sun/Sun-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-czech.conllu Sun-danish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-czech.conllu data/Sun/Sun-danish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-czech.conllu Sun-german.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-czech.conllu data/Sun/Sun-german.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-czech.conllu Sun-persian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-czech.conllu data/Sun/Sun-persian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-czech.conllu Sun-french.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-czech.conllu data/Sun/Sun-french.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-czech.conllu Sun-italian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-czech.conllu data/Sun/Sun-italian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-czech.conllu Sun-dutch.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-czech.conllu data/Sun/Sun-dutch.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-czech.conllu Sun-portuguese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-czech.conllu data/Sun/Sun-portuguese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-czech.conllu Sun-romanian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-czech.conllu data/Sun/Sun-romanian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-czech.conllu Sun-slovak.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-czech.conllu data/Sun/Sun-slovak.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-czech.conllu Sun-turkish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-czech.conllu data/Sun/Sun-turkish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-czech.conllu Sun-vietnamese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-czech.conllu data/Sun/Sun-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-czech.conllu Sun-chinese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-czech.conllu data/Sun/Sun-chinese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-danish.conllu Sun-german.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-danish.conllu data/Sun/Sun-german.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-danish.conllu Sun-persian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-danish.conllu data/Sun/Sun-persian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-danish.conllu Sun-french.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-danish.conllu data/Sun/Sun-french.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-danish.conllu Sun-italian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-danish.conllu data/Sun/Sun-italian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-danish.conllu Sun-dutch.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-danish.conllu data/Sun/Sun-dutch.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-danish.conllu Sun-portuguese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-danish.conllu data/Sun/Sun-portuguese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-danish.conllu Sun-romanian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-danish.conllu data/Sun/Sun-romanian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-danish.conllu Sun-slovak.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-danish.conllu data/Sun/Sun-slovak.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-danish.conllu Sun-turkish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-danish.conllu data/Sun/Sun-turkish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-danish.conllu Sun-vietnamese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-danish.conllu data/Sun/Sun-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-danish.conllu Sun-chinese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-danish.conllu data/Sun/Sun-chinese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-german.conllu Sun-persian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-german.conllu data/Sun/Sun-persian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-german.conllu Sun-french.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-german.conllu data/Sun/Sun-french.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-german.conllu Sun-italian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-german.conllu data/Sun/Sun-italian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-german.conllu Sun-dutch.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-german.conllu data/Sun/Sun-dutch.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-german.conllu Sun-portuguese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-german.conllu data/Sun/Sun-portuguese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-german.conllu Sun-romanian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-german.conllu data/Sun/Sun-romanian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-german.conllu Sun-slovak.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-german.conllu data/Sun/Sun-slovak.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-german.conllu Sun-turkish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-german.conllu data/Sun/Sun-turkish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-german.conllu Sun-vietnamese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-german.conllu data/Sun/Sun-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-german.conllu Sun-chinese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-german.conllu data/Sun/Sun-chinese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-persian.conllu Sun-french.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-persian.conllu data/Sun/Sun-french.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-persian.conllu Sun-italian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-persian.conllu data/Sun/Sun-italian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-persian.conllu Sun-dutch.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-persian.conllu data/Sun/Sun-dutch.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-persian.conllu Sun-portuguese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-persian.conllu data/Sun/Sun-portuguese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-persian.conllu Sun-romanian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-persian.conllu data/Sun/Sun-romanian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-persian.conllu Sun-slovak.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-persian.conllu data/Sun/Sun-slovak.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-persian.conllu Sun-turkish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-persian.conllu data/Sun/Sun-turkish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-persian.conllu Sun-vietnamese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-persian.conllu data/Sun/Sun-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-persian.conllu Sun-chinese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-persian.conllu data/Sun/Sun-chinese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-french.conllu Sun-italian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-french.conllu data/Sun/Sun-italian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-french.conllu Sun-dutch.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-french.conllu data/Sun/Sun-dutch.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-french.conllu Sun-portuguese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-french.conllu data/Sun/Sun-portuguese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-french.conllu Sun-romanian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-french.conllu data/Sun/Sun-romanian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-french.conllu Sun-slovak.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-french.conllu data/Sun/Sun-slovak.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-french.conllu Sun-turkish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-french.conllu data/Sun/Sun-turkish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-french.conllu Sun-vietnamese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-french.conllu data/Sun/Sun-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-french.conllu Sun-chinese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-french.conllu data/Sun/Sun-chinese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-italian.conllu Sun-dutch.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-italian.conllu data/Sun/Sun-dutch.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-italian.conllu Sun-portuguese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-italian.conllu data/Sun/Sun-portuguese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-italian.conllu Sun-romanian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-italian.conllu data/Sun/Sun-romanian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-italian.conllu Sun-slovak.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-italian.conllu data/Sun/Sun-slovak.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-italian.conllu Sun-turkish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-italian.conllu data/Sun/Sun-turkish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-italian.conllu Sun-vietnamese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-italian.conllu data/Sun/Sun-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-italian.conllu Sun-chinese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-italian.conllu data/Sun/Sun-chinese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-dutch.conllu Sun-portuguese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-dutch.conllu data/Sun/Sun-portuguese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-dutch.conllu Sun-romanian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-dutch.conllu data/Sun/Sun-romanian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-dutch.conllu Sun-slovak.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-dutch.conllu data/Sun/Sun-slovak.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-dutch.conllu Sun-turkish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-dutch.conllu data/Sun/Sun-turkish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-dutch.conllu Sun-vietnamese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-dutch.conllu data/Sun/Sun-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-dutch.conllu Sun-chinese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-dutch.conllu data/Sun/Sun-chinese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-portuguese.conllu Sun-romanian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-portuguese.conllu data/Sun/Sun-romanian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-portuguese.conllu Sun-slovak.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-portuguese.conllu data/Sun/Sun-slovak.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-portuguese.conllu Sun-turkish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-portuguese.conllu data/Sun/Sun-turkish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-portuguese.conllu Sun-vietnamese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-portuguese.conllu data/Sun/Sun-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-portuguese.conllu Sun-chinese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-portuguese.conllu data/Sun/Sun-chinese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-romanian.conllu Sun-slovak.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-romanian.conllu data/Sun/Sun-slovak.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-romanian.conllu Sun-turkish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-romanian.conllu data/Sun/Sun-turkish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-romanian.conllu Sun-vietnamese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-romanian.conllu data/Sun/Sun-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-romanian.conllu Sun-chinese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-romanian.conllu data/Sun/Sun-chinese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-slovak.conllu Sun-turkish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-slovak.conllu data/Sun/Sun-turkish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-slovak.conllu Sun-vietnamese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-slovak.conllu data/Sun/Sun-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-slovak.conllu Sun-chinese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-slovak.conllu data/Sun/Sun-chinese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-turkish.conllu Sun-vietnamese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-turkish.conllu data/Sun/Sun-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-turkish.conllu Sun-chinese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-turkish.conllu data/Sun/Sun-chinese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-vietnamese.conllu Sun-chinese.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-vietnamese.conllu data/Sun/Sun-chinese.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-english.conllu Sun-arabic.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-english.conllu data/Sun/Sun-arabic.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-english.conllu Sun-catalan.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-english.conllu data/Sun/Sun-catalan.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-english.conllu Sun-basque.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-english.conllu data/Sun/Sun-basque.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-english.conllu Sun-hungarian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-english.conllu data/Sun/Sun-hungarian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-english.conllu Sun-polish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-english.conllu data/Sun/Sun-polish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-english.conllu Sun-russian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-english.conllu data/Sun/Sun-russian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-arabic.conllu Sun-catalan.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-arabic.conllu data/Sun/Sun-catalan.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-arabic.conllu Sun-basque.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-arabic.conllu data/Sun/Sun-basque.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-arabic.conllu Sun-hungarian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-arabic.conllu data/Sun/Sun-hungarian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-arabic.conllu Sun-polish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-arabic.conllu data/Sun/Sun-polish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-arabic.conllu Sun-russian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-arabic.conllu data/Sun/Sun-russian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-catalan.conllu Sun-basque.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-catalan.conllu data/Sun/Sun-basque.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-catalan.conllu Sun-hungarian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-catalan.conllu data/Sun/Sun-hungarian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-catalan.conllu Sun-polish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-catalan.conllu data/Sun/Sun-polish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-catalan.conllu Sun-russian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-catalan.conllu data/Sun/Sun-russian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-basque.conllu Sun-hungarian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-basque.conllu data/Sun/Sun-hungarian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-basque.conllu Sun-polish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-basque.conllu data/Sun/Sun-polish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-basque.conllu Sun-russian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-basque.conllu data/Sun/Sun-russian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-hungarian.conllu Sun-polish.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-hungarian.conllu data/Sun/Sun-polish.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-hungarian.conllu Sun-russian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-hungarian.conllu data/Sun/Sun-russian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
echo Sun-polish.conllu Sun-russian.conllu >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
gfud cosine-similarity data/Sun/Sun-polish.conllu data/Sun/Sun-russian.conllu DEPREL >> cosine-sim-per-topic/Sun-cosine-sim.txt ; 
} 
topic_combinations