#! /bin/bash 
function topic_combinations { 
echo China-north_sami.conllu China-irish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-north_sami.conllu data/China/China-irish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-north_sami.conllu China-scottish_gaelic.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-north_sami.conllu data/China/China-scottish_gaelic.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-north_sami.conllu China-gothic.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-north_sami.conllu data/China/China-gothic.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-north_sami.conllu China-maltese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-north_sami.conllu data/China/China-maltese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-north_sami.conllu China-wolof.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-north_sami.conllu data/China/China-wolof.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-irish.conllu China-scottish_gaelic.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-irish.conllu data/China/China-scottish_gaelic.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-irish.conllu China-gothic.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-irish.conllu data/China/China-gothic.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-irish.conllu China-maltese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-irish.conllu data/China/China-maltese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-irish.conllu China-wolof.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-irish.conllu data/China/China-wolof.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-scottish_gaelic.conllu China-gothic.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-scottish_gaelic.conllu data/China/China-gothic.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-scottish_gaelic.conllu China-maltese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-scottish_gaelic.conllu data/China/China-maltese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-scottish_gaelic.conllu China-wolof.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-scottish_gaelic.conllu data/China/China-wolof.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-gothic.conllu China-maltese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-gothic.conllu data/China/China-maltese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-gothic.conllu China-wolof.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-gothic.conllu data/China/China-wolof.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-maltese.conllu China-wolof.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-maltese.conllu data/China/China-wolof.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-welsh.conllu China-estonian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-welsh.conllu data/China/China-estonian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-welsh.conllu China-latin.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-welsh.conllu data/China/China-latin.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-welsh.conllu China-old_church_slavonic.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-welsh.conllu data/China/China-old_church_slavonic.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-estonian.conllu China-latin.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-estonian.conllu data/China/China-latin.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-estonian.conllu China-old_church_slavonic.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-estonian.conllu data/China/China-old_church_slavonic.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-latin.conllu China-old_church_slavonic.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-latin.conllu data/China/China-old_church_slavonic.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-afrikaans.conllu China-catalan.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-afrikaans.conllu data/China/China-catalan.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-afrikaans.conllu China-greek.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-afrikaans.conllu data/China/China-greek.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-afrikaans.conllu China-croatian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-afrikaans.conllu data/China/China-croatian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-afrikaans.conllu China-indonesian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-afrikaans.conllu data/China/China-indonesian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-afrikaans.conllu China-hebrew.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-afrikaans.conllu data/China/China-hebrew.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-afrikaans.conllu China-kazakh.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-afrikaans.conllu data/China/China-kazakh.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-afrikaans.conllu China-latvian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-afrikaans.conllu data/China/China-latvian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-afrikaans.conllu China-lithuanian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-afrikaans.conllu data/China/China-lithuanian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-afrikaans.conllu China-marathi.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-afrikaans.conllu data/China/China-marathi.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-afrikaans.conllu China-polish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-afrikaans.conllu data/China/China-polish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-afrikaans.conllu China-slovak.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-afrikaans.conllu data/China/China-slovak.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-afrikaans.conllu China-slovenian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-afrikaans.conllu data/China/China-slovenian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-afrikaans.conllu China-tamil.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-afrikaans.conllu data/China/China-tamil.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-afrikaans.conllu China-ukrainian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-afrikaans.conllu data/China/China-ukrainian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-afrikaans.conllu China-urdu.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-afrikaans.conllu data/China/China-urdu.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-afrikaans.conllu China-uyghur.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-afrikaans.conllu data/China/China-uyghur.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-catalan.conllu China-greek.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-catalan.conllu data/China/China-greek.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-catalan.conllu China-croatian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-catalan.conllu data/China/China-croatian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-catalan.conllu China-indonesian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-catalan.conllu data/China/China-indonesian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-catalan.conllu China-hebrew.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-catalan.conllu data/China/China-hebrew.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-catalan.conllu China-kazakh.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-catalan.conllu data/China/China-kazakh.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-catalan.conllu China-latvian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-catalan.conllu data/China/China-latvian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-catalan.conllu China-lithuanian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-catalan.conllu data/China/China-lithuanian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-catalan.conllu China-marathi.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-catalan.conllu data/China/China-marathi.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-catalan.conllu China-polish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-catalan.conllu data/China/China-polish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-catalan.conllu China-slovak.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-catalan.conllu data/China/China-slovak.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-catalan.conllu China-slovenian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-catalan.conllu data/China/China-slovenian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-catalan.conllu China-tamil.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-catalan.conllu data/China/China-tamil.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-catalan.conllu China-ukrainian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-catalan.conllu data/China/China-ukrainian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-catalan.conllu China-urdu.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-catalan.conllu data/China/China-urdu.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-catalan.conllu China-uyghur.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-catalan.conllu data/China/China-uyghur.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-greek.conllu China-croatian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-greek.conllu data/China/China-croatian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-greek.conllu China-indonesian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-greek.conllu data/China/China-indonesian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-greek.conllu China-hebrew.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-greek.conllu data/China/China-hebrew.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-greek.conllu China-kazakh.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-greek.conllu data/China/China-kazakh.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-greek.conllu China-latvian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-greek.conllu data/China/China-latvian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-greek.conllu China-lithuanian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-greek.conllu data/China/China-lithuanian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-greek.conllu China-marathi.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-greek.conllu data/China/China-marathi.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-greek.conllu China-polish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-greek.conllu data/China/China-polish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-greek.conllu China-slovak.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-greek.conllu data/China/China-slovak.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-greek.conllu China-slovenian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-greek.conllu data/China/China-slovenian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-greek.conllu China-tamil.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-greek.conllu data/China/China-tamil.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-greek.conllu China-ukrainian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-greek.conllu data/China/China-ukrainian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-greek.conllu China-urdu.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-greek.conllu data/China/China-urdu.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-greek.conllu China-uyghur.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-greek.conllu data/China/China-uyghur.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-croatian.conllu China-indonesian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-croatian.conllu data/China/China-indonesian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-croatian.conllu China-hebrew.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-croatian.conllu data/China/China-hebrew.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-croatian.conllu China-kazakh.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-croatian.conllu data/China/China-kazakh.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-croatian.conllu China-latvian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-croatian.conllu data/China/China-latvian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-croatian.conllu China-lithuanian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-croatian.conllu data/China/China-lithuanian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-croatian.conllu China-marathi.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-croatian.conllu data/China/China-marathi.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-croatian.conllu China-polish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-croatian.conllu data/China/China-polish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-croatian.conllu China-slovak.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-croatian.conllu data/China/China-slovak.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-croatian.conllu China-slovenian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-croatian.conllu data/China/China-slovenian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-croatian.conllu China-tamil.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-croatian.conllu data/China/China-tamil.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-croatian.conllu China-ukrainian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-croatian.conllu data/China/China-ukrainian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-croatian.conllu China-urdu.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-croatian.conllu data/China/China-urdu.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-croatian.conllu China-uyghur.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-croatian.conllu data/China/China-uyghur.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-indonesian.conllu China-hebrew.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-indonesian.conllu data/China/China-hebrew.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-indonesian.conllu China-kazakh.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-indonesian.conllu data/China/China-kazakh.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-indonesian.conllu China-latvian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-indonesian.conllu data/China/China-latvian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-indonesian.conllu China-lithuanian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-indonesian.conllu data/China/China-lithuanian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-indonesian.conllu China-marathi.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-indonesian.conllu data/China/China-marathi.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-indonesian.conllu China-polish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-indonesian.conllu data/China/China-polish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-indonesian.conllu China-slovak.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-indonesian.conllu data/China/China-slovak.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-indonesian.conllu China-slovenian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-indonesian.conllu data/China/China-slovenian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-indonesian.conllu China-tamil.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-indonesian.conllu data/China/China-tamil.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-indonesian.conllu China-ukrainian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-indonesian.conllu data/China/China-ukrainian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-indonesian.conllu China-urdu.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-indonesian.conllu data/China/China-urdu.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-indonesian.conllu China-uyghur.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-indonesian.conllu data/China/China-uyghur.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-hebrew.conllu China-kazakh.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-hebrew.conllu data/China/China-kazakh.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-hebrew.conllu China-latvian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-hebrew.conllu data/China/China-latvian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-hebrew.conllu China-lithuanian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-hebrew.conllu data/China/China-lithuanian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-hebrew.conllu China-marathi.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-hebrew.conllu data/China/China-marathi.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-hebrew.conllu China-polish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-hebrew.conllu data/China/China-polish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-hebrew.conllu China-slovak.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-hebrew.conllu data/China/China-slovak.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-hebrew.conllu China-slovenian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-hebrew.conllu data/China/China-slovenian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-hebrew.conllu China-tamil.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-hebrew.conllu data/China/China-tamil.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-hebrew.conllu China-ukrainian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-hebrew.conllu data/China/China-ukrainian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-hebrew.conllu China-urdu.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-hebrew.conllu data/China/China-urdu.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-hebrew.conllu China-uyghur.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-hebrew.conllu data/China/China-uyghur.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-kazakh.conllu China-latvian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-kazakh.conllu data/China/China-latvian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-kazakh.conllu China-lithuanian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-kazakh.conllu data/China/China-lithuanian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-kazakh.conllu China-marathi.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-kazakh.conllu data/China/China-marathi.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-kazakh.conllu China-polish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-kazakh.conllu data/China/China-polish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-kazakh.conllu China-slovak.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-kazakh.conllu data/China/China-slovak.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-kazakh.conllu China-slovenian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-kazakh.conllu data/China/China-slovenian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-kazakh.conllu China-tamil.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-kazakh.conllu data/China/China-tamil.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-kazakh.conllu China-ukrainian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-kazakh.conllu data/China/China-ukrainian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-kazakh.conllu China-urdu.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-kazakh.conllu data/China/China-urdu.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-kazakh.conllu China-uyghur.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-kazakh.conllu data/China/China-uyghur.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-latvian.conllu China-lithuanian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-latvian.conllu data/China/China-lithuanian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-latvian.conllu China-marathi.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-latvian.conllu data/China/China-marathi.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-latvian.conllu China-polish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-latvian.conllu data/China/China-polish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-latvian.conllu China-slovak.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-latvian.conllu data/China/China-slovak.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-latvian.conllu China-slovenian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-latvian.conllu data/China/China-slovenian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-latvian.conllu China-tamil.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-latvian.conllu data/China/China-tamil.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-latvian.conllu China-ukrainian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-latvian.conllu data/China/China-ukrainian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-latvian.conllu China-urdu.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-latvian.conllu data/China/China-urdu.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-latvian.conllu China-uyghur.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-latvian.conllu data/China/China-uyghur.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-lithuanian.conllu China-marathi.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-lithuanian.conllu data/China/China-marathi.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-lithuanian.conllu China-polish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-lithuanian.conllu data/China/China-polish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-lithuanian.conllu China-slovak.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-lithuanian.conllu data/China/China-slovak.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-lithuanian.conllu China-slovenian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-lithuanian.conllu data/China/China-slovenian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-lithuanian.conllu China-tamil.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-lithuanian.conllu data/China/China-tamil.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-lithuanian.conllu China-ukrainian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-lithuanian.conllu data/China/China-ukrainian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-lithuanian.conllu China-urdu.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-lithuanian.conllu data/China/China-urdu.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-lithuanian.conllu China-uyghur.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-lithuanian.conllu data/China/China-uyghur.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-marathi.conllu China-polish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-marathi.conllu data/China/China-polish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-marathi.conllu China-slovak.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-marathi.conllu data/China/China-slovak.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-marathi.conllu China-slovenian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-marathi.conllu data/China/China-slovenian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-marathi.conllu China-tamil.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-marathi.conllu data/China/China-tamil.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-marathi.conllu China-ukrainian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-marathi.conllu data/China/China-ukrainian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-marathi.conllu China-urdu.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-marathi.conllu data/China/China-urdu.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-marathi.conllu China-uyghur.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-marathi.conllu data/China/China-uyghur.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-polish.conllu China-slovak.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-polish.conllu data/China/China-slovak.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-polish.conllu China-slovenian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-polish.conllu data/China/China-slovenian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-polish.conllu China-tamil.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-polish.conllu data/China/China-tamil.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-polish.conllu China-ukrainian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-polish.conllu data/China/China-ukrainian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-polish.conllu China-urdu.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-polish.conllu data/China/China-urdu.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-polish.conllu China-uyghur.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-polish.conllu data/China/China-uyghur.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-slovak.conllu China-slovenian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-slovak.conllu data/China/China-slovenian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-slovak.conllu China-tamil.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-slovak.conllu data/China/China-tamil.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-slovak.conllu China-ukrainian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-slovak.conllu data/China/China-ukrainian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-slovak.conllu China-urdu.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-slovak.conllu data/China/China-urdu.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-slovak.conllu China-uyghur.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-slovak.conllu data/China/China-uyghur.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-slovenian.conllu China-tamil.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-slovenian.conllu data/China/China-tamil.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-slovenian.conllu China-ukrainian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-slovenian.conllu data/China/China-ukrainian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-slovenian.conllu China-urdu.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-slovenian.conllu data/China/China-urdu.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-slovenian.conllu China-uyghur.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-slovenian.conllu data/China/China-uyghur.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-tamil.conllu China-ukrainian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-tamil.conllu data/China/China-ukrainian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-tamil.conllu China-urdu.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-tamil.conllu data/China/China-urdu.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-tamil.conllu China-uyghur.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-tamil.conllu data/China/China-uyghur.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-ukrainian.conllu China-urdu.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-ukrainian.conllu data/China/China-urdu.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-ukrainian.conllu China-uyghur.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-ukrainian.conllu data/China/China-uyghur.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-urdu.conllu China-uyghur.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-urdu.conllu data/China/China-uyghur.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-arabic.conllu China-belarusian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-arabic.conllu data/China/China-belarusian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-arabic.conllu China-bulgarian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-arabic.conllu data/China/China-bulgarian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-arabic.conllu China-danish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-arabic.conllu data/China/China-danish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-arabic.conllu China-basque.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-arabic.conllu data/China/China-basque.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-arabic.conllu China-persian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-arabic.conllu data/China/China-persian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-arabic.conllu China-hindi.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-arabic.conllu data/China/China-hindi.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-arabic.conllu China-hungarian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-arabic.conllu data/China/China-hungarian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-arabic.conllu China-dutch.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-arabic.conllu data/China/China-dutch.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-arabic.conllu China-serbian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-arabic.conllu data/China/China-serbian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-arabic.conllu China-swedish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-arabic.conllu data/China/China-swedish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-arabic.conllu China-classical_chinese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-arabic.conllu data/China/China-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-belarusian.conllu China-bulgarian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-belarusian.conllu data/China/China-bulgarian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-belarusian.conllu China-danish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-belarusian.conllu data/China/China-danish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-belarusian.conllu China-basque.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-belarusian.conllu data/China/China-basque.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-belarusian.conllu China-persian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-belarusian.conllu data/China/China-persian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-belarusian.conllu China-hindi.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-belarusian.conllu data/China/China-hindi.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-belarusian.conllu China-hungarian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-belarusian.conllu data/China/China-hungarian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-belarusian.conllu China-dutch.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-belarusian.conllu data/China/China-dutch.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-belarusian.conllu China-serbian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-belarusian.conllu data/China/China-serbian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-belarusian.conllu China-swedish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-belarusian.conllu data/China/China-swedish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-belarusian.conllu China-classical_chinese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-belarusian.conllu data/China/China-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-bulgarian.conllu China-danish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-bulgarian.conllu data/China/China-danish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-bulgarian.conllu China-basque.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-bulgarian.conllu data/China/China-basque.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-bulgarian.conllu China-persian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-bulgarian.conllu data/China/China-persian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-bulgarian.conllu China-hindi.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-bulgarian.conllu data/China/China-hindi.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-bulgarian.conllu China-hungarian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-bulgarian.conllu data/China/China-hungarian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-bulgarian.conllu China-dutch.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-bulgarian.conllu data/China/China-dutch.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-bulgarian.conllu China-serbian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-bulgarian.conllu data/China/China-serbian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-bulgarian.conllu China-swedish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-bulgarian.conllu data/China/China-swedish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-bulgarian.conllu China-classical_chinese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-bulgarian.conllu data/China/China-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-danish.conllu China-basque.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-danish.conllu data/China/China-basque.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-danish.conllu China-persian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-danish.conllu data/China/China-persian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-danish.conllu China-hindi.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-danish.conllu data/China/China-hindi.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-danish.conllu China-hungarian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-danish.conllu data/China/China-hungarian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-danish.conllu China-dutch.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-danish.conllu data/China/China-dutch.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-danish.conllu China-serbian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-danish.conllu data/China/China-serbian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-danish.conllu China-swedish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-danish.conllu data/China/China-swedish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-danish.conllu China-classical_chinese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-danish.conllu data/China/China-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-basque.conllu China-persian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-basque.conllu data/China/China-persian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-basque.conllu China-hindi.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-basque.conllu data/China/China-hindi.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-basque.conllu China-hungarian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-basque.conllu data/China/China-hungarian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-basque.conllu China-dutch.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-basque.conllu data/China/China-dutch.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-basque.conllu China-serbian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-basque.conllu data/China/China-serbian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-basque.conllu China-swedish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-basque.conllu data/China/China-swedish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-basque.conllu China-classical_chinese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-basque.conllu data/China/China-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-persian.conllu China-hindi.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-persian.conllu data/China/China-hindi.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-persian.conllu China-hungarian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-persian.conllu data/China/China-hungarian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-persian.conllu China-dutch.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-persian.conllu data/China/China-dutch.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-persian.conllu China-serbian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-persian.conllu data/China/China-serbian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-persian.conllu China-swedish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-persian.conllu data/China/China-swedish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-persian.conllu China-classical_chinese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-persian.conllu data/China/China-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-hindi.conllu China-hungarian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-hindi.conllu data/China/China-hungarian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-hindi.conllu China-dutch.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-hindi.conllu data/China/China-dutch.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-hindi.conllu China-serbian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-hindi.conllu data/China/China-serbian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-hindi.conllu China-swedish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-hindi.conllu data/China/China-swedish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-hindi.conllu China-classical_chinese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-hindi.conllu data/China/China-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-hungarian.conllu China-dutch.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-hungarian.conllu data/China/China-dutch.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-hungarian.conllu China-serbian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-hungarian.conllu data/China/China-serbian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-hungarian.conllu China-swedish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-hungarian.conllu data/China/China-swedish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-hungarian.conllu China-classical_chinese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-hungarian.conllu data/China/China-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-dutch.conllu China-serbian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-dutch.conllu data/China/China-serbian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-dutch.conllu China-swedish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-dutch.conllu data/China/China-swedish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-dutch.conllu China-classical_chinese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-dutch.conllu data/China/China-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-serbian.conllu China-swedish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-serbian.conllu data/China/China-swedish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-serbian.conllu China-classical_chinese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-serbian.conllu data/China/China-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-swedish.conllu China-classical_chinese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-swedish.conllu data/China/China-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-english.conllu China-czech.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-english.conllu data/China/China-czech.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-english.conllu China-german.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-english.conllu data/China/China-german.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-english.conllu China-spanish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-english.conllu data/China/China-spanish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-english.conllu China-french.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-english.conllu data/China/China-french.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-english.conllu China-galician.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-english.conllu data/China/China-galician.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-english.conllu China-korean.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-english.conllu data/China/China-korean.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-english.conllu China-armenian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-english.conllu data/China/China-armenian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-english.conllu China-italian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-english.conllu data/China/China-italian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-english.conllu China-japanese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-english.conllu data/China/China-japanese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-english.conllu China-portuguese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-english.conllu data/China/China-portuguese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-english.conllu China-romanian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-english.conllu data/China/China-romanian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-english.conllu China-russian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-english.conllu data/China/China-russian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-english.conllu China-finnish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-english.conllu data/China/China-finnish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-english.conllu China-telugu.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-english.conllu data/China/China-telugu.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-english.conllu China-turkish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-english.conllu data/China/China-turkish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-english.conllu China-vietnamese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-english.conllu data/China/China-vietnamese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-english.conllu China-chinese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-english.conllu data/China/China-chinese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-czech.conllu China-german.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-czech.conllu data/China/China-german.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-czech.conllu China-spanish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-czech.conllu data/China/China-spanish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-czech.conllu China-french.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-czech.conllu data/China/China-french.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-czech.conllu China-galician.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-czech.conllu data/China/China-galician.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-czech.conllu China-korean.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-czech.conllu data/China/China-korean.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-czech.conllu China-armenian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-czech.conllu data/China/China-armenian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-czech.conllu China-italian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-czech.conllu data/China/China-italian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-czech.conllu China-japanese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-czech.conllu data/China/China-japanese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-czech.conllu China-portuguese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-czech.conllu data/China/China-portuguese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-czech.conllu China-romanian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-czech.conllu data/China/China-romanian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-czech.conllu China-russian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-czech.conllu data/China/China-russian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-czech.conllu China-finnish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-czech.conllu data/China/China-finnish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-czech.conllu China-telugu.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-czech.conllu data/China/China-telugu.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-czech.conllu China-turkish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-czech.conllu data/China/China-turkish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-czech.conllu China-vietnamese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-czech.conllu data/China/China-vietnamese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-czech.conllu China-chinese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-czech.conllu data/China/China-chinese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-german.conllu China-spanish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-german.conllu data/China/China-spanish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-german.conllu China-french.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-german.conllu data/China/China-french.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-german.conllu China-galician.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-german.conllu data/China/China-galician.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-german.conllu China-korean.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-german.conllu data/China/China-korean.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-german.conllu China-armenian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-german.conllu data/China/China-armenian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-german.conllu China-italian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-german.conllu data/China/China-italian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-german.conllu China-japanese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-german.conllu data/China/China-japanese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-german.conllu China-portuguese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-german.conllu data/China/China-portuguese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-german.conllu China-romanian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-german.conllu data/China/China-romanian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-german.conllu China-russian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-german.conllu data/China/China-russian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-german.conllu China-finnish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-german.conllu data/China/China-finnish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-german.conllu China-telugu.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-german.conllu data/China/China-telugu.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-german.conllu China-turkish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-german.conllu data/China/China-turkish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-german.conllu China-vietnamese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-german.conllu data/China/China-vietnamese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-german.conllu China-chinese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-german.conllu data/China/China-chinese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-spanish.conllu China-french.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-spanish.conllu data/China/China-french.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-spanish.conllu China-galician.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-spanish.conllu data/China/China-galician.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-spanish.conllu China-korean.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-spanish.conllu data/China/China-korean.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-spanish.conllu China-armenian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-spanish.conllu data/China/China-armenian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-spanish.conllu China-italian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-spanish.conllu data/China/China-italian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-spanish.conllu China-japanese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-spanish.conllu data/China/China-japanese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-spanish.conllu China-portuguese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-spanish.conllu data/China/China-portuguese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-spanish.conllu China-romanian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-spanish.conllu data/China/China-romanian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-spanish.conllu China-russian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-spanish.conllu data/China/China-russian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-spanish.conllu China-finnish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-spanish.conllu data/China/China-finnish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-spanish.conllu China-telugu.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-spanish.conllu data/China/China-telugu.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-spanish.conllu China-turkish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-spanish.conllu data/China/China-turkish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-spanish.conllu China-vietnamese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-spanish.conllu data/China/China-vietnamese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-spanish.conllu China-chinese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-spanish.conllu data/China/China-chinese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-french.conllu China-galician.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-french.conllu data/China/China-galician.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-french.conllu China-korean.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-french.conllu data/China/China-korean.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-french.conllu China-armenian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-french.conllu data/China/China-armenian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-french.conllu China-italian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-french.conllu data/China/China-italian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-french.conllu China-japanese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-french.conllu data/China/China-japanese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-french.conllu China-portuguese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-french.conllu data/China/China-portuguese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-french.conllu China-romanian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-french.conllu data/China/China-romanian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-french.conllu China-russian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-french.conllu data/China/China-russian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-french.conllu China-finnish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-french.conllu data/China/China-finnish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-french.conllu China-telugu.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-french.conllu data/China/China-telugu.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-french.conllu China-turkish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-french.conllu data/China/China-turkish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-french.conllu China-vietnamese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-french.conllu data/China/China-vietnamese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-french.conllu China-chinese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-french.conllu data/China/China-chinese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-galician.conllu China-korean.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-galician.conllu data/China/China-korean.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-galician.conllu China-armenian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-galician.conllu data/China/China-armenian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-galician.conllu China-italian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-galician.conllu data/China/China-italian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-galician.conllu China-japanese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-galician.conllu data/China/China-japanese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-galician.conllu China-portuguese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-galician.conllu data/China/China-portuguese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-galician.conllu China-romanian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-galician.conllu data/China/China-romanian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-galician.conllu China-russian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-galician.conllu data/China/China-russian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-galician.conllu China-finnish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-galician.conllu data/China/China-finnish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-galician.conllu China-telugu.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-galician.conllu data/China/China-telugu.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-galician.conllu China-turkish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-galician.conllu data/China/China-turkish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-galician.conllu China-vietnamese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-galician.conllu data/China/China-vietnamese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-galician.conllu China-chinese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-galician.conllu data/China/China-chinese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-korean.conllu China-armenian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-korean.conllu data/China/China-armenian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-korean.conllu China-italian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-korean.conllu data/China/China-italian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-korean.conllu China-japanese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-korean.conllu data/China/China-japanese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-korean.conllu China-portuguese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-korean.conllu data/China/China-portuguese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-korean.conllu China-romanian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-korean.conllu data/China/China-romanian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-korean.conllu China-russian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-korean.conllu data/China/China-russian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-korean.conllu China-finnish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-korean.conllu data/China/China-finnish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-korean.conllu China-telugu.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-korean.conllu data/China/China-telugu.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-korean.conllu China-turkish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-korean.conllu data/China/China-turkish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-korean.conllu China-vietnamese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-korean.conllu data/China/China-vietnamese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-korean.conllu China-chinese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-korean.conllu data/China/China-chinese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-armenian.conllu China-italian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-armenian.conllu data/China/China-italian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-armenian.conllu China-japanese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-armenian.conllu data/China/China-japanese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-armenian.conllu China-portuguese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-armenian.conllu data/China/China-portuguese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-armenian.conllu China-romanian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-armenian.conllu data/China/China-romanian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-armenian.conllu China-russian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-armenian.conllu data/China/China-russian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-armenian.conllu China-finnish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-armenian.conllu data/China/China-finnish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-armenian.conllu China-telugu.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-armenian.conllu data/China/China-telugu.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-armenian.conllu China-turkish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-armenian.conllu data/China/China-turkish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-armenian.conllu China-vietnamese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-armenian.conllu data/China/China-vietnamese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-armenian.conllu China-chinese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-armenian.conllu data/China/China-chinese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-italian.conllu China-japanese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-italian.conllu data/China/China-japanese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-italian.conllu China-portuguese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-italian.conllu data/China/China-portuguese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-italian.conllu China-romanian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-italian.conllu data/China/China-romanian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-italian.conllu China-russian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-italian.conllu data/China/China-russian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-italian.conllu China-finnish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-italian.conllu data/China/China-finnish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-italian.conllu China-telugu.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-italian.conllu data/China/China-telugu.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-italian.conllu China-turkish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-italian.conllu data/China/China-turkish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-italian.conllu China-vietnamese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-italian.conllu data/China/China-vietnamese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-italian.conllu China-chinese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-italian.conllu data/China/China-chinese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-japanese.conllu China-portuguese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-japanese.conllu data/China/China-portuguese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-japanese.conllu China-romanian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-japanese.conllu data/China/China-romanian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-japanese.conllu China-russian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-japanese.conllu data/China/China-russian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-japanese.conllu China-finnish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-japanese.conllu data/China/China-finnish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-japanese.conllu China-telugu.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-japanese.conllu data/China/China-telugu.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-japanese.conllu China-turkish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-japanese.conllu data/China/China-turkish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-japanese.conllu China-vietnamese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-japanese.conllu data/China/China-vietnamese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-japanese.conllu China-chinese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-japanese.conllu data/China/China-chinese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-portuguese.conllu China-romanian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-portuguese.conllu data/China/China-romanian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-portuguese.conllu China-russian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-portuguese.conllu data/China/China-russian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-portuguese.conllu China-finnish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-portuguese.conllu data/China/China-finnish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-portuguese.conllu China-telugu.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-portuguese.conllu data/China/China-telugu.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-portuguese.conllu China-turkish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-portuguese.conllu data/China/China-turkish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-portuguese.conllu China-vietnamese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-portuguese.conllu data/China/China-vietnamese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-portuguese.conllu China-chinese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-portuguese.conllu data/China/China-chinese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-romanian.conllu China-russian.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-romanian.conllu data/China/China-russian.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-romanian.conllu China-finnish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-romanian.conllu data/China/China-finnish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-romanian.conllu China-telugu.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-romanian.conllu data/China/China-telugu.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-romanian.conllu China-turkish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-romanian.conllu data/China/China-turkish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-romanian.conllu China-vietnamese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-romanian.conllu data/China/China-vietnamese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-romanian.conllu China-chinese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-romanian.conllu data/China/China-chinese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-russian.conllu China-finnish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-russian.conllu data/China/China-finnish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-russian.conllu China-telugu.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-russian.conllu data/China/China-telugu.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-russian.conllu China-turkish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-russian.conllu data/China/China-turkish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-russian.conllu China-vietnamese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-russian.conllu data/China/China-vietnamese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-russian.conllu China-chinese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-russian.conllu data/China/China-chinese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-finnish.conllu China-telugu.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-finnish.conllu data/China/China-telugu.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-finnish.conllu China-turkish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-finnish.conllu data/China/China-turkish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-finnish.conllu China-vietnamese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-finnish.conllu data/China/China-vietnamese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-finnish.conllu China-chinese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-finnish.conllu data/China/China-chinese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-telugu.conllu China-turkish.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-telugu.conllu data/China/China-turkish.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-telugu.conllu China-vietnamese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-telugu.conllu data/China/China-vietnamese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-telugu.conllu China-chinese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-telugu.conllu data/China/China-chinese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-turkish.conllu China-vietnamese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-turkish.conllu data/China/China-vietnamese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-turkish.conllu China-chinese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-turkish.conllu data/China/China-chinese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
echo China-vietnamese.conllu China-chinese.conllu >> cosine-sim-per-topic/China-cosine-sim.txt ; 
gfud cosine-similarity data/China/China-vietnamese.conllu data/China/China-chinese.conllu DEPREL >> cosine-sim-per-topic/China-cosine-sim.txt ; 
} 
topic_combinations