#! /bin/bash 
function topic_combinations { 
echo Dog-irish.conllu Dog-scottish_gaelic.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-irish.conllu data/Dog/Dog-scottish_gaelic.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-irish.conllu Dog-gothic.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-irish.conllu data/Dog/Dog-gothic.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-irish.conllu Dog-latin.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-irish.conllu data/Dog/Dog-latin.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-irish.conllu Dog-maltese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-irish.conllu data/Dog/Dog-maltese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-irish.conllu Dog-old_church_slavonic.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-irish.conllu data/Dog/Dog-old_church_slavonic.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-irish.conllu Dog-classical_chinese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-irish.conllu data/Dog/Dog-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-irish.conllu Dog-wolof.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-irish.conllu data/Dog/Dog-wolof.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-scottish_gaelic.conllu Dog-gothic.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-scottish_gaelic.conllu data/Dog/Dog-gothic.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-scottish_gaelic.conllu Dog-latin.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-scottish_gaelic.conllu data/Dog/Dog-latin.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-scottish_gaelic.conllu Dog-maltese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-scottish_gaelic.conllu data/Dog/Dog-maltese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-scottish_gaelic.conllu Dog-old_church_slavonic.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-scottish_gaelic.conllu data/Dog/Dog-old_church_slavonic.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-scottish_gaelic.conllu Dog-classical_chinese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-scottish_gaelic.conllu data/Dog/Dog-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-scottish_gaelic.conllu Dog-wolof.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-scottish_gaelic.conllu data/Dog/Dog-wolof.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-gothic.conllu Dog-latin.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-gothic.conllu data/Dog/Dog-latin.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-gothic.conllu Dog-maltese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-gothic.conllu data/Dog/Dog-maltese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-gothic.conllu Dog-old_church_slavonic.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-gothic.conllu data/Dog/Dog-old_church_slavonic.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-gothic.conllu Dog-classical_chinese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-gothic.conllu data/Dog/Dog-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-gothic.conllu Dog-wolof.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-gothic.conllu data/Dog/Dog-wolof.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-latin.conllu Dog-maltese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-latin.conllu data/Dog/Dog-maltese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-latin.conllu Dog-old_church_slavonic.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-latin.conllu data/Dog/Dog-old_church_slavonic.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-latin.conllu Dog-classical_chinese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-latin.conllu data/Dog/Dog-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-latin.conllu Dog-wolof.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-latin.conllu data/Dog/Dog-wolof.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-maltese.conllu Dog-old_church_slavonic.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-maltese.conllu data/Dog/Dog-old_church_slavonic.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-maltese.conllu Dog-classical_chinese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-maltese.conllu data/Dog/Dog-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-maltese.conllu Dog-wolof.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-maltese.conllu data/Dog/Dog-wolof.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-old_church_slavonic.conllu Dog-classical_chinese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-old_church_slavonic.conllu data/Dog/Dog-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-old_church_slavonic.conllu Dog-wolof.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-old_church_slavonic.conllu data/Dog/Dog-wolof.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-classical_chinese.conllu Dog-wolof.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-classical_chinese.conllu data/Dog/Dog-wolof.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-arabic.conllu Dog-belarusian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-arabic.conllu data/Dog/Dog-belarusian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-arabic.conllu Dog-danish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-arabic.conllu data/Dog/Dog-danish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-arabic.conllu Dog-greek.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-arabic.conllu data/Dog/Dog-greek.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-arabic.conllu Dog-basque.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-arabic.conllu data/Dog/Dog-basque.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-arabic.conllu Dog-hindi.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-arabic.conllu data/Dog/Dog-hindi.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-arabic.conllu Dog-croatian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-arabic.conllu data/Dog/Dog-croatian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-arabic.conllu Dog-lithuanian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-arabic.conllu data/Dog/Dog-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-arabic.conllu Dog-marathi.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-arabic.conllu data/Dog/Dog-marathi.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-arabic.conllu Dog-romanian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-arabic.conllu data/Dog/Dog-romanian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-arabic.conllu Dog-sanskrit.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-arabic.conllu data/Dog/Dog-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-arabic.conllu Dog-tamil.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-arabic.conllu data/Dog/Dog-tamil.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-arabic.conllu Dog-telugu.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-arabic.conllu data/Dog/Dog-telugu.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-arabic.conllu Dog-urdu.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-arabic.conllu data/Dog/Dog-urdu.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-arabic.conllu Dog-uyghur.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-arabic.conllu data/Dog/Dog-uyghur.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-belarusian.conllu Dog-danish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-belarusian.conllu data/Dog/Dog-danish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-belarusian.conllu Dog-greek.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-belarusian.conllu data/Dog/Dog-greek.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-belarusian.conllu Dog-basque.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-belarusian.conllu data/Dog/Dog-basque.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-belarusian.conllu Dog-hindi.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-belarusian.conllu data/Dog/Dog-hindi.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-belarusian.conllu Dog-croatian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-belarusian.conllu data/Dog/Dog-croatian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-belarusian.conllu Dog-lithuanian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-belarusian.conllu data/Dog/Dog-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-belarusian.conllu Dog-marathi.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-belarusian.conllu data/Dog/Dog-marathi.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-belarusian.conllu Dog-romanian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-belarusian.conllu data/Dog/Dog-romanian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-belarusian.conllu Dog-sanskrit.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-belarusian.conllu data/Dog/Dog-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-belarusian.conllu Dog-tamil.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-belarusian.conllu data/Dog/Dog-tamil.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-belarusian.conllu Dog-telugu.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-belarusian.conllu data/Dog/Dog-telugu.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-belarusian.conllu Dog-urdu.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-belarusian.conllu data/Dog/Dog-urdu.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-belarusian.conllu Dog-uyghur.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-belarusian.conllu data/Dog/Dog-uyghur.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-danish.conllu Dog-greek.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-danish.conllu data/Dog/Dog-greek.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-danish.conllu Dog-basque.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-danish.conllu data/Dog/Dog-basque.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-danish.conllu Dog-hindi.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-danish.conllu data/Dog/Dog-hindi.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-danish.conllu Dog-croatian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-danish.conllu data/Dog/Dog-croatian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-danish.conllu Dog-lithuanian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-danish.conllu data/Dog/Dog-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-danish.conllu Dog-marathi.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-danish.conllu data/Dog/Dog-marathi.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-danish.conllu Dog-romanian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-danish.conllu data/Dog/Dog-romanian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-danish.conllu Dog-sanskrit.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-danish.conllu data/Dog/Dog-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-danish.conllu Dog-tamil.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-danish.conllu data/Dog/Dog-tamil.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-danish.conllu Dog-telugu.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-danish.conllu data/Dog/Dog-telugu.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-danish.conllu Dog-urdu.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-danish.conllu data/Dog/Dog-urdu.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-danish.conllu Dog-uyghur.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-danish.conllu data/Dog/Dog-uyghur.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-greek.conllu Dog-basque.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-greek.conllu data/Dog/Dog-basque.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-greek.conllu Dog-hindi.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-greek.conllu data/Dog/Dog-hindi.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-greek.conllu Dog-croatian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-greek.conllu data/Dog/Dog-croatian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-greek.conllu Dog-lithuanian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-greek.conllu data/Dog/Dog-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-greek.conllu Dog-marathi.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-greek.conllu data/Dog/Dog-marathi.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-greek.conllu Dog-romanian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-greek.conllu data/Dog/Dog-romanian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-greek.conllu Dog-sanskrit.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-greek.conllu data/Dog/Dog-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-greek.conllu Dog-tamil.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-greek.conllu data/Dog/Dog-tamil.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-greek.conllu Dog-telugu.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-greek.conllu data/Dog/Dog-telugu.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-greek.conllu Dog-urdu.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-greek.conllu data/Dog/Dog-urdu.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-greek.conllu Dog-uyghur.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-greek.conllu data/Dog/Dog-uyghur.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-basque.conllu Dog-hindi.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-basque.conllu data/Dog/Dog-hindi.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-basque.conllu Dog-croatian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-basque.conllu data/Dog/Dog-croatian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-basque.conllu Dog-lithuanian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-basque.conllu data/Dog/Dog-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-basque.conllu Dog-marathi.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-basque.conllu data/Dog/Dog-marathi.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-basque.conllu Dog-romanian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-basque.conllu data/Dog/Dog-romanian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-basque.conllu Dog-sanskrit.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-basque.conllu data/Dog/Dog-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-basque.conllu Dog-tamil.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-basque.conllu data/Dog/Dog-tamil.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-basque.conllu Dog-telugu.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-basque.conllu data/Dog/Dog-telugu.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-basque.conllu Dog-urdu.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-basque.conllu data/Dog/Dog-urdu.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-basque.conllu Dog-uyghur.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-basque.conllu data/Dog/Dog-uyghur.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-hindi.conllu Dog-croatian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-hindi.conllu data/Dog/Dog-croatian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-hindi.conllu Dog-lithuanian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-hindi.conllu data/Dog/Dog-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-hindi.conllu Dog-marathi.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-hindi.conllu data/Dog/Dog-marathi.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-hindi.conllu Dog-romanian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-hindi.conllu data/Dog/Dog-romanian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-hindi.conllu Dog-sanskrit.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-hindi.conllu data/Dog/Dog-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-hindi.conllu Dog-tamil.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-hindi.conllu data/Dog/Dog-tamil.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-hindi.conllu Dog-telugu.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-hindi.conllu data/Dog/Dog-telugu.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-hindi.conllu Dog-urdu.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-hindi.conllu data/Dog/Dog-urdu.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-hindi.conllu Dog-uyghur.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-hindi.conllu data/Dog/Dog-uyghur.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-croatian.conllu Dog-lithuanian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-croatian.conllu data/Dog/Dog-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-croatian.conllu Dog-marathi.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-croatian.conllu data/Dog/Dog-marathi.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-croatian.conllu Dog-romanian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-croatian.conllu data/Dog/Dog-romanian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-croatian.conllu Dog-sanskrit.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-croatian.conllu data/Dog/Dog-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-croatian.conllu Dog-tamil.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-croatian.conllu data/Dog/Dog-tamil.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-croatian.conllu Dog-telugu.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-croatian.conllu data/Dog/Dog-telugu.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-croatian.conllu Dog-urdu.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-croatian.conllu data/Dog/Dog-urdu.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-croatian.conllu Dog-uyghur.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-croatian.conllu data/Dog/Dog-uyghur.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-lithuanian.conllu Dog-marathi.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-lithuanian.conllu data/Dog/Dog-marathi.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-lithuanian.conllu Dog-romanian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-lithuanian.conllu data/Dog/Dog-romanian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-lithuanian.conllu Dog-sanskrit.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-lithuanian.conllu data/Dog/Dog-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-lithuanian.conllu Dog-tamil.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-lithuanian.conllu data/Dog/Dog-tamil.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-lithuanian.conllu Dog-telugu.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-lithuanian.conllu data/Dog/Dog-telugu.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-lithuanian.conllu Dog-urdu.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-lithuanian.conllu data/Dog/Dog-urdu.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-lithuanian.conllu Dog-uyghur.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-lithuanian.conllu data/Dog/Dog-uyghur.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-marathi.conllu Dog-romanian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-marathi.conllu data/Dog/Dog-romanian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-marathi.conllu Dog-sanskrit.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-marathi.conllu data/Dog/Dog-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-marathi.conllu Dog-tamil.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-marathi.conllu data/Dog/Dog-tamil.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-marathi.conllu Dog-telugu.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-marathi.conllu data/Dog/Dog-telugu.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-marathi.conllu Dog-urdu.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-marathi.conllu data/Dog/Dog-urdu.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-marathi.conllu Dog-uyghur.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-marathi.conllu data/Dog/Dog-uyghur.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-romanian.conllu Dog-sanskrit.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-romanian.conllu data/Dog/Dog-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-romanian.conllu Dog-tamil.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-romanian.conllu data/Dog/Dog-tamil.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-romanian.conllu Dog-telugu.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-romanian.conllu data/Dog/Dog-telugu.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-romanian.conllu Dog-urdu.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-romanian.conllu data/Dog/Dog-urdu.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-romanian.conllu Dog-uyghur.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-romanian.conllu data/Dog/Dog-uyghur.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-sanskrit.conllu Dog-tamil.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-sanskrit.conllu data/Dog/Dog-tamil.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-sanskrit.conllu Dog-telugu.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-sanskrit.conllu data/Dog/Dog-telugu.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-sanskrit.conllu Dog-urdu.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-sanskrit.conllu data/Dog/Dog-urdu.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-sanskrit.conllu Dog-uyghur.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-sanskrit.conllu data/Dog/Dog-uyghur.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-tamil.conllu Dog-telugu.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-tamil.conllu data/Dog/Dog-telugu.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-tamil.conllu Dog-urdu.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-tamil.conllu data/Dog/Dog-urdu.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-tamil.conllu Dog-uyghur.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-tamil.conllu data/Dog/Dog-uyghur.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-telugu.conllu Dog-urdu.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-telugu.conllu data/Dog/Dog-urdu.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-telugu.conllu Dog-uyghur.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-telugu.conllu data/Dog/Dog-uyghur.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-urdu.conllu Dog-uyghur.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-urdu.conllu data/Dog/Dog-uyghur.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-afrikaans.conllu Dog-bulgarian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-afrikaans.conllu data/Dog/Dog-bulgarian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-afrikaans.conllu Dog-welsh.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-afrikaans.conllu data/Dog/Dog-welsh.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-afrikaans.conllu Dog-estonian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-afrikaans.conllu data/Dog/Dog-estonian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-afrikaans.conllu Dog-persian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-afrikaans.conllu data/Dog/Dog-persian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-afrikaans.conllu Dog-galician.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-afrikaans.conllu data/Dog/Dog-galician.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-afrikaans.conllu Dog-korean.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-afrikaans.conllu data/Dog/Dog-korean.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-afrikaans.conllu Dog-armenian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-afrikaans.conllu data/Dog/Dog-armenian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-afrikaans.conllu Dog-indonesian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-afrikaans.conllu data/Dog/Dog-indonesian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-afrikaans.conllu Dog-hebrew.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-afrikaans.conllu data/Dog/Dog-hebrew.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-afrikaans.conllu Dog-kazakh.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-afrikaans.conllu data/Dog/Dog-kazakh.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-afrikaans.conllu Dog-latvian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-afrikaans.conllu data/Dog/Dog-latvian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-afrikaans.conllu Dog-polish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-afrikaans.conllu data/Dog/Dog-polish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-afrikaans.conllu Dog-slovak.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-afrikaans.conllu data/Dog/Dog-slovak.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-afrikaans.conllu Dog-slovenian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-afrikaans.conllu data/Dog/Dog-slovenian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-afrikaans.conllu Dog-serbian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-afrikaans.conllu data/Dog/Dog-serbian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-afrikaans.conllu Dog-finnish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-afrikaans.conllu data/Dog/Dog-finnish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-afrikaans.conllu Dog-swedish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-afrikaans.conllu data/Dog/Dog-swedish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-afrikaans.conllu Dog-ukrainian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-afrikaans.conllu data/Dog/Dog-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-afrikaans.conllu Dog-vietnamese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-afrikaans.conllu data/Dog/Dog-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-afrikaans.conllu Dog-chinese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-afrikaans.conllu data/Dog/Dog-chinese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-bulgarian.conllu Dog-welsh.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-bulgarian.conllu data/Dog/Dog-welsh.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-bulgarian.conllu Dog-estonian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-bulgarian.conllu data/Dog/Dog-estonian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-bulgarian.conllu Dog-persian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-bulgarian.conllu data/Dog/Dog-persian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-bulgarian.conllu Dog-galician.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-bulgarian.conllu data/Dog/Dog-galician.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-bulgarian.conllu Dog-korean.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-bulgarian.conllu data/Dog/Dog-korean.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-bulgarian.conllu Dog-armenian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-bulgarian.conllu data/Dog/Dog-armenian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-bulgarian.conllu Dog-indonesian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-bulgarian.conllu data/Dog/Dog-indonesian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-bulgarian.conllu Dog-hebrew.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-bulgarian.conllu data/Dog/Dog-hebrew.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-bulgarian.conllu Dog-kazakh.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-bulgarian.conllu data/Dog/Dog-kazakh.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-bulgarian.conllu Dog-latvian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-bulgarian.conllu data/Dog/Dog-latvian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-bulgarian.conllu Dog-polish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-bulgarian.conllu data/Dog/Dog-polish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-bulgarian.conllu Dog-slovak.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-bulgarian.conllu data/Dog/Dog-slovak.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-bulgarian.conllu Dog-slovenian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-bulgarian.conllu data/Dog/Dog-slovenian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-bulgarian.conllu Dog-serbian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-bulgarian.conllu data/Dog/Dog-serbian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-bulgarian.conllu Dog-finnish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-bulgarian.conllu data/Dog/Dog-finnish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-bulgarian.conllu Dog-swedish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-bulgarian.conllu data/Dog/Dog-swedish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-bulgarian.conllu Dog-ukrainian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-bulgarian.conllu data/Dog/Dog-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-bulgarian.conllu Dog-vietnamese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-bulgarian.conllu data/Dog/Dog-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-bulgarian.conllu Dog-chinese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-bulgarian.conllu data/Dog/Dog-chinese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-welsh.conllu Dog-estonian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-welsh.conllu data/Dog/Dog-estonian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-welsh.conllu Dog-persian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-welsh.conllu data/Dog/Dog-persian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-welsh.conllu Dog-galician.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-welsh.conllu data/Dog/Dog-galician.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-welsh.conllu Dog-korean.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-welsh.conllu data/Dog/Dog-korean.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-welsh.conllu Dog-armenian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-welsh.conllu data/Dog/Dog-armenian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-welsh.conllu Dog-indonesian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-welsh.conllu data/Dog/Dog-indonesian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-welsh.conllu Dog-hebrew.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-welsh.conllu data/Dog/Dog-hebrew.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-welsh.conllu Dog-kazakh.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-welsh.conllu data/Dog/Dog-kazakh.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-welsh.conllu Dog-latvian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-welsh.conllu data/Dog/Dog-latvian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-welsh.conllu Dog-polish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-welsh.conllu data/Dog/Dog-polish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-welsh.conllu Dog-slovak.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-welsh.conllu data/Dog/Dog-slovak.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-welsh.conllu Dog-slovenian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-welsh.conllu data/Dog/Dog-slovenian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-welsh.conllu Dog-serbian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-welsh.conllu data/Dog/Dog-serbian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-welsh.conllu Dog-finnish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-welsh.conllu data/Dog/Dog-finnish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-welsh.conllu Dog-swedish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-welsh.conllu data/Dog/Dog-swedish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-welsh.conllu Dog-ukrainian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-welsh.conllu data/Dog/Dog-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-welsh.conllu Dog-vietnamese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-welsh.conllu data/Dog/Dog-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-welsh.conllu Dog-chinese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-welsh.conllu data/Dog/Dog-chinese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-estonian.conllu Dog-persian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-estonian.conllu data/Dog/Dog-persian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-estonian.conllu Dog-galician.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-estonian.conllu data/Dog/Dog-galician.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-estonian.conllu Dog-korean.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-estonian.conllu data/Dog/Dog-korean.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-estonian.conllu Dog-armenian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-estonian.conllu data/Dog/Dog-armenian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-estonian.conllu Dog-indonesian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-estonian.conllu data/Dog/Dog-indonesian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-estonian.conllu Dog-hebrew.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-estonian.conllu data/Dog/Dog-hebrew.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-estonian.conllu Dog-kazakh.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-estonian.conllu data/Dog/Dog-kazakh.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-estonian.conllu Dog-latvian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-estonian.conllu data/Dog/Dog-latvian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-estonian.conllu Dog-polish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-estonian.conllu data/Dog/Dog-polish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-estonian.conllu Dog-slovak.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-estonian.conllu data/Dog/Dog-slovak.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-estonian.conllu Dog-slovenian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-estonian.conllu data/Dog/Dog-slovenian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-estonian.conllu Dog-serbian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-estonian.conllu data/Dog/Dog-serbian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-estonian.conllu Dog-finnish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-estonian.conllu data/Dog/Dog-finnish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-estonian.conllu Dog-swedish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-estonian.conllu data/Dog/Dog-swedish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-estonian.conllu Dog-ukrainian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-estonian.conllu data/Dog/Dog-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-estonian.conllu Dog-vietnamese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-estonian.conllu data/Dog/Dog-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-estonian.conllu Dog-chinese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-estonian.conllu data/Dog/Dog-chinese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-persian.conllu Dog-galician.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-persian.conllu data/Dog/Dog-galician.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-persian.conllu Dog-korean.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-persian.conllu data/Dog/Dog-korean.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-persian.conllu Dog-armenian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-persian.conllu data/Dog/Dog-armenian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-persian.conllu Dog-indonesian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-persian.conllu data/Dog/Dog-indonesian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-persian.conllu Dog-hebrew.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-persian.conllu data/Dog/Dog-hebrew.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-persian.conllu Dog-kazakh.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-persian.conllu data/Dog/Dog-kazakh.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-persian.conllu Dog-latvian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-persian.conllu data/Dog/Dog-latvian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-persian.conllu Dog-polish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-persian.conllu data/Dog/Dog-polish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-persian.conllu Dog-slovak.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-persian.conllu data/Dog/Dog-slovak.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-persian.conllu Dog-slovenian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-persian.conllu data/Dog/Dog-slovenian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-persian.conllu Dog-serbian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-persian.conllu data/Dog/Dog-serbian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-persian.conllu Dog-finnish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-persian.conllu data/Dog/Dog-finnish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-persian.conllu Dog-swedish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-persian.conllu data/Dog/Dog-swedish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-persian.conllu Dog-ukrainian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-persian.conllu data/Dog/Dog-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-persian.conllu Dog-vietnamese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-persian.conllu data/Dog/Dog-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-persian.conllu Dog-chinese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-persian.conllu data/Dog/Dog-chinese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-galician.conllu Dog-korean.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-galician.conllu data/Dog/Dog-korean.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-galician.conllu Dog-armenian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-galician.conllu data/Dog/Dog-armenian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-galician.conllu Dog-indonesian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-galician.conllu data/Dog/Dog-indonesian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-galician.conllu Dog-hebrew.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-galician.conllu data/Dog/Dog-hebrew.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-galician.conllu Dog-kazakh.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-galician.conllu data/Dog/Dog-kazakh.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-galician.conllu Dog-latvian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-galician.conllu data/Dog/Dog-latvian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-galician.conllu Dog-polish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-galician.conllu data/Dog/Dog-polish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-galician.conllu Dog-slovak.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-galician.conllu data/Dog/Dog-slovak.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-galician.conllu Dog-slovenian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-galician.conllu data/Dog/Dog-slovenian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-galician.conllu Dog-serbian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-galician.conllu data/Dog/Dog-serbian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-galician.conllu Dog-finnish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-galician.conllu data/Dog/Dog-finnish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-galician.conllu Dog-swedish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-galician.conllu data/Dog/Dog-swedish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-galician.conllu Dog-ukrainian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-galician.conllu data/Dog/Dog-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-galician.conllu Dog-vietnamese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-galician.conllu data/Dog/Dog-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-galician.conllu Dog-chinese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-galician.conllu data/Dog/Dog-chinese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-korean.conllu Dog-armenian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-korean.conllu data/Dog/Dog-armenian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-korean.conllu Dog-indonesian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-korean.conllu data/Dog/Dog-indonesian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-korean.conllu Dog-hebrew.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-korean.conllu data/Dog/Dog-hebrew.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-korean.conllu Dog-kazakh.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-korean.conllu data/Dog/Dog-kazakh.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-korean.conllu Dog-latvian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-korean.conllu data/Dog/Dog-latvian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-korean.conllu Dog-polish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-korean.conllu data/Dog/Dog-polish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-korean.conllu Dog-slovak.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-korean.conllu data/Dog/Dog-slovak.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-korean.conllu Dog-slovenian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-korean.conllu data/Dog/Dog-slovenian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-korean.conllu Dog-serbian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-korean.conllu data/Dog/Dog-serbian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-korean.conllu Dog-finnish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-korean.conllu data/Dog/Dog-finnish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-korean.conllu Dog-swedish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-korean.conllu data/Dog/Dog-swedish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-korean.conllu Dog-ukrainian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-korean.conllu data/Dog/Dog-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-korean.conllu Dog-vietnamese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-korean.conllu data/Dog/Dog-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-korean.conllu Dog-chinese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-korean.conllu data/Dog/Dog-chinese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-armenian.conllu Dog-indonesian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-armenian.conllu data/Dog/Dog-indonesian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-armenian.conllu Dog-hebrew.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-armenian.conllu data/Dog/Dog-hebrew.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-armenian.conllu Dog-kazakh.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-armenian.conllu data/Dog/Dog-kazakh.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-armenian.conllu Dog-latvian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-armenian.conllu data/Dog/Dog-latvian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-armenian.conllu Dog-polish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-armenian.conllu data/Dog/Dog-polish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-armenian.conllu Dog-slovak.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-armenian.conllu data/Dog/Dog-slovak.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-armenian.conllu Dog-slovenian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-armenian.conllu data/Dog/Dog-slovenian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-armenian.conllu Dog-serbian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-armenian.conllu data/Dog/Dog-serbian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-armenian.conllu Dog-finnish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-armenian.conllu data/Dog/Dog-finnish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-armenian.conllu Dog-swedish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-armenian.conllu data/Dog/Dog-swedish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-armenian.conllu Dog-ukrainian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-armenian.conllu data/Dog/Dog-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-armenian.conllu Dog-vietnamese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-armenian.conllu data/Dog/Dog-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-armenian.conllu Dog-chinese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-armenian.conllu data/Dog/Dog-chinese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-indonesian.conllu Dog-hebrew.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-indonesian.conllu data/Dog/Dog-hebrew.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-indonesian.conllu Dog-kazakh.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-indonesian.conllu data/Dog/Dog-kazakh.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-indonesian.conllu Dog-latvian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-indonesian.conllu data/Dog/Dog-latvian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-indonesian.conllu Dog-polish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-indonesian.conllu data/Dog/Dog-polish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-indonesian.conllu Dog-slovak.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-indonesian.conllu data/Dog/Dog-slovak.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-indonesian.conllu Dog-slovenian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-indonesian.conllu data/Dog/Dog-slovenian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-indonesian.conllu Dog-serbian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-indonesian.conllu data/Dog/Dog-serbian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-indonesian.conllu Dog-finnish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-indonesian.conllu data/Dog/Dog-finnish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-indonesian.conllu Dog-swedish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-indonesian.conllu data/Dog/Dog-swedish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-indonesian.conllu Dog-ukrainian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-indonesian.conllu data/Dog/Dog-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-indonesian.conllu Dog-vietnamese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-indonesian.conllu data/Dog/Dog-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-indonesian.conllu Dog-chinese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-indonesian.conllu data/Dog/Dog-chinese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-hebrew.conllu Dog-kazakh.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-hebrew.conllu data/Dog/Dog-kazakh.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-hebrew.conllu Dog-latvian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-hebrew.conllu data/Dog/Dog-latvian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-hebrew.conllu Dog-polish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-hebrew.conllu data/Dog/Dog-polish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-hebrew.conllu Dog-slovak.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-hebrew.conllu data/Dog/Dog-slovak.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-hebrew.conllu Dog-slovenian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-hebrew.conllu data/Dog/Dog-slovenian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-hebrew.conllu Dog-serbian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-hebrew.conllu data/Dog/Dog-serbian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-hebrew.conllu Dog-finnish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-hebrew.conllu data/Dog/Dog-finnish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-hebrew.conllu Dog-swedish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-hebrew.conllu data/Dog/Dog-swedish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-hebrew.conllu Dog-ukrainian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-hebrew.conllu data/Dog/Dog-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-hebrew.conllu Dog-vietnamese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-hebrew.conllu data/Dog/Dog-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-hebrew.conllu Dog-chinese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-hebrew.conllu data/Dog/Dog-chinese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-kazakh.conllu Dog-latvian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-kazakh.conllu data/Dog/Dog-latvian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-kazakh.conllu Dog-polish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-kazakh.conllu data/Dog/Dog-polish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-kazakh.conllu Dog-slovak.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-kazakh.conllu data/Dog/Dog-slovak.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-kazakh.conllu Dog-slovenian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-kazakh.conllu data/Dog/Dog-slovenian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-kazakh.conllu Dog-serbian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-kazakh.conllu data/Dog/Dog-serbian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-kazakh.conllu Dog-finnish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-kazakh.conllu data/Dog/Dog-finnish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-kazakh.conllu Dog-swedish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-kazakh.conllu data/Dog/Dog-swedish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-kazakh.conllu Dog-ukrainian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-kazakh.conllu data/Dog/Dog-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-kazakh.conllu Dog-vietnamese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-kazakh.conllu data/Dog/Dog-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-kazakh.conllu Dog-chinese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-kazakh.conllu data/Dog/Dog-chinese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-latvian.conllu Dog-polish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-latvian.conllu data/Dog/Dog-polish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-latvian.conllu Dog-slovak.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-latvian.conllu data/Dog/Dog-slovak.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-latvian.conllu Dog-slovenian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-latvian.conllu data/Dog/Dog-slovenian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-latvian.conllu Dog-serbian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-latvian.conllu data/Dog/Dog-serbian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-latvian.conllu Dog-finnish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-latvian.conllu data/Dog/Dog-finnish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-latvian.conllu Dog-swedish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-latvian.conllu data/Dog/Dog-swedish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-latvian.conllu Dog-ukrainian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-latvian.conllu data/Dog/Dog-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-latvian.conllu Dog-vietnamese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-latvian.conllu data/Dog/Dog-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-latvian.conllu Dog-chinese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-latvian.conllu data/Dog/Dog-chinese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-polish.conllu Dog-slovak.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-polish.conllu data/Dog/Dog-slovak.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-polish.conllu Dog-slovenian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-polish.conllu data/Dog/Dog-slovenian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-polish.conllu Dog-serbian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-polish.conllu data/Dog/Dog-serbian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-polish.conllu Dog-finnish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-polish.conllu data/Dog/Dog-finnish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-polish.conllu Dog-swedish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-polish.conllu data/Dog/Dog-swedish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-polish.conllu Dog-ukrainian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-polish.conllu data/Dog/Dog-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-polish.conllu Dog-vietnamese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-polish.conllu data/Dog/Dog-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-polish.conllu Dog-chinese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-polish.conllu data/Dog/Dog-chinese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-slovak.conllu Dog-slovenian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-slovak.conllu data/Dog/Dog-slovenian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-slovak.conllu Dog-serbian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-slovak.conllu data/Dog/Dog-serbian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-slovak.conllu Dog-finnish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-slovak.conllu data/Dog/Dog-finnish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-slovak.conllu Dog-swedish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-slovak.conllu data/Dog/Dog-swedish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-slovak.conllu Dog-ukrainian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-slovak.conllu data/Dog/Dog-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-slovak.conllu Dog-vietnamese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-slovak.conllu data/Dog/Dog-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-slovak.conllu Dog-chinese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-slovak.conllu data/Dog/Dog-chinese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-slovenian.conllu Dog-serbian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-slovenian.conllu data/Dog/Dog-serbian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-slovenian.conllu Dog-finnish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-slovenian.conllu data/Dog/Dog-finnish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-slovenian.conllu Dog-swedish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-slovenian.conllu data/Dog/Dog-swedish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-slovenian.conllu Dog-ukrainian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-slovenian.conllu data/Dog/Dog-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-slovenian.conllu Dog-vietnamese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-slovenian.conllu data/Dog/Dog-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-slovenian.conllu Dog-chinese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-slovenian.conllu data/Dog/Dog-chinese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-serbian.conllu Dog-finnish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-serbian.conllu data/Dog/Dog-finnish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-serbian.conllu Dog-swedish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-serbian.conllu data/Dog/Dog-swedish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-serbian.conllu Dog-ukrainian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-serbian.conllu data/Dog/Dog-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-serbian.conllu Dog-vietnamese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-serbian.conllu data/Dog/Dog-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-serbian.conllu Dog-chinese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-serbian.conllu data/Dog/Dog-chinese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-finnish.conllu Dog-swedish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-finnish.conllu data/Dog/Dog-swedish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-finnish.conllu Dog-ukrainian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-finnish.conllu data/Dog/Dog-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-finnish.conllu Dog-vietnamese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-finnish.conllu data/Dog/Dog-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-finnish.conllu Dog-chinese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-finnish.conllu data/Dog/Dog-chinese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-swedish.conllu Dog-ukrainian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-swedish.conllu data/Dog/Dog-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-swedish.conllu Dog-vietnamese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-swedish.conllu data/Dog/Dog-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-swedish.conllu Dog-chinese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-swedish.conllu data/Dog/Dog-chinese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-ukrainian.conllu Dog-vietnamese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-ukrainian.conllu data/Dog/Dog-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-ukrainian.conllu Dog-chinese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-ukrainian.conllu data/Dog/Dog-chinese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-vietnamese.conllu Dog-chinese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-vietnamese.conllu data/Dog/Dog-chinese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-english.conllu Dog-catalan.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-english.conllu data/Dog/Dog-catalan.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-english.conllu Dog-spanish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-english.conllu data/Dog/Dog-spanish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-english.conllu Dog-french.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-english.conllu data/Dog/Dog-french.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-english.conllu Dog-japanese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-english.conllu data/Dog/Dog-japanese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-english.conllu Dog-turkish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-english.conllu data/Dog/Dog-turkish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-catalan.conllu Dog-spanish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-catalan.conllu data/Dog/Dog-spanish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-catalan.conllu Dog-french.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-catalan.conllu data/Dog/Dog-french.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-catalan.conllu Dog-japanese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-catalan.conllu data/Dog/Dog-japanese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-catalan.conllu Dog-turkish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-catalan.conllu data/Dog/Dog-turkish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-spanish.conllu Dog-french.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-spanish.conllu data/Dog/Dog-french.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-spanish.conllu Dog-japanese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-spanish.conllu data/Dog/Dog-japanese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-spanish.conllu Dog-turkish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-spanish.conllu data/Dog/Dog-turkish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-french.conllu Dog-japanese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-french.conllu data/Dog/Dog-japanese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-french.conllu Dog-turkish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-french.conllu data/Dog/Dog-turkish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-japanese.conllu Dog-turkish.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-japanese.conllu data/Dog/Dog-turkish.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-czech.conllu Dog-german.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-czech.conllu data/Dog/Dog-german.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-czech.conllu Dog-hungarian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-czech.conllu data/Dog/Dog-hungarian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-czech.conllu Dog-dutch.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-czech.conllu data/Dog/Dog-dutch.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-czech.conllu Dog-portuguese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-czech.conllu data/Dog/Dog-portuguese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-czech.conllu Dog-russian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-czech.conllu data/Dog/Dog-russian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-german.conllu Dog-hungarian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-german.conllu data/Dog/Dog-hungarian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-german.conllu Dog-dutch.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-german.conllu data/Dog/Dog-dutch.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-german.conllu Dog-portuguese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-german.conllu data/Dog/Dog-portuguese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-german.conllu Dog-russian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-german.conllu data/Dog/Dog-russian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-hungarian.conllu Dog-dutch.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-hungarian.conllu data/Dog/Dog-dutch.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-hungarian.conllu Dog-portuguese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-hungarian.conllu data/Dog/Dog-portuguese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-hungarian.conllu Dog-russian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-hungarian.conllu data/Dog/Dog-russian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-dutch.conllu Dog-portuguese.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-dutch.conllu data/Dog/Dog-portuguese.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-dutch.conllu Dog-russian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-dutch.conllu data/Dog/Dog-russian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
echo Dog-portuguese.conllu Dog-russian.conllu >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
gfud cosine-similarity data/Dog/Dog-portuguese.conllu data/Dog/Dog-russian.conllu DEPREL >> cosine-sim-per-topic/Dog-cosine-sim.txt ; 
} 
topic_combinations