#! /bin/bash 
function topic_combinations { 
echo India-north_sami.conllu India-scottish_gaelic.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-north_sami.conllu data/India/India-scottish_gaelic.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-north_sami.conllu India-gothic.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-north_sami.conllu data/India/India-gothic.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-north_sami.conllu India-maltese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-north_sami.conllu data/India/India-maltese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-north_sami.conllu India-uyghur.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-north_sami.conllu data/India/India-uyghur.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-north_sami.conllu India-wolof.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-north_sami.conllu data/India/India-wolof.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-scottish_gaelic.conllu India-gothic.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-scottish_gaelic.conllu data/India/India-gothic.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-scottish_gaelic.conllu India-maltese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-scottish_gaelic.conllu data/India/India-maltese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-scottish_gaelic.conllu India-uyghur.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-scottish_gaelic.conllu data/India/India-uyghur.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-scottish_gaelic.conllu India-wolof.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-scottish_gaelic.conllu data/India/India-wolof.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-gothic.conllu India-maltese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-gothic.conllu data/India/India-maltese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-gothic.conllu India-uyghur.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-gothic.conllu data/India/India-uyghur.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-gothic.conllu India-wolof.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-gothic.conllu data/India/India-wolof.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-maltese.conllu India-uyghur.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-maltese.conllu data/India/India-uyghur.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-maltese.conllu India-wolof.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-maltese.conllu data/India/India-wolof.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-uyghur.conllu India-wolof.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-uyghur.conllu data/India/India-wolof.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-afrikaans.conllu India-croatian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-afrikaans.conllu data/India/India-croatian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-afrikaans.conllu India-latin.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-afrikaans.conllu data/India/India-latin.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-afrikaans.conllu India-classical_chinese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-afrikaans.conllu data/India/India-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-croatian.conllu India-latin.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-croatian.conllu data/India/India-latin.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-croatian.conllu India-classical_chinese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-croatian.conllu data/India/India-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-latin.conllu India-classical_chinese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-latin.conllu data/India/India-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-belarusian.conllu India-bulgarian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-belarusian.conllu data/India/India-bulgarian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-belarusian.conllu India-catalan.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-belarusian.conllu data/India/India-catalan.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-belarusian.conllu India-welsh.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-belarusian.conllu data/India/India-welsh.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-belarusian.conllu India-greek.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-belarusian.conllu data/India/India-greek.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-belarusian.conllu India-basque.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-belarusian.conllu data/India/India-basque.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-belarusian.conllu India-irish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-belarusian.conllu data/India/India-irish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-belarusian.conllu India-indonesian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-belarusian.conllu data/India/India-indonesian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-belarusian.conllu India-hebrew.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-belarusian.conllu data/India/India-hebrew.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-belarusian.conllu India-lithuanian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-belarusian.conllu data/India/India-lithuanian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-belarusian.conllu India-polish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-belarusian.conllu data/India/India-polish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-belarusian.conllu India-romanian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-belarusian.conllu data/India/India-romanian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-belarusian.conllu India-slovak.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-belarusian.conllu data/India/India-slovak.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-belarusian.conllu India-slovenian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-belarusian.conllu data/India/India-slovenian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-belarusian.conllu India-serbian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-belarusian.conllu data/India/India-serbian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-belarusian.conllu India-telugu.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-belarusian.conllu data/India/India-telugu.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-belarusian.conllu India-turkish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-belarusian.conllu data/India/India-turkish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-belarusian.conllu India-urdu.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-belarusian.conllu data/India/India-urdu.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-bulgarian.conllu India-catalan.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-bulgarian.conllu data/India/India-catalan.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-bulgarian.conllu India-welsh.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-bulgarian.conllu data/India/India-welsh.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-bulgarian.conllu India-greek.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-bulgarian.conllu data/India/India-greek.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-bulgarian.conllu India-basque.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-bulgarian.conllu data/India/India-basque.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-bulgarian.conllu India-irish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-bulgarian.conllu data/India/India-irish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-bulgarian.conllu India-indonesian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-bulgarian.conllu data/India/India-indonesian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-bulgarian.conllu India-hebrew.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-bulgarian.conllu data/India/India-hebrew.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-bulgarian.conllu India-lithuanian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-bulgarian.conllu data/India/India-lithuanian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-bulgarian.conllu India-polish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-bulgarian.conllu data/India/India-polish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-bulgarian.conllu India-romanian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-bulgarian.conllu data/India/India-romanian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-bulgarian.conllu India-slovak.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-bulgarian.conllu data/India/India-slovak.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-bulgarian.conllu India-slovenian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-bulgarian.conllu data/India/India-slovenian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-bulgarian.conllu India-serbian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-bulgarian.conllu data/India/India-serbian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-bulgarian.conllu India-telugu.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-bulgarian.conllu data/India/India-telugu.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-bulgarian.conllu India-turkish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-bulgarian.conllu data/India/India-turkish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-bulgarian.conllu India-urdu.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-bulgarian.conllu data/India/India-urdu.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-catalan.conllu India-welsh.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-catalan.conllu data/India/India-welsh.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-catalan.conllu India-greek.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-catalan.conllu data/India/India-greek.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-catalan.conllu India-basque.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-catalan.conllu data/India/India-basque.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-catalan.conllu India-irish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-catalan.conllu data/India/India-irish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-catalan.conllu India-indonesian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-catalan.conllu data/India/India-indonesian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-catalan.conllu India-hebrew.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-catalan.conllu data/India/India-hebrew.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-catalan.conllu India-lithuanian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-catalan.conllu data/India/India-lithuanian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-catalan.conllu India-polish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-catalan.conllu data/India/India-polish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-catalan.conllu India-romanian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-catalan.conllu data/India/India-romanian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-catalan.conllu India-slovak.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-catalan.conllu data/India/India-slovak.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-catalan.conllu India-slovenian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-catalan.conllu data/India/India-slovenian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-catalan.conllu India-serbian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-catalan.conllu data/India/India-serbian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-catalan.conllu India-telugu.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-catalan.conllu data/India/India-telugu.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-catalan.conllu India-turkish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-catalan.conllu data/India/India-turkish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-catalan.conllu India-urdu.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-catalan.conllu data/India/India-urdu.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-welsh.conllu India-greek.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-welsh.conllu data/India/India-greek.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-welsh.conllu India-basque.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-welsh.conllu data/India/India-basque.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-welsh.conllu India-irish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-welsh.conllu data/India/India-irish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-welsh.conllu India-indonesian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-welsh.conllu data/India/India-indonesian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-welsh.conllu India-hebrew.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-welsh.conllu data/India/India-hebrew.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-welsh.conllu India-lithuanian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-welsh.conllu data/India/India-lithuanian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-welsh.conllu India-polish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-welsh.conllu data/India/India-polish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-welsh.conllu India-romanian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-welsh.conllu data/India/India-romanian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-welsh.conllu India-slovak.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-welsh.conllu data/India/India-slovak.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-welsh.conllu India-slovenian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-welsh.conllu data/India/India-slovenian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-welsh.conllu India-serbian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-welsh.conllu data/India/India-serbian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-welsh.conllu India-telugu.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-welsh.conllu data/India/India-telugu.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-welsh.conllu India-turkish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-welsh.conllu data/India/India-turkish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-welsh.conllu India-urdu.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-welsh.conllu data/India/India-urdu.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-greek.conllu India-basque.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-greek.conllu data/India/India-basque.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-greek.conllu India-irish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-greek.conllu data/India/India-irish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-greek.conllu India-indonesian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-greek.conllu data/India/India-indonesian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-greek.conllu India-hebrew.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-greek.conllu data/India/India-hebrew.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-greek.conllu India-lithuanian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-greek.conllu data/India/India-lithuanian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-greek.conllu India-polish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-greek.conllu data/India/India-polish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-greek.conllu India-romanian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-greek.conllu data/India/India-romanian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-greek.conllu India-slovak.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-greek.conllu data/India/India-slovak.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-greek.conllu India-slovenian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-greek.conllu data/India/India-slovenian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-greek.conllu India-serbian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-greek.conllu data/India/India-serbian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-greek.conllu India-telugu.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-greek.conllu data/India/India-telugu.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-greek.conllu India-turkish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-greek.conllu data/India/India-turkish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-greek.conllu India-urdu.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-greek.conllu data/India/India-urdu.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-basque.conllu India-irish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-basque.conllu data/India/India-irish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-basque.conllu India-indonesian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-basque.conllu data/India/India-indonesian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-basque.conllu India-hebrew.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-basque.conllu data/India/India-hebrew.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-basque.conllu India-lithuanian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-basque.conllu data/India/India-lithuanian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-basque.conllu India-polish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-basque.conllu data/India/India-polish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-basque.conllu India-romanian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-basque.conllu data/India/India-romanian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-basque.conllu India-slovak.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-basque.conllu data/India/India-slovak.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-basque.conllu India-slovenian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-basque.conllu data/India/India-slovenian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-basque.conllu India-serbian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-basque.conllu data/India/India-serbian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-basque.conllu India-telugu.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-basque.conllu data/India/India-telugu.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-basque.conllu India-turkish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-basque.conllu data/India/India-turkish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-basque.conllu India-urdu.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-basque.conllu data/India/India-urdu.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-irish.conllu India-indonesian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-irish.conllu data/India/India-indonesian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-irish.conllu India-hebrew.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-irish.conllu data/India/India-hebrew.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-irish.conllu India-lithuanian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-irish.conllu data/India/India-lithuanian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-irish.conllu India-polish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-irish.conllu data/India/India-polish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-irish.conllu India-romanian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-irish.conllu data/India/India-romanian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-irish.conllu India-slovak.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-irish.conllu data/India/India-slovak.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-irish.conllu India-slovenian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-irish.conllu data/India/India-slovenian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-irish.conllu India-serbian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-irish.conllu data/India/India-serbian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-irish.conllu India-telugu.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-irish.conllu data/India/India-telugu.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-irish.conllu India-turkish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-irish.conllu data/India/India-turkish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-irish.conllu India-urdu.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-irish.conllu data/India/India-urdu.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-indonesian.conllu India-hebrew.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-indonesian.conllu data/India/India-hebrew.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-indonesian.conllu India-lithuanian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-indonesian.conllu data/India/India-lithuanian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-indonesian.conllu India-polish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-indonesian.conllu data/India/India-polish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-indonesian.conllu India-romanian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-indonesian.conllu data/India/India-romanian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-indonesian.conllu India-slovak.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-indonesian.conllu data/India/India-slovak.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-indonesian.conllu India-slovenian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-indonesian.conllu data/India/India-slovenian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-indonesian.conllu India-serbian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-indonesian.conllu data/India/India-serbian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-indonesian.conllu India-telugu.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-indonesian.conllu data/India/India-telugu.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-indonesian.conllu India-turkish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-indonesian.conllu data/India/India-turkish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-indonesian.conllu India-urdu.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-indonesian.conllu data/India/India-urdu.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-hebrew.conllu India-lithuanian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-hebrew.conllu data/India/India-lithuanian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-hebrew.conllu India-polish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-hebrew.conllu data/India/India-polish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-hebrew.conllu India-romanian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-hebrew.conllu data/India/India-romanian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-hebrew.conllu India-slovak.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-hebrew.conllu data/India/India-slovak.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-hebrew.conllu India-slovenian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-hebrew.conllu data/India/India-slovenian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-hebrew.conllu India-serbian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-hebrew.conllu data/India/India-serbian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-hebrew.conllu India-telugu.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-hebrew.conllu data/India/India-telugu.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-hebrew.conllu India-turkish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-hebrew.conllu data/India/India-turkish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-hebrew.conllu India-urdu.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-hebrew.conllu data/India/India-urdu.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-lithuanian.conllu India-polish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-lithuanian.conllu data/India/India-polish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-lithuanian.conllu India-romanian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-lithuanian.conllu data/India/India-romanian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-lithuanian.conllu India-slovak.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-lithuanian.conllu data/India/India-slovak.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-lithuanian.conllu India-slovenian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-lithuanian.conllu data/India/India-slovenian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-lithuanian.conllu India-serbian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-lithuanian.conllu data/India/India-serbian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-lithuanian.conllu India-telugu.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-lithuanian.conllu data/India/India-telugu.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-lithuanian.conllu India-turkish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-lithuanian.conllu data/India/India-turkish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-lithuanian.conllu India-urdu.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-lithuanian.conllu data/India/India-urdu.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-polish.conllu India-romanian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-polish.conllu data/India/India-romanian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-polish.conllu India-slovak.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-polish.conllu data/India/India-slovak.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-polish.conllu India-slovenian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-polish.conllu data/India/India-slovenian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-polish.conllu India-serbian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-polish.conllu data/India/India-serbian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-polish.conllu India-telugu.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-polish.conllu data/India/India-telugu.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-polish.conllu India-turkish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-polish.conllu data/India/India-turkish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-polish.conllu India-urdu.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-polish.conllu data/India/India-urdu.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-romanian.conllu India-slovak.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-romanian.conllu data/India/India-slovak.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-romanian.conllu India-slovenian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-romanian.conllu data/India/India-slovenian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-romanian.conllu India-serbian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-romanian.conllu data/India/India-serbian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-romanian.conllu India-telugu.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-romanian.conllu data/India/India-telugu.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-romanian.conllu India-turkish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-romanian.conllu data/India/India-turkish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-romanian.conllu India-urdu.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-romanian.conllu data/India/India-urdu.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-slovak.conllu India-slovenian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-slovak.conllu data/India/India-slovenian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-slovak.conllu India-serbian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-slovak.conllu data/India/India-serbian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-slovak.conllu India-telugu.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-slovak.conllu data/India/India-telugu.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-slovak.conllu India-turkish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-slovak.conllu data/India/India-turkish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-slovak.conllu India-urdu.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-slovak.conllu data/India/India-urdu.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-slovenian.conllu India-serbian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-slovenian.conllu data/India/India-serbian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-slovenian.conllu India-telugu.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-slovenian.conllu data/India/India-telugu.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-slovenian.conllu India-turkish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-slovenian.conllu data/India/India-turkish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-slovenian.conllu India-urdu.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-slovenian.conllu data/India/India-urdu.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-serbian.conllu India-telugu.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-serbian.conllu data/India/India-telugu.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-serbian.conllu India-turkish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-serbian.conllu data/India/India-turkish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-serbian.conllu India-urdu.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-serbian.conllu data/India/India-urdu.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-telugu.conllu India-turkish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-telugu.conllu data/India/India-turkish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-telugu.conllu India-urdu.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-telugu.conllu data/India/India-urdu.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-turkish.conllu India-urdu.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-turkish.conllu data/India/India-urdu.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-spanish.conllu India-persian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-spanish.conllu data/India/India-persian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-spanish.conllu India-korean.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-spanish.conllu data/India/India-korean.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-spanish.conllu India-armenian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-spanish.conllu data/India/India-armenian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-spanish.conllu India-hindi.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-spanish.conllu data/India/India-hindi.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-spanish.conllu India-kazakh.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-spanish.conllu data/India/India-kazakh.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-spanish.conllu India-latvian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-spanish.conllu data/India/India-latvian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-spanish.conllu India-hungarian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-spanish.conllu data/India/India-hungarian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-spanish.conllu India-marathi.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-spanish.conllu data/India/India-marathi.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-spanish.conllu India-sanskrit.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-spanish.conllu data/India/India-sanskrit.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-spanish.conllu India-finnish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-spanish.conllu data/India/India-finnish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-spanish.conllu India-swedish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-spanish.conllu data/India/India-swedish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-spanish.conllu India-tamil.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-spanish.conllu data/India/India-tamil.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-spanish.conllu India-ukrainian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-spanish.conllu data/India/India-ukrainian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-spanish.conllu India-vietnamese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-spanish.conllu data/India/India-vietnamese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-spanish.conllu India-chinese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-spanish.conllu data/India/India-chinese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-persian.conllu India-korean.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-persian.conllu data/India/India-korean.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-persian.conllu India-armenian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-persian.conllu data/India/India-armenian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-persian.conllu India-hindi.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-persian.conllu data/India/India-hindi.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-persian.conllu India-kazakh.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-persian.conllu data/India/India-kazakh.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-persian.conllu India-latvian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-persian.conllu data/India/India-latvian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-persian.conllu India-hungarian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-persian.conllu data/India/India-hungarian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-persian.conllu India-marathi.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-persian.conllu data/India/India-marathi.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-persian.conllu India-sanskrit.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-persian.conllu data/India/India-sanskrit.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-persian.conllu India-finnish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-persian.conllu data/India/India-finnish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-persian.conllu India-swedish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-persian.conllu data/India/India-swedish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-persian.conllu India-tamil.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-persian.conllu data/India/India-tamil.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-persian.conllu India-ukrainian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-persian.conllu data/India/India-ukrainian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-persian.conllu India-vietnamese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-persian.conllu data/India/India-vietnamese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-persian.conllu India-chinese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-persian.conllu data/India/India-chinese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-korean.conllu India-armenian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-korean.conllu data/India/India-armenian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-korean.conllu India-hindi.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-korean.conllu data/India/India-hindi.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-korean.conllu India-kazakh.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-korean.conllu data/India/India-kazakh.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-korean.conllu India-latvian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-korean.conllu data/India/India-latvian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-korean.conllu India-hungarian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-korean.conllu data/India/India-hungarian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-korean.conllu India-marathi.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-korean.conllu data/India/India-marathi.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-korean.conllu India-sanskrit.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-korean.conllu data/India/India-sanskrit.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-korean.conllu India-finnish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-korean.conllu data/India/India-finnish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-korean.conllu India-swedish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-korean.conllu data/India/India-swedish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-korean.conllu India-tamil.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-korean.conllu data/India/India-tamil.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-korean.conllu India-ukrainian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-korean.conllu data/India/India-ukrainian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-korean.conllu India-vietnamese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-korean.conllu data/India/India-vietnamese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-korean.conllu India-chinese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-korean.conllu data/India/India-chinese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-armenian.conllu India-hindi.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-armenian.conllu data/India/India-hindi.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-armenian.conllu India-kazakh.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-armenian.conllu data/India/India-kazakh.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-armenian.conllu India-latvian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-armenian.conllu data/India/India-latvian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-armenian.conllu India-hungarian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-armenian.conllu data/India/India-hungarian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-armenian.conllu India-marathi.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-armenian.conllu data/India/India-marathi.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-armenian.conllu India-sanskrit.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-armenian.conllu data/India/India-sanskrit.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-armenian.conllu India-finnish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-armenian.conllu data/India/India-finnish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-armenian.conllu India-swedish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-armenian.conllu data/India/India-swedish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-armenian.conllu India-tamil.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-armenian.conllu data/India/India-tamil.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-armenian.conllu India-ukrainian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-armenian.conllu data/India/India-ukrainian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-armenian.conllu India-vietnamese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-armenian.conllu data/India/India-vietnamese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-armenian.conllu India-chinese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-armenian.conllu data/India/India-chinese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-hindi.conllu India-kazakh.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-hindi.conllu data/India/India-kazakh.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-hindi.conllu India-latvian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-hindi.conllu data/India/India-latvian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-hindi.conllu India-hungarian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-hindi.conllu data/India/India-hungarian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-hindi.conllu India-marathi.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-hindi.conllu data/India/India-marathi.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-hindi.conllu India-sanskrit.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-hindi.conllu data/India/India-sanskrit.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-hindi.conllu India-finnish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-hindi.conllu data/India/India-finnish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-hindi.conllu India-swedish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-hindi.conllu data/India/India-swedish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-hindi.conllu India-tamil.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-hindi.conllu data/India/India-tamil.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-hindi.conllu India-ukrainian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-hindi.conllu data/India/India-ukrainian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-hindi.conllu India-vietnamese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-hindi.conllu data/India/India-vietnamese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-hindi.conllu India-chinese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-hindi.conllu data/India/India-chinese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-kazakh.conllu India-latvian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-kazakh.conllu data/India/India-latvian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-kazakh.conllu India-hungarian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-kazakh.conllu data/India/India-hungarian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-kazakh.conllu India-marathi.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-kazakh.conllu data/India/India-marathi.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-kazakh.conllu India-sanskrit.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-kazakh.conllu data/India/India-sanskrit.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-kazakh.conllu India-finnish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-kazakh.conllu data/India/India-finnish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-kazakh.conllu India-swedish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-kazakh.conllu data/India/India-swedish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-kazakh.conllu India-tamil.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-kazakh.conllu data/India/India-tamil.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-kazakh.conllu India-ukrainian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-kazakh.conllu data/India/India-ukrainian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-kazakh.conllu India-vietnamese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-kazakh.conllu data/India/India-vietnamese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-kazakh.conllu India-chinese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-kazakh.conllu data/India/India-chinese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-latvian.conllu India-hungarian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-latvian.conllu data/India/India-hungarian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-latvian.conllu India-marathi.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-latvian.conllu data/India/India-marathi.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-latvian.conllu India-sanskrit.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-latvian.conllu data/India/India-sanskrit.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-latvian.conllu India-finnish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-latvian.conllu data/India/India-finnish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-latvian.conllu India-swedish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-latvian.conllu data/India/India-swedish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-latvian.conllu India-tamil.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-latvian.conllu data/India/India-tamil.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-latvian.conllu India-ukrainian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-latvian.conllu data/India/India-ukrainian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-latvian.conllu India-vietnamese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-latvian.conllu data/India/India-vietnamese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-latvian.conllu India-chinese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-latvian.conllu data/India/India-chinese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-hungarian.conllu India-marathi.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-hungarian.conllu data/India/India-marathi.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-hungarian.conllu India-sanskrit.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-hungarian.conllu data/India/India-sanskrit.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-hungarian.conllu India-finnish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-hungarian.conllu data/India/India-finnish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-hungarian.conllu India-swedish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-hungarian.conllu data/India/India-swedish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-hungarian.conllu India-tamil.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-hungarian.conllu data/India/India-tamil.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-hungarian.conllu India-ukrainian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-hungarian.conllu data/India/India-ukrainian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-hungarian.conllu India-vietnamese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-hungarian.conllu data/India/India-vietnamese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-hungarian.conllu India-chinese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-hungarian.conllu data/India/India-chinese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-marathi.conllu India-sanskrit.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-marathi.conllu data/India/India-sanskrit.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-marathi.conllu India-finnish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-marathi.conllu data/India/India-finnish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-marathi.conllu India-swedish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-marathi.conllu data/India/India-swedish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-marathi.conllu India-tamil.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-marathi.conllu data/India/India-tamil.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-marathi.conllu India-ukrainian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-marathi.conllu data/India/India-ukrainian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-marathi.conllu India-vietnamese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-marathi.conllu data/India/India-vietnamese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-marathi.conllu India-chinese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-marathi.conllu data/India/India-chinese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-sanskrit.conllu India-finnish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-sanskrit.conllu data/India/India-finnish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-sanskrit.conllu India-swedish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-sanskrit.conllu data/India/India-swedish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-sanskrit.conllu India-tamil.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-sanskrit.conllu data/India/India-tamil.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-sanskrit.conllu India-ukrainian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-sanskrit.conllu data/India/India-ukrainian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-sanskrit.conllu India-vietnamese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-sanskrit.conllu data/India/India-vietnamese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-sanskrit.conllu India-chinese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-sanskrit.conllu data/India/India-chinese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-finnish.conllu India-swedish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-finnish.conllu data/India/India-swedish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-finnish.conllu India-tamil.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-finnish.conllu data/India/India-tamil.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-finnish.conllu India-ukrainian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-finnish.conllu data/India/India-ukrainian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-finnish.conllu India-vietnamese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-finnish.conllu data/India/India-vietnamese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-finnish.conllu India-chinese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-finnish.conllu data/India/India-chinese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-swedish.conllu India-tamil.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-swedish.conllu data/India/India-tamil.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-swedish.conllu India-ukrainian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-swedish.conllu data/India/India-ukrainian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-swedish.conllu India-vietnamese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-swedish.conllu data/India/India-vietnamese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-swedish.conllu India-chinese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-swedish.conllu data/India/India-chinese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-tamil.conllu India-ukrainian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-tamil.conllu data/India/India-ukrainian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-tamil.conllu India-vietnamese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-tamil.conllu data/India/India-vietnamese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-tamil.conllu India-chinese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-tamil.conllu data/India/India-chinese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-ukrainian.conllu India-vietnamese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-ukrainian.conllu data/India/India-vietnamese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-ukrainian.conllu India-chinese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-ukrainian.conllu data/India/India-chinese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-vietnamese.conllu India-chinese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-vietnamese.conllu data/India/India-chinese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-english.conllu India-arabic.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-english.conllu data/India/India-arabic.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-english.conllu India-czech.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-english.conllu data/India/India-czech.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-english.conllu India-danish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-english.conllu data/India/India-danish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-english.conllu India-german.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-english.conllu data/India/India-german.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-english.conllu India-estonian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-english.conllu data/India/India-estonian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-english.conllu India-french.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-english.conllu data/India/India-french.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-english.conllu India-galician.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-english.conllu data/India/India-galician.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-english.conllu India-italian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-english.conllu data/India/India-italian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-english.conllu India-dutch.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-english.conllu data/India/India-dutch.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-english.conllu India-japanese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-english.conllu data/India/India-japanese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-english.conllu India-portuguese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-english.conllu data/India/India-portuguese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-english.conllu India-russian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-english.conllu data/India/India-russian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-arabic.conllu India-czech.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-arabic.conllu data/India/India-czech.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-arabic.conllu India-danish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-arabic.conllu data/India/India-danish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-arabic.conllu India-german.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-arabic.conllu data/India/India-german.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-arabic.conllu India-estonian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-arabic.conllu data/India/India-estonian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-arabic.conllu India-french.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-arabic.conllu data/India/India-french.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-arabic.conllu India-galician.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-arabic.conllu data/India/India-galician.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-arabic.conllu India-italian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-arabic.conllu data/India/India-italian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-arabic.conllu India-dutch.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-arabic.conllu data/India/India-dutch.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-arabic.conllu India-japanese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-arabic.conllu data/India/India-japanese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-arabic.conllu India-portuguese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-arabic.conllu data/India/India-portuguese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-arabic.conllu India-russian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-arabic.conllu data/India/India-russian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-czech.conllu India-danish.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-czech.conllu data/India/India-danish.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-czech.conllu India-german.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-czech.conllu data/India/India-german.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-czech.conllu India-estonian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-czech.conllu data/India/India-estonian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-czech.conllu India-french.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-czech.conllu data/India/India-french.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-czech.conllu India-galician.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-czech.conllu data/India/India-galician.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-czech.conllu India-italian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-czech.conllu data/India/India-italian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-czech.conllu India-dutch.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-czech.conllu data/India/India-dutch.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-czech.conllu India-japanese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-czech.conllu data/India/India-japanese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-czech.conllu India-portuguese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-czech.conllu data/India/India-portuguese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-czech.conllu India-russian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-czech.conllu data/India/India-russian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-danish.conllu India-german.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-danish.conllu data/India/India-german.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-danish.conllu India-estonian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-danish.conllu data/India/India-estonian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-danish.conllu India-french.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-danish.conllu data/India/India-french.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-danish.conllu India-galician.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-danish.conllu data/India/India-galician.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-danish.conllu India-italian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-danish.conllu data/India/India-italian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-danish.conllu India-dutch.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-danish.conllu data/India/India-dutch.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-danish.conllu India-japanese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-danish.conllu data/India/India-japanese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-danish.conllu India-portuguese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-danish.conllu data/India/India-portuguese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-danish.conllu India-russian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-danish.conllu data/India/India-russian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-german.conllu India-estonian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-german.conllu data/India/India-estonian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-german.conllu India-french.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-german.conllu data/India/India-french.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-german.conllu India-galician.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-german.conllu data/India/India-galician.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-german.conllu India-italian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-german.conllu data/India/India-italian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-german.conllu India-dutch.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-german.conllu data/India/India-dutch.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-german.conllu India-japanese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-german.conllu data/India/India-japanese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-german.conllu India-portuguese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-german.conllu data/India/India-portuguese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-german.conllu India-russian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-german.conllu data/India/India-russian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-estonian.conllu India-french.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-estonian.conllu data/India/India-french.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-estonian.conllu India-galician.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-estonian.conllu data/India/India-galician.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-estonian.conllu India-italian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-estonian.conllu data/India/India-italian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-estonian.conllu India-dutch.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-estonian.conllu data/India/India-dutch.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-estonian.conllu India-japanese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-estonian.conllu data/India/India-japanese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-estonian.conllu India-portuguese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-estonian.conllu data/India/India-portuguese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-estonian.conllu India-russian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-estonian.conllu data/India/India-russian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-french.conllu India-galician.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-french.conllu data/India/India-galician.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-french.conllu India-italian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-french.conllu data/India/India-italian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-french.conllu India-dutch.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-french.conllu data/India/India-dutch.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-french.conllu India-japanese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-french.conllu data/India/India-japanese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-french.conllu India-portuguese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-french.conllu data/India/India-portuguese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-french.conllu India-russian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-french.conllu data/India/India-russian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-galician.conllu India-italian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-galician.conllu data/India/India-italian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-galician.conllu India-dutch.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-galician.conllu data/India/India-dutch.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-galician.conllu India-japanese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-galician.conllu data/India/India-japanese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-galician.conllu India-portuguese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-galician.conllu data/India/India-portuguese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-galician.conllu India-russian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-galician.conllu data/India/India-russian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-italian.conllu India-dutch.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-italian.conllu data/India/India-dutch.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-italian.conllu India-japanese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-italian.conllu data/India/India-japanese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-italian.conllu India-portuguese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-italian.conllu data/India/India-portuguese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-italian.conllu India-russian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-italian.conllu data/India/India-russian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-dutch.conllu India-japanese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-dutch.conllu data/India/India-japanese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-dutch.conllu India-portuguese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-dutch.conllu data/India/India-portuguese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-dutch.conllu India-russian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-dutch.conllu data/India/India-russian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-japanese.conllu India-portuguese.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-japanese.conllu data/India/India-portuguese.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-japanese.conllu India-russian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-japanese.conllu data/India/India-russian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
echo India-portuguese.conllu India-russian.conllu >> cosine-sim-per-topic/India-cosine-sim.txt ; 
gfud cosine-similarity data/India/India-portuguese.conllu data/India/India-russian.conllu DEPREL >> cosine-sim-per-topic/India-cosine-sim.txt ; 
} 
topic_combinations