#! /bin/bash 
function topic_combinations { 
echo Iran-scottish_gaelic.conllu Iran-gothic.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-scottish_gaelic.conllu data/Iran/Iran-gothic.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-scottish_gaelic.conllu Iran-maltese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-scottish_gaelic.conllu data/Iran/Iran-maltese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-scottish_gaelic.conllu Iran-sanskrit.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-scottish_gaelic.conllu data/Iran/Iran-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-scottish_gaelic.conllu Iran-wolof.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-scottish_gaelic.conllu data/Iran/Iran-wolof.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-gothic.conllu Iran-maltese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-gothic.conllu data/Iran/Iran-maltese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-gothic.conllu Iran-sanskrit.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-gothic.conllu data/Iran/Iran-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-gothic.conllu Iran-wolof.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-gothic.conllu data/Iran/Iran-wolof.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-maltese.conllu Iran-sanskrit.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-maltese.conllu data/Iran/Iran-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-maltese.conllu Iran-wolof.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-maltese.conllu data/Iran/Iran-wolof.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-sanskrit.conllu Iran-wolof.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-sanskrit.conllu data/Iran/Iran-wolof.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-north_sami.conllu Iran-estonian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-north_sami.conllu data/Iran/Iran-estonian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-north_sami.conllu Iran-irish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-north_sami.conllu data/Iran/Iran-irish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-north_sami.conllu Iran-latin.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-north_sami.conllu data/Iran/Iran-latin.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-north_sami.conllu Iran-marathi.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-north_sami.conllu data/Iran/Iran-marathi.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-north_sami.conllu Iran-slovak.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-north_sami.conllu data/Iran/Iran-slovak.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-north_sami.conllu Iran-tamil.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-north_sami.conllu data/Iran/Iran-tamil.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-north_sami.conllu Iran-uyghur.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-north_sami.conllu data/Iran/Iran-uyghur.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-north_sami.conllu Iran-classical_chinese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-north_sami.conllu data/Iran/Iran-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-estonian.conllu Iran-irish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-estonian.conllu data/Iran/Iran-irish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-estonian.conllu Iran-latin.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-estonian.conllu data/Iran/Iran-latin.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-estonian.conllu Iran-marathi.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-estonian.conllu data/Iran/Iran-marathi.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-estonian.conllu Iran-slovak.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-estonian.conllu data/Iran/Iran-slovak.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-estonian.conllu Iran-tamil.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-estonian.conllu data/Iran/Iran-tamil.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-estonian.conllu Iran-uyghur.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-estonian.conllu data/Iran/Iran-uyghur.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-estonian.conllu Iran-classical_chinese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-estonian.conllu data/Iran/Iran-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-irish.conllu Iran-latin.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-irish.conllu data/Iran/Iran-latin.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-irish.conllu Iran-marathi.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-irish.conllu data/Iran/Iran-marathi.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-irish.conllu Iran-slovak.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-irish.conllu data/Iran/Iran-slovak.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-irish.conllu Iran-tamil.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-irish.conllu data/Iran/Iran-tamil.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-irish.conllu Iran-uyghur.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-irish.conllu data/Iran/Iran-uyghur.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-irish.conllu Iran-classical_chinese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-irish.conllu data/Iran/Iran-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-latin.conllu Iran-marathi.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-latin.conllu data/Iran/Iran-marathi.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-latin.conllu Iran-slovak.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-latin.conllu data/Iran/Iran-slovak.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-latin.conllu Iran-tamil.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-latin.conllu data/Iran/Iran-tamil.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-latin.conllu Iran-uyghur.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-latin.conllu data/Iran/Iran-uyghur.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-latin.conllu Iran-classical_chinese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-latin.conllu data/Iran/Iran-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-marathi.conllu Iran-slovak.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-marathi.conllu data/Iran/Iran-slovak.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-marathi.conllu Iran-tamil.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-marathi.conllu data/Iran/Iran-tamil.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-marathi.conllu Iran-uyghur.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-marathi.conllu data/Iran/Iran-uyghur.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-marathi.conllu Iran-classical_chinese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-marathi.conllu data/Iran/Iran-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-slovak.conllu Iran-tamil.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-slovak.conllu data/Iran/Iran-tamil.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-slovak.conllu Iran-uyghur.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-slovak.conllu data/Iran/Iran-uyghur.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-slovak.conllu Iran-classical_chinese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-slovak.conllu data/Iran/Iran-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-tamil.conllu Iran-uyghur.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-tamil.conllu data/Iran/Iran-uyghur.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-tamil.conllu Iran-classical_chinese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-tamil.conllu data/Iran/Iran-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-uyghur.conllu Iran-classical_chinese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-uyghur.conllu data/Iran/Iran-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-belarusian.conllu Iran-bulgarian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-belarusian.conllu data/Iran/Iran-bulgarian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-belarusian.conllu Iran-catalan.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-belarusian.conllu data/Iran/Iran-catalan.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-belarusian.conllu Iran-welsh.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-belarusian.conllu data/Iran/Iran-welsh.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-belarusian.conllu Iran-danish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-belarusian.conllu data/Iran/Iran-danish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-belarusian.conllu Iran-greek.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-belarusian.conllu data/Iran/Iran-greek.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-belarusian.conllu Iran-spanish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-belarusian.conllu data/Iran/Iran-spanish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-belarusian.conllu Iran-galician.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-belarusian.conllu data/Iran/Iran-galician.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-belarusian.conllu Iran-hindi.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-belarusian.conllu data/Iran/Iran-hindi.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-belarusian.conllu Iran-indonesian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-belarusian.conllu data/Iran/Iran-indonesian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-belarusian.conllu Iran-latvian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-belarusian.conllu data/Iran/Iran-latvian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-belarusian.conllu Iran-lithuanian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-belarusian.conllu data/Iran/Iran-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-belarusian.conllu Iran-polish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-belarusian.conllu data/Iran/Iran-polish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-belarusian.conllu Iran-romanian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-belarusian.conllu data/Iran/Iran-romanian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-belarusian.conllu Iran-urdu.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-belarusian.conllu data/Iran/Iran-urdu.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-belarusian.conllu Iran-vietnamese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-belarusian.conllu data/Iran/Iran-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-belarusian.conllu Iran-chinese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-belarusian.conllu data/Iran/Iran-chinese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-bulgarian.conllu Iran-catalan.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-bulgarian.conllu data/Iran/Iran-catalan.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-bulgarian.conllu Iran-welsh.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-bulgarian.conllu data/Iran/Iran-welsh.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-bulgarian.conllu Iran-danish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-bulgarian.conllu data/Iran/Iran-danish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-bulgarian.conllu Iran-greek.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-bulgarian.conllu data/Iran/Iran-greek.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-bulgarian.conllu Iran-spanish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-bulgarian.conllu data/Iran/Iran-spanish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-bulgarian.conllu Iran-galician.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-bulgarian.conllu data/Iran/Iran-galician.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-bulgarian.conllu Iran-hindi.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-bulgarian.conllu data/Iran/Iran-hindi.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-bulgarian.conllu Iran-indonesian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-bulgarian.conllu data/Iran/Iran-indonesian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-bulgarian.conllu Iran-latvian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-bulgarian.conllu data/Iran/Iran-latvian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-bulgarian.conllu Iran-lithuanian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-bulgarian.conllu data/Iran/Iran-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-bulgarian.conllu Iran-polish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-bulgarian.conllu data/Iran/Iran-polish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-bulgarian.conllu Iran-romanian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-bulgarian.conllu data/Iran/Iran-romanian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-bulgarian.conllu Iran-urdu.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-bulgarian.conllu data/Iran/Iran-urdu.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-bulgarian.conllu Iran-vietnamese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-bulgarian.conllu data/Iran/Iran-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-bulgarian.conllu Iran-chinese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-bulgarian.conllu data/Iran/Iran-chinese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-catalan.conllu Iran-welsh.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-catalan.conllu data/Iran/Iran-welsh.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-catalan.conllu Iran-danish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-catalan.conllu data/Iran/Iran-danish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-catalan.conllu Iran-greek.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-catalan.conllu data/Iran/Iran-greek.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-catalan.conllu Iran-spanish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-catalan.conllu data/Iran/Iran-spanish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-catalan.conllu Iran-galician.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-catalan.conllu data/Iran/Iran-galician.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-catalan.conllu Iran-hindi.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-catalan.conllu data/Iran/Iran-hindi.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-catalan.conllu Iran-indonesian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-catalan.conllu data/Iran/Iran-indonesian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-catalan.conllu Iran-latvian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-catalan.conllu data/Iran/Iran-latvian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-catalan.conllu Iran-lithuanian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-catalan.conllu data/Iran/Iran-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-catalan.conllu Iran-polish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-catalan.conllu data/Iran/Iran-polish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-catalan.conllu Iran-romanian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-catalan.conllu data/Iran/Iran-romanian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-catalan.conllu Iran-urdu.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-catalan.conllu data/Iran/Iran-urdu.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-catalan.conllu Iran-vietnamese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-catalan.conllu data/Iran/Iran-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-catalan.conllu Iran-chinese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-catalan.conllu data/Iran/Iran-chinese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-welsh.conllu Iran-danish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-welsh.conllu data/Iran/Iran-danish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-welsh.conllu Iran-greek.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-welsh.conllu data/Iran/Iran-greek.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-welsh.conllu Iran-spanish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-welsh.conllu data/Iran/Iran-spanish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-welsh.conllu Iran-galician.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-welsh.conllu data/Iran/Iran-galician.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-welsh.conllu Iran-hindi.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-welsh.conllu data/Iran/Iran-hindi.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-welsh.conllu Iran-indonesian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-welsh.conllu data/Iran/Iran-indonesian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-welsh.conllu Iran-latvian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-welsh.conllu data/Iran/Iran-latvian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-welsh.conllu Iran-lithuanian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-welsh.conllu data/Iran/Iran-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-welsh.conllu Iran-polish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-welsh.conllu data/Iran/Iran-polish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-welsh.conllu Iran-romanian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-welsh.conllu data/Iran/Iran-romanian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-welsh.conllu Iran-urdu.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-welsh.conllu data/Iran/Iran-urdu.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-welsh.conllu Iran-vietnamese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-welsh.conllu data/Iran/Iran-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-welsh.conllu Iran-chinese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-welsh.conllu data/Iran/Iran-chinese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-danish.conllu Iran-greek.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-danish.conllu data/Iran/Iran-greek.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-danish.conllu Iran-spanish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-danish.conllu data/Iran/Iran-spanish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-danish.conllu Iran-galician.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-danish.conllu data/Iran/Iran-galician.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-danish.conllu Iran-hindi.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-danish.conllu data/Iran/Iran-hindi.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-danish.conllu Iran-indonesian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-danish.conllu data/Iran/Iran-indonesian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-danish.conllu Iran-latvian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-danish.conllu data/Iran/Iran-latvian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-danish.conllu Iran-lithuanian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-danish.conllu data/Iran/Iran-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-danish.conllu Iran-polish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-danish.conllu data/Iran/Iran-polish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-danish.conllu Iran-romanian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-danish.conllu data/Iran/Iran-romanian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-danish.conllu Iran-urdu.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-danish.conllu data/Iran/Iran-urdu.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-danish.conllu Iran-vietnamese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-danish.conllu data/Iran/Iran-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-danish.conllu Iran-chinese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-danish.conllu data/Iran/Iran-chinese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-greek.conllu Iran-spanish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-greek.conllu data/Iran/Iran-spanish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-greek.conllu Iran-galician.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-greek.conllu data/Iran/Iran-galician.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-greek.conllu Iran-hindi.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-greek.conllu data/Iran/Iran-hindi.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-greek.conllu Iran-indonesian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-greek.conllu data/Iran/Iran-indonesian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-greek.conllu Iran-latvian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-greek.conllu data/Iran/Iran-latvian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-greek.conllu Iran-lithuanian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-greek.conllu data/Iran/Iran-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-greek.conllu Iran-polish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-greek.conllu data/Iran/Iran-polish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-greek.conllu Iran-romanian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-greek.conllu data/Iran/Iran-romanian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-greek.conllu Iran-urdu.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-greek.conllu data/Iran/Iran-urdu.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-greek.conllu Iran-vietnamese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-greek.conllu data/Iran/Iran-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-greek.conllu Iran-chinese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-greek.conllu data/Iran/Iran-chinese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-spanish.conllu Iran-galician.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-spanish.conllu data/Iran/Iran-galician.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-spanish.conllu Iran-hindi.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-spanish.conllu data/Iran/Iran-hindi.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-spanish.conllu Iran-indonesian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-spanish.conllu data/Iran/Iran-indonesian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-spanish.conllu Iran-latvian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-spanish.conllu data/Iran/Iran-latvian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-spanish.conllu Iran-lithuanian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-spanish.conllu data/Iran/Iran-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-spanish.conllu Iran-polish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-spanish.conllu data/Iran/Iran-polish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-spanish.conllu Iran-romanian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-spanish.conllu data/Iran/Iran-romanian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-spanish.conllu Iran-urdu.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-spanish.conllu data/Iran/Iran-urdu.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-spanish.conllu Iran-vietnamese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-spanish.conllu data/Iran/Iran-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-spanish.conllu Iran-chinese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-spanish.conllu data/Iran/Iran-chinese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-galician.conllu Iran-hindi.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-galician.conllu data/Iran/Iran-hindi.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-galician.conllu Iran-indonesian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-galician.conllu data/Iran/Iran-indonesian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-galician.conllu Iran-latvian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-galician.conllu data/Iran/Iran-latvian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-galician.conllu Iran-lithuanian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-galician.conllu data/Iran/Iran-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-galician.conllu Iran-polish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-galician.conllu data/Iran/Iran-polish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-galician.conllu Iran-romanian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-galician.conllu data/Iran/Iran-romanian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-galician.conllu Iran-urdu.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-galician.conllu data/Iran/Iran-urdu.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-galician.conllu Iran-vietnamese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-galician.conllu data/Iran/Iran-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-galician.conllu Iran-chinese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-galician.conllu data/Iran/Iran-chinese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-hindi.conllu Iran-indonesian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-hindi.conllu data/Iran/Iran-indonesian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-hindi.conllu Iran-latvian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-hindi.conllu data/Iran/Iran-latvian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-hindi.conllu Iran-lithuanian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-hindi.conllu data/Iran/Iran-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-hindi.conllu Iran-polish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-hindi.conllu data/Iran/Iran-polish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-hindi.conllu Iran-romanian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-hindi.conllu data/Iran/Iran-romanian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-hindi.conllu Iran-urdu.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-hindi.conllu data/Iran/Iran-urdu.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-hindi.conllu Iran-vietnamese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-hindi.conllu data/Iran/Iran-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-hindi.conllu Iran-chinese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-hindi.conllu data/Iran/Iran-chinese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-indonesian.conllu Iran-latvian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-indonesian.conllu data/Iran/Iran-latvian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-indonesian.conllu Iran-lithuanian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-indonesian.conllu data/Iran/Iran-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-indonesian.conllu Iran-polish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-indonesian.conllu data/Iran/Iran-polish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-indonesian.conllu Iran-romanian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-indonesian.conllu data/Iran/Iran-romanian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-indonesian.conllu Iran-urdu.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-indonesian.conllu data/Iran/Iran-urdu.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-indonesian.conllu Iran-vietnamese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-indonesian.conllu data/Iran/Iran-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-indonesian.conllu Iran-chinese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-indonesian.conllu data/Iran/Iran-chinese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-latvian.conllu Iran-lithuanian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-latvian.conllu data/Iran/Iran-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-latvian.conllu Iran-polish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-latvian.conllu data/Iran/Iran-polish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-latvian.conllu Iran-romanian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-latvian.conllu data/Iran/Iran-romanian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-latvian.conllu Iran-urdu.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-latvian.conllu data/Iran/Iran-urdu.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-latvian.conllu Iran-vietnamese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-latvian.conllu data/Iran/Iran-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-latvian.conllu Iran-chinese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-latvian.conllu data/Iran/Iran-chinese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-lithuanian.conllu Iran-polish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-lithuanian.conllu data/Iran/Iran-polish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-lithuanian.conllu Iran-romanian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-lithuanian.conllu data/Iran/Iran-romanian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-lithuanian.conllu Iran-urdu.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-lithuanian.conllu data/Iran/Iran-urdu.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-lithuanian.conllu Iran-vietnamese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-lithuanian.conllu data/Iran/Iran-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-lithuanian.conllu Iran-chinese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-lithuanian.conllu data/Iran/Iran-chinese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-polish.conllu Iran-romanian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-polish.conllu data/Iran/Iran-romanian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-polish.conllu Iran-urdu.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-polish.conllu data/Iran/Iran-urdu.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-polish.conllu Iran-vietnamese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-polish.conllu data/Iran/Iran-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-polish.conllu Iran-chinese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-polish.conllu data/Iran/Iran-chinese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-romanian.conllu Iran-urdu.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-romanian.conllu data/Iran/Iran-urdu.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-romanian.conllu Iran-vietnamese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-romanian.conllu data/Iran/Iran-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-romanian.conllu Iran-chinese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-romanian.conllu data/Iran/Iran-chinese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-urdu.conllu Iran-vietnamese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-urdu.conllu data/Iran/Iran-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-urdu.conllu Iran-chinese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-urdu.conllu data/Iran/Iran-chinese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-vietnamese.conllu Iran-chinese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-vietnamese.conllu data/Iran/Iran-chinese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-arabic.conllu Iran-czech.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-arabic.conllu data/Iran/Iran-czech.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-arabic.conllu Iran-basque.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-arabic.conllu data/Iran/Iran-basque.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-arabic.conllu Iran-korean.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-arabic.conllu data/Iran/Iran-korean.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-arabic.conllu Iran-armenian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-arabic.conllu data/Iran/Iran-armenian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-arabic.conllu Iran-croatian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-arabic.conllu data/Iran/Iran-croatian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-arabic.conllu Iran-hebrew.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-arabic.conllu data/Iran/Iran-hebrew.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-arabic.conllu Iran-kazakh.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-arabic.conllu data/Iran/Iran-kazakh.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-arabic.conllu Iran-hungarian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-arabic.conllu data/Iran/Iran-hungarian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-arabic.conllu Iran-slovenian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-arabic.conllu data/Iran/Iran-slovenian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-arabic.conllu Iran-finnish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-arabic.conllu data/Iran/Iran-finnish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-arabic.conllu Iran-swedish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-arabic.conllu data/Iran/Iran-swedish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-czech.conllu Iran-basque.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-czech.conllu data/Iran/Iran-basque.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-czech.conllu Iran-korean.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-czech.conllu data/Iran/Iran-korean.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-czech.conllu Iran-armenian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-czech.conllu data/Iran/Iran-armenian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-czech.conllu Iran-croatian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-czech.conllu data/Iran/Iran-croatian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-czech.conllu Iran-hebrew.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-czech.conllu data/Iran/Iran-hebrew.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-czech.conllu Iran-kazakh.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-czech.conllu data/Iran/Iran-kazakh.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-czech.conllu Iran-hungarian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-czech.conllu data/Iran/Iran-hungarian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-czech.conllu Iran-slovenian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-czech.conllu data/Iran/Iran-slovenian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-czech.conllu Iran-finnish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-czech.conllu data/Iran/Iran-finnish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-czech.conllu Iran-swedish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-czech.conllu data/Iran/Iran-swedish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-basque.conllu Iran-korean.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-basque.conllu data/Iran/Iran-korean.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-basque.conllu Iran-armenian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-basque.conllu data/Iran/Iran-armenian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-basque.conllu Iran-croatian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-basque.conllu data/Iran/Iran-croatian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-basque.conllu Iran-hebrew.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-basque.conllu data/Iran/Iran-hebrew.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-basque.conllu Iran-kazakh.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-basque.conllu data/Iran/Iran-kazakh.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-basque.conllu Iran-hungarian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-basque.conllu data/Iran/Iran-hungarian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-basque.conllu Iran-slovenian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-basque.conllu data/Iran/Iran-slovenian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-basque.conllu Iran-finnish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-basque.conllu data/Iran/Iran-finnish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-basque.conllu Iran-swedish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-basque.conllu data/Iran/Iran-swedish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-korean.conllu Iran-armenian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-korean.conllu data/Iran/Iran-armenian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-korean.conllu Iran-croatian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-korean.conllu data/Iran/Iran-croatian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-korean.conllu Iran-hebrew.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-korean.conllu data/Iran/Iran-hebrew.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-korean.conllu Iran-kazakh.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-korean.conllu data/Iran/Iran-kazakh.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-korean.conllu Iran-hungarian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-korean.conllu data/Iran/Iran-hungarian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-korean.conllu Iran-slovenian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-korean.conllu data/Iran/Iran-slovenian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-korean.conllu Iran-finnish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-korean.conllu data/Iran/Iran-finnish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-korean.conllu Iran-swedish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-korean.conllu data/Iran/Iran-swedish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-armenian.conllu Iran-croatian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-armenian.conllu data/Iran/Iran-croatian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-armenian.conllu Iran-hebrew.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-armenian.conllu data/Iran/Iran-hebrew.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-armenian.conllu Iran-kazakh.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-armenian.conllu data/Iran/Iran-kazakh.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-armenian.conllu Iran-hungarian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-armenian.conllu data/Iran/Iran-hungarian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-armenian.conllu Iran-slovenian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-armenian.conllu data/Iran/Iran-slovenian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-armenian.conllu Iran-finnish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-armenian.conllu data/Iran/Iran-finnish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-armenian.conllu Iran-swedish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-armenian.conllu data/Iran/Iran-swedish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-croatian.conllu Iran-hebrew.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-croatian.conllu data/Iran/Iran-hebrew.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-croatian.conllu Iran-kazakh.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-croatian.conllu data/Iran/Iran-kazakh.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-croatian.conllu Iran-hungarian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-croatian.conllu data/Iran/Iran-hungarian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-croatian.conllu Iran-slovenian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-croatian.conllu data/Iran/Iran-slovenian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-croatian.conllu Iran-finnish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-croatian.conllu data/Iran/Iran-finnish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-croatian.conllu Iran-swedish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-croatian.conllu data/Iran/Iran-swedish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-hebrew.conllu Iran-kazakh.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-hebrew.conllu data/Iran/Iran-kazakh.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-hebrew.conllu Iran-hungarian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-hebrew.conllu data/Iran/Iran-hungarian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-hebrew.conllu Iran-slovenian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-hebrew.conllu data/Iran/Iran-slovenian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-hebrew.conllu Iran-finnish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-hebrew.conllu data/Iran/Iran-finnish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-hebrew.conllu Iran-swedish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-hebrew.conllu data/Iran/Iran-swedish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-kazakh.conllu Iran-hungarian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-kazakh.conllu data/Iran/Iran-hungarian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-kazakh.conllu Iran-slovenian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-kazakh.conllu data/Iran/Iran-slovenian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-kazakh.conllu Iran-finnish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-kazakh.conllu data/Iran/Iran-finnish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-kazakh.conllu Iran-swedish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-kazakh.conllu data/Iran/Iran-swedish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-hungarian.conllu Iran-slovenian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-hungarian.conllu data/Iran/Iran-slovenian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-hungarian.conllu Iran-finnish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-hungarian.conllu data/Iran/Iran-finnish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-hungarian.conllu Iran-swedish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-hungarian.conllu data/Iran/Iran-swedish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-slovenian.conllu Iran-finnish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-slovenian.conllu data/Iran/Iran-finnish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-slovenian.conllu Iran-swedish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-slovenian.conllu data/Iran/Iran-swedish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-finnish.conllu Iran-swedish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-finnish.conllu data/Iran/Iran-swedish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-english.conllu Iran-afrikaans.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-english.conllu data/Iran/Iran-afrikaans.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-english.conllu Iran-german.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-english.conllu data/Iran/Iran-german.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-english.conllu Iran-persian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-english.conllu data/Iran/Iran-persian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-english.conllu Iran-french.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-english.conllu data/Iran/Iran-french.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-english.conllu Iran-italian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-english.conllu data/Iran/Iran-italian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-english.conllu Iran-dutch.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-english.conllu data/Iran/Iran-dutch.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-english.conllu Iran-japanese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-english.conllu data/Iran/Iran-japanese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-english.conllu Iran-portuguese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-english.conllu data/Iran/Iran-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-english.conllu Iran-russian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-english.conllu data/Iran/Iran-russian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-english.conllu Iran-serbian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-english.conllu data/Iran/Iran-serbian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-english.conllu Iran-telugu.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-english.conllu data/Iran/Iran-telugu.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-english.conllu Iran-turkish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-english.conllu data/Iran/Iran-turkish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-english.conllu Iran-ukrainian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-english.conllu data/Iran/Iran-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-afrikaans.conllu Iran-german.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-afrikaans.conllu data/Iran/Iran-german.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-afrikaans.conllu Iran-persian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-afrikaans.conllu data/Iran/Iran-persian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-afrikaans.conllu Iran-french.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-afrikaans.conllu data/Iran/Iran-french.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-afrikaans.conllu Iran-italian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-afrikaans.conllu data/Iran/Iran-italian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-afrikaans.conllu Iran-dutch.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-afrikaans.conllu data/Iran/Iran-dutch.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-afrikaans.conllu Iran-japanese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-afrikaans.conllu data/Iran/Iran-japanese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-afrikaans.conllu Iran-portuguese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-afrikaans.conllu data/Iran/Iran-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-afrikaans.conllu Iran-russian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-afrikaans.conllu data/Iran/Iran-russian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-afrikaans.conllu Iran-serbian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-afrikaans.conllu data/Iran/Iran-serbian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-afrikaans.conllu Iran-telugu.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-afrikaans.conllu data/Iran/Iran-telugu.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-afrikaans.conllu Iran-turkish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-afrikaans.conllu data/Iran/Iran-turkish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-afrikaans.conllu Iran-ukrainian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-afrikaans.conllu data/Iran/Iran-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-german.conllu Iran-persian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-german.conllu data/Iran/Iran-persian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-german.conllu Iran-french.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-german.conllu data/Iran/Iran-french.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-german.conllu Iran-italian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-german.conllu data/Iran/Iran-italian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-german.conllu Iran-dutch.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-german.conllu data/Iran/Iran-dutch.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-german.conllu Iran-japanese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-german.conllu data/Iran/Iran-japanese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-german.conllu Iran-portuguese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-german.conllu data/Iran/Iran-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-german.conllu Iran-russian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-german.conllu data/Iran/Iran-russian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-german.conllu Iran-serbian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-german.conllu data/Iran/Iran-serbian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-german.conllu Iran-telugu.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-german.conllu data/Iran/Iran-telugu.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-german.conllu Iran-turkish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-german.conllu data/Iran/Iran-turkish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-german.conllu Iran-ukrainian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-german.conllu data/Iran/Iran-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-persian.conllu Iran-french.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-persian.conllu data/Iran/Iran-french.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-persian.conllu Iran-italian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-persian.conllu data/Iran/Iran-italian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-persian.conllu Iran-dutch.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-persian.conllu data/Iran/Iran-dutch.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-persian.conllu Iran-japanese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-persian.conllu data/Iran/Iran-japanese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-persian.conllu Iran-portuguese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-persian.conllu data/Iran/Iran-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-persian.conllu Iran-russian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-persian.conllu data/Iran/Iran-russian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-persian.conllu Iran-serbian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-persian.conllu data/Iran/Iran-serbian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-persian.conllu Iran-telugu.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-persian.conllu data/Iran/Iran-telugu.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-persian.conllu Iran-turkish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-persian.conllu data/Iran/Iran-turkish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-persian.conllu Iran-ukrainian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-persian.conllu data/Iran/Iran-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-french.conllu Iran-italian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-french.conllu data/Iran/Iran-italian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-french.conllu Iran-dutch.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-french.conllu data/Iran/Iran-dutch.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-french.conllu Iran-japanese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-french.conllu data/Iran/Iran-japanese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-french.conllu Iran-portuguese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-french.conllu data/Iran/Iran-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-french.conllu Iran-russian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-french.conllu data/Iran/Iran-russian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-french.conllu Iran-serbian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-french.conllu data/Iran/Iran-serbian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-french.conllu Iran-telugu.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-french.conllu data/Iran/Iran-telugu.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-french.conllu Iran-turkish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-french.conllu data/Iran/Iran-turkish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-french.conllu Iran-ukrainian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-french.conllu data/Iran/Iran-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-italian.conllu Iran-dutch.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-italian.conllu data/Iran/Iran-dutch.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-italian.conllu Iran-japanese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-italian.conllu data/Iran/Iran-japanese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-italian.conllu Iran-portuguese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-italian.conllu data/Iran/Iran-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-italian.conllu Iran-russian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-italian.conllu data/Iran/Iran-russian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-italian.conllu Iran-serbian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-italian.conllu data/Iran/Iran-serbian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-italian.conllu Iran-telugu.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-italian.conllu data/Iran/Iran-telugu.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-italian.conllu Iran-turkish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-italian.conllu data/Iran/Iran-turkish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-italian.conllu Iran-ukrainian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-italian.conllu data/Iran/Iran-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-dutch.conllu Iran-japanese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-dutch.conllu data/Iran/Iran-japanese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-dutch.conllu Iran-portuguese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-dutch.conllu data/Iran/Iran-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-dutch.conllu Iran-russian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-dutch.conllu data/Iran/Iran-russian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-dutch.conllu Iran-serbian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-dutch.conllu data/Iran/Iran-serbian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-dutch.conllu Iran-telugu.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-dutch.conllu data/Iran/Iran-telugu.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-dutch.conllu Iran-turkish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-dutch.conllu data/Iran/Iran-turkish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-dutch.conllu Iran-ukrainian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-dutch.conllu data/Iran/Iran-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-japanese.conllu Iran-portuguese.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-japanese.conllu data/Iran/Iran-portuguese.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-japanese.conllu Iran-russian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-japanese.conllu data/Iran/Iran-russian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-japanese.conllu Iran-serbian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-japanese.conllu data/Iran/Iran-serbian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-japanese.conllu Iran-telugu.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-japanese.conllu data/Iran/Iran-telugu.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-japanese.conllu Iran-turkish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-japanese.conllu data/Iran/Iran-turkish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-japanese.conllu Iran-ukrainian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-japanese.conllu data/Iran/Iran-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-portuguese.conllu Iran-russian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-portuguese.conllu data/Iran/Iran-russian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-portuguese.conllu Iran-serbian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-portuguese.conllu data/Iran/Iran-serbian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-portuguese.conllu Iran-telugu.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-portuguese.conllu data/Iran/Iran-telugu.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-portuguese.conllu Iran-turkish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-portuguese.conllu data/Iran/Iran-turkish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-portuguese.conllu Iran-ukrainian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-portuguese.conllu data/Iran/Iran-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-russian.conllu Iran-serbian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-russian.conllu data/Iran/Iran-serbian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-russian.conllu Iran-telugu.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-russian.conllu data/Iran/Iran-telugu.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-russian.conllu Iran-turkish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-russian.conllu data/Iran/Iran-turkish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-russian.conllu Iran-ukrainian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-russian.conllu data/Iran/Iran-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-serbian.conllu Iran-telugu.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-serbian.conllu data/Iran/Iran-telugu.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-serbian.conllu Iran-turkish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-serbian.conllu data/Iran/Iran-turkish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-serbian.conllu Iran-ukrainian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-serbian.conllu data/Iran/Iran-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-telugu.conllu Iran-turkish.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-telugu.conllu data/Iran/Iran-turkish.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-telugu.conllu Iran-ukrainian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-telugu.conllu data/Iran/Iran-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
echo Iran-turkish.conllu Iran-ukrainian.conllu >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
gfud cosine-similarity data/Iran/Iran-turkish.conllu data/Iran/Iran-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Iran-cosine-sim.txt ; 
} 
topic_combinations