#! /bin/bash 
function topic_combinations { 
echo Italy-north_sami.conllu Italy-scottish_gaelic.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-north_sami.conllu data/Italy/Italy-scottish_gaelic.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-north_sami.conllu Italy-gothic.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-north_sami.conllu data/Italy/Italy-gothic.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-north_sami.conllu Italy-sanskrit.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-north_sami.conllu data/Italy/Italy-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-north_sami.conllu Italy-wolof.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-north_sami.conllu data/Italy/Italy-wolof.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-scottish_gaelic.conllu Italy-gothic.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-scottish_gaelic.conllu data/Italy/Italy-gothic.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-scottish_gaelic.conllu Italy-sanskrit.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-scottish_gaelic.conllu data/Italy/Italy-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-scottish_gaelic.conllu Italy-wolof.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-scottish_gaelic.conllu data/Italy/Italy-wolof.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-gothic.conllu Italy-sanskrit.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-gothic.conllu data/Italy/Italy-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-gothic.conllu Italy-wolof.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-gothic.conllu data/Italy/Italy-wolof.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-sanskrit.conllu Italy-wolof.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-sanskrit.conllu data/Italy/Italy-wolof.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-irish.conllu Italy-latin.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-irish.conllu data/Italy/Italy-latin.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-irish.conllu Italy-latvian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-irish.conllu data/Italy/Italy-latvian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-irish.conllu Italy-maltese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-irish.conllu data/Italy/Italy-maltese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-irish.conllu Italy-marathi.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-irish.conllu data/Italy/Italy-marathi.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-irish.conllu Italy-old_church_slavonic.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-irish.conllu data/Italy/Italy-old_church_slavonic.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-irish.conllu Italy-tamil.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-irish.conllu data/Italy/Italy-tamil.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-irish.conllu Italy-urdu.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-irish.conllu data/Italy/Italy-urdu.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-irish.conllu Italy-uyghur.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-irish.conllu data/Italy/Italy-uyghur.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-latin.conllu Italy-latvian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-latin.conllu data/Italy/Italy-latvian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-latin.conllu Italy-maltese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-latin.conllu data/Italy/Italy-maltese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-latin.conllu Italy-marathi.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-latin.conllu data/Italy/Italy-marathi.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-latin.conllu Italy-old_church_slavonic.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-latin.conllu data/Italy/Italy-old_church_slavonic.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-latin.conllu Italy-tamil.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-latin.conllu data/Italy/Italy-tamil.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-latin.conllu Italy-urdu.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-latin.conllu data/Italy/Italy-urdu.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-latin.conllu Italy-uyghur.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-latin.conllu data/Italy/Italy-uyghur.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-latvian.conllu Italy-maltese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-latvian.conllu data/Italy/Italy-maltese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-latvian.conllu Italy-marathi.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-latvian.conllu data/Italy/Italy-marathi.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-latvian.conllu Italy-old_church_slavonic.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-latvian.conllu data/Italy/Italy-old_church_slavonic.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-latvian.conllu Italy-tamil.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-latvian.conllu data/Italy/Italy-tamil.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-latvian.conllu Italy-urdu.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-latvian.conllu data/Italy/Italy-urdu.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-latvian.conllu Italy-uyghur.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-latvian.conllu data/Italy/Italy-uyghur.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-maltese.conllu Italy-marathi.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-maltese.conllu data/Italy/Italy-marathi.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-maltese.conllu Italy-old_church_slavonic.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-maltese.conllu data/Italy/Italy-old_church_slavonic.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-maltese.conllu Italy-tamil.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-maltese.conllu data/Italy/Italy-tamil.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-maltese.conllu Italy-urdu.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-maltese.conllu data/Italy/Italy-urdu.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-maltese.conllu Italy-uyghur.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-maltese.conllu data/Italy/Italy-uyghur.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-marathi.conllu Italy-old_church_slavonic.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-marathi.conllu data/Italy/Italy-old_church_slavonic.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-marathi.conllu Italy-tamil.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-marathi.conllu data/Italy/Italy-tamil.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-marathi.conllu Italy-urdu.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-marathi.conllu data/Italy/Italy-urdu.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-marathi.conllu Italy-uyghur.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-marathi.conllu data/Italy/Italy-uyghur.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-old_church_slavonic.conllu Italy-tamil.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-old_church_slavonic.conllu data/Italy/Italy-tamil.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-old_church_slavonic.conllu Italy-urdu.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-old_church_slavonic.conllu data/Italy/Italy-urdu.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-old_church_slavonic.conllu Italy-uyghur.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-old_church_slavonic.conllu data/Italy/Italy-uyghur.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-tamil.conllu Italy-urdu.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-tamil.conllu data/Italy/Italy-urdu.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-tamil.conllu Italy-uyghur.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-tamil.conllu data/Italy/Italy-uyghur.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-urdu.conllu Italy-uyghur.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-urdu.conllu data/Italy/Italy-uyghur.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-belarusian.conllu Italy-catalan.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-belarusian.conllu data/Italy/Italy-catalan.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-belarusian.conllu Italy-welsh.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-belarusian.conllu data/Italy/Italy-welsh.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-belarusian.conllu Italy-danish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-belarusian.conllu data/Italy/Italy-danish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-belarusian.conllu Italy-greek.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-belarusian.conllu data/Italy/Italy-greek.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-belarusian.conllu Italy-basque.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-belarusian.conllu data/Italy/Italy-basque.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-belarusian.conllu Italy-persian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-belarusian.conllu data/Italy/Italy-persian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-belarusian.conllu Italy-galician.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-belarusian.conllu data/Italy/Italy-galician.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-belarusian.conllu Italy-hindi.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-belarusian.conllu data/Italy/Italy-hindi.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-belarusian.conllu Italy-croatian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-belarusian.conllu data/Italy/Italy-croatian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-belarusian.conllu Italy-hebrew.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-belarusian.conllu data/Italy/Italy-hebrew.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-belarusian.conllu Italy-kazakh.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-belarusian.conllu data/Italy/Italy-kazakh.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-belarusian.conllu Italy-lithuanian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-belarusian.conllu data/Italy/Italy-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-belarusian.conllu Italy-polish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-belarusian.conllu data/Italy/Italy-polish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-belarusian.conllu Italy-slovak.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-belarusian.conllu data/Italy/Italy-slovak.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-belarusian.conllu Italy-serbian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-belarusian.conllu data/Italy/Italy-serbian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-catalan.conllu Italy-welsh.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-catalan.conllu data/Italy/Italy-welsh.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-catalan.conllu Italy-danish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-catalan.conllu data/Italy/Italy-danish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-catalan.conllu Italy-greek.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-catalan.conllu data/Italy/Italy-greek.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-catalan.conllu Italy-basque.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-catalan.conllu data/Italy/Italy-basque.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-catalan.conllu Italy-persian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-catalan.conllu data/Italy/Italy-persian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-catalan.conllu Italy-galician.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-catalan.conllu data/Italy/Italy-galician.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-catalan.conllu Italy-hindi.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-catalan.conllu data/Italy/Italy-hindi.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-catalan.conllu Italy-croatian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-catalan.conllu data/Italy/Italy-croatian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-catalan.conllu Italy-hebrew.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-catalan.conllu data/Italy/Italy-hebrew.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-catalan.conllu Italy-kazakh.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-catalan.conllu data/Italy/Italy-kazakh.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-catalan.conllu Italy-lithuanian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-catalan.conllu data/Italy/Italy-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-catalan.conllu Italy-polish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-catalan.conllu data/Italy/Italy-polish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-catalan.conllu Italy-slovak.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-catalan.conllu data/Italy/Italy-slovak.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-catalan.conllu Italy-serbian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-catalan.conllu data/Italy/Italy-serbian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-welsh.conllu Italy-danish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-welsh.conllu data/Italy/Italy-danish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-welsh.conllu Italy-greek.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-welsh.conllu data/Italy/Italy-greek.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-welsh.conllu Italy-basque.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-welsh.conllu data/Italy/Italy-basque.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-welsh.conllu Italy-persian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-welsh.conllu data/Italy/Italy-persian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-welsh.conllu Italy-galician.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-welsh.conllu data/Italy/Italy-galician.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-welsh.conllu Italy-hindi.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-welsh.conllu data/Italy/Italy-hindi.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-welsh.conllu Italy-croatian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-welsh.conllu data/Italy/Italy-croatian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-welsh.conllu Italy-hebrew.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-welsh.conllu data/Italy/Italy-hebrew.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-welsh.conllu Italy-kazakh.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-welsh.conllu data/Italy/Italy-kazakh.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-welsh.conllu Italy-lithuanian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-welsh.conllu data/Italy/Italy-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-welsh.conllu Italy-polish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-welsh.conllu data/Italy/Italy-polish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-welsh.conllu Italy-slovak.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-welsh.conllu data/Italy/Italy-slovak.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-welsh.conllu Italy-serbian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-welsh.conllu data/Italy/Italy-serbian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-danish.conllu Italy-greek.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-danish.conllu data/Italy/Italy-greek.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-danish.conllu Italy-basque.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-danish.conllu data/Italy/Italy-basque.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-danish.conllu Italy-persian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-danish.conllu data/Italy/Italy-persian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-danish.conllu Italy-galician.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-danish.conllu data/Italy/Italy-galician.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-danish.conllu Italy-hindi.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-danish.conllu data/Italy/Italy-hindi.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-danish.conllu Italy-croatian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-danish.conllu data/Italy/Italy-croatian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-danish.conllu Italy-hebrew.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-danish.conllu data/Italy/Italy-hebrew.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-danish.conllu Italy-kazakh.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-danish.conllu data/Italy/Italy-kazakh.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-danish.conllu Italy-lithuanian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-danish.conllu data/Italy/Italy-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-danish.conllu Italy-polish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-danish.conllu data/Italy/Italy-polish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-danish.conllu Italy-slovak.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-danish.conllu data/Italy/Italy-slovak.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-danish.conllu Italy-serbian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-danish.conllu data/Italy/Italy-serbian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-greek.conllu Italy-basque.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-greek.conllu data/Italy/Italy-basque.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-greek.conllu Italy-persian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-greek.conllu data/Italy/Italy-persian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-greek.conllu Italy-galician.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-greek.conllu data/Italy/Italy-galician.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-greek.conllu Italy-hindi.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-greek.conllu data/Italy/Italy-hindi.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-greek.conllu Italy-croatian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-greek.conllu data/Italy/Italy-croatian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-greek.conllu Italy-hebrew.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-greek.conllu data/Italy/Italy-hebrew.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-greek.conllu Italy-kazakh.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-greek.conllu data/Italy/Italy-kazakh.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-greek.conllu Italy-lithuanian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-greek.conllu data/Italy/Italy-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-greek.conllu Italy-polish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-greek.conllu data/Italy/Italy-polish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-greek.conllu Italy-slovak.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-greek.conllu data/Italy/Italy-slovak.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-greek.conllu Italy-serbian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-greek.conllu data/Italy/Italy-serbian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-basque.conllu Italy-persian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-basque.conllu data/Italy/Italy-persian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-basque.conllu Italy-galician.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-basque.conllu data/Italy/Italy-galician.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-basque.conllu Italy-hindi.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-basque.conllu data/Italy/Italy-hindi.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-basque.conllu Italy-croatian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-basque.conllu data/Italy/Italy-croatian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-basque.conllu Italy-hebrew.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-basque.conllu data/Italy/Italy-hebrew.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-basque.conllu Italy-kazakh.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-basque.conllu data/Italy/Italy-kazakh.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-basque.conllu Italy-lithuanian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-basque.conllu data/Italy/Italy-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-basque.conllu Italy-polish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-basque.conllu data/Italy/Italy-polish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-basque.conllu Italy-slovak.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-basque.conllu data/Italy/Italy-slovak.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-basque.conllu Italy-serbian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-basque.conllu data/Italy/Italy-serbian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-persian.conllu Italy-galician.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-persian.conllu data/Italy/Italy-galician.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-persian.conllu Italy-hindi.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-persian.conllu data/Italy/Italy-hindi.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-persian.conllu Italy-croatian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-persian.conllu data/Italy/Italy-croatian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-persian.conllu Italy-hebrew.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-persian.conllu data/Italy/Italy-hebrew.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-persian.conllu Italy-kazakh.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-persian.conllu data/Italy/Italy-kazakh.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-persian.conllu Italy-lithuanian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-persian.conllu data/Italy/Italy-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-persian.conllu Italy-polish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-persian.conllu data/Italy/Italy-polish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-persian.conllu Italy-slovak.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-persian.conllu data/Italy/Italy-slovak.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-persian.conllu Italy-serbian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-persian.conllu data/Italy/Italy-serbian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-galician.conllu Italy-hindi.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-galician.conllu data/Italy/Italy-hindi.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-galician.conllu Italy-croatian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-galician.conllu data/Italy/Italy-croatian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-galician.conllu Italy-hebrew.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-galician.conllu data/Italy/Italy-hebrew.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-galician.conllu Italy-kazakh.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-galician.conllu data/Italy/Italy-kazakh.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-galician.conllu Italy-lithuanian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-galician.conllu data/Italy/Italy-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-galician.conllu Italy-polish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-galician.conllu data/Italy/Italy-polish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-galician.conllu Italy-slovak.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-galician.conllu data/Italy/Italy-slovak.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-galician.conllu Italy-serbian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-galician.conllu data/Italy/Italy-serbian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-hindi.conllu Italy-croatian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-hindi.conllu data/Italy/Italy-croatian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-hindi.conllu Italy-hebrew.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-hindi.conllu data/Italy/Italy-hebrew.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-hindi.conllu Italy-kazakh.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-hindi.conllu data/Italy/Italy-kazakh.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-hindi.conllu Italy-lithuanian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-hindi.conllu data/Italy/Italy-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-hindi.conllu Italy-polish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-hindi.conllu data/Italy/Italy-polish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-hindi.conllu Italy-slovak.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-hindi.conllu data/Italy/Italy-slovak.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-hindi.conllu Italy-serbian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-hindi.conllu data/Italy/Italy-serbian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-croatian.conllu Italy-hebrew.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-croatian.conllu data/Italy/Italy-hebrew.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-croatian.conllu Italy-kazakh.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-croatian.conllu data/Italy/Italy-kazakh.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-croatian.conllu Italy-lithuanian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-croatian.conllu data/Italy/Italy-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-croatian.conllu Italy-polish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-croatian.conllu data/Italy/Italy-polish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-croatian.conllu Italy-slovak.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-croatian.conllu data/Italy/Italy-slovak.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-croatian.conllu Italy-serbian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-croatian.conllu data/Italy/Italy-serbian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-hebrew.conllu Italy-kazakh.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-hebrew.conllu data/Italy/Italy-kazakh.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-hebrew.conllu Italy-lithuanian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-hebrew.conllu data/Italy/Italy-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-hebrew.conllu Italy-polish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-hebrew.conllu data/Italy/Italy-polish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-hebrew.conllu Italy-slovak.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-hebrew.conllu data/Italy/Italy-slovak.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-hebrew.conllu Italy-serbian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-hebrew.conllu data/Italy/Italy-serbian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-kazakh.conllu Italy-lithuanian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-kazakh.conllu data/Italy/Italy-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-kazakh.conllu Italy-polish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-kazakh.conllu data/Italy/Italy-polish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-kazakh.conllu Italy-slovak.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-kazakh.conllu data/Italy/Italy-slovak.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-kazakh.conllu Italy-serbian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-kazakh.conllu data/Italy/Italy-serbian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-lithuanian.conllu Italy-polish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-lithuanian.conllu data/Italy/Italy-polish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-lithuanian.conllu Italy-slovak.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-lithuanian.conllu data/Italy/Italy-slovak.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-lithuanian.conllu Italy-serbian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-lithuanian.conllu data/Italy/Italy-serbian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-polish.conllu Italy-slovak.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-polish.conllu data/Italy/Italy-slovak.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-polish.conllu Italy-serbian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-polish.conllu data/Italy/Italy-serbian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-slovak.conllu Italy-serbian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-slovak.conllu data/Italy/Italy-serbian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-afrikaans.conllu Italy-spanish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-afrikaans.conllu data/Italy/Italy-spanish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-afrikaans.conllu Italy-indonesian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-afrikaans.conllu data/Italy/Italy-indonesian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-afrikaans.conllu Italy-hungarian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-afrikaans.conllu data/Italy/Italy-hungarian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-afrikaans.conllu Italy-dutch.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-afrikaans.conllu data/Italy/Italy-dutch.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-afrikaans.conllu Italy-finnish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-afrikaans.conllu data/Italy/Italy-finnish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-afrikaans.conllu Italy-swedish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-afrikaans.conllu data/Italy/Italy-swedish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-afrikaans.conllu Italy-ukrainian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-afrikaans.conllu data/Italy/Italy-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-afrikaans.conllu Italy-classical_chinese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-afrikaans.conllu data/Italy/Italy-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-spanish.conllu Italy-indonesian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-spanish.conllu data/Italy/Italy-indonesian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-spanish.conllu Italy-hungarian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-spanish.conllu data/Italy/Italy-hungarian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-spanish.conllu Italy-dutch.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-spanish.conllu data/Italy/Italy-dutch.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-spanish.conllu Italy-finnish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-spanish.conllu data/Italy/Italy-finnish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-spanish.conllu Italy-swedish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-spanish.conllu data/Italy/Italy-swedish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-spanish.conllu Italy-ukrainian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-spanish.conllu data/Italy/Italy-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-spanish.conllu Italy-classical_chinese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-spanish.conllu data/Italy/Italy-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-indonesian.conllu Italy-hungarian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-indonesian.conllu data/Italy/Italy-hungarian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-indonesian.conllu Italy-dutch.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-indonesian.conllu data/Italy/Italy-dutch.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-indonesian.conllu Italy-finnish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-indonesian.conllu data/Italy/Italy-finnish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-indonesian.conllu Italy-swedish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-indonesian.conllu data/Italy/Italy-swedish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-indonesian.conllu Italy-ukrainian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-indonesian.conllu data/Italy/Italy-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-indonesian.conllu Italy-classical_chinese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-indonesian.conllu data/Italy/Italy-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-hungarian.conllu Italy-dutch.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-hungarian.conllu data/Italy/Italy-dutch.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-hungarian.conllu Italy-finnish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-hungarian.conllu data/Italy/Italy-finnish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-hungarian.conllu Italy-swedish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-hungarian.conllu data/Italy/Italy-swedish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-hungarian.conllu Italy-ukrainian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-hungarian.conllu data/Italy/Italy-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-hungarian.conllu Italy-classical_chinese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-hungarian.conllu data/Italy/Italy-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-dutch.conllu Italy-finnish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-dutch.conllu data/Italy/Italy-finnish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-dutch.conllu Italy-swedish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-dutch.conllu data/Italy/Italy-swedish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-dutch.conllu Italy-ukrainian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-dutch.conllu data/Italy/Italy-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-dutch.conllu Italy-classical_chinese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-dutch.conllu data/Italy/Italy-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-finnish.conllu Italy-swedish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-finnish.conllu data/Italy/Italy-swedish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-finnish.conllu Italy-ukrainian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-finnish.conllu data/Italy/Italy-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-finnish.conllu Italy-classical_chinese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-finnish.conllu data/Italy/Italy-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-swedish.conllu Italy-ukrainian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-swedish.conllu data/Italy/Italy-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-swedish.conllu Italy-classical_chinese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-swedish.conllu data/Italy/Italy-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-ukrainian.conllu Italy-classical_chinese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-ukrainian.conllu data/Italy/Italy-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-english.conllu Italy-arabic.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-english.conllu data/Italy/Italy-arabic.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-english.conllu Italy-bulgarian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-english.conllu data/Italy/Italy-bulgarian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-english.conllu Italy-czech.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-english.conllu data/Italy/Italy-czech.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-english.conllu Italy-german.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-english.conllu data/Italy/Italy-german.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-english.conllu Italy-estonian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-english.conllu data/Italy/Italy-estonian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-english.conllu Italy-french.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-english.conllu data/Italy/Italy-french.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-english.conllu Italy-korean.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-english.conllu data/Italy/Italy-korean.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-english.conllu Italy-armenian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-english.conllu data/Italy/Italy-armenian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-english.conllu Italy-italian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-english.conllu data/Italy/Italy-italian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-english.conllu Italy-japanese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-english.conllu data/Italy/Italy-japanese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-english.conllu Italy-portuguese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-english.conllu data/Italy/Italy-portuguese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-english.conllu Italy-romanian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-english.conllu data/Italy/Italy-romanian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-english.conllu Italy-russian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-english.conllu data/Italy/Italy-russian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-english.conllu Italy-slovenian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-english.conllu data/Italy/Italy-slovenian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-english.conllu Italy-telugu.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-english.conllu data/Italy/Italy-telugu.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-english.conllu Italy-turkish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-english.conllu data/Italy/Italy-turkish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-english.conllu Italy-vietnamese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-english.conllu data/Italy/Italy-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-english.conllu Italy-chinese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-english.conllu data/Italy/Italy-chinese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-arabic.conllu Italy-bulgarian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-arabic.conllu data/Italy/Italy-bulgarian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-arabic.conllu Italy-czech.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-arabic.conllu data/Italy/Italy-czech.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-arabic.conllu Italy-german.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-arabic.conllu data/Italy/Italy-german.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-arabic.conllu Italy-estonian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-arabic.conllu data/Italy/Italy-estonian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-arabic.conllu Italy-french.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-arabic.conllu data/Italy/Italy-french.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-arabic.conllu Italy-korean.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-arabic.conllu data/Italy/Italy-korean.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-arabic.conllu Italy-armenian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-arabic.conllu data/Italy/Italy-armenian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-arabic.conllu Italy-italian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-arabic.conllu data/Italy/Italy-italian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-arabic.conllu Italy-japanese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-arabic.conllu data/Italy/Italy-japanese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-arabic.conllu Italy-portuguese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-arabic.conllu data/Italy/Italy-portuguese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-arabic.conllu Italy-romanian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-arabic.conllu data/Italy/Italy-romanian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-arabic.conllu Italy-russian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-arabic.conllu data/Italy/Italy-russian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-arabic.conllu Italy-slovenian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-arabic.conllu data/Italy/Italy-slovenian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-arabic.conllu Italy-telugu.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-arabic.conllu data/Italy/Italy-telugu.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-arabic.conllu Italy-turkish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-arabic.conllu data/Italy/Italy-turkish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-arabic.conllu Italy-vietnamese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-arabic.conllu data/Italy/Italy-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-arabic.conllu Italy-chinese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-arabic.conllu data/Italy/Italy-chinese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-bulgarian.conllu Italy-czech.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-bulgarian.conllu data/Italy/Italy-czech.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-bulgarian.conllu Italy-german.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-bulgarian.conllu data/Italy/Italy-german.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-bulgarian.conllu Italy-estonian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-bulgarian.conllu data/Italy/Italy-estonian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-bulgarian.conllu Italy-french.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-bulgarian.conllu data/Italy/Italy-french.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-bulgarian.conllu Italy-korean.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-bulgarian.conllu data/Italy/Italy-korean.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-bulgarian.conllu Italy-armenian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-bulgarian.conllu data/Italy/Italy-armenian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-bulgarian.conllu Italy-italian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-bulgarian.conllu data/Italy/Italy-italian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-bulgarian.conllu Italy-japanese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-bulgarian.conllu data/Italy/Italy-japanese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-bulgarian.conllu Italy-portuguese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-bulgarian.conllu data/Italy/Italy-portuguese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-bulgarian.conllu Italy-romanian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-bulgarian.conllu data/Italy/Italy-romanian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-bulgarian.conllu Italy-russian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-bulgarian.conllu data/Italy/Italy-russian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-bulgarian.conllu Italy-slovenian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-bulgarian.conllu data/Italy/Italy-slovenian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-bulgarian.conllu Italy-telugu.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-bulgarian.conllu data/Italy/Italy-telugu.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-bulgarian.conllu Italy-turkish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-bulgarian.conllu data/Italy/Italy-turkish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-bulgarian.conllu Italy-vietnamese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-bulgarian.conllu data/Italy/Italy-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-bulgarian.conllu Italy-chinese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-bulgarian.conllu data/Italy/Italy-chinese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-czech.conllu Italy-german.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-czech.conllu data/Italy/Italy-german.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-czech.conllu Italy-estonian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-czech.conllu data/Italy/Italy-estonian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-czech.conllu Italy-french.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-czech.conllu data/Italy/Italy-french.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-czech.conllu Italy-korean.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-czech.conllu data/Italy/Italy-korean.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-czech.conllu Italy-armenian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-czech.conllu data/Italy/Italy-armenian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-czech.conllu Italy-italian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-czech.conllu data/Italy/Italy-italian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-czech.conllu Italy-japanese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-czech.conllu data/Italy/Italy-japanese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-czech.conllu Italy-portuguese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-czech.conllu data/Italy/Italy-portuguese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-czech.conllu Italy-romanian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-czech.conllu data/Italy/Italy-romanian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-czech.conllu Italy-russian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-czech.conllu data/Italy/Italy-russian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-czech.conllu Italy-slovenian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-czech.conllu data/Italy/Italy-slovenian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-czech.conllu Italy-telugu.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-czech.conllu data/Italy/Italy-telugu.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-czech.conllu Italy-turkish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-czech.conllu data/Italy/Italy-turkish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-czech.conllu Italy-vietnamese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-czech.conllu data/Italy/Italy-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-czech.conllu Italy-chinese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-czech.conllu data/Italy/Italy-chinese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-german.conllu Italy-estonian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-german.conllu data/Italy/Italy-estonian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-german.conllu Italy-french.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-german.conllu data/Italy/Italy-french.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-german.conllu Italy-korean.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-german.conllu data/Italy/Italy-korean.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-german.conllu Italy-armenian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-german.conllu data/Italy/Italy-armenian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-german.conllu Italy-italian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-german.conllu data/Italy/Italy-italian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-german.conllu Italy-japanese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-german.conllu data/Italy/Italy-japanese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-german.conllu Italy-portuguese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-german.conllu data/Italy/Italy-portuguese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-german.conllu Italy-romanian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-german.conllu data/Italy/Italy-romanian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-german.conllu Italy-russian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-german.conllu data/Italy/Italy-russian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-german.conllu Italy-slovenian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-german.conllu data/Italy/Italy-slovenian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-german.conllu Italy-telugu.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-german.conllu data/Italy/Italy-telugu.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-german.conllu Italy-turkish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-german.conllu data/Italy/Italy-turkish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-german.conllu Italy-vietnamese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-german.conllu data/Italy/Italy-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-german.conllu Italy-chinese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-german.conllu data/Italy/Italy-chinese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-estonian.conllu Italy-french.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-estonian.conllu data/Italy/Italy-french.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-estonian.conllu Italy-korean.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-estonian.conllu data/Italy/Italy-korean.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-estonian.conllu Italy-armenian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-estonian.conllu data/Italy/Italy-armenian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-estonian.conllu Italy-italian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-estonian.conllu data/Italy/Italy-italian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-estonian.conllu Italy-japanese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-estonian.conllu data/Italy/Italy-japanese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-estonian.conllu Italy-portuguese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-estonian.conllu data/Italy/Italy-portuguese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-estonian.conllu Italy-romanian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-estonian.conllu data/Italy/Italy-romanian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-estonian.conllu Italy-russian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-estonian.conllu data/Italy/Italy-russian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-estonian.conllu Italy-slovenian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-estonian.conllu data/Italy/Italy-slovenian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-estonian.conllu Italy-telugu.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-estonian.conllu data/Italy/Italy-telugu.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-estonian.conllu Italy-turkish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-estonian.conllu data/Italy/Italy-turkish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-estonian.conllu Italy-vietnamese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-estonian.conllu data/Italy/Italy-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-estonian.conllu Italy-chinese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-estonian.conllu data/Italy/Italy-chinese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-french.conllu Italy-korean.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-french.conllu data/Italy/Italy-korean.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-french.conllu Italy-armenian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-french.conllu data/Italy/Italy-armenian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-french.conllu Italy-italian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-french.conllu data/Italy/Italy-italian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-french.conllu Italy-japanese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-french.conllu data/Italy/Italy-japanese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-french.conllu Italy-portuguese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-french.conllu data/Italy/Italy-portuguese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-french.conllu Italy-romanian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-french.conllu data/Italy/Italy-romanian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-french.conllu Italy-russian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-french.conllu data/Italy/Italy-russian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-french.conllu Italy-slovenian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-french.conllu data/Italy/Italy-slovenian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-french.conllu Italy-telugu.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-french.conllu data/Italy/Italy-telugu.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-french.conllu Italy-turkish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-french.conllu data/Italy/Italy-turkish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-french.conllu Italy-vietnamese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-french.conllu data/Italy/Italy-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-french.conllu Italy-chinese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-french.conllu data/Italy/Italy-chinese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-korean.conllu Italy-armenian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-korean.conllu data/Italy/Italy-armenian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-korean.conllu Italy-italian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-korean.conllu data/Italy/Italy-italian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-korean.conllu Italy-japanese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-korean.conllu data/Italy/Italy-japanese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-korean.conllu Italy-portuguese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-korean.conllu data/Italy/Italy-portuguese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-korean.conllu Italy-romanian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-korean.conllu data/Italy/Italy-romanian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-korean.conllu Italy-russian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-korean.conllu data/Italy/Italy-russian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-korean.conllu Italy-slovenian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-korean.conllu data/Italy/Italy-slovenian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-korean.conllu Italy-telugu.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-korean.conllu data/Italy/Italy-telugu.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-korean.conllu Italy-turkish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-korean.conllu data/Italy/Italy-turkish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-korean.conllu Italy-vietnamese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-korean.conllu data/Italy/Italy-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-korean.conllu Italy-chinese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-korean.conllu data/Italy/Italy-chinese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-armenian.conllu Italy-italian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-armenian.conllu data/Italy/Italy-italian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-armenian.conllu Italy-japanese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-armenian.conllu data/Italy/Italy-japanese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-armenian.conllu Italy-portuguese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-armenian.conllu data/Italy/Italy-portuguese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-armenian.conllu Italy-romanian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-armenian.conllu data/Italy/Italy-romanian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-armenian.conllu Italy-russian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-armenian.conllu data/Italy/Italy-russian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-armenian.conllu Italy-slovenian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-armenian.conllu data/Italy/Italy-slovenian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-armenian.conllu Italy-telugu.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-armenian.conllu data/Italy/Italy-telugu.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-armenian.conllu Italy-turkish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-armenian.conllu data/Italy/Italy-turkish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-armenian.conllu Italy-vietnamese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-armenian.conllu data/Italy/Italy-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-armenian.conllu Italy-chinese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-armenian.conllu data/Italy/Italy-chinese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-italian.conllu Italy-japanese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-italian.conllu data/Italy/Italy-japanese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-italian.conllu Italy-portuguese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-italian.conllu data/Italy/Italy-portuguese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-italian.conllu Italy-romanian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-italian.conllu data/Italy/Italy-romanian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-italian.conllu Italy-russian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-italian.conllu data/Italy/Italy-russian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-italian.conllu Italy-slovenian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-italian.conllu data/Italy/Italy-slovenian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-italian.conllu Italy-telugu.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-italian.conllu data/Italy/Italy-telugu.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-italian.conllu Italy-turkish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-italian.conllu data/Italy/Italy-turkish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-italian.conllu Italy-vietnamese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-italian.conllu data/Italy/Italy-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-italian.conllu Italy-chinese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-italian.conllu data/Italy/Italy-chinese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-japanese.conllu Italy-portuguese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-japanese.conllu data/Italy/Italy-portuguese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-japanese.conllu Italy-romanian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-japanese.conllu data/Italy/Italy-romanian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-japanese.conllu Italy-russian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-japanese.conllu data/Italy/Italy-russian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-japanese.conllu Italy-slovenian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-japanese.conllu data/Italy/Italy-slovenian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-japanese.conllu Italy-telugu.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-japanese.conllu data/Italy/Italy-telugu.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-japanese.conllu Italy-turkish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-japanese.conllu data/Italy/Italy-turkish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-japanese.conllu Italy-vietnamese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-japanese.conllu data/Italy/Italy-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-japanese.conllu Italy-chinese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-japanese.conllu data/Italy/Italy-chinese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-portuguese.conllu Italy-romanian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-portuguese.conllu data/Italy/Italy-romanian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-portuguese.conllu Italy-russian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-portuguese.conllu data/Italy/Italy-russian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-portuguese.conllu Italy-slovenian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-portuguese.conllu data/Italy/Italy-slovenian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-portuguese.conllu Italy-telugu.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-portuguese.conllu data/Italy/Italy-telugu.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-portuguese.conllu Italy-turkish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-portuguese.conllu data/Italy/Italy-turkish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-portuguese.conllu Italy-vietnamese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-portuguese.conllu data/Italy/Italy-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-portuguese.conllu Italy-chinese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-portuguese.conllu data/Italy/Italy-chinese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-romanian.conllu Italy-russian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-romanian.conllu data/Italy/Italy-russian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-romanian.conllu Italy-slovenian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-romanian.conllu data/Italy/Italy-slovenian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-romanian.conllu Italy-telugu.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-romanian.conllu data/Italy/Italy-telugu.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-romanian.conllu Italy-turkish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-romanian.conllu data/Italy/Italy-turkish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-romanian.conllu Italy-vietnamese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-romanian.conllu data/Italy/Italy-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-romanian.conllu Italy-chinese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-romanian.conllu data/Italy/Italy-chinese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-russian.conllu Italy-slovenian.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-russian.conllu data/Italy/Italy-slovenian.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-russian.conllu Italy-telugu.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-russian.conllu data/Italy/Italy-telugu.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-russian.conllu Italy-turkish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-russian.conllu data/Italy/Italy-turkish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-russian.conllu Italy-vietnamese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-russian.conllu data/Italy/Italy-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-russian.conllu Italy-chinese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-russian.conllu data/Italy/Italy-chinese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-slovenian.conllu Italy-telugu.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-slovenian.conllu data/Italy/Italy-telugu.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-slovenian.conllu Italy-turkish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-slovenian.conllu data/Italy/Italy-turkish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-slovenian.conllu Italy-vietnamese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-slovenian.conllu data/Italy/Italy-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-slovenian.conllu Italy-chinese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-slovenian.conllu data/Italy/Italy-chinese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-telugu.conllu Italy-turkish.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-telugu.conllu data/Italy/Italy-turkish.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-telugu.conllu Italy-vietnamese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-telugu.conllu data/Italy/Italy-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-telugu.conllu Italy-chinese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-telugu.conllu data/Italy/Italy-chinese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-turkish.conllu Italy-vietnamese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-turkish.conllu data/Italy/Italy-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-turkish.conllu Italy-chinese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-turkish.conllu data/Italy/Italy-chinese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
echo Italy-vietnamese.conllu Italy-chinese.conllu >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
gfud cosine-similarity data/Italy/Italy-vietnamese.conllu data/Italy/Italy-chinese.conllu DEPREL >> cosine-sim-per-topic/Italy-cosine-sim.txt ; 
} 
topic_combinations