#! /bin/bash 
function topic_combinations { 
echo Maize-arabic.conllu Maize-welsh.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-arabic.conllu data/Maize/Maize-welsh.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-arabic.conllu Maize-irish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-arabic.conllu data/Maize/Maize-irish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-arabic.conllu Maize-scottish_gaelic.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-arabic.conllu data/Maize/Maize-scottish_gaelic.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-arabic.conllu Maize-armenian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-arabic.conllu data/Maize/Maize-armenian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-arabic.conllu Maize-croatian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-arabic.conllu data/Maize/Maize-croatian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-arabic.conllu Maize-latin.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-arabic.conllu data/Maize/Maize-latin.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-arabic.conllu Maize-latvian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-arabic.conllu data/Maize/Maize-latvian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-arabic.conllu Maize-urdu.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-arabic.conllu data/Maize/Maize-urdu.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-welsh.conllu Maize-irish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-welsh.conllu data/Maize/Maize-irish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-welsh.conllu Maize-scottish_gaelic.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-welsh.conllu data/Maize/Maize-scottish_gaelic.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-welsh.conllu Maize-armenian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-welsh.conllu data/Maize/Maize-armenian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-welsh.conllu Maize-croatian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-welsh.conllu data/Maize/Maize-croatian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-welsh.conllu Maize-latin.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-welsh.conllu data/Maize/Maize-latin.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-welsh.conllu Maize-latvian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-welsh.conllu data/Maize/Maize-latvian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-welsh.conllu Maize-urdu.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-welsh.conllu data/Maize/Maize-urdu.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-irish.conllu Maize-scottish_gaelic.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-irish.conllu data/Maize/Maize-scottish_gaelic.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-irish.conllu Maize-armenian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-irish.conllu data/Maize/Maize-armenian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-irish.conllu Maize-croatian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-irish.conllu data/Maize/Maize-croatian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-irish.conllu Maize-latin.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-irish.conllu data/Maize/Maize-latin.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-irish.conllu Maize-latvian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-irish.conllu data/Maize/Maize-latvian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-irish.conllu Maize-urdu.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-irish.conllu data/Maize/Maize-urdu.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-scottish_gaelic.conllu Maize-armenian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-scottish_gaelic.conllu data/Maize/Maize-armenian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-scottish_gaelic.conllu Maize-croatian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-scottish_gaelic.conllu data/Maize/Maize-croatian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-scottish_gaelic.conllu Maize-latin.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-scottish_gaelic.conllu data/Maize/Maize-latin.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-scottish_gaelic.conllu Maize-latvian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-scottish_gaelic.conllu data/Maize/Maize-latvian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-scottish_gaelic.conllu Maize-urdu.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-scottish_gaelic.conllu data/Maize/Maize-urdu.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-armenian.conllu Maize-croatian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-armenian.conllu data/Maize/Maize-croatian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-armenian.conllu Maize-latin.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-armenian.conllu data/Maize/Maize-latin.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-armenian.conllu Maize-latvian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-armenian.conllu data/Maize/Maize-latvian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-armenian.conllu Maize-urdu.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-armenian.conllu data/Maize/Maize-urdu.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-croatian.conllu Maize-latin.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-croatian.conllu data/Maize/Maize-latin.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-croatian.conllu Maize-latvian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-croatian.conllu data/Maize/Maize-latvian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-croatian.conllu Maize-urdu.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-croatian.conllu data/Maize/Maize-urdu.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-latin.conllu Maize-latvian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-latin.conllu data/Maize/Maize-latvian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-latin.conllu Maize-urdu.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-latin.conllu data/Maize/Maize-urdu.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-latvian.conllu Maize-urdu.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-latvian.conllu data/Maize/Maize-urdu.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-danish.conllu Maize-estonian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-danish.conllu data/Maize/Maize-estonian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-danish.conllu Maize-greek.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-danish.conllu data/Maize/Maize-greek.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-danish.conllu Maize-basque.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-danish.conllu data/Maize/Maize-basque.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-danish.conllu Maize-korean.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-danish.conllu data/Maize/Maize-korean.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-danish.conllu Maize-hindi.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-danish.conllu data/Maize/Maize-hindi.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-danish.conllu Maize-hebrew.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-danish.conllu data/Maize/Maize-hebrew.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-danish.conllu Maize-kazakh.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-danish.conllu data/Maize/Maize-kazakh.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-danish.conllu Maize-lithuanian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-danish.conllu data/Maize/Maize-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-danish.conllu Maize-marathi.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-danish.conllu data/Maize/Maize-marathi.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-danish.conllu Maize-polish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-danish.conllu data/Maize/Maize-polish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-danish.conllu Maize-romanian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-danish.conllu data/Maize/Maize-romanian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-danish.conllu Maize-slovenian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-danish.conllu data/Maize/Maize-slovenian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-danish.conllu Maize-finnish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-danish.conllu data/Maize/Maize-finnish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-danish.conllu Maize-swedish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-danish.conllu data/Maize/Maize-swedish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-danish.conllu Maize-tamil.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-danish.conllu data/Maize/Maize-tamil.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-danish.conllu Maize-telugu.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-danish.conllu data/Maize/Maize-telugu.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-danish.conllu Maize-turkish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-danish.conllu data/Maize/Maize-turkish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-danish.conllu Maize-uyghur.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-danish.conllu data/Maize/Maize-uyghur.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-danish.conllu Maize-chinese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-danish.conllu data/Maize/Maize-chinese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-estonian.conllu Maize-greek.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-estonian.conllu data/Maize/Maize-greek.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-estonian.conllu Maize-basque.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-estonian.conllu data/Maize/Maize-basque.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-estonian.conllu Maize-korean.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-estonian.conllu data/Maize/Maize-korean.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-estonian.conllu Maize-hindi.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-estonian.conllu data/Maize/Maize-hindi.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-estonian.conllu Maize-hebrew.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-estonian.conllu data/Maize/Maize-hebrew.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-estonian.conllu Maize-kazakh.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-estonian.conllu data/Maize/Maize-kazakh.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-estonian.conllu Maize-lithuanian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-estonian.conllu data/Maize/Maize-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-estonian.conllu Maize-marathi.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-estonian.conllu data/Maize/Maize-marathi.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-estonian.conllu Maize-polish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-estonian.conllu data/Maize/Maize-polish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-estonian.conllu Maize-romanian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-estonian.conllu data/Maize/Maize-romanian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-estonian.conllu Maize-slovenian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-estonian.conllu data/Maize/Maize-slovenian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-estonian.conllu Maize-finnish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-estonian.conllu data/Maize/Maize-finnish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-estonian.conllu Maize-swedish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-estonian.conllu data/Maize/Maize-swedish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-estonian.conllu Maize-tamil.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-estonian.conllu data/Maize/Maize-tamil.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-estonian.conllu Maize-telugu.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-estonian.conllu data/Maize/Maize-telugu.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-estonian.conllu Maize-turkish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-estonian.conllu data/Maize/Maize-turkish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-estonian.conllu Maize-uyghur.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-estonian.conllu data/Maize/Maize-uyghur.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-estonian.conllu Maize-chinese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-estonian.conllu data/Maize/Maize-chinese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-greek.conllu Maize-basque.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-greek.conllu data/Maize/Maize-basque.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-greek.conllu Maize-korean.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-greek.conllu data/Maize/Maize-korean.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-greek.conllu Maize-hindi.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-greek.conllu data/Maize/Maize-hindi.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-greek.conllu Maize-hebrew.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-greek.conllu data/Maize/Maize-hebrew.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-greek.conllu Maize-kazakh.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-greek.conllu data/Maize/Maize-kazakh.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-greek.conllu Maize-lithuanian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-greek.conllu data/Maize/Maize-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-greek.conllu Maize-marathi.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-greek.conllu data/Maize/Maize-marathi.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-greek.conllu Maize-polish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-greek.conllu data/Maize/Maize-polish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-greek.conllu Maize-romanian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-greek.conllu data/Maize/Maize-romanian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-greek.conllu Maize-slovenian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-greek.conllu data/Maize/Maize-slovenian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-greek.conllu Maize-finnish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-greek.conllu data/Maize/Maize-finnish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-greek.conllu Maize-swedish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-greek.conllu data/Maize/Maize-swedish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-greek.conllu Maize-tamil.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-greek.conllu data/Maize/Maize-tamil.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-greek.conllu Maize-telugu.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-greek.conllu data/Maize/Maize-telugu.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-greek.conllu Maize-turkish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-greek.conllu data/Maize/Maize-turkish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-greek.conllu Maize-uyghur.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-greek.conllu data/Maize/Maize-uyghur.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-greek.conllu Maize-chinese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-greek.conllu data/Maize/Maize-chinese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-basque.conllu Maize-korean.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-basque.conllu data/Maize/Maize-korean.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-basque.conllu Maize-hindi.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-basque.conllu data/Maize/Maize-hindi.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-basque.conllu Maize-hebrew.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-basque.conllu data/Maize/Maize-hebrew.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-basque.conllu Maize-kazakh.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-basque.conllu data/Maize/Maize-kazakh.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-basque.conllu Maize-lithuanian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-basque.conllu data/Maize/Maize-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-basque.conllu Maize-marathi.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-basque.conllu data/Maize/Maize-marathi.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-basque.conllu Maize-polish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-basque.conllu data/Maize/Maize-polish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-basque.conllu Maize-romanian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-basque.conllu data/Maize/Maize-romanian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-basque.conllu Maize-slovenian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-basque.conllu data/Maize/Maize-slovenian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-basque.conllu Maize-finnish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-basque.conllu data/Maize/Maize-finnish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-basque.conllu Maize-swedish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-basque.conllu data/Maize/Maize-swedish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-basque.conllu Maize-tamil.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-basque.conllu data/Maize/Maize-tamil.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-basque.conllu Maize-telugu.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-basque.conllu data/Maize/Maize-telugu.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-basque.conllu Maize-turkish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-basque.conllu data/Maize/Maize-turkish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-basque.conllu Maize-uyghur.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-basque.conllu data/Maize/Maize-uyghur.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-basque.conllu Maize-chinese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-basque.conllu data/Maize/Maize-chinese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-korean.conllu Maize-hindi.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-korean.conllu data/Maize/Maize-hindi.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-korean.conllu Maize-hebrew.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-korean.conllu data/Maize/Maize-hebrew.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-korean.conllu Maize-kazakh.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-korean.conllu data/Maize/Maize-kazakh.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-korean.conllu Maize-lithuanian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-korean.conllu data/Maize/Maize-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-korean.conllu Maize-marathi.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-korean.conllu data/Maize/Maize-marathi.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-korean.conllu Maize-polish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-korean.conllu data/Maize/Maize-polish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-korean.conllu Maize-romanian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-korean.conllu data/Maize/Maize-romanian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-korean.conllu Maize-slovenian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-korean.conllu data/Maize/Maize-slovenian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-korean.conllu Maize-finnish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-korean.conllu data/Maize/Maize-finnish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-korean.conllu Maize-swedish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-korean.conllu data/Maize/Maize-swedish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-korean.conllu Maize-tamil.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-korean.conllu data/Maize/Maize-tamil.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-korean.conllu Maize-telugu.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-korean.conllu data/Maize/Maize-telugu.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-korean.conllu Maize-turkish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-korean.conllu data/Maize/Maize-turkish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-korean.conllu Maize-uyghur.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-korean.conllu data/Maize/Maize-uyghur.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-korean.conllu Maize-chinese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-korean.conllu data/Maize/Maize-chinese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-hindi.conllu Maize-hebrew.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-hindi.conllu data/Maize/Maize-hebrew.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-hindi.conllu Maize-kazakh.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-hindi.conllu data/Maize/Maize-kazakh.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-hindi.conllu Maize-lithuanian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-hindi.conllu data/Maize/Maize-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-hindi.conllu Maize-marathi.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-hindi.conllu data/Maize/Maize-marathi.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-hindi.conllu Maize-polish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-hindi.conllu data/Maize/Maize-polish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-hindi.conllu Maize-romanian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-hindi.conllu data/Maize/Maize-romanian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-hindi.conllu Maize-slovenian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-hindi.conllu data/Maize/Maize-slovenian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-hindi.conllu Maize-finnish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-hindi.conllu data/Maize/Maize-finnish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-hindi.conllu Maize-swedish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-hindi.conllu data/Maize/Maize-swedish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-hindi.conllu Maize-tamil.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-hindi.conllu data/Maize/Maize-tamil.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-hindi.conllu Maize-telugu.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-hindi.conllu data/Maize/Maize-telugu.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-hindi.conllu Maize-turkish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-hindi.conllu data/Maize/Maize-turkish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-hindi.conllu Maize-uyghur.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-hindi.conllu data/Maize/Maize-uyghur.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-hindi.conllu Maize-chinese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-hindi.conllu data/Maize/Maize-chinese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-hebrew.conllu Maize-kazakh.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-hebrew.conllu data/Maize/Maize-kazakh.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-hebrew.conllu Maize-lithuanian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-hebrew.conllu data/Maize/Maize-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-hebrew.conllu Maize-marathi.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-hebrew.conllu data/Maize/Maize-marathi.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-hebrew.conllu Maize-polish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-hebrew.conllu data/Maize/Maize-polish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-hebrew.conllu Maize-romanian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-hebrew.conllu data/Maize/Maize-romanian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-hebrew.conllu Maize-slovenian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-hebrew.conllu data/Maize/Maize-slovenian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-hebrew.conllu Maize-finnish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-hebrew.conllu data/Maize/Maize-finnish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-hebrew.conllu Maize-swedish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-hebrew.conllu data/Maize/Maize-swedish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-hebrew.conllu Maize-tamil.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-hebrew.conllu data/Maize/Maize-tamil.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-hebrew.conllu Maize-telugu.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-hebrew.conllu data/Maize/Maize-telugu.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-hebrew.conllu Maize-turkish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-hebrew.conllu data/Maize/Maize-turkish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-hebrew.conllu Maize-uyghur.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-hebrew.conllu data/Maize/Maize-uyghur.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-hebrew.conllu Maize-chinese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-hebrew.conllu data/Maize/Maize-chinese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-kazakh.conllu Maize-lithuanian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-kazakh.conllu data/Maize/Maize-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-kazakh.conllu Maize-marathi.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-kazakh.conllu data/Maize/Maize-marathi.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-kazakh.conllu Maize-polish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-kazakh.conllu data/Maize/Maize-polish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-kazakh.conllu Maize-romanian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-kazakh.conllu data/Maize/Maize-romanian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-kazakh.conllu Maize-slovenian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-kazakh.conllu data/Maize/Maize-slovenian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-kazakh.conllu Maize-finnish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-kazakh.conllu data/Maize/Maize-finnish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-kazakh.conllu Maize-swedish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-kazakh.conllu data/Maize/Maize-swedish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-kazakh.conllu Maize-tamil.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-kazakh.conllu data/Maize/Maize-tamil.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-kazakh.conllu Maize-telugu.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-kazakh.conllu data/Maize/Maize-telugu.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-kazakh.conllu Maize-turkish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-kazakh.conllu data/Maize/Maize-turkish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-kazakh.conllu Maize-uyghur.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-kazakh.conllu data/Maize/Maize-uyghur.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-kazakh.conllu Maize-chinese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-kazakh.conllu data/Maize/Maize-chinese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-lithuanian.conllu Maize-marathi.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-lithuanian.conllu data/Maize/Maize-marathi.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-lithuanian.conllu Maize-polish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-lithuanian.conllu data/Maize/Maize-polish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-lithuanian.conllu Maize-romanian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-lithuanian.conllu data/Maize/Maize-romanian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-lithuanian.conllu Maize-slovenian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-lithuanian.conllu data/Maize/Maize-slovenian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-lithuanian.conllu Maize-finnish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-lithuanian.conllu data/Maize/Maize-finnish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-lithuanian.conllu Maize-swedish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-lithuanian.conllu data/Maize/Maize-swedish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-lithuanian.conllu Maize-tamil.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-lithuanian.conllu data/Maize/Maize-tamil.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-lithuanian.conllu Maize-telugu.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-lithuanian.conllu data/Maize/Maize-telugu.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-lithuanian.conllu Maize-turkish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-lithuanian.conllu data/Maize/Maize-turkish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-lithuanian.conllu Maize-uyghur.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-lithuanian.conllu data/Maize/Maize-uyghur.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-lithuanian.conllu Maize-chinese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-lithuanian.conllu data/Maize/Maize-chinese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-marathi.conllu Maize-polish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-marathi.conllu data/Maize/Maize-polish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-marathi.conllu Maize-romanian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-marathi.conllu data/Maize/Maize-romanian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-marathi.conllu Maize-slovenian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-marathi.conllu data/Maize/Maize-slovenian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-marathi.conllu Maize-finnish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-marathi.conllu data/Maize/Maize-finnish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-marathi.conllu Maize-swedish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-marathi.conllu data/Maize/Maize-swedish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-marathi.conllu Maize-tamil.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-marathi.conllu data/Maize/Maize-tamil.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-marathi.conllu Maize-telugu.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-marathi.conllu data/Maize/Maize-telugu.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-marathi.conllu Maize-turkish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-marathi.conllu data/Maize/Maize-turkish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-marathi.conllu Maize-uyghur.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-marathi.conllu data/Maize/Maize-uyghur.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-marathi.conllu Maize-chinese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-marathi.conllu data/Maize/Maize-chinese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-polish.conllu Maize-romanian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-polish.conllu data/Maize/Maize-romanian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-polish.conllu Maize-slovenian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-polish.conllu data/Maize/Maize-slovenian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-polish.conllu Maize-finnish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-polish.conllu data/Maize/Maize-finnish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-polish.conllu Maize-swedish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-polish.conllu data/Maize/Maize-swedish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-polish.conllu Maize-tamil.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-polish.conllu data/Maize/Maize-tamil.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-polish.conllu Maize-telugu.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-polish.conllu data/Maize/Maize-telugu.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-polish.conllu Maize-turkish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-polish.conllu data/Maize/Maize-turkish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-polish.conllu Maize-uyghur.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-polish.conllu data/Maize/Maize-uyghur.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-polish.conllu Maize-chinese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-polish.conllu data/Maize/Maize-chinese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-romanian.conllu Maize-slovenian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-romanian.conllu data/Maize/Maize-slovenian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-romanian.conllu Maize-finnish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-romanian.conllu data/Maize/Maize-finnish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-romanian.conllu Maize-swedish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-romanian.conllu data/Maize/Maize-swedish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-romanian.conllu Maize-tamil.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-romanian.conllu data/Maize/Maize-tamil.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-romanian.conllu Maize-telugu.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-romanian.conllu data/Maize/Maize-telugu.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-romanian.conllu Maize-turkish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-romanian.conllu data/Maize/Maize-turkish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-romanian.conllu Maize-uyghur.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-romanian.conllu data/Maize/Maize-uyghur.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-romanian.conllu Maize-chinese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-romanian.conllu data/Maize/Maize-chinese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-slovenian.conllu Maize-finnish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-slovenian.conllu data/Maize/Maize-finnish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-slovenian.conllu Maize-swedish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-slovenian.conllu data/Maize/Maize-swedish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-slovenian.conllu Maize-tamil.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-slovenian.conllu data/Maize/Maize-tamil.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-slovenian.conllu Maize-telugu.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-slovenian.conllu data/Maize/Maize-telugu.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-slovenian.conllu Maize-turkish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-slovenian.conllu data/Maize/Maize-turkish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-slovenian.conllu Maize-uyghur.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-slovenian.conllu data/Maize/Maize-uyghur.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-slovenian.conllu Maize-chinese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-slovenian.conllu data/Maize/Maize-chinese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-finnish.conllu Maize-swedish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-finnish.conllu data/Maize/Maize-swedish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-finnish.conllu Maize-tamil.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-finnish.conllu data/Maize/Maize-tamil.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-finnish.conllu Maize-telugu.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-finnish.conllu data/Maize/Maize-telugu.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-finnish.conllu Maize-turkish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-finnish.conllu data/Maize/Maize-turkish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-finnish.conllu Maize-uyghur.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-finnish.conllu data/Maize/Maize-uyghur.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-finnish.conllu Maize-chinese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-finnish.conllu data/Maize/Maize-chinese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-swedish.conllu Maize-tamil.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-swedish.conllu data/Maize/Maize-tamil.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-swedish.conllu Maize-telugu.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-swedish.conllu data/Maize/Maize-telugu.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-swedish.conllu Maize-turkish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-swedish.conllu data/Maize/Maize-turkish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-swedish.conllu Maize-uyghur.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-swedish.conllu data/Maize/Maize-uyghur.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-swedish.conllu Maize-chinese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-swedish.conllu data/Maize/Maize-chinese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-tamil.conllu Maize-telugu.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-tamil.conllu data/Maize/Maize-telugu.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-tamil.conllu Maize-turkish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-tamil.conllu data/Maize/Maize-turkish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-tamil.conllu Maize-uyghur.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-tamil.conllu data/Maize/Maize-uyghur.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-tamil.conllu Maize-chinese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-tamil.conllu data/Maize/Maize-chinese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-telugu.conllu Maize-turkish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-telugu.conllu data/Maize/Maize-turkish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-telugu.conllu Maize-uyghur.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-telugu.conllu data/Maize/Maize-uyghur.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-telugu.conllu Maize-chinese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-telugu.conllu data/Maize/Maize-chinese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-turkish.conllu Maize-uyghur.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-turkish.conllu data/Maize/Maize-uyghur.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-turkish.conllu Maize-chinese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-turkish.conllu data/Maize/Maize-chinese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-uyghur.conllu Maize-chinese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-uyghur.conllu data/Maize/Maize-chinese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-afrikaans.conllu Maize-belarusian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-afrikaans.conllu data/Maize/Maize-belarusian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-afrikaans.conllu Maize-bulgarian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-afrikaans.conllu data/Maize/Maize-bulgarian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-afrikaans.conllu Maize-catalan.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-afrikaans.conllu data/Maize/Maize-catalan.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-afrikaans.conllu Maize-czech.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-afrikaans.conllu data/Maize/Maize-czech.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-afrikaans.conllu Maize-persian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-afrikaans.conllu data/Maize/Maize-persian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-afrikaans.conllu Maize-galician.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-afrikaans.conllu data/Maize/Maize-galician.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-afrikaans.conllu Maize-indonesian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-afrikaans.conllu data/Maize/Maize-indonesian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-afrikaans.conllu Maize-italian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-afrikaans.conllu data/Maize/Maize-italian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-afrikaans.conllu Maize-hungarian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-afrikaans.conllu data/Maize/Maize-hungarian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-afrikaans.conllu Maize-dutch.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-afrikaans.conllu data/Maize/Maize-dutch.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-afrikaans.conllu Maize-japanese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-afrikaans.conllu data/Maize/Maize-japanese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-afrikaans.conllu Maize-portuguese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-afrikaans.conllu data/Maize/Maize-portuguese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-afrikaans.conllu Maize-russian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-afrikaans.conllu data/Maize/Maize-russian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-afrikaans.conllu Maize-slovak.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-afrikaans.conllu data/Maize/Maize-slovak.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-afrikaans.conllu Maize-serbian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-afrikaans.conllu data/Maize/Maize-serbian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-afrikaans.conllu Maize-ukrainian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-afrikaans.conllu data/Maize/Maize-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-afrikaans.conllu Maize-vietnamese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-afrikaans.conllu data/Maize/Maize-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-belarusian.conllu Maize-bulgarian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-belarusian.conllu data/Maize/Maize-bulgarian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-belarusian.conllu Maize-catalan.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-belarusian.conllu data/Maize/Maize-catalan.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-belarusian.conllu Maize-czech.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-belarusian.conllu data/Maize/Maize-czech.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-belarusian.conllu Maize-persian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-belarusian.conllu data/Maize/Maize-persian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-belarusian.conllu Maize-galician.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-belarusian.conllu data/Maize/Maize-galician.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-belarusian.conllu Maize-indonesian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-belarusian.conllu data/Maize/Maize-indonesian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-belarusian.conllu Maize-italian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-belarusian.conllu data/Maize/Maize-italian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-belarusian.conllu Maize-hungarian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-belarusian.conllu data/Maize/Maize-hungarian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-belarusian.conllu Maize-dutch.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-belarusian.conllu data/Maize/Maize-dutch.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-belarusian.conllu Maize-japanese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-belarusian.conllu data/Maize/Maize-japanese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-belarusian.conllu Maize-portuguese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-belarusian.conllu data/Maize/Maize-portuguese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-belarusian.conllu Maize-russian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-belarusian.conllu data/Maize/Maize-russian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-belarusian.conllu Maize-slovak.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-belarusian.conllu data/Maize/Maize-slovak.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-belarusian.conllu Maize-serbian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-belarusian.conllu data/Maize/Maize-serbian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-belarusian.conllu Maize-ukrainian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-belarusian.conllu data/Maize/Maize-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-belarusian.conllu Maize-vietnamese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-belarusian.conllu data/Maize/Maize-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-bulgarian.conllu Maize-catalan.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-bulgarian.conllu data/Maize/Maize-catalan.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-bulgarian.conllu Maize-czech.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-bulgarian.conllu data/Maize/Maize-czech.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-bulgarian.conllu Maize-persian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-bulgarian.conllu data/Maize/Maize-persian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-bulgarian.conllu Maize-galician.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-bulgarian.conllu data/Maize/Maize-galician.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-bulgarian.conllu Maize-indonesian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-bulgarian.conllu data/Maize/Maize-indonesian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-bulgarian.conllu Maize-italian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-bulgarian.conllu data/Maize/Maize-italian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-bulgarian.conllu Maize-hungarian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-bulgarian.conllu data/Maize/Maize-hungarian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-bulgarian.conllu Maize-dutch.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-bulgarian.conllu data/Maize/Maize-dutch.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-bulgarian.conllu Maize-japanese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-bulgarian.conllu data/Maize/Maize-japanese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-bulgarian.conllu Maize-portuguese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-bulgarian.conllu data/Maize/Maize-portuguese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-bulgarian.conllu Maize-russian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-bulgarian.conllu data/Maize/Maize-russian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-bulgarian.conllu Maize-slovak.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-bulgarian.conllu data/Maize/Maize-slovak.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-bulgarian.conllu Maize-serbian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-bulgarian.conllu data/Maize/Maize-serbian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-bulgarian.conllu Maize-ukrainian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-bulgarian.conllu data/Maize/Maize-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-bulgarian.conllu Maize-vietnamese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-bulgarian.conllu data/Maize/Maize-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-catalan.conllu Maize-czech.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-catalan.conllu data/Maize/Maize-czech.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-catalan.conllu Maize-persian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-catalan.conllu data/Maize/Maize-persian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-catalan.conllu Maize-galician.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-catalan.conllu data/Maize/Maize-galician.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-catalan.conllu Maize-indonesian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-catalan.conllu data/Maize/Maize-indonesian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-catalan.conllu Maize-italian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-catalan.conllu data/Maize/Maize-italian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-catalan.conllu Maize-hungarian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-catalan.conllu data/Maize/Maize-hungarian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-catalan.conllu Maize-dutch.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-catalan.conllu data/Maize/Maize-dutch.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-catalan.conllu Maize-japanese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-catalan.conllu data/Maize/Maize-japanese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-catalan.conllu Maize-portuguese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-catalan.conllu data/Maize/Maize-portuguese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-catalan.conllu Maize-russian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-catalan.conllu data/Maize/Maize-russian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-catalan.conllu Maize-slovak.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-catalan.conllu data/Maize/Maize-slovak.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-catalan.conllu Maize-serbian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-catalan.conllu data/Maize/Maize-serbian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-catalan.conllu Maize-ukrainian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-catalan.conllu data/Maize/Maize-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-catalan.conllu Maize-vietnamese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-catalan.conllu data/Maize/Maize-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-czech.conllu Maize-persian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-czech.conllu data/Maize/Maize-persian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-czech.conllu Maize-galician.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-czech.conllu data/Maize/Maize-galician.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-czech.conllu Maize-indonesian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-czech.conllu data/Maize/Maize-indonesian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-czech.conllu Maize-italian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-czech.conllu data/Maize/Maize-italian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-czech.conllu Maize-hungarian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-czech.conllu data/Maize/Maize-hungarian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-czech.conllu Maize-dutch.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-czech.conllu data/Maize/Maize-dutch.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-czech.conllu Maize-japanese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-czech.conllu data/Maize/Maize-japanese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-czech.conllu Maize-portuguese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-czech.conllu data/Maize/Maize-portuguese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-czech.conllu Maize-russian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-czech.conllu data/Maize/Maize-russian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-czech.conllu Maize-slovak.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-czech.conllu data/Maize/Maize-slovak.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-czech.conllu Maize-serbian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-czech.conllu data/Maize/Maize-serbian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-czech.conllu Maize-ukrainian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-czech.conllu data/Maize/Maize-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-czech.conllu Maize-vietnamese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-czech.conllu data/Maize/Maize-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-persian.conllu Maize-galician.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-persian.conllu data/Maize/Maize-galician.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-persian.conllu Maize-indonesian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-persian.conllu data/Maize/Maize-indonesian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-persian.conllu Maize-italian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-persian.conllu data/Maize/Maize-italian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-persian.conllu Maize-hungarian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-persian.conllu data/Maize/Maize-hungarian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-persian.conllu Maize-dutch.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-persian.conllu data/Maize/Maize-dutch.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-persian.conllu Maize-japanese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-persian.conllu data/Maize/Maize-japanese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-persian.conllu Maize-portuguese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-persian.conllu data/Maize/Maize-portuguese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-persian.conllu Maize-russian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-persian.conllu data/Maize/Maize-russian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-persian.conllu Maize-slovak.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-persian.conllu data/Maize/Maize-slovak.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-persian.conllu Maize-serbian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-persian.conllu data/Maize/Maize-serbian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-persian.conllu Maize-ukrainian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-persian.conllu data/Maize/Maize-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-persian.conllu Maize-vietnamese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-persian.conllu data/Maize/Maize-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-galician.conllu Maize-indonesian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-galician.conllu data/Maize/Maize-indonesian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-galician.conllu Maize-italian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-galician.conllu data/Maize/Maize-italian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-galician.conllu Maize-hungarian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-galician.conllu data/Maize/Maize-hungarian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-galician.conllu Maize-dutch.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-galician.conllu data/Maize/Maize-dutch.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-galician.conllu Maize-japanese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-galician.conllu data/Maize/Maize-japanese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-galician.conllu Maize-portuguese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-galician.conllu data/Maize/Maize-portuguese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-galician.conllu Maize-russian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-galician.conllu data/Maize/Maize-russian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-galician.conllu Maize-slovak.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-galician.conllu data/Maize/Maize-slovak.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-galician.conllu Maize-serbian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-galician.conllu data/Maize/Maize-serbian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-galician.conllu Maize-ukrainian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-galician.conllu data/Maize/Maize-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-galician.conllu Maize-vietnamese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-galician.conllu data/Maize/Maize-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-indonesian.conllu Maize-italian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-indonesian.conllu data/Maize/Maize-italian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-indonesian.conllu Maize-hungarian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-indonesian.conllu data/Maize/Maize-hungarian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-indonesian.conllu Maize-dutch.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-indonesian.conllu data/Maize/Maize-dutch.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-indonesian.conllu Maize-japanese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-indonesian.conllu data/Maize/Maize-japanese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-indonesian.conllu Maize-portuguese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-indonesian.conllu data/Maize/Maize-portuguese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-indonesian.conllu Maize-russian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-indonesian.conllu data/Maize/Maize-russian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-indonesian.conllu Maize-slovak.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-indonesian.conllu data/Maize/Maize-slovak.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-indonesian.conllu Maize-serbian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-indonesian.conllu data/Maize/Maize-serbian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-indonesian.conllu Maize-ukrainian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-indonesian.conllu data/Maize/Maize-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-indonesian.conllu Maize-vietnamese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-indonesian.conllu data/Maize/Maize-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-italian.conllu Maize-hungarian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-italian.conllu data/Maize/Maize-hungarian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-italian.conllu Maize-dutch.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-italian.conllu data/Maize/Maize-dutch.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-italian.conllu Maize-japanese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-italian.conllu data/Maize/Maize-japanese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-italian.conllu Maize-portuguese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-italian.conllu data/Maize/Maize-portuguese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-italian.conllu Maize-russian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-italian.conllu data/Maize/Maize-russian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-italian.conllu Maize-slovak.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-italian.conllu data/Maize/Maize-slovak.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-italian.conllu Maize-serbian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-italian.conllu data/Maize/Maize-serbian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-italian.conllu Maize-ukrainian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-italian.conllu data/Maize/Maize-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-italian.conllu Maize-vietnamese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-italian.conllu data/Maize/Maize-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-hungarian.conllu Maize-dutch.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-hungarian.conllu data/Maize/Maize-dutch.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-hungarian.conllu Maize-japanese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-hungarian.conllu data/Maize/Maize-japanese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-hungarian.conllu Maize-portuguese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-hungarian.conllu data/Maize/Maize-portuguese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-hungarian.conllu Maize-russian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-hungarian.conllu data/Maize/Maize-russian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-hungarian.conllu Maize-slovak.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-hungarian.conllu data/Maize/Maize-slovak.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-hungarian.conllu Maize-serbian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-hungarian.conllu data/Maize/Maize-serbian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-hungarian.conllu Maize-ukrainian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-hungarian.conllu data/Maize/Maize-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-hungarian.conllu Maize-vietnamese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-hungarian.conllu data/Maize/Maize-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-dutch.conllu Maize-japanese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-dutch.conllu data/Maize/Maize-japanese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-dutch.conllu Maize-portuguese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-dutch.conllu data/Maize/Maize-portuguese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-dutch.conllu Maize-russian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-dutch.conllu data/Maize/Maize-russian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-dutch.conllu Maize-slovak.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-dutch.conllu data/Maize/Maize-slovak.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-dutch.conllu Maize-serbian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-dutch.conllu data/Maize/Maize-serbian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-dutch.conllu Maize-ukrainian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-dutch.conllu data/Maize/Maize-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-dutch.conllu Maize-vietnamese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-dutch.conllu data/Maize/Maize-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-japanese.conllu Maize-portuguese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-japanese.conllu data/Maize/Maize-portuguese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-japanese.conllu Maize-russian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-japanese.conllu data/Maize/Maize-russian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-japanese.conllu Maize-slovak.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-japanese.conllu data/Maize/Maize-slovak.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-japanese.conllu Maize-serbian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-japanese.conllu data/Maize/Maize-serbian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-japanese.conllu Maize-ukrainian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-japanese.conllu data/Maize/Maize-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-japanese.conllu Maize-vietnamese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-japanese.conllu data/Maize/Maize-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-portuguese.conllu Maize-russian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-portuguese.conllu data/Maize/Maize-russian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-portuguese.conllu Maize-slovak.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-portuguese.conllu data/Maize/Maize-slovak.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-portuguese.conllu Maize-serbian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-portuguese.conllu data/Maize/Maize-serbian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-portuguese.conllu Maize-ukrainian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-portuguese.conllu data/Maize/Maize-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-portuguese.conllu Maize-vietnamese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-portuguese.conllu data/Maize/Maize-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-russian.conllu Maize-slovak.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-russian.conllu data/Maize/Maize-slovak.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-russian.conllu Maize-serbian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-russian.conllu data/Maize/Maize-serbian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-russian.conllu Maize-ukrainian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-russian.conllu data/Maize/Maize-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-russian.conllu Maize-vietnamese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-russian.conllu data/Maize/Maize-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-slovak.conllu Maize-serbian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-slovak.conllu data/Maize/Maize-serbian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-slovak.conllu Maize-ukrainian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-slovak.conllu data/Maize/Maize-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-slovak.conllu Maize-vietnamese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-slovak.conllu data/Maize/Maize-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-serbian.conllu Maize-ukrainian.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-serbian.conllu data/Maize/Maize-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-serbian.conllu Maize-vietnamese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-serbian.conllu data/Maize/Maize-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-ukrainian.conllu Maize-vietnamese.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-ukrainian.conllu data/Maize/Maize-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-german.conllu Maize-spanish.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-german.conllu data/Maize/Maize-spanish.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
echo Maize-english.conllu Maize-french.conllu >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
gfud cosine-similarity data/Maize/Maize-english.conllu data/Maize/Maize-french.conllu DEPREL >> cosine-sim-per-topic/Maize-cosine-sim.txt ; 
} 
topic_combinations