#! /bin/bash 
function topic_combinations { 
echo New_York_City-scottish_gaelic.conllu New_York_City-gothic.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-scottish_gaelic.conllu data/New_York_City/New_York_City-gothic.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-scottish_gaelic.conllu New_York_City-sanskrit.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-scottish_gaelic.conllu data/New_York_City/New_York_City-sanskrit.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-scottish_gaelic.conllu New_York_City-uyghur.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-scottish_gaelic.conllu data/New_York_City/New_York_City-uyghur.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-gothic.conllu New_York_City-sanskrit.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-gothic.conllu data/New_York_City/New_York_City-sanskrit.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-gothic.conllu New_York_City-uyghur.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-gothic.conllu data/New_York_City/New_York_City-uyghur.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-sanskrit.conllu New_York_City-uyghur.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-sanskrit.conllu data/New_York_City/New_York_City-uyghur.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-arabic.conllu New_York_City-irish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-arabic.conllu data/New_York_City/New_York_City-irish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-arabic.conllu New_York_City-hindi.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-arabic.conllu data/New_York_City/New_York_City-hindi.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-arabic.conllu New_York_City-kazakh.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-arabic.conllu data/New_York_City/New_York_City-kazakh.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-arabic.conllu New_York_City-latin.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-arabic.conllu data/New_York_City/New_York_City-latin.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-arabic.conllu New_York_City-latvian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-arabic.conllu data/New_York_City/New_York_City-latvian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-arabic.conllu New_York_City-maltese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-arabic.conllu data/New_York_City/New_York_City-maltese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-arabic.conllu New_York_City-marathi.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-arabic.conllu data/New_York_City/New_York_City-marathi.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-arabic.conllu New_York_City-slovenian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-arabic.conllu data/New_York_City/New_York_City-slovenian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-arabic.conllu New_York_City-turkish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-arabic.conllu data/New_York_City/New_York_City-turkish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-arabic.conllu New_York_City-urdu.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-arabic.conllu data/New_York_City/New_York_City-urdu.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-arabic.conllu New_York_City-classical_chinese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-arabic.conllu data/New_York_City/New_York_City-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-irish.conllu New_York_City-hindi.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-irish.conllu data/New_York_City/New_York_City-hindi.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-irish.conllu New_York_City-kazakh.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-irish.conllu data/New_York_City/New_York_City-kazakh.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-irish.conllu New_York_City-latin.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-irish.conllu data/New_York_City/New_York_City-latin.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-irish.conllu New_York_City-latvian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-irish.conllu data/New_York_City/New_York_City-latvian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-irish.conllu New_York_City-maltese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-irish.conllu data/New_York_City/New_York_City-maltese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-irish.conllu New_York_City-marathi.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-irish.conllu data/New_York_City/New_York_City-marathi.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-irish.conllu New_York_City-slovenian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-irish.conllu data/New_York_City/New_York_City-slovenian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-irish.conllu New_York_City-turkish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-irish.conllu data/New_York_City/New_York_City-turkish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-irish.conllu New_York_City-urdu.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-irish.conllu data/New_York_City/New_York_City-urdu.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-irish.conllu New_York_City-classical_chinese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-irish.conllu data/New_York_City/New_York_City-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-hindi.conllu New_York_City-kazakh.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-hindi.conllu data/New_York_City/New_York_City-kazakh.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-hindi.conllu New_York_City-latin.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-hindi.conllu data/New_York_City/New_York_City-latin.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-hindi.conllu New_York_City-latvian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-hindi.conllu data/New_York_City/New_York_City-latvian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-hindi.conllu New_York_City-maltese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-hindi.conllu data/New_York_City/New_York_City-maltese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-hindi.conllu New_York_City-marathi.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-hindi.conllu data/New_York_City/New_York_City-marathi.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-hindi.conllu New_York_City-slovenian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-hindi.conllu data/New_York_City/New_York_City-slovenian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-hindi.conllu New_York_City-turkish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-hindi.conllu data/New_York_City/New_York_City-turkish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-hindi.conllu New_York_City-urdu.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-hindi.conllu data/New_York_City/New_York_City-urdu.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-hindi.conllu New_York_City-classical_chinese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-hindi.conllu data/New_York_City/New_York_City-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-kazakh.conllu New_York_City-latin.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-kazakh.conllu data/New_York_City/New_York_City-latin.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-kazakh.conllu New_York_City-latvian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-kazakh.conllu data/New_York_City/New_York_City-latvian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-kazakh.conllu New_York_City-maltese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-kazakh.conllu data/New_York_City/New_York_City-maltese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-kazakh.conllu New_York_City-marathi.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-kazakh.conllu data/New_York_City/New_York_City-marathi.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-kazakh.conllu New_York_City-slovenian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-kazakh.conllu data/New_York_City/New_York_City-slovenian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-kazakh.conllu New_York_City-turkish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-kazakh.conllu data/New_York_City/New_York_City-turkish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-kazakh.conllu New_York_City-urdu.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-kazakh.conllu data/New_York_City/New_York_City-urdu.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-kazakh.conllu New_York_City-classical_chinese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-kazakh.conllu data/New_York_City/New_York_City-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-latin.conllu New_York_City-latvian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-latin.conllu data/New_York_City/New_York_City-latvian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-latin.conllu New_York_City-maltese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-latin.conllu data/New_York_City/New_York_City-maltese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-latin.conllu New_York_City-marathi.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-latin.conllu data/New_York_City/New_York_City-marathi.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-latin.conllu New_York_City-slovenian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-latin.conllu data/New_York_City/New_York_City-slovenian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-latin.conllu New_York_City-turkish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-latin.conllu data/New_York_City/New_York_City-turkish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-latin.conllu New_York_City-urdu.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-latin.conllu data/New_York_City/New_York_City-urdu.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-latin.conllu New_York_City-classical_chinese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-latin.conllu data/New_York_City/New_York_City-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-latvian.conllu New_York_City-maltese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-latvian.conllu data/New_York_City/New_York_City-maltese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-latvian.conllu New_York_City-marathi.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-latvian.conllu data/New_York_City/New_York_City-marathi.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-latvian.conllu New_York_City-slovenian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-latvian.conllu data/New_York_City/New_York_City-slovenian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-latvian.conllu New_York_City-turkish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-latvian.conllu data/New_York_City/New_York_City-turkish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-latvian.conllu New_York_City-urdu.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-latvian.conllu data/New_York_City/New_York_City-urdu.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-latvian.conllu New_York_City-classical_chinese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-latvian.conllu data/New_York_City/New_York_City-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-maltese.conllu New_York_City-marathi.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-maltese.conllu data/New_York_City/New_York_City-marathi.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-maltese.conllu New_York_City-slovenian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-maltese.conllu data/New_York_City/New_York_City-slovenian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-maltese.conllu New_York_City-turkish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-maltese.conllu data/New_York_City/New_York_City-turkish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-maltese.conllu New_York_City-urdu.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-maltese.conllu data/New_York_City/New_York_City-urdu.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-maltese.conllu New_York_City-classical_chinese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-maltese.conllu data/New_York_City/New_York_City-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-marathi.conllu New_York_City-slovenian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-marathi.conllu data/New_York_City/New_York_City-slovenian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-marathi.conllu New_York_City-turkish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-marathi.conllu data/New_York_City/New_York_City-turkish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-marathi.conllu New_York_City-urdu.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-marathi.conllu data/New_York_City/New_York_City-urdu.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-marathi.conllu New_York_City-classical_chinese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-marathi.conllu data/New_York_City/New_York_City-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-slovenian.conllu New_York_City-turkish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-slovenian.conllu data/New_York_City/New_York_City-turkish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-slovenian.conllu New_York_City-urdu.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-slovenian.conllu data/New_York_City/New_York_City-urdu.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-slovenian.conllu New_York_City-classical_chinese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-slovenian.conllu data/New_York_City/New_York_City-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-turkish.conllu New_York_City-urdu.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-turkish.conllu data/New_York_City/New_York_City-urdu.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-turkish.conllu New_York_City-classical_chinese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-turkish.conllu data/New_York_City/New_York_City-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-urdu.conllu New_York_City-classical_chinese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-urdu.conllu data/New_York_City/New_York_City-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-afrikaans.conllu New_York_City-belarusian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-afrikaans.conllu data/New_York_City/New_York_City-belarusian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-afrikaans.conllu New_York_City-bulgarian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-afrikaans.conllu data/New_York_City/New_York_City-bulgarian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-afrikaans.conllu New_York_City-welsh.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-afrikaans.conllu data/New_York_City/New_York_City-welsh.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-afrikaans.conllu New_York_City-greek.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-afrikaans.conllu data/New_York_City/New_York_City-greek.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-afrikaans.conllu New_York_City-basque.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-afrikaans.conllu data/New_York_City/New_York_City-basque.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-afrikaans.conllu New_York_City-persian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-afrikaans.conllu data/New_York_City/New_York_City-persian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-afrikaans.conllu New_York_City-galician.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-afrikaans.conllu data/New_York_City/New_York_City-galician.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-afrikaans.conllu New_York_City-croatian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-afrikaans.conllu data/New_York_City/New_York_City-croatian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-afrikaans.conllu New_York_City-hebrew.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-afrikaans.conllu data/New_York_City/New_York_City-hebrew.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-afrikaans.conllu New_York_City-lithuanian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-afrikaans.conllu data/New_York_City/New_York_City-lithuanian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-afrikaans.conllu New_York_City-hungarian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-afrikaans.conllu data/New_York_City/New_York_City-hungarian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-afrikaans.conllu New_York_City-romanian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-afrikaans.conllu data/New_York_City/New_York_City-romanian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-afrikaans.conllu New_York_City-serbian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-afrikaans.conllu data/New_York_City/New_York_City-serbian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-afrikaans.conllu New_York_City-telugu.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-afrikaans.conllu data/New_York_City/New_York_City-telugu.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-afrikaans.conllu New_York_City-ukrainian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-afrikaans.conllu data/New_York_City/New_York_City-ukrainian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-belarusian.conllu New_York_City-bulgarian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-belarusian.conllu data/New_York_City/New_York_City-bulgarian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-belarusian.conllu New_York_City-welsh.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-belarusian.conllu data/New_York_City/New_York_City-welsh.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-belarusian.conllu New_York_City-greek.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-belarusian.conllu data/New_York_City/New_York_City-greek.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-belarusian.conllu New_York_City-basque.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-belarusian.conllu data/New_York_City/New_York_City-basque.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-belarusian.conllu New_York_City-persian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-belarusian.conllu data/New_York_City/New_York_City-persian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-belarusian.conllu New_York_City-galician.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-belarusian.conllu data/New_York_City/New_York_City-galician.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-belarusian.conllu New_York_City-croatian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-belarusian.conllu data/New_York_City/New_York_City-croatian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-belarusian.conllu New_York_City-hebrew.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-belarusian.conllu data/New_York_City/New_York_City-hebrew.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-belarusian.conllu New_York_City-lithuanian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-belarusian.conllu data/New_York_City/New_York_City-lithuanian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-belarusian.conllu New_York_City-hungarian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-belarusian.conllu data/New_York_City/New_York_City-hungarian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-belarusian.conllu New_York_City-romanian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-belarusian.conllu data/New_York_City/New_York_City-romanian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-belarusian.conllu New_York_City-serbian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-belarusian.conllu data/New_York_City/New_York_City-serbian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-belarusian.conllu New_York_City-telugu.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-belarusian.conllu data/New_York_City/New_York_City-telugu.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-belarusian.conllu New_York_City-ukrainian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-belarusian.conllu data/New_York_City/New_York_City-ukrainian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-bulgarian.conllu New_York_City-welsh.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-bulgarian.conllu data/New_York_City/New_York_City-welsh.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-bulgarian.conllu New_York_City-greek.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-bulgarian.conllu data/New_York_City/New_York_City-greek.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-bulgarian.conllu New_York_City-basque.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-bulgarian.conllu data/New_York_City/New_York_City-basque.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-bulgarian.conllu New_York_City-persian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-bulgarian.conllu data/New_York_City/New_York_City-persian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-bulgarian.conllu New_York_City-galician.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-bulgarian.conllu data/New_York_City/New_York_City-galician.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-bulgarian.conllu New_York_City-croatian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-bulgarian.conllu data/New_York_City/New_York_City-croatian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-bulgarian.conllu New_York_City-hebrew.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-bulgarian.conllu data/New_York_City/New_York_City-hebrew.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-bulgarian.conllu New_York_City-lithuanian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-bulgarian.conllu data/New_York_City/New_York_City-lithuanian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-bulgarian.conllu New_York_City-hungarian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-bulgarian.conllu data/New_York_City/New_York_City-hungarian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-bulgarian.conllu New_York_City-romanian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-bulgarian.conllu data/New_York_City/New_York_City-romanian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-bulgarian.conllu New_York_City-serbian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-bulgarian.conllu data/New_York_City/New_York_City-serbian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-bulgarian.conllu New_York_City-telugu.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-bulgarian.conllu data/New_York_City/New_York_City-telugu.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-bulgarian.conllu New_York_City-ukrainian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-bulgarian.conllu data/New_York_City/New_York_City-ukrainian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-welsh.conllu New_York_City-greek.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-welsh.conllu data/New_York_City/New_York_City-greek.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-welsh.conllu New_York_City-basque.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-welsh.conllu data/New_York_City/New_York_City-basque.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-welsh.conllu New_York_City-persian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-welsh.conllu data/New_York_City/New_York_City-persian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-welsh.conllu New_York_City-galician.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-welsh.conllu data/New_York_City/New_York_City-galician.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-welsh.conllu New_York_City-croatian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-welsh.conllu data/New_York_City/New_York_City-croatian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-welsh.conllu New_York_City-hebrew.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-welsh.conllu data/New_York_City/New_York_City-hebrew.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-welsh.conllu New_York_City-lithuanian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-welsh.conllu data/New_York_City/New_York_City-lithuanian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-welsh.conllu New_York_City-hungarian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-welsh.conllu data/New_York_City/New_York_City-hungarian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-welsh.conllu New_York_City-romanian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-welsh.conllu data/New_York_City/New_York_City-romanian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-welsh.conllu New_York_City-serbian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-welsh.conllu data/New_York_City/New_York_City-serbian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-welsh.conllu New_York_City-telugu.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-welsh.conllu data/New_York_City/New_York_City-telugu.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-welsh.conllu New_York_City-ukrainian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-welsh.conllu data/New_York_City/New_York_City-ukrainian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-greek.conllu New_York_City-basque.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-greek.conllu data/New_York_City/New_York_City-basque.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-greek.conllu New_York_City-persian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-greek.conllu data/New_York_City/New_York_City-persian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-greek.conllu New_York_City-galician.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-greek.conllu data/New_York_City/New_York_City-galician.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-greek.conllu New_York_City-croatian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-greek.conllu data/New_York_City/New_York_City-croatian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-greek.conllu New_York_City-hebrew.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-greek.conllu data/New_York_City/New_York_City-hebrew.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-greek.conllu New_York_City-lithuanian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-greek.conllu data/New_York_City/New_York_City-lithuanian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-greek.conllu New_York_City-hungarian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-greek.conllu data/New_York_City/New_York_City-hungarian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-greek.conllu New_York_City-romanian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-greek.conllu data/New_York_City/New_York_City-romanian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-greek.conllu New_York_City-serbian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-greek.conllu data/New_York_City/New_York_City-serbian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-greek.conllu New_York_City-telugu.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-greek.conllu data/New_York_City/New_York_City-telugu.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-greek.conllu New_York_City-ukrainian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-greek.conllu data/New_York_City/New_York_City-ukrainian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-basque.conllu New_York_City-persian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-basque.conllu data/New_York_City/New_York_City-persian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-basque.conllu New_York_City-galician.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-basque.conllu data/New_York_City/New_York_City-galician.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-basque.conllu New_York_City-croatian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-basque.conllu data/New_York_City/New_York_City-croatian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-basque.conllu New_York_City-hebrew.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-basque.conllu data/New_York_City/New_York_City-hebrew.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-basque.conllu New_York_City-lithuanian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-basque.conllu data/New_York_City/New_York_City-lithuanian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-basque.conllu New_York_City-hungarian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-basque.conllu data/New_York_City/New_York_City-hungarian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-basque.conllu New_York_City-romanian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-basque.conllu data/New_York_City/New_York_City-romanian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-basque.conllu New_York_City-serbian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-basque.conllu data/New_York_City/New_York_City-serbian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-basque.conllu New_York_City-telugu.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-basque.conllu data/New_York_City/New_York_City-telugu.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-basque.conllu New_York_City-ukrainian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-basque.conllu data/New_York_City/New_York_City-ukrainian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-persian.conllu New_York_City-galician.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-persian.conllu data/New_York_City/New_York_City-galician.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-persian.conllu New_York_City-croatian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-persian.conllu data/New_York_City/New_York_City-croatian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-persian.conllu New_York_City-hebrew.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-persian.conllu data/New_York_City/New_York_City-hebrew.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-persian.conllu New_York_City-lithuanian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-persian.conllu data/New_York_City/New_York_City-lithuanian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-persian.conllu New_York_City-hungarian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-persian.conllu data/New_York_City/New_York_City-hungarian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-persian.conllu New_York_City-romanian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-persian.conllu data/New_York_City/New_York_City-romanian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-persian.conllu New_York_City-serbian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-persian.conllu data/New_York_City/New_York_City-serbian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-persian.conllu New_York_City-telugu.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-persian.conllu data/New_York_City/New_York_City-telugu.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-persian.conllu New_York_City-ukrainian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-persian.conllu data/New_York_City/New_York_City-ukrainian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-galician.conllu New_York_City-croatian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-galician.conllu data/New_York_City/New_York_City-croatian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-galician.conllu New_York_City-hebrew.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-galician.conllu data/New_York_City/New_York_City-hebrew.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-galician.conllu New_York_City-lithuanian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-galician.conllu data/New_York_City/New_York_City-lithuanian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-galician.conllu New_York_City-hungarian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-galician.conllu data/New_York_City/New_York_City-hungarian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-galician.conllu New_York_City-romanian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-galician.conllu data/New_York_City/New_York_City-romanian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-galician.conllu New_York_City-serbian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-galician.conllu data/New_York_City/New_York_City-serbian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-galician.conllu New_York_City-telugu.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-galician.conllu data/New_York_City/New_York_City-telugu.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-galician.conllu New_York_City-ukrainian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-galician.conllu data/New_York_City/New_York_City-ukrainian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-croatian.conllu New_York_City-hebrew.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-croatian.conllu data/New_York_City/New_York_City-hebrew.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-croatian.conllu New_York_City-lithuanian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-croatian.conllu data/New_York_City/New_York_City-lithuanian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-croatian.conllu New_York_City-hungarian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-croatian.conllu data/New_York_City/New_York_City-hungarian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-croatian.conllu New_York_City-romanian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-croatian.conllu data/New_York_City/New_York_City-romanian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-croatian.conllu New_York_City-serbian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-croatian.conllu data/New_York_City/New_York_City-serbian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-croatian.conllu New_York_City-telugu.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-croatian.conllu data/New_York_City/New_York_City-telugu.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-croatian.conllu New_York_City-ukrainian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-croatian.conllu data/New_York_City/New_York_City-ukrainian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-hebrew.conllu New_York_City-lithuanian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-hebrew.conllu data/New_York_City/New_York_City-lithuanian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-hebrew.conllu New_York_City-hungarian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-hebrew.conllu data/New_York_City/New_York_City-hungarian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-hebrew.conllu New_York_City-romanian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-hebrew.conllu data/New_York_City/New_York_City-romanian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-hebrew.conllu New_York_City-serbian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-hebrew.conllu data/New_York_City/New_York_City-serbian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-hebrew.conllu New_York_City-telugu.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-hebrew.conllu data/New_York_City/New_York_City-telugu.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-hebrew.conllu New_York_City-ukrainian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-hebrew.conllu data/New_York_City/New_York_City-ukrainian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-lithuanian.conllu New_York_City-hungarian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-lithuanian.conllu data/New_York_City/New_York_City-hungarian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-lithuanian.conllu New_York_City-romanian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-lithuanian.conllu data/New_York_City/New_York_City-romanian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-lithuanian.conllu New_York_City-serbian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-lithuanian.conllu data/New_York_City/New_York_City-serbian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-lithuanian.conllu New_York_City-telugu.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-lithuanian.conllu data/New_York_City/New_York_City-telugu.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-lithuanian.conllu New_York_City-ukrainian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-lithuanian.conllu data/New_York_City/New_York_City-ukrainian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-hungarian.conllu New_York_City-romanian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-hungarian.conllu data/New_York_City/New_York_City-romanian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-hungarian.conllu New_York_City-serbian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-hungarian.conllu data/New_York_City/New_York_City-serbian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-hungarian.conllu New_York_City-telugu.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-hungarian.conllu data/New_York_City/New_York_City-telugu.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-hungarian.conllu New_York_City-ukrainian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-hungarian.conllu data/New_York_City/New_York_City-ukrainian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-romanian.conllu New_York_City-serbian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-romanian.conllu data/New_York_City/New_York_City-serbian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-romanian.conllu New_York_City-telugu.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-romanian.conllu data/New_York_City/New_York_City-telugu.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-romanian.conllu New_York_City-ukrainian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-romanian.conllu data/New_York_City/New_York_City-ukrainian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-serbian.conllu New_York_City-telugu.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-serbian.conllu data/New_York_City/New_York_City-telugu.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-serbian.conllu New_York_City-ukrainian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-serbian.conllu data/New_York_City/New_York_City-ukrainian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-telugu.conllu New_York_City-ukrainian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-telugu.conllu data/New_York_City/New_York_City-ukrainian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-catalan.conllu New_York_City-czech.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-catalan.conllu data/New_York_City/New_York_City-czech.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-catalan.conllu New_York_City-danish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-catalan.conllu data/New_York_City/New_York_City-danish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-catalan.conllu New_York_City-estonian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-catalan.conllu data/New_York_City/New_York_City-estonian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-catalan.conllu New_York_City-korean.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-catalan.conllu data/New_York_City/New_York_City-korean.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-catalan.conllu New_York_City-indonesian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-catalan.conllu data/New_York_City/New_York_City-indonesian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-catalan.conllu New_York_City-italian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-catalan.conllu data/New_York_City/New_York_City-italian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-catalan.conllu New_York_City-polish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-catalan.conllu data/New_York_City/New_York_City-polish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-catalan.conllu New_York_City-russian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-catalan.conllu data/New_York_City/New_York_City-russian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-catalan.conllu New_York_City-slovak.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-catalan.conllu data/New_York_City/New_York_City-slovak.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-catalan.conllu New_York_City-finnish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-catalan.conllu data/New_York_City/New_York_City-finnish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-catalan.conllu New_York_City-swedish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-catalan.conllu data/New_York_City/New_York_City-swedish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-catalan.conllu New_York_City-tamil.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-catalan.conllu data/New_York_City/New_York_City-tamil.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-catalan.conllu New_York_City-vietnamese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-catalan.conllu data/New_York_City/New_York_City-vietnamese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-catalan.conllu New_York_City-chinese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-catalan.conllu data/New_York_City/New_York_City-chinese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-czech.conllu New_York_City-danish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-czech.conllu data/New_York_City/New_York_City-danish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-czech.conllu New_York_City-estonian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-czech.conllu data/New_York_City/New_York_City-estonian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-czech.conllu New_York_City-korean.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-czech.conllu data/New_York_City/New_York_City-korean.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-czech.conllu New_York_City-indonesian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-czech.conllu data/New_York_City/New_York_City-indonesian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-czech.conllu New_York_City-italian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-czech.conllu data/New_York_City/New_York_City-italian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-czech.conllu New_York_City-polish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-czech.conllu data/New_York_City/New_York_City-polish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-czech.conllu New_York_City-russian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-czech.conllu data/New_York_City/New_York_City-russian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-czech.conllu New_York_City-slovak.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-czech.conllu data/New_York_City/New_York_City-slovak.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-czech.conllu New_York_City-finnish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-czech.conllu data/New_York_City/New_York_City-finnish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-czech.conllu New_York_City-swedish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-czech.conllu data/New_York_City/New_York_City-swedish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-czech.conllu New_York_City-tamil.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-czech.conllu data/New_York_City/New_York_City-tamil.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-czech.conllu New_York_City-vietnamese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-czech.conllu data/New_York_City/New_York_City-vietnamese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-czech.conllu New_York_City-chinese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-czech.conllu data/New_York_City/New_York_City-chinese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-danish.conllu New_York_City-estonian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-danish.conllu data/New_York_City/New_York_City-estonian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-danish.conllu New_York_City-korean.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-danish.conllu data/New_York_City/New_York_City-korean.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-danish.conllu New_York_City-indonesian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-danish.conllu data/New_York_City/New_York_City-indonesian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-danish.conllu New_York_City-italian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-danish.conllu data/New_York_City/New_York_City-italian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-danish.conllu New_York_City-polish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-danish.conllu data/New_York_City/New_York_City-polish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-danish.conllu New_York_City-russian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-danish.conllu data/New_York_City/New_York_City-russian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-danish.conllu New_York_City-slovak.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-danish.conllu data/New_York_City/New_York_City-slovak.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-danish.conllu New_York_City-finnish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-danish.conllu data/New_York_City/New_York_City-finnish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-danish.conllu New_York_City-swedish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-danish.conllu data/New_York_City/New_York_City-swedish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-danish.conllu New_York_City-tamil.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-danish.conllu data/New_York_City/New_York_City-tamil.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-danish.conllu New_York_City-vietnamese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-danish.conllu data/New_York_City/New_York_City-vietnamese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-danish.conllu New_York_City-chinese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-danish.conllu data/New_York_City/New_York_City-chinese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-estonian.conllu New_York_City-korean.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-estonian.conllu data/New_York_City/New_York_City-korean.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-estonian.conllu New_York_City-indonesian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-estonian.conllu data/New_York_City/New_York_City-indonesian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-estonian.conllu New_York_City-italian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-estonian.conllu data/New_York_City/New_York_City-italian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-estonian.conllu New_York_City-polish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-estonian.conllu data/New_York_City/New_York_City-polish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-estonian.conllu New_York_City-russian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-estonian.conllu data/New_York_City/New_York_City-russian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-estonian.conllu New_York_City-slovak.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-estonian.conllu data/New_York_City/New_York_City-slovak.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-estonian.conllu New_York_City-finnish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-estonian.conllu data/New_York_City/New_York_City-finnish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-estonian.conllu New_York_City-swedish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-estonian.conllu data/New_York_City/New_York_City-swedish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-estonian.conllu New_York_City-tamil.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-estonian.conllu data/New_York_City/New_York_City-tamil.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-estonian.conllu New_York_City-vietnamese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-estonian.conllu data/New_York_City/New_York_City-vietnamese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-estonian.conllu New_York_City-chinese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-estonian.conllu data/New_York_City/New_York_City-chinese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-korean.conllu New_York_City-indonesian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-korean.conllu data/New_York_City/New_York_City-indonesian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-korean.conllu New_York_City-italian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-korean.conllu data/New_York_City/New_York_City-italian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-korean.conllu New_York_City-polish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-korean.conllu data/New_York_City/New_York_City-polish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-korean.conllu New_York_City-russian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-korean.conllu data/New_York_City/New_York_City-russian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-korean.conllu New_York_City-slovak.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-korean.conllu data/New_York_City/New_York_City-slovak.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-korean.conllu New_York_City-finnish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-korean.conllu data/New_York_City/New_York_City-finnish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-korean.conllu New_York_City-swedish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-korean.conllu data/New_York_City/New_York_City-swedish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-korean.conllu New_York_City-tamil.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-korean.conllu data/New_York_City/New_York_City-tamil.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-korean.conllu New_York_City-vietnamese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-korean.conllu data/New_York_City/New_York_City-vietnamese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-korean.conllu New_York_City-chinese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-korean.conllu data/New_York_City/New_York_City-chinese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-indonesian.conllu New_York_City-italian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-indonesian.conllu data/New_York_City/New_York_City-italian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-indonesian.conllu New_York_City-polish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-indonesian.conllu data/New_York_City/New_York_City-polish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-indonesian.conllu New_York_City-russian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-indonesian.conllu data/New_York_City/New_York_City-russian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-indonesian.conllu New_York_City-slovak.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-indonesian.conllu data/New_York_City/New_York_City-slovak.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-indonesian.conllu New_York_City-finnish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-indonesian.conllu data/New_York_City/New_York_City-finnish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-indonesian.conllu New_York_City-swedish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-indonesian.conllu data/New_York_City/New_York_City-swedish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-indonesian.conllu New_York_City-tamil.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-indonesian.conllu data/New_York_City/New_York_City-tamil.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-indonesian.conllu New_York_City-vietnamese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-indonesian.conllu data/New_York_City/New_York_City-vietnamese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-indonesian.conllu New_York_City-chinese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-indonesian.conllu data/New_York_City/New_York_City-chinese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-italian.conllu New_York_City-polish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-italian.conllu data/New_York_City/New_York_City-polish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-italian.conllu New_York_City-russian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-italian.conllu data/New_York_City/New_York_City-russian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-italian.conllu New_York_City-slovak.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-italian.conllu data/New_York_City/New_York_City-slovak.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-italian.conllu New_York_City-finnish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-italian.conllu data/New_York_City/New_York_City-finnish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-italian.conllu New_York_City-swedish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-italian.conllu data/New_York_City/New_York_City-swedish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-italian.conllu New_York_City-tamil.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-italian.conllu data/New_York_City/New_York_City-tamil.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-italian.conllu New_York_City-vietnamese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-italian.conllu data/New_York_City/New_York_City-vietnamese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-italian.conllu New_York_City-chinese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-italian.conllu data/New_York_City/New_York_City-chinese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-polish.conllu New_York_City-russian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-polish.conllu data/New_York_City/New_York_City-russian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-polish.conllu New_York_City-slovak.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-polish.conllu data/New_York_City/New_York_City-slovak.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-polish.conllu New_York_City-finnish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-polish.conllu data/New_York_City/New_York_City-finnish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-polish.conllu New_York_City-swedish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-polish.conllu data/New_York_City/New_York_City-swedish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-polish.conllu New_York_City-tamil.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-polish.conllu data/New_York_City/New_York_City-tamil.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-polish.conllu New_York_City-vietnamese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-polish.conllu data/New_York_City/New_York_City-vietnamese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-polish.conllu New_York_City-chinese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-polish.conllu data/New_York_City/New_York_City-chinese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-russian.conllu New_York_City-slovak.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-russian.conllu data/New_York_City/New_York_City-slovak.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-russian.conllu New_York_City-finnish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-russian.conllu data/New_York_City/New_York_City-finnish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-russian.conllu New_York_City-swedish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-russian.conllu data/New_York_City/New_York_City-swedish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-russian.conllu New_York_City-tamil.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-russian.conllu data/New_York_City/New_York_City-tamil.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-russian.conllu New_York_City-vietnamese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-russian.conllu data/New_York_City/New_York_City-vietnamese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-russian.conllu New_York_City-chinese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-russian.conllu data/New_York_City/New_York_City-chinese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-slovak.conllu New_York_City-finnish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-slovak.conllu data/New_York_City/New_York_City-finnish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-slovak.conllu New_York_City-swedish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-slovak.conllu data/New_York_City/New_York_City-swedish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-slovak.conllu New_York_City-tamil.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-slovak.conllu data/New_York_City/New_York_City-tamil.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-slovak.conllu New_York_City-vietnamese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-slovak.conllu data/New_York_City/New_York_City-vietnamese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-slovak.conllu New_York_City-chinese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-slovak.conllu data/New_York_City/New_York_City-chinese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-finnish.conllu New_York_City-swedish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-finnish.conllu data/New_York_City/New_York_City-swedish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-finnish.conllu New_York_City-tamil.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-finnish.conllu data/New_York_City/New_York_City-tamil.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-finnish.conllu New_York_City-vietnamese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-finnish.conllu data/New_York_City/New_York_City-vietnamese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-finnish.conllu New_York_City-chinese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-finnish.conllu data/New_York_City/New_York_City-chinese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-swedish.conllu New_York_City-tamil.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-swedish.conllu data/New_York_City/New_York_City-tamil.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-swedish.conllu New_York_City-vietnamese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-swedish.conllu data/New_York_City/New_York_City-vietnamese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-swedish.conllu New_York_City-chinese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-swedish.conllu data/New_York_City/New_York_City-chinese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-tamil.conllu New_York_City-vietnamese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-tamil.conllu data/New_York_City/New_York_City-vietnamese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-tamil.conllu New_York_City-chinese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-tamil.conllu data/New_York_City/New_York_City-chinese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-vietnamese.conllu New_York_City-chinese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-vietnamese.conllu data/New_York_City/New_York_City-chinese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-english.conllu New_York_City-german.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-english.conllu data/New_York_City/New_York_City-german.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-english.conllu New_York_City-spanish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-english.conllu data/New_York_City/New_York_City-spanish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-english.conllu New_York_City-french.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-english.conllu data/New_York_City/New_York_City-french.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-english.conllu New_York_City-armenian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-english.conllu data/New_York_City/New_York_City-armenian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-english.conllu New_York_City-dutch.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-english.conllu data/New_York_City/New_York_City-dutch.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-english.conllu New_York_City-japanese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-english.conllu data/New_York_City/New_York_City-japanese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-english.conllu New_York_City-portuguese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-english.conllu data/New_York_City/New_York_City-portuguese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-german.conllu New_York_City-spanish.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-german.conllu data/New_York_City/New_York_City-spanish.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-german.conllu New_York_City-french.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-german.conllu data/New_York_City/New_York_City-french.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-german.conllu New_York_City-armenian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-german.conllu data/New_York_City/New_York_City-armenian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-german.conllu New_York_City-dutch.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-german.conllu data/New_York_City/New_York_City-dutch.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-german.conllu New_York_City-japanese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-german.conllu data/New_York_City/New_York_City-japanese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-german.conllu New_York_City-portuguese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-german.conllu data/New_York_City/New_York_City-portuguese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-spanish.conllu New_York_City-french.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-spanish.conllu data/New_York_City/New_York_City-french.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-spanish.conllu New_York_City-armenian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-spanish.conllu data/New_York_City/New_York_City-armenian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-spanish.conllu New_York_City-dutch.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-spanish.conllu data/New_York_City/New_York_City-dutch.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-spanish.conllu New_York_City-japanese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-spanish.conllu data/New_York_City/New_York_City-japanese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-spanish.conllu New_York_City-portuguese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-spanish.conllu data/New_York_City/New_York_City-portuguese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-french.conllu New_York_City-armenian.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-french.conllu data/New_York_City/New_York_City-armenian.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-french.conllu New_York_City-dutch.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-french.conllu data/New_York_City/New_York_City-dutch.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-french.conllu New_York_City-japanese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-french.conllu data/New_York_City/New_York_City-japanese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-french.conllu New_York_City-portuguese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-french.conllu data/New_York_City/New_York_City-portuguese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-armenian.conllu New_York_City-dutch.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-armenian.conllu data/New_York_City/New_York_City-dutch.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-armenian.conllu New_York_City-japanese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-armenian.conllu data/New_York_City/New_York_City-japanese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-armenian.conllu New_York_City-portuguese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-armenian.conllu data/New_York_City/New_York_City-portuguese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-dutch.conllu New_York_City-japanese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-dutch.conllu data/New_York_City/New_York_City-japanese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-dutch.conllu New_York_City-portuguese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-dutch.conllu data/New_York_City/New_York_City-portuguese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
echo New_York_City-japanese.conllu New_York_City-portuguese.conllu >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
gfud cosine-similarity data/New_York_City/New_York_City-japanese.conllu data/New_York_City/New_York_City-portuguese.conllu DEPREL >> cosine-sim-per-topic/New_York_City-cosine-sim.txt ; 
} 
topic_combinations