#! /bin/bash 
function topic_combinations { 
echo Niger-welsh.conllu Niger-north_sami.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-welsh.conllu data/Niger/Niger-north_sami.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-welsh.conllu Niger-estonian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-welsh.conllu data/Niger/Niger-estonian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-welsh.conllu Niger-irish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-welsh.conllu data/Niger/Niger-irish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-welsh.conllu Niger-scottish_gaelic.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-welsh.conllu data/Niger/Niger-scottish_gaelic.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-welsh.conllu Niger-hindi.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-welsh.conllu data/Niger/Niger-hindi.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-welsh.conllu Niger-maltese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-welsh.conllu data/Niger/Niger-maltese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-welsh.conllu Niger-marathi.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-welsh.conllu data/Niger/Niger-marathi.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-welsh.conllu Niger-sanskrit.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-welsh.conllu data/Niger/Niger-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-welsh.conllu Niger-slovenian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-welsh.conllu data/Niger/Niger-slovenian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-welsh.conllu Niger-urdu.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-welsh.conllu data/Niger/Niger-urdu.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-welsh.conllu Niger-uyghur.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-welsh.conllu data/Niger/Niger-uyghur.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-welsh.conllu Niger-classical_chinese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-welsh.conllu data/Niger/Niger-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-welsh.conllu Niger-wolof.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-welsh.conllu data/Niger/Niger-wolof.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-north_sami.conllu Niger-estonian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-north_sami.conllu data/Niger/Niger-estonian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-north_sami.conllu Niger-irish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-north_sami.conllu data/Niger/Niger-irish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-north_sami.conllu Niger-scottish_gaelic.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-north_sami.conllu data/Niger/Niger-scottish_gaelic.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-north_sami.conllu Niger-hindi.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-north_sami.conllu data/Niger/Niger-hindi.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-north_sami.conllu Niger-maltese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-north_sami.conllu data/Niger/Niger-maltese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-north_sami.conllu Niger-marathi.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-north_sami.conllu data/Niger/Niger-marathi.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-north_sami.conllu Niger-sanskrit.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-north_sami.conllu data/Niger/Niger-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-north_sami.conllu Niger-slovenian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-north_sami.conllu data/Niger/Niger-slovenian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-north_sami.conllu Niger-urdu.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-north_sami.conllu data/Niger/Niger-urdu.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-north_sami.conllu Niger-uyghur.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-north_sami.conllu data/Niger/Niger-uyghur.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-north_sami.conllu Niger-classical_chinese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-north_sami.conllu data/Niger/Niger-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-north_sami.conllu Niger-wolof.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-north_sami.conllu data/Niger/Niger-wolof.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-estonian.conllu Niger-irish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-estonian.conllu data/Niger/Niger-irish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-estonian.conllu Niger-scottish_gaelic.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-estonian.conllu data/Niger/Niger-scottish_gaelic.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-estonian.conllu Niger-hindi.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-estonian.conllu data/Niger/Niger-hindi.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-estonian.conllu Niger-maltese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-estonian.conllu data/Niger/Niger-maltese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-estonian.conllu Niger-marathi.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-estonian.conllu data/Niger/Niger-marathi.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-estonian.conllu Niger-sanskrit.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-estonian.conllu data/Niger/Niger-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-estonian.conllu Niger-slovenian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-estonian.conllu data/Niger/Niger-slovenian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-estonian.conllu Niger-urdu.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-estonian.conllu data/Niger/Niger-urdu.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-estonian.conllu Niger-uyghur.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-estonian.conllu data/Niger/Niger-uyghur.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-estonian.conllu Niger-classical_chinese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-estonian.conllu data/Niger/Niger-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-estonian.conllu Niger-wolof.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-estonian.conllu data/Niger/Niger-wolof.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-irish.conllu Niger-scottish_gaelic.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-irish.conllu data/Niger/Niger-scottish_gaelic.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-irish.conllu Niger-hindi.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-irish.conllu data/Niger/Niger-hindi.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-irish.conllu Niger-maltese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-irish.conllu data/Niger/Niger-maltese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-irish.conllu Niger-marathi.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-irish.conllu data/Niger/Niger-marathi.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-irish.conllu Niger-sanskrit.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-irish.conllu data/Niger/Niger-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-irish.conllu Niger-slovenian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-irish.conllu data/Niger/Niger-slovenian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-irish.conllu Niger-urdu.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-irish.conllu data/Niger/Niger-urdu.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-irish.conllu Niger-uyghur.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-irish.conllu data/Niger/Niger-uyghur.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-irish.conllu Niger-classical_chinese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-irish.conllu data/Niger/Niger-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-irish.conllu Niger-wolof.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-irish.conllu data/Niger/Niger-wolof.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-scottish_gaelic.conllu Niger-hindi.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-scottish_gaelic.conllu data/Niger/Niger-hindi.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-scottish_gaelic.conllu Niger-maltese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-scottish_gaelic.conllu data/Niger/Niger-maltese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-scottish_gaelic.conllu Niger-marathi.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-scottish_gaelic.conllu data/Niger/Niger-marathi.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-scottish_gaelic.conllu Niger-sanskrit.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-scottish_gaelic.conllu data/Niger/Niger-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-scottish_gaelic.conllu Niger-slovenian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-scottish_gaelic.conllu data/Niger/Niger-slovenian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-scottish_gaelic.conllu Niger-urdu.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-scottish_gaelic.conllu data/Niger/Niger-urdu.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-scottish_gaelic.conllu Niger-uyghur.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-scottish_gaelic.conllu data/Niger/Niger-uyghur.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-scottish_gaelic.conllu Niger-classical_chinese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-scottish_gaelic.conllu data/Niger/Niger-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-scottish_gaelic.conllu Niger-wolof.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-scottish_gaelic.conllu data/Niger/Niger-wolof.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-hindi.conllu Niger-maltese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-hindi.conllu data/Niger/Niger-maltese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-hindi.conllu Niger-marathi.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-hindi.conllu data/Niger/Niger-marathi.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-hindi.conllu Niger-sanskrit.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-hindi.conllu data/Niger/Niger-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-hindi.conllu Niger-slovenian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-hindi.conllu data/Niger/Niger-slovenian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-hindi.conllu Niger-urdu.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-hindi.conllu data/Niger/Niger-urdu.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-hindi.conllu Niger-uyghur.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-hindi.conllu data/Niger/Niger-uyghur.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-hindi.conllu Niger-classical_chinese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-hindi.conllu data/Niger/Niger-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-hindi.conllu Niger-wolof.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-hindi.conllu data/Niger/Niger-wolof.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-maltese.conllu Niger-marathi.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-maltese.conllu data/Niger/Niger-marathi.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-maltese.conllu Niger-sanskrit.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-maltese.conllu data/Niger/Niger-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-maltese.conllu Niger-slovenian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-maltese.conllu data/Niger/Niger-slovenian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-maltese.conllu Niger-urdu.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-maltese.conllu data/Niger/Niger-urdu.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-maltese.conllu Niger-uyghur.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-maltese.conllu data/Niger/Niger-uyghur.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-maltese.conllu Niger-classical_chinese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-maltese.conllu data/Niger/Niger-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-maltese.conllu Niger-wolof.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-maltese.conllu data/Niger/Niger-wolof.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-marathi.conllu Niger-sanskrit.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-marathi.conllu data/Niger/Niger-sanskrit.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-marathi.conllu Niger-slovenian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-marathi.conllu data/Niger/Niger-slovenian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-marathi.conllu Niger-urdu.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-marathi.conllu data/Niger/Niger-urdu.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-marathi.conllu Niger-uyghur.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-marathi.conllu data/Niger/Niger-uyghur.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-marathi.conllu Niger-classical_chinese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-marathi.conllu data/Niger/Niger-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-marathi.conllu Niger-wolof.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-marathi.conllu data/Niger/Niger-wolof.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-sanskrit.conllu Niger-slovenian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-sanskrit.conllu data/Niger/Niger-slovenian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-sanskrit.conllu Niger-urdu.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-sanskrit.conllu data/Niger/Niger-urdu.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-sanskrit.conllu Niger-uyghur.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-sanskrit.conllu data/Niger/Niger-uyghur.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-sanskrit.conllu Niger-classical_chinese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-sanskrit.conllu data/Niger/Niger-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-sanskrit.conllu Niger-wolof.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-sanskrit.conllu data/Niger/Niger-wolof.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-slovenian.conllu Niger-urdu.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-slovenian.conllu data/Niger/Niger-urdu.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-slovenian.conllu Niger-uyghur.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-slovenian.conllu data/Niger/Niger-uyghur.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-slovenian.conllu Niger-classical_chinese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-slovenian.conllu data/Niger/Niger-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-slovenian.conllu Niger-wolof.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-slovenian.conllu data/Niger/Niger-wolof.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-urdu.conllu Niger-uyghur.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-urdu.conllu data/Niger/Niger-uyghur.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-urdu.conllu Niger-classical_chinese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-urdu.conllu data/Niger/Niger-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-urdu.conllu Niger-wolof.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-urdu.conllu data/Niger/Niger-wolof.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-uyghur.conllu Niger-classical_chinese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-uyghur.conllu data/Niger/Niger-classical_chinese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-uyghur.conllu Niger-wolof.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-uyghur.conllu data/Niger/Niger-wolof.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-classical_chinese.conllu Niger-wolof.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-classical_chinese.conllu data/Niger/Niger-wolof.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-afrikaans.conllu Niger-belarusian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-afrikaans.conllu data/Niger/Niger-belarusian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-afrikaans.conllu Niger-bulgarian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-afrikaans.conllu data/Niger/Niger-bulgarian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-afrikaans.conllu Niger-czech.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-afrikaans.conllu data/Niger/Niger-czech.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-afrikaans.conllu Niger-danish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-afrikaans.conllu data/Niger/Niger-danish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-afrikaans.conllu Niger-greek.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-afrikaans.conllu data/Niger/Niger-greek.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-afrikaans.conllu Niger-persian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-afrikaans.conllu data/Niger/Niger-persian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-afrikaans.conllu Niger-galician.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-afrikaans.conllu data/Niger/Niger-galician.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-afrikaans.conllu Niger-korean.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-afrikaans.conllu data/Niger/Niger-korean.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-afrikaans.conllu Niger-croatian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-afrikaans.conllu data/Niger/Niger-croatian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-afrikaans.conllu Niger-indonesian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-afrikaans.conllu data/Niger/Niger-indonesian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-afrikaans.conllu Niger-kazakh.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-afrikaans.conllu data/Niger/Niger-kazakh.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-afrikaans.conllu Niger-latin.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-afrikaans.conllu data/Niger/Niger-latin.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-afrikaans.conllu Niger-latvian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-afrikaans.conllu data/Niger/Niger-latvian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-afrikaans.conllu Niger-slovak.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-afrikaans.conllu data/Niger/Niger-slovak.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-afrikaans.conllu Niger-serbian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-afrikaans.conllu data/Niger/Niger-serbian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-afrikaans.conllu Niger-tamil.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-afrikaans.conllu data/Niger/Niger-tamil.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-afrikaans.conllu Niger-chinese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-afrikaans.conllu data/Niger/Niger-chinese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-belarusian.conllu Niger-bulgarian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-belarusian.conllu data/Niger/Niger-bulgarian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-belarusian.conllu Niger-czech.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-belarusian.conllu data/Niger/Niger-czech.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-belarusian.conllu Niger-danish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-belarusian.conllu data/Niger/Niger-danish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-belarusian.conllu Niger-greek.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-belarusian.conllu data/Niger/Niger-greek.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-belarusian.conllu Niger-persian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-belarusian.conllu data/Niger/Niger-persian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-belarusian.conllu Niger-galician.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-belarusian.conllu data/Niger/Niger-galician.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-belarusian.conllu Niger-korean.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-belarusian.conllu data/Niger/Niger-korean.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-belarusian.conllu Niger-croatian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-belarusian.conllu data/Niger/Niger-croatian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-belarusian.conllu Niger-indonesian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-belarusian.conllu data/Niger/Niger-indonesian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-belarusian.conllu Niger-kazakh.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-belarusian.conllu data/Niger/Niger-kazakh.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-belarusian.conllu Niger-latin.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-belarusian.conllu data/Niger/Niger-latin.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-belarusian.conllu Niger-latvian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-belarusian.conllu data/Niger/Niger-latvian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-belarusian.conllu Niger-slovak.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-belarusian.conllu data/Niger/Niger-slovak.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-belarusian.conllu Niger-serbian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-belarusian.conllu data/Niger/Niger-serbian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-belarusian.conllu Niger-tamil.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-belarusian.conllu data/Niger/Niger-tamil.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-belarusian.conllu Niger-chinese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-belarusian.conllu data/Niger/Niger-chinese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-bulgarian.conllu Niger-czech.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-bulgarian.conllu data/Niger/Niger-czech.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-bulgarian.conllu Niger-danish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-bulgarian.conllu data/Niger/Niger-danish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-bulgarian.conllu Niger-greek.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-bulgarian.conllu data/Niger/Niger-greek.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-bulgarian.conllu Niger-persian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-bulgarian.conllu data/Niger/Niger-persian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-bulgarian.conllu Niger-galician.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-bulgarian.conllu data/Niger/Niger-galician.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-bulgarian.conllu Niger-korean.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-bulgarian.conllu data/Niger/Niger-korean.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-bulgarian.conllu Niger-croatian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-bulgarian.conllu data/Niger/Niger-croatian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-bulgarian.conllu Niger-indonesian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-bulgarian.conllu data/Niger/Niger-indonesian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-bulgarian.conllu Niger-kazakh.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-bulgarian.conllu data/Niger/Niger-kazakh.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-bulgarian.conllu Niger-latin.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-bulgarian.conllu data/Niger/Niger-latin.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-bulgarian.conllu Niger-latvian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-bulgarian.conllu data/Niger/Niger-latvian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-bulgarian.conllu Niger-slovak.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-bulgarian.conllu data/Niger/Niger-slovak.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-bulgarian.conllu Niger-serbian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-bulgarian.conllu data/Niger/Niger-serbian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-bulgarian.conllu Niger-tamil.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-bulgarian.conllu data/Niger/Niger-tamil.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-bulgarian.conllu Niger-chinese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-bulgarian.conllu data/Niger/Niger-chinese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-czech.conllu Niger-danish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-czech.conllu data/Niger/Niger-danish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-czech.conllu Niger-greek.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-czech.conllu data/Niger/Niger-greek.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-czech.conllu Niger-persian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-czech.conllu data/Niger/Niger-persian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-czech.conllu Niger-galician.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-czech.conllu data/Niger/Niger-galician.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-czech.conllu Niger-korean.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-czech.conllu data/Niger/Niger-korean.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-czech.conllu Niger-croatian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-czech.conllu data/Niger/Niger-croatian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-czech.conllu Niger-indonesian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-czech.conllu data/Niger/Niger-indonesian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-czech.conllu Niger-kazakh.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-czech.conllu data/Niger/Niger-kazakh.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-czech.conllu Niger-latin.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-czech.conllu data/Niger/Niger-latin.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-czech.conllu Niger-latvian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-czech.conllu data/Niger/Niger-latvian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-czech.conllu Niger-slovak.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-czech.conllu data/Niger/Niger-slovak.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-czech.conllu Niger-serbian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-czech.conllu data/Niger/Niger-serbian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-czech.conllu Niger-tamil.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-czech.conllu data/Niger/Niger-tamil.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-czech.conllu Niger-chinese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-czech.conllu data/Niger/Niger-chinese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-danish.conllu Niger-greek.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-danish.conllu data/Niger/Niger-greek.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-danish.conllu Niger-persian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-danish.conllu data/Niger/Niger-persian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-danish.conllu Niger-galician.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-danish.conllu data/Niger/Niger-galician.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-danish.conllu Niger-korean.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-danish.conllu data/Niger/Niger-korean.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-danish.conllu Niger-croatian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-danish.conllu data/Niger/Niger-croatian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-danish.conllu Niger-indonesian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-danish.conllu data/Niger/Niger-indonesian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-danish.conllu Niger-kazakh.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-danish.conllu data/Niger/Niger-kazakh.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-danish.conllu Niger-latin.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-danish.conllu data/Niger/Niger-latin.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-danish.conllu Niger-latvian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-danish.conllu data/Niger/Niger-latvian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-danish.conllu Niger-slovak.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-danish.conllu data/Niger/Niger-slovak.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-danish.conllu Niger-serbian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-danish.conllu data/Niger/Niger-serbian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-danish.conllu Niger-tamil.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-danish.conllu data/Niger/Niger-tamil.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-danish.conllu Niger-chinese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-danish.conllu data/Niger/Niger-chinese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-greek.conllu Niger-persian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-greek.conllu data/Niger/Niger-persian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-greek.conllu Niger-galician.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-greek.conllu data/Niger/Niger-galician.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-greek.conllu Niger-korean.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-greek.conllu data/Niger/Niger-korean.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-greek.conllu Niger-croatian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-greek.conllu data/Niger/Niger-croatian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-greek.conllu Niger-indonesian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-greek.conllu data/Niger/Niger-indonesian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-greek.conllu Niger-kazakh.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-greek.conllu data/Niger/Niger-kazakh.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-greek.conllu Niger-latin.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-greek.conllu data/Niger/Niger-latin.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-greek.conllu Niger-latvian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-greek.conllu data/Niger/Niger-latvian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-greek.conllu Niger-slovak.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-greek.conllu data/Niger/Niger-slovak.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-greek.conllu Niger-serbian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-greek.conllu data/Niger/Niger-serbian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-greek.conllu Niger-tamil.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-greek.conllu data/Niger/Niger-tamil.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-greek.conllu Niger-chinese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-greek.conllu data/Niger/Niger-chinese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-persian.conllu Niger-galician.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-persian.conllu data/Niger/Niger-galician.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-persian.conllu Niger-korean.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-persian.conllu data/Niger/Niger-korean.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-persian.conllu Niger-croatian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-persian.conllu data/Niger/Niger-croatian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-persian.conllu Niger-indonesian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-persian.conllu data/Niger/Niger-indonesian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-persian.conllu Niger-kazakh.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-persian.conllu data/Niger/Niger-kazakh.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-persian.conllu Niger-latin.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-persian.conllu data/Niger/Niger-latin.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-persian.conllu Niger-latvian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-persian.conllu data/Niger/Niger-latvian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-persian.conllu Niger-slovak.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-persian.conllu data/Niger/Niger-slovak.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-persian.conllu Niger-serbian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-persian.conllu data/Niger/Niger-serbian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-persian.conllu Niger-tamil.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-persian.conllu data/Niger/Niger-tamil.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-persian.conllu Niger-chinese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-persian.conllu data/Niger/Niger-chinese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-galician.conllu Niger-korean.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-galician.conllu data/Niger/Niger-korean.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-galician.conllu Niger-croatian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-galician.conllu data/Niger/Niger-croatian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-galician.conllu Niger-indonesian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-galician.conllu data/Niger/Niger-indonesian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-galician.conllu Niger-kazakh.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-galician.conllu data/Niger/Niger-kazakh.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-galician.conllu Niger-latin.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-galician.conllu data/Niger/Niger-latin.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-galician.conllu Niger-latvian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-galician.conllu data/Niger/Niger-latvian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-galician.conllu Niger-slovak.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-galician.conllu data/Niger/Niger-slovak.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-galician.conllu Niger-serbian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-galician.conllu data/Niger/Niger-serbian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-galician.conllu Niger-tamil.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-galician.conllu data/Niger/Niger-tamil.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-galician.conllu Niger-chinese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-galician.conllu data/Niger/Niger-chinese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-korean.conllu Niger-croatian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-korean.conllu data/Niger/Niger-croatian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-korean.conllu Niger-indonesian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-korean.conllu data/Niger/Niger-indonesian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-korean.conllu Niger-kazakh.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-korean.conllu data/Niger/Niger-kazakh.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-korean.conllu Niger-latin.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-korean.conllu data/Niger/Niger-latin.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-korean.conllu Niger-latvian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-korean.conllu data/Niger/Niger-latvian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-korean.conllu Niger-slovak.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-korean.conllu data/Niger/Niger-slovak.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-korean.conllu Niger-serbian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-korean.conllu data/Niger/Niger-serbian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-korean.conllu Niger-tamil.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-korean.conllu data/Niger/Niger-tamil.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-korean.conllu Niger-chinese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-korean.conllu data/Niger/Niger-chinese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-croatian.conllu Niger-indonesian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-croatian.conllu data/Niger/Niger-indonesian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-croatian.conllu Niger-kazakh.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-croatian.conllu data/Niger/Niger-kazakh.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-croatian.conllu Niger-latin.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-croatian.conllu data/Niger/Niger-latin.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-croatian.conllu Niger-latvian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-croatian.conllu data/Niger/Niger-latvian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-croatian.conllu Niger-slovak.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-croatian.conllu data/Niger/Niger-slovak.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-croatian.conllu Niger-serbian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-croatian.conllu data/Niger/Niger-serbian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-croatian.conllu Niger-tamil.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-croatian.conllu data/Niger/Niger-tamil.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-croatian.conllu Niger-chinese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-croatian.conllu data/Niger/Niger-chinese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-indonesian.conllu Niger-kazakh.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-indonesian.conllu data/Niger/Niger-kazakh.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-indonesian.conllu Niger-latin.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-indonesian.conllu data/Niger/Niger-latin.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-indonesian.conllu Niger-latvian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-indonesian.conllu data/Niger/Niger-latvian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-indonesian.conllu Niger-slovak.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-indonesian.conllu data/Niger/Niger-slovak.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-indonesian.conllu Niger-serbian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-indonesian.conllu data/Niger/Niger-serbian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-indonesian.conllu Niger-tamil.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-indonesian.conllu data/Niger/Niger-tamil.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-indonesian.conllu Niger-chinese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-indonesian.conllu data/Niger/Niger-chinese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-kazakh.conllu Niger-latin.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-kazakh.conllu data/Niger/Niger-latin.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-kazakh.conllu Niger-latvian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-kazakh.conllu data/Niger/Niger-latvian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-kazakh.conllu Niger-slovak.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-kazakh.conllu data/Niger/Niger-slovak.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-kazakh.conllu Niger-serbian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-kazakh.conllu data/Niger/Niger-serbian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-kazakh.conllu Niger-tamil.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-kazakh.conllu data/Niger/Niger-tamil.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-kazakh.conllu Niger-chinese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-kazakh.conllu data/Niger/Niger-chinese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-latin.conllu Niger-latvian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-latin.conllu data/Niger/Niger-latvian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-latin.conllu Niger-slovak.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-latin.conllu data/Niger/Niger-slovak.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-latin.conllu Niger-serbian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-latin.conllu data/Niger/Niger-serbian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-latin.conllu Niger-tamil.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-latin.conllu data/Niger/Niger-tamil.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-latin.conllu Niger-chinese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-latin.conllu data/Niger/Niger-chinese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-latvian.conllu Niger-slovak.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-latvian.conllu data/Niger/Niger-slovak.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-latvian.conllu Niger-serbian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-latvian.conllu data/Niger/Niger-serbian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-latvian.conllu Niger-tamil.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-latvian.conllu data/Niger/Niger-tamil.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-latvian.conllu Niger-chinese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-latvian.conllu data/Niger/Niger-chinese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-slovak.conllu Niger-serbian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-slovak.conllu data/Niger/Niger-serbian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-slovak.conllu Niger-tamil.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-slovak.conllu data/Niger/Niger-tamil.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-slovak.conllu Niger-chinese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-slovak.conllu data/Niger/Niger-chinese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-serbian.conllu Niger-tamil.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-serbian.conllu data/Niger/Niger-tamil.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-serbian.conllu Niger-chinese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-serbian.conllu data/Niger/Niger-chinese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-tamil.conllu Niger-chinese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-tamil.conllu data/Niger/Niger-chinese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-catalan.conllu Niger-spanish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-catalan.conllu data/Niger/Niger-spanish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-catalan.conllu Niger-basque.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-catalan.conllu data/Niger/Niger-basque.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-catalan.conllu Niger-french.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-catalan.conllu data/Niger/Niger-french.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-catalan.conllu Niger-armenian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-catalan.conllu data/Niger/Niger-armenian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-catalan.conllu Niger-italian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-catalan.conllu data/Niger/Niger-italian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-catalan.conllu Niger-hebrew.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-catalan.conllu data/Niger/Niger-hebrew.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-catalan.conllu Niger-lithuanian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-catalan.conllu data/Niger/Niger-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-catalan.conllu Niger-hungarian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-catalan.conllu data/Niger/Niger-hungarian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-catalan.conllu Niger-dutch.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-catalan.conllu data/Niger/Niger-dutch.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-catalan.conllu Niger-japanese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-catalan.conllu data/Niger/Niger-japanese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-catalan.conllu Niger-polish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-catalan.conllu data/Niger/Niger-polish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-catalan.conllu Niger-portuguese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-catalan.conllu data/Niger/Niger-portuguese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-catalan.conllu Niger-romanian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-catalan.conllu data/Niger/Niger-romanian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-catalan.conllu Niger-finnish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-catalan.conllu data/Niger/Niger-finnish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-catalan.conllu Niger-swedish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-catalan.conllu data/Niger/Niger-swedish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-catalan.conllu Niger-turkish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-catalan.conllu data/Niger/Niger-turkish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-spanish.conllu Niger-basque.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-spanish.conllu data/Niger/Niger-basque.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-spanish.conllu Niger-french.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-spanish.conllu data/Niger/Niger-french.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-spanish.conllu Niger-armenian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-spanish.conllu data/Niger/Niger-armenian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-spanish.conllu Niger-italian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-spanish.conllu data/Niger/Niger-italian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-spanish.conllu Niger-hebrew.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-spanish.conllu data/Niger/Niger-hebrew.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-spanish.conllu Niger-lithuanian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-spanish.conllu data/Niger/Niger-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-spanish.conllu Niger-hungarian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-spanish.conllu data/Niger/Niger-hungarian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-spanish.conllu Niger-dutch.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-spanish.conllu data/Niger/Niger-dutch.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-spanish.conllu Niger-japanese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-spanish.conllu data/Niger/Niger-japanese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-spanish.conllu Niger-polish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-spanish.conllu data/Niger/Niger-polish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-spanish.conllu Niger-portuguese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-spanish.conllu data/Niger/Niger-portuguese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-spanish.conllu Niger-romanian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-spanish.conllu data/Niger/Niger-romanian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-spanish.conllu Niger-finnish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-spanish.conllu data/Niger/Niger-finnish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-spanish.conllu Niger-swedish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-spanish.conllu data/Niger/Niger-swedish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-spanish.conllu Niger-turkish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-spanish.conllu data/Niger/Niger-turkish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-basque.conllu Niger-french.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-basque.conllu data/Niger/Niger-french.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-basque.conllu Niger-armenian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-basque.conllu data/Niger/Niger-armenian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-basque.conllu Niger-italian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-basque.conllu data/Niger/Niger-italian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-basque.conllu Niger-hebrew.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-basque.conllu data/Niger/Niger-hebrew.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-basque.conllu Niger-lithuanian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-basque.conllu data/Niger/Niger-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-basque.conllu Niger-hungarian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-basque.conllu data/Niger/Niger-hungarian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-basque.conllu Niger-dutch.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-basque.conllu data/Niger/Niger-dutch.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-basque.conllu Niger-japanese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-basque.conllu data/Niger/Niger-japanese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-basque.conllu Niger-polish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-basque.conllu data/Niger/Niger-polish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-basque.conllu Niger-portuguese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-basque.conllu data/Niger/Niger-portuguese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-basque.conllu Niger-romanian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-basque.conllu data/Niger/Niger-romanian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-basque.conllu Niger-finnish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-basque.conllu data/Niger/Niger-finnish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-basque.conllu Niger-swedish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-basque.conllu data/Niger/Niger-swedish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-basque.conllu Niger-turkish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-basque.conllu data/Niger/Niger-turkish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-french.conllu Niger-armenian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-french.conllu data/Niger/Niger-armenian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-french.conllu Niger-italian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-french.conllu data/Niger/Niger-italian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-french.conllu Niger-hebrew.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-french.conllu data/Niger/Niger-hebrew.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-french.conllu Niger-lithuanian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-french.conllu data/Niger/Niger-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-french.conllu Niger-hungarian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-french.conllu data/Niger/Niger-hungarian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-french.conllu Niger-dutch.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-french.conllu data/Niger/Niger-dutch.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-french.conllu Niger-japanese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-french.conllu data/Niger/Niger-japanese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-french.conllu Niger-polish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-french.conllu data/Niger/Niger-polish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-french.conllu Niger-portuguese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-french.conllu data/Niger/Niger-portuguese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-french.conllu Niger-romanian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-french.conllu data/Niger/Niger-romanian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-french.conllu Niger-finnish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-french.conllu data/Niger/Niger-finnish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-french.conllu Niger-swedish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-french.conllu data/Niger/Niger-swedish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-french.conllu Niger-turkish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-french.conllu data/Niger/Niger-turkish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-armenian.conllu Niger-italian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-armenian.conllu data/Niger/Niger-italian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-armenian.conllu Niger-hebrew.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-armenian.conllu data/Niger/Niger-hebrew.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-armenian.conllu Niger-lithuanian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-armenian.conllu data/Niger/Niger-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-armenian.conllu Niger-hungarian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-armenian.conllu data/Niger/Niger-hungarian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-armenian.conllu Niger-dutch.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-armenian.conllu data/Niger/Niger-dutch.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-armenian.conllu Niger-japanese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-armenian.conllu data/Niger/Niger-japanese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-armenian.conllu Niger-polish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-armenian.conllu data/Niger/Niger-polish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-armenian.conllu Niger-portuguese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-armenian.conllu data/Niger/Niger-portuguese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-armenian.conllu Niger-romanian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-armenian.conllu data/Niger/Niger-romanian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-armenian.conllu Niger-finnish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-armenian.conllu data/Niger/Niger-finnish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-armenian.conllu Niger-swedish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-armenian.conllu data/Niger/Niger-swedish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-armenian.conllu Niger-turkish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-armenian.conllu data/Niger/Niger-turkish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-italian.conllu Niger-hebrew.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-italian.conllu data/Niger/Niger-hebrew.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-italian.conllu Niger-lithuanian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-italian.conllu data/Niger/Niger-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-italian.conllu Niger-hungarian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-italian.conllu data/Niger/Niger-hungarian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-italian.conllu Niger-dutch.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-italian.conllu data/Niger/Niger-dutch.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-italian.conllu Niger-japanese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-italian.conllu data/Niger/Niger-japanese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-italian.conllu Niger-polish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-italian.conllu data/Niger/Niger-polish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-italian.conllu Niger-portuguese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-italian.conllu data/Niger/Niger-portuguese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-italian.conllu Niger-romanian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-italian.conllu data/Niger/Niger-romanian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-italian.conllu Niger-finnish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-italian.conllu data/Niger/Niger-finnish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-italian.conllu Niger-swedish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-italian.conllu data/Niger/Niger-swedish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-italian.conllu Niger-turkish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-italian.conllu data/Niger/Niger-turkish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-hebrew.conllu Niger-lithuanian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-hebrew.conllu data/Niger/Niger-lithuanian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-hebrew.conllu Niger-hungarian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-hebrew.conllu data/Niger/Niger-hungarian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-hebrew.conllu Niger-dutch.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-hebrew.conllu data/Niger/Niger-dutch.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-hebrew.conllu Niger-japanese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-hebrew.conllu data/Niger/Niger-japanese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-hebrew.conllu Niger-polish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-hebrew.conllu data/Niger/Niger-polish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-hebrew.conllu Niger-portuguese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-hebrew.conllu data/Niger/Niger-portuguese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-hebrew.conllu Niger-romanian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-hebrew.conllu data/Niger/Niger-romanian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-hebrew.conllu Niger-finnish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-hebrew.conllu data/Niger/Niger-finnish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-hebrew.conllu Niger-swedish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-hebrew.conllu data/Niger/Niger-swedish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-hebrew.conllu Niger-turkish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-hebrew.conllu data/Niger/Niger-turkish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-lithuanian.conllu Niger-hungarian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-lithuanian.conllu data/Niger/Niger-hungarian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-lithuanian.conllu Niger-dutch.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-lithuanian.conllu data/Niger/Niger-dutch.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-lithuanian.conllu Niger-japanese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-lithuanian.conllu data/Niger/Niger-japanese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-lithuanian.conllu Niger-polish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-lithuanian.conllu data/Niger/Niger-polish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-lithuanian.conllu Niger-portuguese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-lithuanian.conllu data/Niger/Niger-portuguese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-lithuanian.conllu Niger-romanian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-lithuanian.conllu data/Niger/Niger-romanian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-lithuanian.conllu Niger-finnish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-lithuanian.conllu data/Niger/Niger-finnish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-lithuanian.conllu Niger-swedish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-lithuanian.conllu data/Niger/Niger-swedish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-lithuanian.conllu Niger-turkish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-lithuanian.conllu data/Niger/Niger-turkish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-hungarian.conllu Niger-dutch.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-hungarian.conllu data/Niger/Niger-dutch.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-hungarian.conllu Niger-japanese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-hungarian.conllu data/Niger/Niger-japanese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-hungarian.conllu Niger-polish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-hungarian.conllu data/Niger/Niger-polish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-hungarian.conllu Niger-portuguese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-hungarian.conllu data/Niger/Niger-portuguese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-hungarian.conllu Niger-romanian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-hungarian.conllu data/Niger/Niger-romanian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-hungarian.conllu Niger-finnish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-hungarian.conllu data/Niger/Niger-finnish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-hungarian.conllu Niger-swedish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-hungarian.conllu data/Niger/Niger-swedish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-hungarian.conllu Niger-turkish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-hungarian.conllu data/Niger/Niger-turkish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-dutch.conllu Niger-japanese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-dutch.conllu data/Niger/Niger-japanese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-dutch.conllu Niger-polish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-dutch.conllu data/Niger/Niger-polish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-dutch.conllu Niger-portuguese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-dutch.conllu data/Niger/Niger-portuguese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-dutch.conllu Niger-romanian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-dutch.conllu data/Niger/Niger-romanian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-dutch.conllu Niger-finnish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-dutch.conllu data/Niger/Niger-finnish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-dutch.conllu Niger-swedish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-dutch.conllu data/Niger/Niger-swedish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-dutch.conllu Niger-turkish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-dutch.conllu data/Niger/Niger-turkish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-japanese.conllu Niger-polish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-japanese.conllu data/Niger/Niger-polish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-japanese.conllu Niger-portuguese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-japanese.conllu data/Niger/Niger-portuguese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-japanese.conllu Niger-romanian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-japanese.conllu data/Niger/Niger-romanian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-japanese.conllu Niger-finnish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-japanese.conllu data/Niger/Niger-finnish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-japanese.conllu Niger-swedish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-japanese.conllu data/Niger/Niger-swedish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-japanese.conllu Niger-turkish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-japanese.conllu data/Niger/Niger-turkish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-polish.conllu Niger-portuguese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-polish.conllu data/Niger/Niger-portuguese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-polish.conllu Niger-romanian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-polish.conllu data/Niger/Niger-romanian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-polish.conllu Niger-finnish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-polish.conllu data/Niger/Niger-finnish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-polish.conllu Niger-swedish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-polish.conllu data/Niger/Niger-swedish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-polish.conllu Niger-turkish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-polish.conllu data/Niger/Niger-turkish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-portuguese.conllu Niger-romanian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-portuguese.conllu data/Niger/Niger-romanian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-portuguese.conllu Niger-finnish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-portuguese.conllu data/Niger/Niger-finnish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-portuguese.conllu Niger-swedish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-portuguese.conllu data/Niger/Niger-swedish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-portuguese.conllu Niger-turkish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-portuguese.conllu data/Niger/Niger-turkish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-romanian.conllu Niger-finnish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-romanian.conllu data/Niger/Niger-finnish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-romanian.conllu Niger-swedish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-romanian.conllu data/Niger/Niger-swedish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-romanian.conllu Niger-turkish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-romanian.conllu data/Niger/Niger-turkish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-finnish.conllu Niger-swedish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-finnish.conllu data/Niger/Niger-swedish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-finnish.conllu Niger-turkish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-finnish.conllu data/Niger/Niger-turkish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-swedish.conllu Niger-turkish.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-swedish.conllu data/Niger/Niger-turkish.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-english.conllu Niger-arabic.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-english.conllu data/Niger/Niger-arabic.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-english.conllu Niger-german.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-english.conllu data/Niger/Niger-german.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-english.conllu Niger-russian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-english.conllu data/Niger/Niger-russian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-english.conllu Niger-telugu.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-english.conllu data/Niger/Niger-telugu.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-english.conllu Niger-ukrainian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-english.conllu data/Niger/Niger-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-english.conllu Niger-vietnamese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-english.conllu data/Niger/Niger-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-arabic.conllu Niger-german.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-arabic.conllu data/Niger/Niger-german.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-arabic.conllu Niger-russian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-arabic.conllu data/Niger/Niger-russian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-arabic.conllu Niger-telugu.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-arabic.conllu data/Niger/Niger-telugu.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-arabic.conllu Niger-ukrainian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-arabic.conllu data/Niger/Niger-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-arabic.conllu Niger-vietnamese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-arabic.conllu data/Niger/Niger-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-german.conllu Niger-russian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-german.conllu data/Niger/Niger-russian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-german.conllu Niger-telugu.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-german.conllu data/Niger/Niger-telugu.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-german.conllu Niger-ukrainian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-german.conllu data/Niger/Niger-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-german.conllu Niger-vietnamese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-german.conllu data/Niger/Niger-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-russian.conllu Niger-telugu.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-russian.conllu data/Niger/Niger-telugu.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-russian.conllu Niger-ukrainian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-russian.conllu data/Niger/Niger-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-russian.conllu Niger-vietnamese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-russian.conllu data/Niger/Niger-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-telugu.conllu Niger-ukrainian.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-telugu.conllu data/Niger/Niger-ukrainian.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-telugu.conllu Niger-vietnamese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-telugu.conllu data/Niger/Niger-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
echo Niger-ukrainian.conllu Niger-vietnamese.conllu >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
gfud cosine-similarity data/Niger/Niger-ukrainian.conllu data/Niger/Niger-vietnamese.conllu DEPREL >> cosine-sim-per-topic/Niger-cosine-sim.txt ; 
} 
topic_combinations